import type { Lesson } from '../../types'

export const lesson102ByMyself: Lesson = {
  id: 'a2-m10-l2',
  moduleId: 'm10-reflexives',
  order: 1,
  title: 'by myself / for yourself (solo, sin ayuda)',
  objective: 'Usar "by" + pronombre reflexivo (by myself, by yourself...) para decir "solo/a, sin ayuda" y "yourself" para "tú mismo".',
  explanation_es: `En inglés, la expresión "by + reflexivo" significa "solo" o "sin ayuda de nadie".

Veamos las formas:
- by myself = solo/a (yo), sin ayuda: I live by myself. = Vivo solo.
- by yourself = solo/a (tú), sin ayuda: You did it by yourself. = Lo hiciste tú solo.
- by himself = solo (él): He cooked dinner by himself. = Él cocinó la cena solo.
- by herself = sola (ella): She did it by herself. = Ella lo hizo sola.
- by ourselves = solos/as (nosotros): We cleaned the house by ourselves. = Limpiamos la casa solos.
- by themselves = solos (ellos): They traveled by themselves. = Viajaron solos.

También podemos usar el reflexivo sin "by" para enfatizar "yo mismo / tú mismo":
- You can make it yourself. = Puedes hacerlo tú mismo.
- I made this cake myself. = Hice este pastel yo mismo.

OJO: "by myself" es una sola expresión; no la separes. No digas "by my self" (en dos palabras), y no digas "I live myself" (falta el "by").`,
  examples: [
    { english: 'I live by myself.', spanish: 'Vivo solo.', note: 'by myself = solo, sin compañía' },
    { english: 'She did it by herself.', spanish: 'Ella lo hizo sola.', note: 'sin ayuda' },
    { english: 'You can make it yourself.', spanish: 'Puedes hacerlo tú mismo.' },
    { english: 'He finished the project by himself.', spanish: 'Él terminó el proyecto solo.' },
    { english: 'We moved the furniture by ourselves.', spanish: 'Movimos los muebles solos.' },
  ],
  rule: `Regla:
- by + reflexivo = solo/a, sin ayuda: by myself, by yourself, by himself, by herself, by ourselves, by themselves.
- El reflexivo también enfatiza "yo mismo / tú mismo": I did it myself.

Recuerda: "by myself" se escribe en dos palabras juntas separadas por espacio, pero "my self" (separado como dos palabras independientes) es incorrecto. Y nunca digas "I live myself"; debe ser "I live by myself".`,
  formation: {
    title: 'Cómo se forma "by" + reflexivo',
    intro: '"By" + pronombre reflexivo significa "solo/a" o "sin ayuda". El reflexivo solo (sin "by") sirve para enfatizar "yo mismo / tú mismo".',
    patterns: [
      {
        name: 'by + reflexivo (solo/a, sin ayuda)',
        formula: 'by myself / by yourself / by himself / by herself / by ourselves / by themselves',
        examples: [
          { english: 'I live by myself.', spanish: 'Vivo solo.' },
          { english: 'She did it by herself.', spanish: 'Ella lo hizo sola.' },
          { english: 'We cleaned the house by ourselves.', spanish: 'Limpiamos la casa solos.' },
        ],
        note: 'Cada persona tiene su forma: I→myself, you→yourself, he→himself, she→herself, we→ourselves, they→themselves.',
      },
      {
        name: 'Reflexivo sin "by" (énfasis)',
        formula: 'sujeto + verbo + reflexivo (yo mismo / tú mismo)',
        examples: [
          { english: 'You can make it yourself.', spanish: 'Puedes hacerlo tú mismo.' },
          { english: 'I made this cake myself.', spanish: 'Hice este pastel yo mismo.' },
        ],
        note: 'El reflexivo sin "by" no significa "solo"; solo enfatiza quién hizo la acción.',
      },
    ],
    notes: [
      '"Myself" es una sola palabra: ❌ by my self → ✅ by myself.',
      'No digas "I live myself": para "vivo solo" necesitas el "by": I live by myself.',
      'El reflexivo nunca lleva -s: by herself, no "by herselfs".',
    ],
  },
  commonMistakes: [
    { wrong: '❌ I live myself.', correct: '✅ I live by myself.', explanation: 'Para decir "vivo solo" necesitas "by" antes del reflexivo: I live by myself.' },
    { wrong: '❌ I did my homework by my self.', correct: '✅ I did my homework by myself.', explanation: '"Myself" es una sola palabra. "My self" en dos palabras no existe.' },
    { wrong: '❌ She lives by herselfs.', correct: '✅ She lives by herself.', explanation: '"Herself" no lleva -s. La -s ya está en "herself" como parte de la palabra.' },
  ],
  vocabulary: [
    { word: 'by myself', translation_es: 'solo/a, sin ayuda', level: 'A2', category: 'expressions', partOfSpeech: 'phrase', example: 'I live by myself.', exampleTranslation: 'Vivo solo.' },
    { word: 'by yourself', translation_es: 'solo/a (tú), sin ayuda', level: 'A2', category: 'expressions', partOfSpeech: 'phrase', example: 'You can do it by yourself.', exampleTranslation: 'Puedes hacerlo tú solo.' },
    { word: 'by himself', translation_es: 'solo (él), sin ayuda', level: 'A2', category: 'expressions', partOfSpeech: 'phrase', example: 'He cooked dinner by himself.', exampleTranslation: 'Él cocinó la cena solo.' },
    { word: 'by herself', translation_es: 'sola (ella), sin ayuda', level: 'A2', category: 'expressions', partOfSpeech: 'phrase', example: 'She fixed the lamp by herself.', exampleTranslation: 'Ella arregló la lámpara sola.' },
    { word: 'by ourselves', translation_es: 'solos/as, sin ayuda', level: 'A2', category: 'expressions', partOfSpeech: 'phrase', example: 'We cleaned the house by ourselves.', exampleTranslation: 'Limpiamos la casa solos.' },
    { word: 'by themselves', translation_es: 'solos, sin ayuda', level: 'A2', category: 'expressions', partOfSpeech: 'phrase', example: 'They traveled by themselves.', exampleTranslation: 'Viajaron solos.' },
  ],
  grammarPoints: [
    {
      id: 'gp-by-reflexive',
      level: 'A2',
      name: 'by + reflexive pronoun',
      explanation_es: '"by" + pronombre reflexivo significa "solo" o "sin ayuda". El reflexivo solo (sin "by") enfatiza "yo mismo, tú mismo".',
      formula: 'by + myself/yourself/himself/herself/ourselves/themselves',
      examples: ['I live by myself.', 'She did it by herself.', 'You can make it yourself.'],
    },
  ],
  exercises: [
    {
      id: 'a2-m10-l2-ex1',
      type: 'multiple_choice',
      concept: 'by + reflexive',
      difficulty: 1,
      prompt: 'Completa: "I live ___."',
      promptTranslation: 'Vivo solo.',
      correctAnswer: 'by myself',
      options: ['by myself', 'myself', 'by my self'],
      explanation: 'Para decir "vivo solo" usamos "by myself". → I live by myself.',
    },
    {
      id: 'a2-m10-l2-ex2',
      type: 'fill_blank',
      concept: 'by + reflexive',
      difficulty: 2,
      prompt: 'Completa: "She did it ___."',
      promptTranslation: 'Ella lo hizo sola.',
      correctAnswer: 'by herself',
      acceptedAnswers: ['by herself', 'By herself'],
      explanation: 'Con "she" usamos "by herself". → She did it by herself. = Ella lo hizo sola, sin ayuda.',
    },
    {
      id: 'a2-m10-l2-ex3',
      type: 'reorder',
      concept: 'by + reflexive',
      difficulty: 2,
      prompt: 'Ordena las palabras: did / She / by herself / it',
      promptTranslation: 'Ella lo hizo sola.',
      correctAnswer: 'She did it by herself.',
      words: ['She', 'did', 'it', 'by herself'],
      explanation: 'El orden es: sujeto + verbo + objeto + by + reflexivo. → She did it by herself.',
    },
    {
      id: 'a2-m10-l2-ex4',
      type: 'translate',
      concept: 'by + reflexive',
      difficulty: 3,
      prompt: 'Traduce: "Él vive solo."',
      promptTranslation: 'He lives by himself.',
      correctAnswer: 'He lives by himself.',
      acceptedAnswers: ['He lives by himself', 'He lives by himself.', 'he lives by himself', 'He lives alone'],
      acceptApproximate: true,
      explanation: '"Vivir solo" = live by himself. → He lives by himself.',
    },
    {
      id: 'a2-m10-l2-ex5',
      type: 'error_correction',
      concept: 'by + reflexive',
      difficulty: 3,
      prompt: 'Corrige el error: "I did my homework by my self."',
      promptTranslation: 'Hice mis deberes yo solo.',
      correctAnswer: 'I did my homework by myself.',
      acceptedAnswers: ['I did my homework by myself', 'I did my homework by myself.', 'i did my homework by myself'],
      acceptApproximate: true,
      explanation: '"Myself" es una sola palabra. → I did my homework by myself.',
    },
    {
      id: 'a2-m10-l2-ex6',
      type: 'true_false',
      concept: 'by + reflexive',
      difficulty: 2,
      prompt: '"I live myself" es una frase correcta en inglés.',
      promptTranslation: '"I live myself" is correct English.',
      correctAnswer: 'false',
      acceptedAnswers: ['False', 'FALSE', 'f'],
      explanation: 'Falso. Necesitamos "by": I live by myself. Sin "by" la frase no significa "vivo solo".',
    },
    {
      id: 'a2-m10-l2-ex7',
      type: 'match',
      concept: 'by + reflexive',
      difficulty: 2,
      prompt: 'Relaciona cada expresión con su traducción.',
      promptTranslation: 'Match each expression with its translation.',
      correctAnswer: 'by myself=solo/a, by yourself=solo/a (tú), by himself=solo (él), by herself=sola (ella), by ourselves=solos/as, by themselves=solos',
      pairs: [
        { left: 'by myself', right: 'solo/a, sin ayuda' },
        { left: 'by yourself', right: 'solo/a (tú), sin ayuda' },
        { left: 'by himself', right: 'solo (él), sin ayuda' },
        { left: 'by herself', right: 'sola (ella), sin ayuda' },
        { left: 'by ourselves', right: 'solos/as, sin ayuda' },
        { left: 'by themselves', right: 'solos, sin ayuda' },
      ],
      explanation: 'Cada persona tiene su forma: I→myself, You→yourself, He→himself, She→herself, We→ourselves, They→themselves, siempre precedidas de "by".',
    },
    {
      id: 'a2-m10-l2-ex8',
      type: 'multiple_choice',
      concept: 'by + reflexive',
      difficulty: 3,
      prompt: 'Completa (hablando con una persona): "You can do it ___."',
      promptTranslation: 'Puedes hacerlo tú solo.',
      correctAnswer: 'by yourself',
      options: ['by yourself', 'by yourselves', 'by hisself'],
      explanation: 'Dirigiéndonos a "you", usamos "by yourself". → You can do it by yourself.',
    },
    {
      id: 'a2-m10-l2-ex9',
      type: 'fill_blank',
      concept: 'reflexive for emphasis',
      difficulty: 3,
      prompt: 'Completa (énfasis): "I made this cake ___."',
      promptTranslation: 'Hice este pastel yo mismo.',
      correctAnswer: 'myself',
      acceptedAnswers: ['myself', 'by myself'],
      explanation: 'El reflexivo sin "by" enfatiza "yo mismo". → I made this cake myself.',
    },
    {
      id: 'a2-m10-l2-ex10',
      type: 'multiple_choice',
      concept: 'by + reflexive',
      difficulty: 4,
      prompt: 'Completa: "We cooked the whole dinner ___."',
      promptTranslation: 'Cocinamos toda la cena solos.',
      correctAnswer: 'by ourselves',
      options: ['by ourselves', 'by ourself', 'ourselves by'],
      explanation: 'Con "we" el reflexivo es "ourselves" y va tras "by". → We cooked the whole dinner by ourselves.',
    },
  ],
  miniTest: [
    {
      id: 'a2-m10-l2-mt1',
      type: 'multiple_choice',
      concept: 'by + reflexive',
      difficulty: 2,
      prompt: 'Completa: "He painted the room ___."',
      promptTranslation: 'Él pintó la habitación solo.',
      correctAnswer: 'by himself',
      options: ['by himself', 'by him', 'himself by'],
      explanation: 'Con "he" usamos "by himself". → He painted the room by himself.',
    },
    {
      id: 'a2-m10-l2-mt2',
      type: 'fill_blank',
      concept: 'by + reflexive',
      difficulty: 2,
      prompt: 'Completa: "They live ___ in a big house."',
      promptTranslation: 'Viven solos en una casa grande.',
      correctAnswer: 'by themselves',
      acceptedAnswers: ['by themselves', 'By themselves'],
      explanation: 'Con "they" usamos "by themselves". → They live by themselves.',
    },
    {
      id: 'a2-m10-l2-mt3',
      type: 'translate',
      concept: 'by + reflexive',
      difficulty: 3,
      prompt: 'Traduce: "Lo hiciste tú mismo."',
      promptTranslation: 'You did it yourself.',
      correctAnswer: 'You did it yourself.',
      acceptedAnswers: ['You did it yourself', 'You did it yourself.', 'you did it yourself', 'You made it yourself'],
      acceptApproximate: true,
      explanation: 'Con énfasis en "tú mismo" usamos "yourself" después del objeto. → You did it yourself.',
    },
    {
      id: 'a2-m10-l2-mt4',
      type: 'error_correction',
      concept: 'by + reflexive',
      difficulty: 3,
      prompt: 'Corrige el error: "She lives by her self."',
      promptTranslation: 'Ella vive sola.',
      correctAnswer: 'She lives by herself.',
      acceptedAnswers: ['She lives by herself', 'She lives by herself.', 'she lives by herself'],
      acceptApproximate: true,
      explanation: '"Herself" es una sola palabra. → She lives by herself.',
    },
    {
      id: 'a2-m10-l2-mt5',
      type: 'multiple_choice',
      concept: 'by + reflexive',
      difficulty: 4,
      prompt: '¿Cuál es la forma correcta?',
      promptTranslation: 'Which is the correct form?',
      correctAnswer: 'I live by myself.',
      options: ['I live myself.', 'I live by myself.', 'I live by my self.'],
      explanation: 'Para "vivo solo" necesitamos "by myself" (una sola palabra). → I live by myself.',
    },
  ],
  reviewItems: ['a2-m10-l1'],
  prerequisites: ['a2-m10-l1'],
}
