import type { Lesson } from '../../types'

export const lesson103EachOther: Lesson = {
  id: 'a2-m10-l3',
  moduleId: 'm10-reflexives',
  order: 2,
  title: 'each other (el uno al otro)',
  objective: 'Usar "each other" para expresar que dos o más personas hacen algo mutuamente (el uno al otro).',
  explanation_es: `"Each other" significa "el uno al otro" o "mutuamente". Se usa cuando dos o más personas hacen algo entre ellas.

- We help each other. = Nos ayudamos el uno al otro (mutuamente).
- They love each other. = Se quieren el uno al otro.
- My friends and I send each other messages. = Mis amigos y yo nos enviamos mensajes el uno al otro.

Diferencia clave entre "ourselves" y "each other":
- "Ourselves" = a nosotros mismos (la acción vuelve al mismo grupo).
  - We help ourselves. = Nos ayudamos a nosotros mismos.
- "Each other" = el uno al otro (mutuamente, entre dos o más).
  - We help each other. = Nos ayudamos mutuamente.

OJO: en inglés "each other" es una expresión fija de dos palabras. No la confundas con "ourselves". Si el significado es "mutuamente", usa "each other".`,
  examples: [
    { english: 'We help each other.', spanish: 'Nos ayudamos el uno al otro.', note: 'mutuamente' },
    { english: 'They love each other.', spanish: 'Se quieren el uno al otro.' },
    { english: 'My friends and I send each other messages.', spanish: 'Mis amigos y yo nos enviamos mensajes el uno al otro.' },
    { english: 'The two teams know each other well.', spanish: 'Los dos equipos se conocen bien.' },
    { english: 'We should respect each other.', spanish: 'Deberíamos respetarnos mutuamente.' },
  ],
  rule: `Regla:
- "Each other" = el uno al otro / mutuamente. Se usa entre dos o más personas que hacen algo entre sí.
- "Ourselves" (reflexivo) = a nosotros mismos. No significa "mutuamente".
- Ejemplo: We help each other (nos ayudamos mutuamente) vs We help ourselves (nos ayudamos a nosotros mismos).`,
  formation: {
    title: 'Cómo se forma "each other"',
    intro: '"Each other" significa "el uno al otro" o "mutuamente" y se usa cuando dos o más personas hacen algo entre sí. No confundas con los reflexivos.',
    patterns: [
      {
        name: 'each other (mutuamente)',
        formula: 'sujeto (dos o más) + verbo + each other',
        examples: [
          { english: 'We help each other.', spanish: 'Nos ayudamos el uno al otro.' },
          { english: 'They love each other.', spanish: 'Se quieren el uno al otro.' },
        ],
        note: 'La acción es mutua: cada uno hace algo al otro.',
      },
      {
        name: 'Con objeto directo',
        formula: 'sujeto + verbo + each other + objeto',
        examples: [
          { english: 'My friends and I send each other messages.', spanish: 'Mis amigos y yo nos enviamos mensajes el uno al otro.' },
          { english: 'We tell each other our secrets.', spanish: 'Nos contamos nuestros secretos.' },
        ],
        note: '"Each other" va después del verbo, antes del objeto: send each other messages.',
      },
    ],
    notes: [
      '"Each other" son dos palabras separadas y sin -s al final: each other, no "eachothers".',
      'each other (mutuamente) ≠ ourselves (a nosotros mismos): We help each other vs We help ourselves.',
      'Con dos o más personas siempre "each other"; es una expresión fija.',
    ],
  },
  commonMistakes: [
    { wrong: '❌ We help ourselves.', correct: '✅ We help each other.', explanation: 'Si el significado es "mutuamente" (el uno al otro), usamos "each other". "Ourselves" = a nosotros mismos.' },
    { wrong: '❌ They love eachothers.', correct: '✅ They love each other.', explanation: '"Each other" son dos palabras separadas, sin "s" al final: each other, no "eachothers".' },
    { wrong: '❌ We send messages each other.', correct: '✅ We send each other messages.', explanation: '"Each other" va después del verbo, antes del objeto: send each other messages.' },
  ],
  vocabulary: [
    { word: 'each other', translation_es: 'el uno al otro, mutuamente', level: 'A2', category: 'expressions', partOfSpeech: 'phrase', example: 'They talk to each other every day.', exampleTranslation: 'Hablaron entre ellos todos los días.' },
    { word: 'mutually', translation_es: 'mutuamente', level: 'A2', category: 'adverbs', partOfSpeech: 'adverb', example: 'We help each other.', exampleTranslation: 'Nos ayudamos mutuamente.' },
    { word: 'one another', translation_es: 'el uno al otro (más de dos)', level: 'A2', category: 'expressions', partOfSpeech: 'phrase', example: 'The students help one another.', exampleTranslation: 'Los estudiantes se ayudan unos a otros.' },
    { word: 'know each other', translation_es: 'conocerse el uno al otro', level: 'A2', category: 'expressions', partOfSpeech: 'phrase', example: 'We know each other very well.', exampleTranslation: 'Nos conocemos muy bien.' },
  ],
  grammarPoints: [
    {
      id: 'gp-each-other',
      level: 'A2',
      name: 'each other (reciprocal)',
      explanation_es: '"Each other" expresa una acción mutua entre dos o más personas (el uno al otro). No debe confundirse con los reflexivos (ourselves = a nosotros mismos).',
      formula: 'subject + verb + each other',
      examples: ['We help each other.', 'They love each other.', 'My friends and I send each other messages.'],
    },
  ],
  exercises: [
    {
      id: 'a2-m10-l3-ex1',
      type: 'multiple_choice',
      concept: 'each other',
      difficulty: 1,
      prompt: 'Completa: "We help ___."',
      promptTranslation: 'Nos ayudamos el uno al otro.',
      correctAnswer: 'each other',
      options: ['each other', 'ourselves', 'our selves'],
      explanation: 'Si nos ayudamos mutuamente (el uno al otro), usamos "each other". → We help each other.',
    },
    {
      id: 'a2-m10-l3-ex2',
      type: 'fill_blank',
      concept: 'each other',
      difficulty: 2,
      prompt: 'Completa: "They love ___ very much."',
      promptTranslation: 'Se quieren el uno al otro muchísimo.',
      correctAnswer: 'each other',
      acceptedAnswers: ['each other', 'Each other'],
      explanation: 'Amor mutuo entre dos personas = love each other. → They love each other very much.',
    },
    {
      id: 'a2-m10-l3-ex3',
      type: 'multiple_choice',
      concept: 'each other',
      difficulty: 2,
      prompt: 'Completa: "My friends and I send ___ messages."',
      promptTranslation: 'Mis amigos y yo nos enviamos mensajes el uno al otro.',
      correctAnswer: 'each other',
      options: ['each other', 'ourselves', 'each others'],
      explanation: '"Cada uno envía al otro" = send each other messages. Recuerda: "each other" sin -s.',
    },
    {
      id: 'a2-m10-l3-ex4',
      type: 'match',
      concept: 'each other vs reflexive',
      difficulty: 3,
      prompt: 'Relaciona cada frase con su significado correcto.',
      promptTranslation: 'Match each sentence with its correct meaning.',
      correctAnswer: 'We help each other.=Nos ayudamos mutuamente; We help ourselves.=Nos ayudamos a nosotros mismos; They love each other.=Se quieren el uno al otro; She looked at herself.=Ella se miró a sí misma; We enjoy ourselves.=Nos divertimos',
      pairs: [
        { left: 'We help each other.', right: 'Nos ayudamos mutuamente.' },
        { left: 'We help ourselves.', right: 'Nos ayudamos a nosotros mismos.' },
        { left: 'They love each other.', right: 'Se quieren el uno al otro.' },
        { left: 'She looked at herself.', right: 'Ella se miró a sí misma.' },
        { left: 'We enjoy ourselves.', right: 'Nos divertimos.' },
      ],
      explanation: '"Each other" expresa una acción mutua (el uno al otro); los reflexivos (ourselves, herself) indican que la acción vuelve a la misma persona.',
    },
    {
      id: 'a2-m10-l3-ex5',
      type: 'translate',
      concept: 'each other',
      difficulty: 3,
      prompt: 'Traduce: "Nos enviamos mensajes el uno al otro."',
      promptTranslation: 'We send each other messages.',
      correctAnswer: 'We send each other messages.',
      acceptedAnswers: ['We send each other messages', 'We send messages to each other', 'we send each other messages.', 'We send each other messages.'],
      acceptApproximate: true,
      explanation: '"Enviarse mensajes mutuamente" = send each other messages (o send messages to each other).',
    },
    {
      id: 'a2-m10-l3-ex6',
      type: 'error_correction',
      concept: 'each other',
      difficulty: 3,
      prompt: 'Corrige el error (queremos decir "mutuamente"): "We help ourselves."',
      promptTranslation: 'Nos ayudamos el uno al otro.',
      correctAnswer: 'We help each other.',
      acceptedAnswers: ['We help each other', 'We help each other.', 'we help each other'],
      acceptApproximate: true,
      explanation: 'Si el significado es "mutuamente", usamos "each other", no "ourselves" (a nosotros mismos). → We help each other.',
    },
    {
      id: 'a2-m10-l3-ex7',
      type: 'reorder',
      concept: 'each other',
      difficulty: 2,
      prompt: 'Ordena las palabras: They / help / each other / .',
      promptTranslation: 'Ellos se ayudan el uno al otro.',
      correctAnswer: 'They help each other.',
      words: ['They', 'help', 'each other'],
      explanation: 'Orden: sujeto + verbo + each other. → They help each other.',
    },
    {
      id: 'a2-m10-l3-ex8',
      type: 'true_false',
      concept: 'each other',
      difficulty: 3,
      prompt: '"Each other" significa "a nosotros mismos".',
      promptTranslation: '"Each other" means "a nosotros mismos".',
      correctAnswer: 'false',
      acceptedAnswers: ['False', 'FALSE', 'f'],
      explanation: 'Falso. "Each other" = el uno al otro (mutuamente). "A nosotros mismos" es "ourselves".',
    },
    {
      id: 'a2-m10-l3-ex9',
      type: 'multiple_choice',
      concept: 'each other',
      difficulty: 3,
      prompt: 'Completa: "The two friends text ___ every day."',
      promptTranslation: 'Los dos amigos se escriben mensajes todos los días.',
      correctAnswer: 'each other',
      options: ['each other', 'themselves', 'each others'],
      explanation: 'Acción mutua entre dos amigos = text each other. "Themselves" sería "a sí mismos", que no tiene sentido aquí.',
    },
    {
      id: 'a2-m10-l3-ex10',
      type: 'fill_blank',
      concept: 'each other',
      difficulty: 4,
      prompt: 'Completa: "Couples should support ___."',
      promptTranslation: 'Las parejas deberían apoyarse mutuamente.',
      correctAnswer: 'each other',
      acceptedAnswers: ['each other', 'Each other'],
      explanation: 'Entre las dos personas de la pareja hay apoyo mutuo: support each other.',
    },
  ],
  miniTest: [
    {
      id: 'a2-m10-l3-mt1',
      type: 'multiple_choice',
      concept: 'each other',
      difficulty: 2,
      prompt: 'Completa: "Ana and Luis write ___ every week."',
      promptTranslation: 'Ana y Luis se escriben todas las semanas.',
      correctAnswer: 'each other',
      options: ['each other', 'themselves', 'themself'],
      explanation: 'Acción mutua entre Ana y Luis = write each other. → Ana and Luis write each other every week.',
    },
    {
      id: 'a2-m10-l3-mt2',
      type: 'fill_blank',
      concept: 'each other',
      difficulty: 2,
      prompt: 'Completa: "We look at ___ and smile."',
      promptTranslation: 'Nos miramos el uno al otro y sonreímos.',
      correctAnswer: 'each other',
      acceptedAnswers: ['each other', 'Each other'],
      explanation: 'Mirarse mutuamente = look at each other. → We look at each other and smile.',
    },
    {
      id: 'a2-m10-l3-mt3',
      type: 'multiple_choice',
      concept: 'each other',
      difficulty: 3,
      prompt: '¿Qué frase significa "Nos ayudamos mutuamente"?',
      promptTranslation: 'Which sentence means "We help each other"?',
      correctAnswer: 'We help each other.',
      options: ['We help each other.', 'We help ourselves.', 'We help our self.'],
      explanation: '"Mutuamente" = each other. "Ourselves" significa "a nosotros mismos", no "mutuamente".',
    },
    {
      id: 'a2-m10-l3-mt4',
      type: 'translate',
      concept: 'each other',
      difficulty: 3,
      prompt: 'Traduce: "Se quieren el uno al otro."',
      promptTranslation: 'They love each other.',
      correctAnswer: 'They love each other.',
      acceptedAnswers: ['They love each other', 'They love each other.', 'they love each other', 'They love one another'],
      acceptApproximate: true,
      explanation: '"Quererse mutuamente" = love each other. → They love each other.',
    },
    {
      id: 'a2-m10-l3-mt5',
      type: 'error_correction',
      concept: 'each other',
      difficulty: 4,
      prompt: 'Corrige el error: "They are very good friends and help eachothers."',
      promptTranslation: 'Son muy buenos amigos y se ayudan mutuamente.',
      correctAnswer: 'They are very good friends and help each other.',
      acceptedAnswers: ['They are very good friends and help each other', 'They help each other', 'they are very good friends and help each other.'],
      acceptApproximate: true,
      explanation: '"Each other" son dos palabras separadas y sin "s" final: each other, no "eachothers".',
    },
  ],
  reviewItems: ['a2-m10-l2'],
  prerequisites: ['a2-m10-l2'],
}
