import type { Lesson } from '../../types'

export const lesson56ModuleTest: Lesson = {
  id: 'a1-m5-l6',
  moduleId: 'm5-routines',
  order: 5,
  title: 'Mini-test + Checkpoint del Módulo 5',
  objective: 'Evaluar el dominio del Present Simple y el vocabulario de rutinas.',
  explanation_es: `Esta es la lección de evaluación final del Módulo 5. Antes del mini-test, repasemos lo esencial:

**Present Simple — 3 formas:**
- Afirmativo: Sujeto + verbo (+ -s en 3ª persona). "She works in a bank."
- Negativo: Sujeto + don\'t/doesn\'t + verbo (base). "She doesn\'t work on Sunday."
- Pregunta: Do/Does + sujeto + verbo (base)? "Does she work in a bank?"
- WH: "Where do you work?" / "What does he do?" (profesión).

**Clave:** La -s de la 3ª persona aparece UNA sola vez — en el verbo (afirmativo) o en "does/doesn\'t" (negativo y preguntas), nunca en ambos.

**Vocabulario de rutinas:**
get up, have breakfast, go to work, go to school, have lunch, go home (sin "to"), have dinner, go to bed, take a shower, brush one's teeth (+ posesivo).

**Irregular a recordar:** have → has (afirmativo). Pero después de don\'t/doesn\'t/Do/Does, vuelve a "have": "She has a car." / "She doesn\'t have a car." / "Does she have a car?"`,
  examples: [
    { english: 'She works in a bank.', spanish: 'Ella trabaja en un banco.' },
    { english: 'I don\'t drink coffee.', spanish: 'No bebo café.' },
    { english: 'Does he work?', spanish: '¿Trabaja él?' },
    { english: 'What does he do?', spanish: '¿A qué se dedica?' },
    { english: 'I get up at 7.', spanish: 'Me levanto a las 7.' },
  ],
  rule: `**Resumen del módulo:**
- 3 formas: afirmativo (S+V+ -s en 3ª), negativo (S+don\'t/doesn\'t+V), pregunta (Do/Does+S+V).
- Tras don\'t/doesn\'t/Do/Does, el verbo principal va en infinitivo (sin -s).
- WH-questions: palabra interrogativa + Do/Does + sujeto + verbo.
- have → has (afirmativo); después de auxiliar vuelve a "have".
- "go home" (sin "to"), "have breakfast/lunch/dinner" (con "have").`,
  commonMistakes: [
    { wrong: '❌ She doesn\'t works.', correct: '✅ She doesn\'t work.', explanation: 'Tras "doesn\'t", el verbo no lleva -s.' },
    { wrong: '❌ Does she works?', correct: '✅ Does she work?', explanation: 'Tras "does", el verbo no lleva -s.' },
    { wrong: '❌ I go to home.', correct: '✅ I go home.', explanation: '"Home" no lleva "to": go home.' },
  ],
  vocabulary: [],
  grammarPoints: [],
  exercises: [
    {
      id: 'a1-m5-l6-ex1',
      type: 'multiple_choice',
      concept: 'module 5 - present simple affirmative',
      difficulty: 1,
      prompt: 'Completa: "She ___ in London."',
      promptTranslation: 'Ella vive en Londres.',
      correctAnswer: 'lives',
      options: ['live', 'lives', 'livees'],
      explanation: 'Afirmativo, she: añade -s → lives.',
    },
    {
      id: 'a1-m5-l6-ex2',
      type: 'multiple_choice',
      concept: 'module 5 - present simple affirmative - spelling',
      difficulty: 2,
      prompt: 'Completa: "He ___ TV."',
      promptTranslation: 'Él ve la tele.',
      correctAnswer: 'watches',
      options: ['watch', 'watchs', 'watches'],
      explanation: 'Afirmativo, he: verbo en -ch → -es → watches.',
    },
    {
      id: 'a1-m5-l6-ex3',
      type: 'fill_blank',
      concept: 'module 5 - negative',
      difficulty: 2,
      prompt: 'Completa: "I ___ drink coffee." (negativa)',
      promptTranslation: 'No bebo café.',
      correctAnswer: 'don\'t',
      acceptedAnswers: ['do not'],
      explanation: 'Con "I" usamos "don\'t". → I don\'t drink coffee.',
    },
    {
      id: 'a1-m5-l6-ex4',
      type: 'fill_blank',
      concept: 'module 5 - verb after doesn\'t',
      difficulty: 2,
      prompt: 'Completa: "He doesn\'t ___ a car." (verbo: have)',
      promptTranslation: 'Él no tiene coche.',
      correctAnswer: 'have',
      acceptedAnswers: ['Have'],
      explanation: 'Tras "doesn\'t", el irregular "have" vuelve a la base: have (no "has").',
    },
    {
      id: 'a1-m5-l6-ex5',
      type: 'error_correction',
      concept: 'module 5 - verb after doesn\'t',
      difficulty: 3,
      prompt: 'Corrige el error: "She doesn\'t watches TV."',
      correctAnswer: 'She doesn\'t watch TV.',
      acceptedAnswers: ['She doesn\'t watch TV', 'She does not watch TV.'],
      acceptApproximate: true,
      explanation: 'Tras "doesn\'t", el verbo no lleva -s: watch (no "watches").',
    },
    {
      id: 'a1-m5-l6-ex6',
      type: 'reorder',
      concept: 'module 5 - questions',
      difficulty: 3,
      prompt: 'Ordena: Does / she / work / in / a bank',
      promptTranslation: '¿Ella trabaja en un banco?',
      correctAnswer: 'Does she work in a bank?',
      words: ['Does', 'she', 'work', 'in', 'a bank'],
      explanation: 'Does + sujeto + verbo base + resto. → Does she work in a bank?',
    },
    {
      id: 'a1-m5-l6-ex7',
      type: 'translate',
      concept: 'module 5 - WH questions',
      difficulty: 3,
      prompt: 'Traduce: "¿Dónde trabajas?"',
      correctAnswer: 'Where do you work?',
      acceptedAnswers: ['Where do you work', 'where do you work?'],
      acceptApproximate: true,
      explanation: 'WH + Do + sujeto + verbo. → Where do you work?',
    },
    {
      id: 'a1-m5-l6-ex8',
      type: 'multiple_choice',
      concept: 'module 5 - daily routine vocabulary',
      difficulty: 2,
      prompt: 'Elige la opción correcta: "___ home at 6."',
      promptTranslation: 'Vuelvo a casa a las 6.',
      correctAnswer: 'I go',
      options: ['I go', 'I go to', 'I go at'],
      explanation: 'Con "home" no se usa "to": I go home.',
    },
    {
      id: 'a1-m5-l6-ex9',
      type: 'translate',
      concept: 'module 5 - daily routine',
      difficulty: 3,
      prompt: 'Traduce: "Ella se ducha por la mañana."',
      correctAnswer: 'She takes a shower in the morning.',
      acceptedAnswers: ['She takes a shower in the morning', 'she takes a shower in the morning.'],
      acceptApproximate: true,
      explanation: '3ª persona: take → takes. → She takes a shower in the morning.',
    },
    {
      id: 'a1-m5-l6-ex10',
      type: 'match',
      concept: 'module 5 - present simple forms review',
      difficulty: 3,
      prompt: 'Relaciona cada frase con su tipo.',
      promptTranslation: 'Match each sentence with its form.',
      correctAnswer: '',
      pairs: [
        { left: 'She works in a bank.', right: 'Afirmativo' },
        { left: 'She doesn\'t work on Sunday.', right: 'Negativo' },
        { left: 'Does she work in a bank?', right: 'Pregunta (yes/no)' },
        { left: 'Where does she work?', right: 'WH-question' },
        { left: 'What does he do?', right: 'Pregunta por la profesión' },
      ],
      explanation: 'Identifica: afirmativo (S+V+ -s), negativo (S+doesn\'t+V), yes/no (Does/Do+S+V?), WH (palabra interrogativa + Do/Does + sujeto + V), profesión (What + does + sujeto + do?).',
    },
  ],
  miniTest: [
    {
      id: 'a1-m5-l6-mt1',
      type: 'multiple_choice',
      concept: 'module 5 final - affirmative -s',
      difficulty: 1,
      prompt: 'Completa: "She ___ English."',
      promptTranslation: 'Ella estudia inglés.',
      correctAnswer: 'studies',
      options: ['studys', 'studyes', 'studies'],
      explanation: 'Consonante + y → -ies → studies.',
    },
    {
      id: 'a1-m5-l6-mt2',
      type: 'multiple_choice',
      concept: 'module 5 final - irregular have',
      difficulty: 1,
      prompt: 'Completa: "He ___ two children."',
      promptTranslation: 'Él tiene dos hijos.',
      correctAnswer: 'has',
      options: ['have', 'haves', 'has'],
      explanation: 'Irregular: have → has en he/she/it.',
    },
    {
      id: 'a1-m5-l6-mt3',
      type: 'fill_blank',
      concept: 'module 5 final - negative',
      difficulty: 2,
      prompt: 'Completa: "She ___ work on Sunday." (negativa)',
      promptTranslation: 'Ella no trabaja los domingos.',
      correctAnswer: 'doesn\'t',
      acceptedAnswers: ['does not'],
      explanation: 'Con "she" usamos "doesn\'t". → She doesn\'t work on Sunday.',
    },
    {
      id: 'a1-m5-l6-mt4',
      type: 'error_correction',
      concept: 'module 5 final - verb after Does',
      difficulty: 2,
      prompt: 'Corrige el error: "Does she works in a bank?"',
      correctAnswer: 'Does she work in a bank?',
      acceptedAnswers: ['Does she work in a bank', 'does she work in a bank?'],
      acceptApproximate: true,
      explanation: 'Tras "does", el verbo no lleva -s: work (no "works").',
    },
    {
      id: 'a1-m5-l6-mt5',
      type: 'error_correction',
      concept: 'module 5 final - don\'t vs doesn\'t',
      difficulty: 2,
      prompt: 'Corrige el error: "She don\'t like pizza."',
      correctAnswer: 'She doesn\'t like pizza.',
      acceptedAnswers: ['She doesn\'t like pizza', 'She does not like pizza.'],
      acceptApproximate: true,
      explanation: 'Con "she" usamos "doesn\'t". → She doesn\'t like pizza.',
    },
    {
      id: 'a1-m5-l6-mt6',
      type: 'translate',
      concept: 'module 5 final - WH + profession',
      difficulty: 3,
      prompt: 'Traduce: "¿A qué se dedica él? (profesión)"',
      correctAnswer: 'What does he do?',
      acceptedAnswers: ['What does he do', 'what does he do?'],
      acceptApproximate: true,
      explanation: 'Para preguntar la profesión usamos: What + does + sujeto + do? → What does he do?',
    },
    {
      id: 'a1-m5-l6-mt7',
      type: 'translate',
      concept: 'module 5 final - daily routine',
      difficulty: 3,
      prompt: 'Traduce: "Cenamos a las 8."',
      correctAnswer: 'We have dinner at 8.',
      acceptedAnswers: ['We have dinner at 8', 'we have dinner at 8.', 'We have dinner at 8 p.m.'],
      acceptApproximate: true,
      explanation: 'have dinner = cenar. → We have dinner at 8.',
    },
    {
      id: 'a1-m5-l6-mt8',
      type: 'true_false',
      concept: 'module 5 final - rule',
      difficulty: 3,
      prompt: 'Frase correcta: "He doesn\'t has a car."',
      promptTranslation: 'Él no tiene coche.',
      correctAnswer: 'false',
      acceptedAnswers: ['False', 'FALSE'],
      explanation: 'Incorrecto. Tras "doesn\'t" el verbo vuelve a la base: "He doesn\'t have a car." (no "has").',
    },
  ],
  reviewItems: ['a1-m5-l5'],
  prerequisites: ['a1-m5-l5'],
}