import type { Lesson } from '../../types'

export const lesson45MiniTest: Lesson = {
  id: 'a1-m4-l5',
  moduleId: 'm4-family-possessives',
  order: 4,
  title: 'Mini-test: Familia, posesivos y descripciones',
  objective: 'Repasar todo lo aprendido sobre la familia, los posesivos y las descripciones antes del checkpoint del módulo.',
  explanation_es: `En este mini-test vamos a repasar todo el módulo:

1. Vocabulario de la familia: father, mother, brother, sister, grandfather, grandmother, uncle, aunt, cousin...
2. Los adjetivos posesivos: my, your, his, her, our, their.
3. El genitivo sajón ('s): John's car = el coche de John.
4. Descripciones con "to be" + adjetivo: She is tall.

Recuerda:
- Los posesivos (my, your, his...) van antes del sustantivo y NO llevan 's.
- El genitivo sajón ('s) indica el "dueño": my brother's name = el nombre de mi hermano.
- Los adjetivos no cambian de género: She is tall, He is tall.

¡Buena suerte!`,
  examples: [
    { english: 'My name is María.', spanish: 'Mi nombre es María.', note: 'my = mi' },
    { english: "María's brother is a doctor.", spanish: 'El hermano de María es médico.', note: "'s = de (genitivo sajón)" },
    { english: 'Her name is Ana.', spanish: 'Su nombre (de ella) es Ana.', note: 'her = de ella' },
    { english: 'They are happy.', spanish: 'Ellos están felices.', note: 'adjetivo sin cambio de género' },
  ],
  rule: `Resumen del módulo:

- Posesivos: my (mi), your (tu/su), his (su, de él), her (su, de ella), our (nuestro), their (su, de ellos).
- Genitivo sajón: owner + 's + thing → John's car, my mother's house.
- Plural ya terminado en -s: solo apostrofo → my parents' house.
- Descripciones: Subject + to be + adjective → My sister is tall.
- Adjetivos invariables: no cambian con género ni número.`,
  commonMistakes: [
    { wrong: '❌ His is name is John.', correct: '✅ His name is John.', explanation: 'El posesivo "his" va antes del nombre; no lo confundas con "he is".' },
    { wrong: '❌ I have 30 years.', correct: '✅ I am 30 years old.', explanation: 'Para la edad usamos "to be", no "have".' },
    { wrong: '❌ They is friendly.', correct: '✅ They are friendly.', explanation: 'Con "they" (plural) usamos "are".' },
  ],
  vocabulary: [],
  grammarPoints: [],
  exercises: [
    {
      id: 'a1-m4-l5-ex1',
      type: 'fill_blank',
      concept: 'possessive adjectives',
      difficulty: 2,
      prompt: 'Completa con el posesivo correcto: "___ name is María." (yo)',
      correctAnswer: 'My',
      acceptedAnswers: ['my', 'My'],
      explanation: 'Para "mi nombre" usamos "my". → My name is María.',
    },
    {
      id: 'a1-m4-l5-ex2',
      type: 'fill_blank',
      concept: 's possessive',
      difficulty: 2,
      prompt: 'Completa con "s": "This is __ car." (John)',
      correctAnswer: "John's",
      acceptedAnswers: ["John's", 'Johns'],
      explanation: 'Genitivo sajón: John + \'s → John\'s car = el coche de John.',
    },
    {
      id: 'a1-m4-l5-ex3',
      type: 'multiple_choice',
      concept: 'possessive adjectives',
      difficulty: 2,
      prompt: 'Completa: "___ brother is a teacher." (de ella)',
      promptTranslation: 'Su hermano (de ella) es profesor.',
      correctAnswer: 'Her',
      options: ['His', 'Her', 'Their'],
      explanation: 'Para "de ella" usamos "her". → Her brother is a teacher.',
    },
    {
      id: 'a1-m4-l5-ex4',
      type: 'multiple_choice',
      concept: 'family vocabulary',
      difficulty: 1,
      prompt: '¿Cómo se dice "hermana" en inglés?',
      correctAnswer: 'sister',
      options: ['brother', 'sister', 'mother'],
      explanation: '"Sister" = hermana. "Brother" = hermano, "mother" = madre.',
    },
    {
      id: 'a1-m4-l5-ex5',
      type: 'match',
      concept: 'family vocabulary',
      difficulty: 2,
      prompt: 'Relaciona cada miembro de la familia con su traducción:',
      pairs: [
        { left: 'father', right: 'padre' },
        { left: 'mother', right: 'madre' },
        { left: 'grandfather', right: 'abuelo' },
        { left: 'uncle', right: 'tío' },
        { left: 'cousin', right: 'primo/prima' },
        { left: 'wife', right: 'esposa' },
      ],
      correctAnswer: 'father=padre, mother=madre, grandfather=abuelo, uncle=tío, cousin=primo, wife=esposa',
      explanation: 'father=padre, mother=madre, grandfather=abuelo, uncle=tío, cousin=primo/prima, wife=esposa.',
    },
    {
      id: 'a1-m4-l5-ex6',
      type: 'error_correction',
      concept: 'possessive adjectives vs s',
      difficulty: 3,
      prompt: 'Encuentra el error: "His is name is John."',
      correctAnswer: 'His name is John.',
      acceptedAnswers: ['His name is John', 'His name is John.', "His name's John", "His name's John."],
      acceptApproximate: true,
      explanation: 'El posesivo "his" va directamente antes del sustantivo: His name is John. (No decimos "His is name").',
    },
    {
      id: 'a1-m4-l5-ex7',
      type: 'translate',
      concept: 's possessive',
      difficulty: 3,
      prompt: 'Traduce: "La casa de mis padres."',
      correctAnswer: "my parents' house",
      acceptedAnswers: ["my parents' house", "my parents' house.", 'the house of my parents', 'the house of my parents.'],
      acceptApproximate: true,
      explanation: '"Parents" ya termina en -s, así que solo añadimos el apóstrofo: parents\' house = casa de mis padres.',
    },
    {
      id: 'a1-m4-l5-ex8',
      type: 'reading',
      concept: 'family reading comprehension',
      difficulty: 4,
      prompt: 'Lee el texto y responde:',
      reading: {
        text: 'My sister is married. Her husband is a doctor. His name is Tom. They have a son. His name is Leo. Leo is 3 years old. He is very happy and funny. My sister\'s house is big. Our parents live near them.',
        translation: 'Mi hermana está casada. Su esposo es médico. Su nombre es Tom. Tienen un hijo. Su nombre es Leo. Leo tiene 3 años. Es muy feliz y divertido. La casa de mi hermana es grande. Nuestros padres viven cerca de ellos.',
        questions: [
          {
            id: 'a1-m4-l5-ex8-q1',
            type: 'multiple_choice',
            concept: 'family reading comprehension',
            difficulty: 4,
            prompt: '¿Quién es Tom?',
            correctAnswer: 'the husband of my sister',
            options: ['the father of my sister', 'the husband of my sister', 'the son of my sister'],
            explanation: 'El texto dice: "Her husband is a doctor. His name is Tom." Tom es el esposo de la hermana.',
          },
          {
            id: 'a1-m4-l5-ex8-q2',
            type: 'multiple_choice',
            concept: 'family reading comprehension',
            difficulty: 4,
            prompt: '¿Cuántos años tiene Leo?',
            correctAnswer: '3',
            options: ['2', '3', '4'],
            explanation: 'El texto dice: "Leo is 3 years old."',
          },
          {
            id: 'a1-m4-l5-ex8-q3',
            type: 'multiple_choice',
            concept: 'family reading comprehension',
            difficulty: 4,
            prompt: '¿Cómo es la casa de la hermana?',
            correctAnswer: 'big',
            options: ['small', 'big', 'new'],
            explanation: 'El texto dice: "My sister\'s house is big."',
          },
        ],
      },
      correctAnswer: 'reading complete',
      explanation: 'Lee con atención: Tom es el esposo, Leo tiene 3 años y la casa es grande.',
    },
    {
      id: 'a1-m4-l5-ex9',
      type: 'select_correct',
      concept: 'descriptions with to be',
      difficulty: 3,
      prompt: '¿Cuál de estas frases es correcta?',
      correctAnswer: 'My grandfather is old.',
      options: ['My grandfather is old.', 'My grandfather is older old.', 'My grandfather am old.'],
      explanation: '"My grandfather" (él) + is + old. Las otras opciones tienen errores de verbo o de redundancia.',
    },
    {
      id: 'a1-m4-l5-ex10',
      type: 'translate',
      concept: 'possessive adjectives',
      difficulty: 3,
      prompt: 'Traduce: "Sus nombres son Lisa y Tom." (de ellos)',
      correctAnswer: 'Their names are Lisa and Tom.',
      acceptedAnswers: ['Their names are Lisa and Tom', 'Their names are Lisa and Tom.'],
      acceptApproximate: true,
      explanation: '"Their" = de ellos (posesivo). Their names are Lisa and Tom.',
    },
  ],
  miniTest: [
    {
      id: 'a1-m4-l5-mt1',
      type: 'multiple_choice',
      concept: 'family vocabulary',
      difficulty: 1,
      prompt: '¿Cómo se dice "madre" en inglés?',
      correctAnswer: 'mother',
      options: ['mother', 'father', 'aunt'],
      explanation: '"Mother" = madre. "Father" = padre, "aunt" = tía.',
    },
    {
      id: 'a1-m4-l5-mt2',
      type: 'fill_blank',
      concept: 'possessive adjectives',
      difficulty: 2,
      prompt: 'Completa: "This is ___ book." (de él)',
      correctAnswer: 'his',
      explanation: 'Para "de él" usamos "his". → This is his book.',
    },
    {
      id: 'a1-m4-l5-mt3',
      type: 'fill_blank',
      concept: 's possessive',
      difficulty: 2,
      prompt: 'Completa con "s": "This is Tom __ car."',
      correctAnswer: "Tom's",
      acceptedAnswers: ["Tom's", 'Toms'],
      explanation: "Genitivo sajón: Tom + 's → Tom's car = el coche de Tom.",
    },
    {
      id: 'a1-m4-l5-mt4',
      type: 'translate',
      concept: 'descriptions with to be',
      difficulty: 3,
      prompt: 'Traduce: "Mi abuela es amable."',
      correctAnswer: 'My grandmother is friendly.',
      acceptedAnswers: ['My grandmother is friendly', 'My grandmother is friendly.', 'My grandmother is kind', 'My grandmother is nice', 'My granny is friendly', 'My granny is friendly.'],
      acceptApproximate: true,
      explanation: '"My grandmother" = mi abuela, "is" = es, "friendly" = amable. → My grandmother is friendly.',
    },
    {
      id: 'a1-m4-l5-mt5',
      type: 'error_correction',
      concept: 'possessive adjectives',
      difficulty: 4,
      prompt: 'Corrige el error: "Their is names are Lisa and Tom."',
      correctAnswer: 'Their names are Lisa and Tom.',
      acceptedAnswers: ['Their names are Lisa and Tom', 'Their names are Lisa and Tom.'],
      acceptApproximate: true,
      explanation: 'El posesivo "their" va directamente antes del sustantivo: Their names are Lisa and Tom.',
    },
  ],
  reviewItems: ['a1-m4-l4'],
  prerequisites: ['a1-m4-l4'],
}