import type { Lesson } from '../../types'

export const lesson72ReportedQuestions: Lesson = {
  id: 'b1-m7-l2',
  moduleId: 'm7-reported-speech',
  order: 1,
  title: 'Estilo indirecto: preguntas (if/whether + wh-)',
  objective: 'Convertir preguntas directas en preguntas indirectas con "ask if/whether" (sí/no) y "ask + wh- + sujeto + verbo" (abiertas), sin inversión.',
  explanation_es: `Para contar una pregunta en estilo indirecto usamos "ask" (preguntar). Hay dos tipos:

1) Preguntas de sí/no → "ask if" o "ask whether":
- Directo: "Are you tired?" → He asked me if I was tired.
- Directo: "Did you see the film?" → They asked me if I had seen the film.

2) Preguntas abiertas (where, what, when, how...) → mantenemos la palabra interrogativa y usamos el orden normal de frase: wh- + sujeto + verbo. ¡Sin inversión!
- Directo: "Where do you live?" → She asked me where I lived.

¡CUIDADO! En las preguntas indirectas NO hay inversión. No se usa "did" como auxiliar de pregunta:
- ❌ She asked me where did I live.
- ✅ She asked me where I lived.
- ❌ He asked if did I like coffee.
- ✅ He asked if I liked coffee.

Recuerda también el cambio de tiempo (backshift): are→was, do→did, did→had + participio, will→would.`,
  examples: [
    { english: 'Direct: "Are you tired?" → Reported: He asked me if I was tired.', spanish: 'Directo: "¿Estás cansado?" → Indirecto: Él me preguntó si estaba cansado.', note: 'pregunta de sí/no → ask + if' },
    { english: 'Direct: "Where do you live?" → Reported: She asked me where I lived.', spanish: 'Directo: "¿Dónde vives?" → Indirecto: Ella me preguntó dónde vivía.', note: 'wh- + sujeto + verbo, sin inversión' },
    { english: 'Direct: "Did you see the film?" → Reported: They asked me if I had seen the film.', spanish: 'Directo: "¿Viste la película?" → Indirecto: Ellos me preguntaron si había visto la película.', note: 'did + see → had seen' },
    { english: 'Direct: "Will you come?" → Reported: She asked me if I would come.', spanish: 'Directo: "¿Vendrás?" → Indirecto: Ella me preguntó si vendría.', note: 'will → would' },
    { english: 'Direct: "What time is the meeting?" → Reported: He asked what time the meeting was.', spanish: 'Directo: "¿A qué hora es la reunión?" → Indirecto: Él preguntó a qué hora era la reunión.', note: 'is → was' },
  ],
  rule: `Regla:
- Preguntas de sí/no → ask + if/whether + sujeto + verbo: He asked me if I was tired.
- Preguntas abiertas → ask + wh- (where/what/when/how...) + sujeto + verbo: She asked me where I lived.
- NUNCA hay inversión en la parte indirecta: ❌ "where did I live" → ✅ "where I lived".
- Aplica también el backshift: are→was, do→did, did→had + participio, will→would.`,
  commonMistakes: [
    { wrong: '❌ She asked me where did I live.', correct: '✅ She asked me where I lived.', explanation: 'En las preguntas indirectas no hay inversión: where I lived, no "where did I live".' },
    { wrong: '❌ He asked if did I like coffee.', correct: '✅ He asked if I liked coffee.', explanation: 'Tras "if" no usamos "did" como auxiliar de pregunta: if I liked coffee.' },
    { wrong: '❌ She asked me what time is the meeting.', correct: '✅ She asked me what time the meeting was.', explanation: 'Además de no invertir, el tiempo retrocede: is → was.' },
  ],
  vocabulary: [
    { word: 'reply', translation_es: 'responder, contestar', level: 'B1', category: 'reporting verbs', partOfSpeech: 'verb', example: 'She replied that she was fine.', exampleTranslation: 'Ella respondió que estaba bien.' },
    { word: 'wonder', translation_es: 'preguntarse', level: 'B1', category: 'reporting verbs', partOfSpeech: 'verb', example: 'I wondered where he was.', exampleTranslation: 'Me pregunté dónde estaba.' },
    { word: 'find out', translation_es: 'descubrir, enterarse de', level: 'B1', category: 'phrasal verbs', partOfSpeech: 'phrasal verb', example: 'She asked me where I had found out the news.', exampleTranslation: 'Ella me preguntó dónde me había enterado de la noticia.' },
    { word: 'mention', translation_es: 'mencionar', level: 'B1', category: 'reporting verbs', partOfSpeech: 'verb', example: 'He asked if I had mentioned the problem to the boss.', exampleTranslation: 'Él preguntó si había mencionado el problema al jefe.' },
  ],
  grammarPoints: [
    {
      id: 'gp-reported-questions-b1',
      level: 'B1',
      name: 'Reported questions (if/whether + wh-)',
      explanation_es: 'Las preguntas de sí/no se convierten con "ask + if/whether"; las abiertas mantienen la wh- pero con orden de frase normal (sujeto + verbo) y sin inversión, aplicando el backshift.',
      formula: 'ask + if/whether + sujeto + verbo | ask + wh- + sujeto + verbo',
      examples: ['He asked me if I was tired.', 'She asked me where I lived.', 'They asked me if I had seen the film.'],
    },
  ],
  exercises: [
    {
      id: 'b1-m7-l2-ex1',
      type: 'multiple_choice',
      concept: 'reported questions if whether',
      difficulty: 1,
      prompt: 'Completa: Directo: "Are you tired?" → "He asked me ___ I was tired."',
      promptTranslation: 'Él me preguntó si estaba cansado.',
      correctAnswer: 'if',
      options: ['if', 'that', 'where'],
      explanation: 'Para preguntas de sí/no usamos "if" (o "whether"). → He asked me if I was tired.',
    },
    {
      id: 'b1-m7-l2-ex2',
      type: 'fill_blank',
      concept: 'reported questions wh-',
      difficulty: 2,
      prompt: 'Completa: Directo: "Where do you live?" → "She asked me where I ___."',
      promptTranslation: 'Ella me preguntó dónde vivía.',
      correctAnswer: 'lived',
      acceptedAnswers: ['lived', 'Lived'],
      explanation: 'Cambio de tiempo y sin inversión: do you live → I lived. → She asked me where I lived.',
    },
    {
      id: 'b1-m7-l2-ex3',
      type: 'multiple_choice',
      concept: 'reported questions backshift did',
      difficulty: 2,
      prompt: 'Completa: Directo: "Did you see the film?" → "They asked me if I ___ the film."',
      promptTranslation: 'Ellos me preguntaron si había visto la película.',
      correctAnswer: 'had seen',
      options: ['had seen', 'saw', 'have seen'],
      explanation: '"Did you see" (pasado) retrocede a past perfect: "had seen".',
    },
    {
      id: 'b1-m7-l2-ex4',
      type: 'error_correction',
      concept: 'reported questions no inversion',
      difficulty: 3,
      prompt: 'Corrige el error: "She asked me where did I live."',
      promptTranslation: 'Ella me preguntó dónde vivía.',
      correctAnswer: 'She asked me where I lived.',
      acceptedAnswers: ['She asked me where I lived', 'She asked me where I lived.', 'she asked me where i lived'],
      acceptApproximate: true,
      explanation: 'En las preguntas indirectas no hay inversión: where I lived, no "where did I live".',
    },
    {
      id: 'b1-m7-l2-ex5',
      type: 'reorder',
      concept: 'reported questions if',
      difficulty: 3,
      prompt: 'Ordena las palabras: He / me / if / tired / asked / was / I',
      promptTranslation: 'Él me preguntó si estaba cansado.',
      correctAnswer: 'He asked me if I was tired.',
      words: ['He', 'asked', 'me', 'if', 'I', 'was', 'tired'],
      explanation: 'Orden: sujeto + asked + persona + if + sujeto + verbo. → He asked me if I was tired.',
    },
    {
      id: 'b1-m7-l2-ex6',
      type: 'translate',
      concept: 'reported questions wh-',
      difficulty: 3,
      prompt: 'Traduce: "Me preguntó dónde vivía."',
      promptTranslation: 'She asked me where I lived.',
      correctAnswer: 'She asked me where I lived.',
      acceptedAnswers: ['She asked me where I lived', 'She asked me where I lived.', 'she asked me where i lived'],
      acceptApproximate: true,
      explanation: '"Me preguntó dónde" = asked me where + sujeto + verbo (sin inversión): where I lived.',
    },
    {
      id: 'b1-m7-l2-ex7',
      type: 'match',
      concept: 'reported questions',
      difficulty: 3,
      prompt: 'Relaciona cada pregunta directa con su forma indirecta.',
      promptTranslation: 'Match each direct question with its reported form.',
      correctAnswer: '"Are you tired?"→asked me if I was tired; "Where do you live?"→asked me where I lived; "Did you see the film?"→asked me if I had seen the film; "Will you come?"→asked if I would come; "What time is the meeting?"→asked what time the meeting was',
      pairs: [
        { left: '"Are you tired?"', right: 'He asked me if I was tired.' },
        { left: '"Where do you live?"', right: 'She asked me where I lived.' },
        { left: '"Did you see the film?"', right: 'They asked me if I had seen the film.' },
        { left: '"Will you come?"', right: 'She asked me if I would come.' },
        { left: '"What time is the meeting?"', right: 'He asked what time the meeting was.' },
      ],
      explanation: 'Las de sí/no usan "if"; las abiertas mantienen la wh- con orden normal, y todas aplican el backshift (are→was, did→had seen, will→would, is→was).',
    },
    {
      id: 'b1-m7-l2-ex8',
      type: 'true_false',
      concept: 'reported questions no inversion',
      difficulty: 3,
      prompt: 'La frase "He asked me where did I work" es correcta en estilo indirecto.',
      promptTranslation: '"He asked me where did I work" is correct reported speech.',
      correctAnswer: 'false',
      acceptedAnswers: ['False', 'FALSE', 'f'],
      explanation: 'Falso. Las preguntas indirectas no llevan inversión: "He asked me where I worked".',
    },
    {
      id: 'b1-m7-l2-ex9',
      type: 'fill_blank',
      concept: 'reported questions backshift will',
      difficulty: 3,
      prompt: 'Completa: Directo: "Will you come?" → "She asked me if I ___ come."',
      promptTranslation: 'Ella me preguntó si vendría.',
      correctAnswer: 'would',
      acceptedAnswers: ['would', 'Would'],
      explanation: '"Will" cambia a "would". → She asked me if I would come.',
    },
    {
      id: 'b1-m7-l2-ex10',
      type: 'multiple_choice',
      concept: 'reported questions wh-',
      difficulty: 4,
      prompt: '¿Cuál es la forma correcta de estilo indirecto para "What time is it?"?',
      promptTranslation: 'Which is the correct reported form of "What time is it?"?',
      correctAnswer: 'She asked what time it was.',
      options: ['She asked what time is it.', 'She asked what time was it.', 'She asked what time it was.'],
      explanation: 'Sin inversión y con backshift: what time it was (is → was).',
    },
    {
      id: 'b1-m7-l2-ex11',
      type: 'listening',
      concept: 'reported questions listening',
      difficulty: 3,
      prompt: 'Escuchá el audio y respondé las preguntas (en inglés, sobre lo que dice).',
      correctAnswer: '',
      explanation: 'Un entrevistador hace preguntas en una entrevista de trabajo. Debes responder qué preguntas hizo.',
      listening: {
        audioText:
          "Good morning. I'm the interviewer. Let me ask you some questions. First, where did you study? Second, how many years of experience do you have? Do you speak any other languages? When can you start working? And finally, what are your salary expectations? Thank you for your time.",
        questions: [
          {
            id: 'b1-m7-l2-ex11-q1',
            type: 'multiple_choice',
            concept: 'listening comprehension reported questions',
            difficulty: 2,
            prompt: 'The interviewer asked where...?',
            correctAnswer: 'the candidate studied',
            options: ['the candidate studied', 'the candidate worked', 'the candidate lived'],
            explanation: '"Where did you study?"',
          },
          {
            id: 'b1-m7-l2-ex11-q2',
            type: 'true_false',
            concept: 'listening comprehension reported questions',
            difficulty: 2,
            prompt: 'The interviewer asked if the candidate spoke other languages.',
            correctAnswer: 'true',
            explanation: '"Do you speak any other languages?"',
          },
          {
            id: 'b1-m7-l2-ex11-q3',
            type: 'multiple_choice',
            concept: 'listening comprehension reported questions',
            difficulty: 3,
            prompt: 'How many questions did the interviewer ask in total?',
            correctAnswer: 'Five questions',
            options: ['Three questions', 'Four questions', 'Five questions'],
            explanation: 'Where did you study, how many years of experience, do you speak other languages, when can you start, and what are your salary expectations.',
          },
        ],
      },
    },
    {
      id: 'b1-m7-l2-ex12',
      type: 'writing',
      concept: 'reported questions writing',
      difficulty: 3,
      prompt: 'Escribile un email a tu profesor reportando las preguntas que hizo tu amigo sobre la lección (usá ask + if/whether y ask + wh-).',
      promptTranslation: 'Write an email to your teacher reporting the questions your friend asked about the lesson.',
      correctAnswer: '',
      explanation: 'Un buen email reporta preguntas usando "asked if", "asked whether", "asked what", "asked where", etc., sin inversión.',
      taskType: 'email',
      targetReader: 'your teacher',
      register: 'formal',
      contentPoints: [
        'Al menos 2 preguntas de sí/no (con if/whether)',
        'Al menos 1 pregunta abierta (con wh-: what, where, when, etc.)',
      ],
      requiresOwnIdea: true,
      minWords: 60,
      maxWords: 100,
    },
    {
      id: 'b1-m7-l2-ex13',
      type: 'speaking',
      concept: 'reported questions pronunciation',
      difficulty: 2,
      prompt: 'Escuchá la frase modelo y repetila en voz alta.',
      correctAnswer: 'She asked me where I had worked before and if I had experience with computers.',
      explanation: 'Practicá la pronunciación de preguntas indirectas sin inversión: "where I had worked" (no "where had I worked"), "if I had experience".',
      speakingMode: 'repeat',
    },
  ],
  miniTest: [
    {
      id: 'b1-m7-l2-mt1',
      type: 'multiple_choice',
      concept: 'reported questions if',
      difficulty: 2,
      prompt: 'Completa: Directo: "Do you like pizza?" → "He asked me ___ I liked pizza."',
      promptTranslation: 'Él me preguntó si me gustaba la pizza.',
      correctAnswer: 'if',
      options: ['if', 'where', 'that'],
      explanation: 'Pregunta de sí/no → if. → He asked me if I liked pizza.',
    },
    {
      id: 'b1-m7-l2-mt2',
      type: 'fill_blank',
      concept: 'reported questions wh-',
      difficulty: 2,
      prompt: 'Completa: Directo: "When do you leave?" → "She asked me when I ___."',
      promptTranslation: 'Ella me preguntó cuándo me iba.',
      correctAnswer: 'left',
      acceptedAnswers: ['left', 'Left'],
      explanation: 'Sin inversión y con backshift: "when I left" (leave → left).',
    },
    {
      id: 'b1-m7-l2-mt3',
      type: 'error_correction',
      concept: 'reported questions no inversion',
      difficulty: 3,
      prompt: 'Corrige el error: "He asked if did I want coffee."',
      promptTranslation: 'Él preguntó si quería café.',
      correctAnswer: 'He asked if I wanted coffee.',
      acceptedAnswers: ['He asked if I wanted coffee', 'He asked if I wanted coffee.', 'he asked if i wanted coffee'],
      acceptApproximate: true,
      explanation: 'Tras "if" no se usa "did": He asked if I wanted coffee.',
    },
    {
      id: 'b1-m7-l2-mt4',
      type: 'translate',
      concept: 'reported questions wh-',
      difficulty: 3,
      prompt: 'Traduce: "Ellos me preguntaron dónde trabajaba."',
      promptTranslation: 'They asked me where I worked.',
      correctAnswer: 'They asked me where I worked.',
      acceptedAnswers: ['They asked me where I worked', 'They asked me where I worked.', 'they asked me where i worked'],
      acceptApproximate: true,
      explanation: '"Me preguntaron dónde" = asked me where + sujeto + verbo, sin inversión: where I worked.',
    },
    {
      id: 'b1-m7-l2-mt5',
      type: 'multiple_choice',
      concept: 'reported questions wh-',
      difficulty: 4,
      prompt: '¿Cuál es la forma correcta de estilo indirecto para "Are you ready?"?',
      promptTranslation: 'Which is the correct reported form of "Are you ready?"?',
      correctAnswer: 'She asked me if I was ready.',
      options: ['She asked me if I was ready.', 'She asked me if was I ready.', 'She asked me if I am ready.'],
      explanation: 'Sí/no → ask + if, con backshift (are → was) y orden normal: if I was ready.',
    },
  ],
  reviewItems: ['b1-m7-l1'],
  prerequisites: ['b1-m7-l1'],
}
