import type { Lesson } from '../../types'

export const lesson154FinalExam: Lesson = {
  id: 'a1-m15-l4',
  moduleId: 'm15-review-exam',
  order: 3,
  title: 'Examen Final A1',
  objective: 'Evaluar todas las competencias A1: gramática, vocabulario, lectura, escritura práctica y comunicación.',
  explanation_es: `¡Has llegado al final del curso! Este es el EXAMEN FINAL de nivel A1. Evalúa todo lo que has aprendido.

Cómo hacer el examen:
- Hay preguntas de gramática (tiempos verbales), vocabulario, lectura, traducción/escritura y comunicación práctica.
- Lee cada pregunta con calma. No hay tiempo límite: tómate el tiempo que necesites.
- En las preguntas de traducción, escribe frases completas y correctas.
- En las preguntas de lectura, lee el texto entero antes de responder.
- Cuando termines, revisa tus respuestas antes de enviar.

Para aprobar el examen necesitas al menos un 60% de respuestas correctas. ¡Mucha suerte!`,
  examples: [
    { english: 'Good luck on your A1 final exam!', spanish: '¡Buena suerte en tu examen final A1!' },
    { english: 'Read each question carefully.', spanish: 'Lee cada pregunta con atención.' },
  ],
  rule: `El examen final evalúa cinco áreas:
1. Gramática (tiempos A1): to be, Present Simple, Present Continuous, Past Simple, going to.
2. Vocabulario: saludos, números, familia, comida, ropa, lugares, colores, profesiones, rutinas.
3. Lectura: comprender textos cortos y responder preguntas.
4. Escritura práctica: traducir frases correctamente.
5. Comunicación: elegir la respuesta adecuada en diálogos reales.`,
  commonMistakes: [
    { wrong: '❌ She don\'t work.', correct: '✅ She doesn\'t work.', explanation: 'Con "she" usamos "doesn\'t", no "don\'t", y el verbo no lleva -s.' },
    { wrong: '❌ I have 30 years.', correct: '✅ I am 30 years old.', explanation: 'La edad se dice con "to be": I am 30 years old.' },
    { wrong: '❌ I didn\'t worked.', correct: '✅ I didn\'t work.', explanation: 'Después de "didn\'t" el verbo vuelve al infinitivo, sin -ed.' },
    { wrong: '❌ I going to travel.', correct: '✅ I\'m going to travel.', explanation: 'going to necesita "to be": I am going to travel.' },
    { wrong: '❌ Where is you?', correct: '✅ Where are you?', explanation: 'Con "you" usamos "are", no "is".' },
  ],
  vocabulary: [],
  grammarPoints: [],
  exercises: [
    {
      id: 'a1-m15-l4-ex1',
      type: 'multiple_choice',
      concept: 'grammar: verb to be',
      difficulty: 3,
      prompt: 'Completa: "She ___ a teacher at the school."',
      promptTranslation: 'Ella es profesora en la escuela.',
      correctAnswer: 'is',
      options: ['am', 'is', 'are'],
      explanation: 'Con "she" (3ª persona singular) usamos "is". → She is a teacher.',
    },
    {
      id: 'a1-m15-l4-ex2',
      type: 'fill_blank',
      concept: 'grammar: present simple',
      difficulty: 3,
      prompt: 'Completa con el Present Simple: "My brother ___ in a bank." (work)',
      promptTranslation: 'Mi hermano trabaja en un banco.',
      correctAnswer: 'works',
      acceptedAnswers: ['works'],
      explanation: 'Present Simple, 3ª persona (my brother = he): añadimos -s → works. Es una rutina habitual.',
    },
    {
      id: 'a1-m15-l4-ex3',
      type: 'multiple_choice',
      concept: 'grammar: present simple negative',
      difficulty: 3,
      prompt: 'Completa: "He ___ drink coffee."',
      promptTranslation: 'Él no bebe café.',
      correctAnswer: "doesn't",
      options: ["doesn't", "don't", 'isn\'t'],
      explanation: 'Negativa del Present Simple con 3ª persona: doesn\'t + verbo. → He doesn\'t drink coffee.',
    },
    {
      id: 'a1-m15-l4-ex4',
      type: 'multiple_choice',
      concept: 'grammar: present continuous',
      difficulty: 4,
      prompt: 'Completa: "Look! They ___ playing football."',
      promptTranslation: '¡Mira! Ellos están jugando al fútbol.',
      correctAnswer: 'are',
      options: ['are', 'is', 'am'],
      explanation: 'Present Continuous = to be + verbo -ing. Con "they" usamos "are". → They are playing football.',
    },
    {
      id: 'a1-m15-l4-ex5',
      type: 'fill_blank',
      concept: 'grammar: past simple',
      difficulty: 4,
      prompt: 'Completa con el pasado: "I ___ to the cinema last night." (go)',
      promptTranslation: 'Fui al cine anoche.',
      correctAnswer: 'went',
      acceptedAnswers: ['went'],
      explanation: '"Go" es irregular: su pasado es "went". → I went to the cinema last night.',
    },
    {
      id: 'a1-m15-l4-ex6',
      type: 'reorder',
      concept: 'grammar: going to',
      difficulty: 4,
      prompt: 'Ordena la frase (going to):',
      promptTranslation: 'Ellos van a comprar una casa.',
      words: ['They', 'are', 'going', 'to', 'buy', 'a', 'house.'],
      correctAnswer: 'They are going to buy a house.',
      explanation: 'Plan futuro: to be + going to + verbo. → They are going to buy a house.',
    },
    {
      id: 'a1-m15-l4-ex7',
      type: 'multiple_choice',
      concept: 'vocabulary: numbers',
      difficulty: 3,
      prompt: '¿Qué número es "ninety-seven"?',
      correctAnswer: '97',
      options: ['67', '97', '79'],
      explanation: '"Ninety" = noventa y "seven" = siete → 97.',
    },
    {
      id: 'a1-m15-l4-ex8',
      type: 'match',
      concept: 'vocabulary: family',
      difficulty: 3,
      prompt: 'Relaciona cada palabra con su significado:',
      pairs: [
        { left: 'wife', right: 'esposa' },
        { left: 'daughter', right: 'hija' },
        { left: 'grandmother', right: 'abuela' },
        { left: 'cousin', right: 'primo/a' },
        { left: 'aunt', right: 'tía' },
        { left: 'son', right: 'hijo' },
      ],
      correctAnswer: 'wife=esposa, daughter=hija, grandmother=abuela, cousin=primo/a, aunt=tía, son=hijo',
      explanation: 'Vocabulario de familia: wife (esposa), daughter (hija), grandmother (abuela), cousin (primo/a), aunt (tía), son (hijo).',
    },
    {
      id: 'a1-m15-l4-ex9',
      type: 'multiple_choice',
      concept: 'vocabulary: food',
      difficulty: 3,
      prompt: '¿Cuál de estas palabras es una VERDURA?',
      correctAnswer: 'potato',
      options: ['potato', 'cheese', 'chicken'],
      explanation: '"Potato" (patata) es una verdura. "Cheese" (queso) es un lácteo y "chicken" (pollo) es carne.',
    },
    {
      id: 'a1-m15-l4-ex10',
      type: 'multiple_choice',
      concept: 'vocabulary: places',
      difficulty: 3,
      prompt: 'Necesitas libros para estudiar. ¿Dónde vas?',
      correctAnswer: 'library',
      options: ['library', 'supermarket', 'station'],
      explanation: 'En la biblioteca (library) hay libros para estudiar. "Supermarket" es para comprar y "station" es para el tren.',
    },
    {
      id: 'a1-m15-l4-ex11',
      type: 'fill_blank',
      concept: 'vocabulary: colours',
      difficulty: 3,
      prompt: 'Completa: "I want a ___ dress." (negro)',
      promptTranslation: 'Quiero un vestido negro.',
      correctAnswer: 'black',
      acceptedAnswers: ['black'],
      explanation: '"Black" = negro. → I want a black dress. = Quiero un vestido negro.',
    },
    {
      id: 'a1-m15-l4-ex12',
      type: 'reading',
      concept: 'reading: daily routine',
      difficulty: 4,
      prompt: 'Lee el texto y responde:',
      reading: {
        text: 'My day\nI get up at seven o\'clock. I have breakfast at seven thirty and I go to work by bus. I work in a bank from nine to five. I have lunch at one o\'clock. In the evening, I go home, I have dinner and I watch TV. I go to bed at eleven.',
        translation: 'Mi día\nMe levanto a las siete. Desayuno a las siete y media y voy al trabajo en autobús. Trabajo en un banco de nueve a cinco. Como a la una. Por la tarde, vuelvo a casa, ceno y veo la tele. Me acuesto a las once.',
        questions: [
          {
            id: 'a1-m15-l4-ex12-q1',
            type: 'multiple_choice',
            concept: 'reading: daily routine',
            difficulty: 4,
            prompt: '¿A qué hora se levanta?',
            correctAnswer: 'at seven o\'clock',
            options: ['at seven o\'clock', 'at seven thirty', 'at eleven'],
            explanation: 'El texto dice: "I get up at seven o\'clock."',
          },
          {
            id: 'a1-m15-l4-ex12-q2',
            type: 'multiple_choice',
            concept: 'reading: daily routine',
            difficulty: 4,
            prompt: '¿Cómo va al trabajo?',
            correctAnswer: 'by bus',
            options: ['by bus', 'by car', 'on foot'],
            explanation: 'El texto dice: "I go to work by bus."',
          },
          {
            id: 'a1-m15-l4-ex12-q3',
            type: 'multiple_choice',
            concept: 'reading: daily routine',
            difficulty: 4,
            prompt: '¿Qué hace por la tarde?',
            correctAnswer: 'goes home, has dinner and watches TV',
            options: ['goes home, has dinner and watches TV', 'goes to work', 'gets up and has breakfast'],
            explanation: 'El texto dice: "In the evening, I go home, I have dinner and I watch TV."',
          },
        ],
      },
      correctAnswer: 'reading complete',
      explanation: 'Lee con atención los detalles: las horas y las acciones de la rutina están en el texto.',
    },
    {
      id: 'a1-m15-l4-ex13',
      type: 'reading',
      concept: 'reading: past weekend',
      difficulty: 4,
      prompt: 'Lee el texto y responde:',
      reading: {
        text: 'Last weekend\nLast weekend I went to the beach with my family. On Saturday, we arrived at eleven in the morning. My children played in the water and I read a book. We ate fish at a restaurant near the beach. On Sunday, we visited an old castle and then we went home. It was a great weekend!',
        translation: 'El fin de semana pasado\nEl fin de semana pasado fui a la playa con mi familia. El sábado llegamos a las once de la mañana. Mis hijos jugaron en el agua y yo leí un libro. Comimos pescado en un restaurante cerca de la playa. El domingo visitamos un castillo antiguo y después volvimos a casa. ¡Fue un fin de semana estupendo!',
        questions: [
          {
            id: 'a1-m15-l4-ex13-q1',
            type: 'multiple_choice',
            concept: 'reading: past weekend',
            difficulty: 4,
            prompt: '¿Dónde fue el fin de semana pasado?',
            correctAnswer: 'to the beach',
            options: ['to the beach', 'to the mountains', 'to the city'],
            explanation: 'El texto dice: "Last weekend I went to the beach with my family."',
          },
          {
            id: 'a1-m15-l4-ex13-q2',
            type: 'multiple_choice',
            concept: 'reading: past weekend',
            difficulty: 4,
            prompt: '¿Qué comieron el sábado?',
            correctAnswer: 'fish',
            options: ['fish', 'chicken', 'rice'],
            explanation: 'El texto dice: "We ate fish at a restaurant near the beach."',
          },
          {
            id: 'a1-m15-l4-ex13-q3',
            type: 'multiple_choice',
            concept: 'reading: past weekend',
            difficulty: 4,
            prompt: '¿Qué visitaron el domingo?',
            correctAnswer: 'an old castle',
            options: ['an old castle', 'a museum', 'a park'],
            explanation: 'El texto dice: "On Sunday, we visited an old castle."',
          },
        ],
      },
      correctAnswer: 'reading complete',
      explanation: 'En los textos en pasado, fíjate en los verbos irregulares (went, ate, visited) y en los detalles (dónde, qué comieron, qué visitaron).',
    },
    {
      id: 'a1-m15-l4-ex14',
      type: 'reading',
      concept: 'reading: future plans',
      difficulty: 4,
      prompt: 'Lee el texto y responde:',
      reading: {
        text: 'My plans\nNext month I\'m going to start a new job in Madrid. I\'m going to move to a new flat near the city centre. My wife is going to work from home and my children are going to study at a new school. We\'re going to visit my parents in August.',
        translation: 'Mis planes\nEl próximo mes voy a empezar un trabajo nuevo en Madrid. Me voy a mudar a un piso nuevo cerca del centro de la ciudad. Mi esposa va a trabajar desde casa y mis hijos van a estudiar en una escuela nueva. Vamos a visitar a mis padres en agosto.',
        questions: [
          {
            id: 'a1-m15-l4-ex14-q1',
            type: 'multiple_choice',
            concept: 'reading: future plans',
            difficulty: 4,
            prompt: '¿Cuándo va a empezar el trabajo nuevo?',
            correctAnswer: 'next month',
            options: ['next month', 'next year', 'in August'],
            explanation: 'El texto dice: "Next month I\'m going to start a new job in Madrid."',
          },
          {
            id: 'a1-m15-l4-ex14-q2',
            type: 'multiple_choice',
            concept: 'reading: future plans',
            difficulty: 4,
            prompt: '¿Dónde va a estar el piso nuevo?',
            correctAnswer: 'near the city centre',
            options: ['near the city centre', 'in the mountains', 'next to the station'],
            explanation: 'El texto dice: "I\'m going to move to a new flat near the city centre."',
          },
          {
            id: 'a1-m15-l4-ex14-q3',
            type: 'multiple_choice',
            concept: 'reading: future plans',
            difficulty: 4,
            prompt: '¿A quién van a visitar en agosto?',
            correctAnswer: 'his parents',
            options: ['his parents', 'his brother', 'his friends'],
            explanation: 'El texto dice: "We\'re going to visit my parents in August."',
          },
        ],
      },
      correctAnswer: 'reading complete',
      explanation: 'Los textos de futuro usan "going to". Busca las expresiones de tiempo (next month, in August) para responder.',
    },
    {
      id: 'a1-m15-l4-ex15',
      type: 'reading',
      concept: 'reading: personal information',
      difficulty: 4,
      prompt: 'Lee el texto y responde:',
      reading: {
        text: 'About me\nHello! My name is Carmen. I am 28 years old and I am from Argentina, but I live in Spain now. I am a nurse at a hospital. I have one sister and two brothers. I like cooking and reading. I can speak Spanish and a little English.',
        translation: 'Sobre mí\n¡Hola! Me llamo Carmen. Tengo 28 años y soy de Argentina, pero ahora vivo en España. Soy enfermera en un hospital. Tengo una hermana y dos hermanos. Me gusta cocinar y leer. Sé hablar español y un poco de inglés.',
        questions: [
          {
            id: 'a1-m15-l4-ex15-q1',
            type: 'multiple_choice',
            concept: 'reading: personal information',
            difficulty: 4,
            prompt: '¿De dónde es Carmen?',
            correctAnswer: 'Argentina',
            options: ['Argentina', 'Spain', 'Mexico'],
            explanation: 'El texto dice: "I am from Argentina, but I live in Spain now."',
          },
          {
            id: 'a1-m15-l4-ex15-q2',
            type: 'multiple_choice',
            concept: 'reading: personal information',
            difficulty: 4,
            prompt: '¿Qué hace Carmen?',
            correctAnswer: 'She is a nurse.',
            options: ['She is a nurse.', 'She is a teacher.', 'She is a doctor.'],
            explanation: 'El texto dice: "I am a nurse at a hospital."',
          },
          {
            id: 'a1-m15-l4-ex15-q3',
            type: 'multiple_choice',
            concept: 'reading: personal information',
            difficulty: 4,
            prompt: '¿Cuántos hermanos y hermanas tiene Carmen?',
            correctAnswer: 'one sister and two brothers',
            options: ['one sister and two brothers', 'two sisters and one brother', 'two sisters and two brothers'],
            explanation: 'El texto dice: "I have one sister and two brothers."',
          },
        ],
      },
      correctAnswer: 'reading complete',
      explanation: 'Los textos de información personal usan "to be" y "have". Fíjate en los datos: edad, origen, profesión, familia.',
    },
    {
      id: 'a1-m15-l4-ex16',
      type: 'translate',
      concept: 'writing: present simple',
      difficulty: 4,
      prompt: 'Traduce: "Vivo en Madrid."',
      correctAnswer: 'I live in Madrid.',
      acceptedAnswers: ['I live in Madrid', 'I live in Madrid.', 'I live in Madrid now'],
      acceptApproximate: true,
      explanation: 'Present Simple con "I": I live in Madrid. = Vivo en Madrid.',
    },
    {
      id: 'a1-m15-l4-ex17',
      type: 'translate',
      concept: 'writing: past simple',
      difficulty: 4,
      prompt: 'Traduce: "Ayer fui al supermercado."',
      correctAnswer: 'I went to the supermarket yesterday.',
      acceptedAnswers: ['I went to the supermarket yesterday', 'I went to the supermarket yesterday.', 'Yesterday I went to the supermarket', 'Yesterday I went to the supermarket.'],
      acceptApproximate: true,
      explanation: 'Pasado de "go" = went. → I went to the supermarket yesterday. = Ayer fui al supermercado.',
    },
    {
      id: 'a1-m15-l4-ex18',
      type: 'translate',
      concept: 'writing: going to',
      difficulty: 4,
      prompt: 'Traduce: "Mañana voy a estudiar inglés."',
      correctAnswer: 'Tomorrow I\'m going to study English.',
      acceptedAnswers: ["Tomorrow I'm going to study English", 'I am going to study English tomorrow', "I'm going to study English tomorrow", 'Tomorrow I am going to study English', 'Tomorrow I\'m going to study English.'],
      acceptApproximate: true,
      explanation: 'Plan futuro con going to: to be + going to + verbo. → Tomorrow I\'m going to study English.',
    },
    {
      id: 'a1-m15-l4-ex19',
      type: 'translate',
      concept: 'writing: likes and routine',
      difficulty: 5,
      prompt: 'Traduce: "Me gusta el café, pero no bebo café por la noche."',
      correctAnswer: 'I like coffee, but I don\'t drink coffee at night.',
      acceptedAnswers: ["I like coffee, but I don't drink coffee at night", "I like coffee but I don't drink coffee at night", 'I like coffee, but I do not drink coffee at night', 'I like coffee, but I don\'t drink coffee at night.'],
      acceptApproximate: true,
      explanation: '"I like coffee" = me gusta el café; "but" = pero; negativa con don\'t: I don\'t drink coffee at night.',
    },
    {
      id: 'a1-m15-l4-ex20',
      type: 'translate',
      concept: 'writing: present continuous',
      difficulty: 5,
      prompt: 'Traduce: "Ahora mismo estoy cocinando la cena."',
      correctAnswer: 'I am cooking dinner right now.',
      acceptedAnswers: ["I'm cooking dinner right now", 'I am cooking dinner right now', "I'm cooking dinner now", 'I am cooking dinner now', 'I am cooking dinner right now.'],
      acceptApproximate: true,
      explanation: '"Ahora mismo" indica Present Continuous: I am cooking dinner right now.',
    },
    {
      id: 'a1-m15-l4-ex21',
      type: 'select_correct',
      concept: 'communication: restaurant',
      difficulty: 4,
      prompt: 'Elige la mejor respuesta: "Are you ready to order?"',
      promptTranslation: '¿Está listo para pedir?',
      correctAnswer: 'Yes, I\'d like a chicken salad, please.',
      options: ['Yes, I\'d like a chicken salad, please.', 'Yes, I am 30 years old.', 'Yes, I am from Spain.'],
      explanation: 'En un restaurante, al preguntar "Are you ready to order?" respondemos con lo que queremos pedir: Yes, I\'d like a chicken salad, please.',
    },
    {
      id: 'a1-m15-l4-ex22',
      type: 'select_correct',
      concept: 'communication: shopping',
      difficulty: 4,
      prompt: 'Elige la mejor respuesta: "Do you have this shirt in blue?"',
      promptTranslation: '¿Tienen esta camisa en azul?',
      correctAnswer: 'Yes, here you are. It\'s fifteen euros.',
      options: ['Yes, here you are. It\'s fifteen euros.', 'Yes, I can swim.', 'Yes, I am going to the bank.'],
      explanation: 'En una tienda, al preguntar por una talla o color, el vendedor responde con confirmación y precio: Yes, here you are. It\'s fifteen euros.',
    },
    {
      id: 'a1-m15-l4-ex23',
      type: 'select_correct',
      concept: 'communication: directions',
      difficulty: 4,
      prompt: 'Elige la mejor respuesta: "How do I get to the station?"',
      promptTranslation: '¿Cómo llego a la estación?',
      correctAnswer: 'Go straight and turn right at the traffic lights.',
      options: ['Go straight and turn right at the traffic lights.', 'It\'s ten euros.', 'Nice to meet you.'],
      explanation: 'Al preguntar cómo llegar a un lugar ("How do I get to...?"), damos direcciones: Go straight and turn right at the traffic lights.',
    },
    {
      id: 'a1-m15-l4-ex24',
      type: 'error_correction',
      concept: 'grammar: mixed tenses',
      difficulty: 5,
      prompt: 'Corrige el error en esta frase: "Yesterday I don\'t go to work."',
      correctAnswer: 'Yesterday I didn\'t go to work.',
      acceptedAnswers: ['Yesterday I didn\'t go to work', 'I didn\'t go to work yesterday', 'I didn\'t go to work yesterday.', 'Yesterday I did not go to work', 'Yesterday I didn\'t go to work.'],
      acceptApproximate: true,
      explanation: '"Yesterday" indica pasado: la negativa en pasado usa "didn\'t" + infinitivo. → Yesterday I didn\'t go to work.',
    },
  ],
  miniTest: [],
  reviewItems: [],
  prerequisites: ['a1-m15-l3'],
}
