import type { Lesson } from '../../types'

export const lesson24MiniTest: Lesson = {
  id: 'b2-m2-l4',
  moduleId: 'm2-causative-passive',
  order: 3,
  title: 'Mini-Test: Causative & Advanced Passive',
  objective: 'Integrar y repasar las lecciones anteriores (causative, passive compound tenses, passive with modals) en ejercicios variados de práctica.',
  explanation_es: `Este mini-test repasa los tres temas principales del módulo:

1. CAUSATIVE (have/get): "I had my hair cut" / "I got him to agree"
2. PASSIVE COMPOUND TENSES: "is being built" / "has been finished" / "had been sent"
3. PASSIVE WITH MODALS & DOUBLE OBJECTS: "must be done" / "She was given a prize" / "He is thought to be..."

Los ejercicios combinan todos estos temas de forma variada. No hay secciones de listening, writing o speaking en este test — es solo práctica y validación.`,
  examples: [],
  rule: 'Este mini-test valida tu comprensión de causativas, pasivas compuestas, y pasivas con modales.',
  commonMistakes: [],
  vocabulary: [],
  grammarPoints: [],
  exercises: [
    {
      id: 'b2-m2-l4-ex1',
      type: 'multiple_choice',
      concept: 'causative have',
      difficulty: 3,
      prompt: 'Completa: "I ___ my report translated into Spanish."',
      promptTranslation: 'Mandé que tradujeron mi informe al español.',
      correctAnswer: 'had',
      options: ['had', 'have', 'got'],
      explanation: 'Causativa: had + object + past participle (translated).',
    },
    {
      id: 'b2-m2-l4-ex2',
      type: 'fill_blank',
      concept: 'causative get',
      difficulty: 3,
      prompt: 'Completa: "She got her brother ___ her with her homework."',
      promptTranslation: 'Logró que su hermano le ayudara con la tarea.',
      correctAnswer: 'to help',
      explanation: 'Causativa get: get + person + to-infinitive.',
    },
    {
      id: 'b2-m2-l4-ex3',
      type: 'multiple_choice',
      concept: 'present continuous passive',
      difficulty: 3,
      prompt: 'Completa: "The bridge ___ rebuilt at the moment."',
      promptTranslation: 'El puente está siendo reconstruido en este momento.',
      correctAnswer: 'is being',
      options: ['is being', 'is', 'has been'],
      explanation: 'Present continuous passive: is/are being + participio.',
    },
    {
      id: 'b2-m2-l4-ex4',
      type: 'fill_blank',
      concept: 'past perfect passive',
      difficulty: 4,
      prompt: 'Completa: "When we arrived, everything ___."',
      promptTranslation: 'Cuando llegamos, todo había sido preparado.',
      correctAnswer: 'had been prepared',
      explanation: 'Past perfect passive: had been + participio.',
    },
    {
      id: 'b2-m2-l4-ex5',
      type: 'error_correction',
      concept: 'passive modals',
      difficulty: 4,
      prompt: 'Encuentra el error: "This problem should to be fixed immediately."',
      correctAnswer: 'This problem should be fixed immediately.',
      acceptedAnswers: [
        'This problem should be fixed immediately',
        'This problem should be fixed immediately.',
      ],
      acceptApproximate: true,
      explanation: 'Modal + be + participio (no "to be" después del modal).',
    },
    {
      id: 'b2-m2-l4-ex6',
      type: 'select_correct',
      concept: 'double object passive',
      difficulty: 3,
      prompt: 'Elegí la forma correcta: "Se le dio un documento importantes."',
      correctAnswer: 'He was given an important document.',
      options: [
        'He was given an important document.',
        'An important document was given to him.',
        'Both are correct.',
      ],
      explanation: 'Ambas formas son correctas, pero "He was given" (indirect object) es más común.',
    },
    {
      id: 'b2-m2-l4-ex7',
      type: 'true_false',
      concept: 'causative meaning',
      difficulty: 2,
      prompt: '"I had my car repaired" significa que yo mismo reparé mi coche.',
      correctAnswer: 'false',
      explanation: 'Falso. Significa que encargué que alguien reparara mi coche.',
    },
    {
      id: 'b2-m2-l4-ex8',
      type: 'translate',
      concept: 'mixed causative and passive',
      difficulty: 4,
      prompt: 'Traduce: "The project is being completed and the client must be given a report by next week."',
      correctAnswer: 'El proyecto está siendo completado y al cliente debe dársele un informe la próxima semana.',
      acceptedAnswers: [
        'El proyecto está siendo completado y al cliente debe dársele un informe la próxima semana',
        'El proyecto está siendo completado y debe darse un informe al cliente la próxima semana.',
      ],
      acceptApproximate: true,
      explanation: '"Is being completed" (present continuous passive) + "must be given" (passive with modal) + "a report" (double object).',
    },
    {
      id: 'b2-m2-l4-ex9',
      type: 'reorder',
      concept: 'passive with modal perfect',
      difficulty: 4,
      prompt: 'Ordena las palabras:',
      promptTranslation: 'El dinero debe de haber sido robado durante la noche.',
      words: ['The', 'money', 'must', 'have', 'been', 'stolen', 'during', 'the', 'night.'],
      correctAnswer: 'The money must have been stolen during the night.',
      explanation: 'Orden: sujeto + must have been + participio + resto. Modal perfect passive.',
    },
    {
      id: 'b2-m2-l4-ex10',
      type: 'multiple_choice',
      concept: 'impersonal infinitive passive',
      difficulty: 4,
      prompt: 'Completa: "She is ___ to be the best candidate for the position."',
      promptTranslation: 'Se cree que es la mejor candidata para el puesto.',
      correctAnswer: 'believed',
      options: ['believed', 'thought', 'said'],
      explanation: 'Cualquiera de estas opciones (believed, thought, said) es correcta con "to be". "Believed" es muy común.',
    },
  ],
  miniTest: [
    {
      id: 'b2-m2-l4-mt1',
      type: 'multiple_choice',
      concept: 'causative and passive review',
      difficulty: 4,
      prompt: 'Completa: "I ___ my house painted and the contractor ___ by the supervisor."',
      promptTranslation: 'Mandé pintar mi casa y el contratista fue supervizado.',
      correctAnswer: 'had / was supervised',
      options: [
        'had / was supervised',
        'got / was being supervised',
        'had / has been supervised',
      ],
      explanation: '"Had" (causative) + "was supervised" (pasiva simple, acción completada).',
    },
    {
      id: 'b2-m2-l4-mt2',
      type: 'error_correction',
      concept: 'mixed structures',
      difficulty: 4,
      prompt: 'Corrige: "The new building is being build and workers should be give higher salaries."',
      correctAnswer: 'The new building is being built and workers should be given higher salaries.',
      acceptedAnswers: [
        'The new building is being built and workers should be given higher salaries',
        'The new building is being built and workers should be given higher salaries.',
      ],
      acceptApproximate: true,
      explanation: '"Is being built" (participio built, no build) + "should be given" (double object passive).',
    },
    {
      id: 'b2-m2-l4-mt3',
      type: 'true_false',
      concept: 'passive understanding',
      difficulty: 3,
      prompt: '"The document has been translated" expresa que alguien acaba de terminar de traducir el documento.',
      correctAnswer: 'true',
      explanation: 'Correcto. Present perfect passive enfatiza el resultado con relevancia presente.',
    },
    {
      id: 'b2-m2-l4-mt4',
      type: 'select_correct',
      concept: 'overall module comprehension',
      difficulty: 4,
      prompt: 'Elegí la oración que mejor resume los conceptos del módulo:',
      correctAnswer: 'The company had the report written, it was being reviewed by the director, and it must have been approved by now.',
      options: [
        'The company had the report written, it was being reviewed by the director, and it must have been approved by now.',
        'The company have the report written, it is reviewed by the director, and it should approve by now.',
        'The company has the report write, the report is review by the director, and it had approved now.',
      ],
      explanation: 'Solo la primera oración usa correctamente causativa (had written), continuous passive (was being reviewed), y modal perfect passive (must have been approved).',
    },
  ],
  reviewItems: ['b1-m4-l1', 'b2-m1-l2', 'b2-m2-l1', 'b2-m2-l2', 'b2-m2-l3'],
  prerequisites: ['b2-m2-l3'],
}
