import type { Lesson } from '../../types'

export const lesson125MiniTest: Lesson = {
  id: 'a2-m12-l5',
  moduleId: 'm12-gerunds-infinitives',
  order: 4,
  title: 'Mini-test: gerundios, infinitivos y phrasal verbs',
  objective: 'Evaluar la consolidación de verbos + -ing, verbos + to + infinitivo, make/let + persona + verbo, y los phrasal verbs comunes.',
  explanation_es: `Esta es la lección de evaluación final del Módulo 12. Antes del mini-test, repasemos lo esencial:

**Verbos + -ing (gerundio):**
- like, love, enjoy, hate, finish, mind + verbo(-ing).
- I enjoy reading. / She likes swimming. / Do you mind waiting?
- ❌ I enjoy to read → ✅ I enjoy reading.

**Verbos + to + infinitivo:**
- want, need, decide, plan, hope, would like + to + verbo.
- I want to learn English. / She decided to move.
- ❌ I want learn → ✅ I want to learn.

**make / let + persona + verbo (sin "to"):**
- My parents make me study. / She let me use her car.
- ❌ make me to study → ✅ make me study.

**Phrasal verbs comunes:**
- get up (levantarse), turn on/off (encender/apagar), look for (buscar), look after (cuidar de), give up (rendirse), find out (descubrir), turn down (bajar el volumen)...
- Con pronombres: turn it off (el pronombre va entre verbo y partícula).`,
  examples: [
    { english: 'I enjoy reading.', spanish: 'Disfruto leyendo.' },
    { english: 'I want to learn English.', spanish: 'Quiero aprender inglés.' },
    { english: 'My parents make me study.', spanish: 'Mis padres me hacen estudiar.' },
    { english: "Don't give up!", spanish: '¡No te rindas!' },
    { english: 'Please turn it off.', spanish: 'Por favor, apágalo.' },
  ],
  rule: `**Resumen del módulo:**
- like/enjoy/hate/finish/mind + verbo(-ing)
- want/need/decide/plan/hope/would like + to + verbo
- make/let + persona + verbo (sin "to")
- Phrasal verbs: verb + particle; con pronombre, el pronombre va en medio (turn it off).`,
  commonMistakes: [
    { wrong: '❌ I enjoy to read.', correct: '✅ I enjoy reading.', explanation: 'Enjoy va seguido de gerundio (-ing).' },
    { wrong: '❌ I want learn English.', correct: '✅ I want to learn English.', explanation: 'Want lleva "to" + infinitivo.' },
    { wrong: '❌ She let me to use her car.', correct: '✅ She let me use her car.', explanation: 'Después de "let" el verbo va sin "to".' },
    { wrong: '❌ Please turn off it.', correct: '✅ Please turn it off.', explanation: 'Con pronombres, el pronombre va entre verbo y partícula.' },
  ],
  vocabulary: [],
  grammarPoints: [],
  exercises: [
    {
      id: 'a2-m12-l5-ex1',
      type: 'multiple_choice',
      concept: 'module 12 - gerund',
      difficulty: 1,
      prompt: 'Completa: "I love ___ in the sea."',
      promptTranslation: 'Me encanta nadar en el mar.',
      correctAnswer: 'swimming',
      options: ['swimming', 'to swimming', 'swim'],
      explanation: '"Love" + gerundio (-ing): love swimming.',
    },
    {
      id: 'a2-m12-l5-ex2',
      type: 'fill_blank',
      concept: 'module 12 - infinitive',
      difficulty: 2,
      prompt: "Completa: \"I'd like ___ a table for two.\"",
      promptTranslation: 'Me gustaría reservar una mesa para dos.',
      correctAnswer: 'to book',
      acceptedAnswers: ['to book', 'To book'],
      explanation: '"Would like" + to + verbo: I\'d like to book a table.',
    },
    {
      id: 'a2-m12-l5-ex3',
      type: 'error_correction',
      concept: 'module 12 - make/let',
      difficulty: 3,
      prompt: 'Corrige el error: "My mother makes me to clean my room."',
      promptTranslation: 'Mi madre me hace limpiar mi habitación.',
      correctAnswer: 'My mother makes me clean my room.',
      acceptedAnswers: ['My mother makes me clean my room', 'My mother makes me clean my room.', 'my mother makes me clean my room'],
      acceptApproximate: true,
      explanation: 'Después de "make" el verbo va sin "to": makes me clean.',
    },
    {
      id: 'a2-m12-l5-ex4',
      type: 'match',
      concept: 'module 12 - phrasal verbs',
      difficulty: 2,
      prompt: 'Relaciona cada phrasal verb con su significado.',
      promptTranslation: 'Match each phrasal verb with its meaning.',
      correctAnswer: 'wake up=despertarse; take off=quitarse/despegar; look after=cuidar de; give up=rendirse; find out=descubrir; turn down=bajar el volumen',
      pairs: [
        { left: 'wake up', right: 'despertarse' },
        { left: 'take off', right: 'quitarse (ropa), despegar' },
        { left: 'look after', right: 'cuidar de' },
        { left: 'give up', right: 'rendirse' },
        { left: 'find out', right: 'descubrir, enterarse' },
        { left: 'turn down', right: 'bajar el volumen' },
      ],
      explanation: 'Cada phrasal verb tiene un significado fijo: wake up=despertarse, take off=quitarse/despegar, look after=cuidar de, give up=rendirse, find out=descubrir, turn down=bajar el volumen.',
    },
    {
      id: 'a2-m12-l5-ex5',
      type: 'reorder',
      concept: 'module 12 - infinitive',
      difficulty: 3,
      prompt: 'Ordena las palabras: to / visit / hope / Paris / they',
      promptTranslation: 'Ellos esperan visitar París.',
      correctAnswer: 'They hope to visit Paris.',
      words: ['They', 'hope', 'to', 'visit', 'Paris'],
      explanation: 'Orden: sujeto + hope + to + verbo + objeto. → They hope to visit Paris.',
    },
    {
      id: 'a2-m12-l5-ex6',
      type: 'translate',
      concept: 'module 12 - gerund',
      difficulty: 3,
      prompt: "Traduce: \"Disfruto leyendo.\"",
      promptTranslation: 'I enjoy reading.',
      correctAnswer: 'I enjoy reading.',
      acceptedAnswers: ['I enjoy reading', 'I enjoy reading.', 'i enjoy reading'],
      acceptApproximate: true,
      explanation: '"Disfrutar de + verbo" = enjoy + gerundio. → I enjoy reading.',
    },
    {
      id: 'a2-m12-l5-ex7',
      type: 'reading',
      concept: 'module 12 - reading consolidation',
      difficulty: 4,
      prompt: 'Lee el texto y responde.',
      reading: {
        text: 'My new routine\nI want to learn English, so I study every day. I enjoy listening to music in English, and I like watching series without subtitles. My parents make me practise for one hour, but I don\'t mind doing it because I love learning new words. I decided to give up my evening TV show and use that time to read. I\'m also looking for a conversation partner, and I hope to find someone who can help me speak better. I won\'t give up!',
        translation: 'Mi nueva rutina\nQuiero aprender inglés, así que estudio todos los días. Disfruto escuchando música en inglés y me gusta ver series sin subtítulos. Mis padres me hacen practicar durante una hora, pero no me importa hacerlo porque me encanta aprender palabras nuevas. Decidí dejar mi serie de la tarde y usar ese tiempo para leer. También estoy buscando un compañero de conversación y espero encontrar a alguien que pueda ayudarme a hablar mejor. ¡No me rendiré!',
        questions: [
          {
            id: 'a2-m12-l5-ex7-q1',
            type: 'multiple_choice',
            concept: 'module 12 - reading consolidation',
            difficulty: 4,
            prompt: '¿Qué quiere hacer el narrador?',
            correctAnswer: 'Quiere aprender inglés.',
            options: ['Quiere dejar el inglés.', 'Quiere aprender inglés.', 'Quiere ver más series.'],
            explanation: 'El texto dice: "I want to learn English."',
          },
          {
            id: 'a2-m12-l5-ex7-q2',
            type: 'multiple_choice',
            concept: 'module 12 - reading consolidation',
            difficulty: 4,
            prompt: '¿Qué le hacen hacer sus padres?',
            correctAnswer: 'Le hacen practicar durante una hora.',
            options: ['Le hacen practicar durante una hora.', 'Le hacen ver la tele.', 'Le hacen cocinar.'],
            explanation: 'El texto dice: "My parents make me practise for one hour." (make me practise = me hacen practicar).',
          },
          {
            id: 'a2-m12-l5-ex7-q3',
            type: 'multiple_choice',
            concept: 'module 12 - reading consolidation',
            difficulty: 4,
            prompt: '¿Qué decidió hacer el narrador?',
            correctAnswer: 'Dejar su serie de la tarde y leer.',
            options: ['Ver más series.', 'Dejar su serie de la tarde y leer.', 'Dejar de estudiar.'],
            explanation: 'El texto dice: "I decided to give up my evening TV show and use that time to read." (give up = dejar).',
          },
          {
            id: 'a2-m12-l5-ex7-q4',
            type: 'multiple_choice',
            concept: 'module 12 - reading consolidation',
            difficulty: 4,
            prompt: '¿Qué está buscando el narrador?',
            correctAnswer: 'Un compañero de conversación.',
            options: ['Un compañero de conversación.', 'Una serie nueva.', 'Un libro.'],
            explanation: 'El texto dice: "I\'m also looking for a conversation partner." (look for = buscar).',
          },
        ],
      },
      correctAnswer: 'reading complete',
      explanation: 'El texto usa verb patterns (want to, enjoy -ing, make me practise, decided to, give up) y phrasal verbs (give up, look for). Lee con atención.',
    },
    {
      id: 'a2-m12-l5-ex8',
      type: 'true_false',
      concept: 'module 12 - make/let',
      difficulty: 3,
      prompt: 'Después de "make" usamos el verbo con "to": "She makes me to wait".',
      promptTranslation: 'After "make" we use "to" + verb: "She makes me to wait".',
      correctAnswer: 'false',
      acceptedAnswers: ['False', 'FALSE', 'f'],
      explanation: 'Falso. Después de "make" el verbo va sin "to": She makes me wait.',
    },
    {
      id: 'a2-m12-l5-ex9',
      type: 'fill_blank',
      concept: 'module 12 - phrasal verbs',
      difficulty: 3,
      prompt: "Completa: \"I need to ___ out the truth.\"",
      promptTranslation: 'Necesito descubrir la verdad.',
      correctAnswer: 'find',
      acceptedAnswers: ['find', 'Find'],
      explanation: '"Find out" = descubrir, enterarse. → I need to find out the truth.',
    },
    {
      id: 'a2-m12-l5-ex10',
      type: 'multiple_choice',
      concept: 'module 12 - gerund vs infinitive',
      difficulty: 4,
      prompt: 'Completa: "She finished ___ and went out."',
      promptTranslation: 'Ella terminó de cocinar y salió.',
      correctAnswer: 'cooking',
      options: ['cooking', 'to cook', 'cook'],
      explanation: '"Finish" va seguido de gerundio (-ing): finished cooking.',
    },
  ],
  miniTest: [
    {
      id: 'a2-m12-l5-mt1',
      type: 'multiple_choice',
      concept: 'module 12 final - gerund',
      difficulty: 2,
      prompt: 'Completa: "Do you mind ___ the window?"',
      promptTranslation: '¿Te importa abrir la ventana?',
      correctAnswer: 'opening',
      options: ['opening', 'to open', 'open'],
      explanation: '"Mind" + gerundio: Do you mind opening the window?',
    },
    {
      id: 'a2-m12-l5-mt2',
      type: 'fill_blank',
      concept: 'module 12 final - infinitive',
      difficulty: 2,
      prompt: 'Completa: "We need ___ some water."',
      promptTranslation: 'Necesitamos comprar agua.',
      correctAnswer: 'to buy',
      acceptedAnswers: ['to buy', 'To buy'],
      explanation: '"Need" + to + verbo: need to buy.',
    },
    {
      id: 'a2-m12-l5-mt3',
      type: 'error_correction',
      concept: 'module 12 final - phrasal verb pronoun',
      difficulty: 3,
      prompt: 'Corrige el error: "Please turn on it."',
      promptTranslation: 'Por favor, enciéndelo.',
      correctAnswer: 'Please turn it on.',
      acceptedAnswers: ['Please turn it on', 'Please turn it on.', 'please turn it on'],
      acceptApproximate: true,
      explanation: 'Con pronombre (it), el pronombre va entre el verbo y la partícula: turn it on.',
    },
    {
      id: 'a2-m12-l5-mt4',
      type: 'translate',
      concept: 'module 12 final - make/let',
      difficulty: 3,
      prompt: 'Traduce: "Mis padres me hacen estudiar."',
      promptTranslation: 'My parents make me study.',
      correctAnswer: 'My parents make me study.',
      acceptedAnswers: ['My parents make me study', 'My parents make me study.', 'my parents make me study'],
      acceptApproximate: true,
      explanation: '"Hacer que alguien haga algo" = make + persona + verbo (sin to): My parents make me study.',
    },
    {
      id: 'a2-m12-l5-mt5',
      type: 'multiple_choice',
      concept: 'module 12 final - consolidation',
      difficulty: 4,
      prompt: '¿Cuál es la frase correcta?',
      promptTranslation: 'Which sentence is correct?',
      correctAnswer: 'He gave up smoking last year.',
      options: ['He gave up to smoke last year.', 'He gave up smoking last year.', 'He gave up smoke last year.'],
      explanation: '"Give up" + gerundio (-ing) cuando significa "dejar de hacer algo": He gave up smoking.',
    },
  ],
  reviewItems: ['a2-m12-l4'],
  prerequisites: ['a2-m12-l4'],
}
