import type { Lesson } from '../../types'

export const lesson121VerbsIng: Lesson = {
  id: 'a2-m12-l1',
  moduleId: 'm12-gerunds-infinitives',
  order: 0,
  title: 'Verbos + -ing (gerundio): like, enjoy, finish, mind...',
  objective: 'Usar verbos como like, love, enjoy, hate, finish y mind seguidos de verbo acabado en -ing (gerundio).',
  explanation_es: `En inglés, después de algunos verbos usamos otro verbo en forma de gerundio (-ing). El gerundio equivale al infinitivo español: "reading" = leer, "swimming" = nadar, "working" = trabajar.

Los verbos más importantes que llevan -ing:
- like → I like reading. = Me gusta leer.
- love → She loves dancing. = A ella le encanta bailar.
- enjoy → I enjoy reading. = Disfruto leyendo / Me gusta leer.
- hate → He hates cooking. = Él odia cocinar.
- finish → He finished working at 6. = Él terminó de trabajar a las 6.
- mind → Do you mind waiting? = ¿Te importa esperar?

Regla: verbo + verbo(-ing):
- enjoy + reading, like + swimming, mind + waiting...

¡OJO con estos errores típicos!
- ❌ I enjoy to read. → ✅ I enjoy reading.
- ❌ She like swim. → ✅ She likes swimming. (además, con she añadimos -s a "like": likes)`,
  examples: [
    { english: 'I enjoy reading.', spanish: 'Disfruto leyendo / Me gusta leer.', note: 'enjoy + -ing' },
    { english: 'She likes swimming.', spanish: 'A ella le gusta nadar.', note: 'like + -ing, con -s por she' },
    { english: 'Do you mind waiting?', spanish: '¿Te importa esperar?', note: 'mind + -ing' },
    { english: 'He finished working at 6.', spanish: 'Él terminó de trabajar a las 6.', note: 'finish + -ing' },
    { english: 'We hate cleaning on Sundays.', spanish: 'Odiamos limpiar los domingos.' },
    { english: 'She loves dancing.', spanish: 'A ella le encanta bailar.' },
  ],
  rule: `Regla:
- Después de like, love, enjoy, hate, finish y mind usamos otro verbo en forma -ing.
- Estructura: like/enjoy/hate/finish/mind + verbo(-ing).
- Con he/she/it, el primer verbo lleva -s: She likes swimming. (¡el gerundio no lleva -s!)`,
  commonMistakes: [
    { wrong: '❌ I enjoy to read.', correct: '✅ I enjoy reading.', explanation: 'Después de "enjoy" usamos el gerundio (-ing), nunca el infinitivo con "to".' },
    { wrong: '❌ She like swim.', correct: '✅ She likes swimming.', explanation: 'Con "she" añadimos -s a "like" (likes) y el segundo verbo va en -ing (swimming).' },
    { wrong: '❌ He finished to work at 6.', correct: '✅ He finished working at 6.', explanation: '"Finish" también va seguido de -ing, no de "to" + verbo.' },
  ],
  vocabulary: [
    { word: 'enjoy', translation_es: 'disfrutar de, gustar mucho', level: 'A1', category: 'verbs', partOfSpeech: 'verb', example: 'I enjoy reading.', exampleTranslation: 'Disfruto leyendo.' },
    { word: 'mind', translation_es: 'importar (en preguntas/negativas)', level: 'A2', category: 'verbs', partOfSpeech: 'verb', example: 'Do you mind waiting?', exampleTranslation: '¿Te importa esperar?' },
    { word: 'finish', translation_es: 'terminar', level: 'A1', category: 'verbs', partOfSpeech: 'verb', example: 'He finished working at 6.', exampleTranslation: 'Él terminó de trabajar a las 6.' },
    { word: 'hate', translation_es: 'odiar', level: 'A1', category: 'verbs', partOfSpeech: 'verb', example: 'We hate cleaning.', exampleTranslation: 'Odiamos limpiar.' },
    { word: 'swimming', translation_es: 'nadar (gerundio)', level: 'A1', category: 'gerunds', partOfSpeech: 'gerund', example: 'She likes swimming.', exampleTranslation: 'A ella le gusta nadar.' },
  ],
  grammarPoints: [
    {
      id: 'gp-verbs-ing',
      level: 'A2',
      name: 'Verbs + -ing (gerund)',
      explanation_es: 'Tras verbos como like, love, enjoy, hate, finish y mind usamos otro verbo en gerundio (-ing), equivalente al infinitivo español.',
      formula: 'like/love/enjoy/hate/finish/mind + verb(-ing)',
      examples: ['I enjoy reading.', 'She likes swimming.', 'Do you mind waiting?'],
    },
  ],
  exercises: [
    {
      id: 'a2-m12-l1-ex1',
      type: 'multiple_choice',
      concept: 'verbs + -ing',
      difficulty: 1,
      prompt: 'Completa: "I enjoy ___."',
      promptTranslation: 'Disfruto leyendo.',
      correctAnswer: 'reading',
      options: ['reading', 'to read', 'read'],
      explanation: 'Después de "enjoy" usamos el gerundio (-ing): I enjoy reading.',
    },
    {
      id: 'a2-m12-l1-ex2',
      type: 'fill_blank',
      concept: 'verbs + -ing',
      difficulty: 1,
      prompt: 'Completa: "She likes ___."',
      promptTranslation: 'A ella le gusta nadar.',
      correctAnswer: 'swimming',
      acceptedAnswers: ['swimming', 'Swimming'],
      explanation: 'Después de "likes" usamos el gerundio: swimming. → She likes swimming.',
    },
    {
      id: 'a2-m12-l1-ex3',
      type: 'multiple_choice',
      concept: 'verbs + -ing',
      difficulty: 2,
      prompt: 'Completa: "Do you mind ___?"',
      promptTranslation: '¿Te importa esperar?',
      correctAnswer: 'waiting',
      options: ['waiting', 'to wait', 'wait'],
      explanation: '"Mind" va seguido del gerundio: Do you mind waiting?',
    },
    {
      id: 'a2-m12-l1-ex4',
      type: 'fill_blank',
      concept: 'verbs + -ing',
      difficulty: 2,
      prompt: 'Completa: "He finished ___ at 6."',
      promptTranslation: 'Él terminó de trabajar a las 6.',
      correctAnswer: 'working',
      acceptedAnswers: ['working', 'Working'],
      explanation: '"Finish" + gerundio: finished working. = terminó de trabajar.',
    },
    {
      id: 'a2-m12-l1-ex5',
      type: 'error_correction',
      concept: 'verbs + -ing',
      difficulty: 3,
      prompt: 'Corrige el error: "I enjoy to read."',
      promptTranslation: 'Disfruto leyendo.',
      correctAnswer: 'I enjoy reading.',
      acceptedAnswers: ['I enjoy reading', 'I enjoy reading.', 'i enjoy reading'],
      acceptApproximate: true,
      explanation: 'Después de "enjoy" usamos -ing, no "to" + verbo: I enjoy reading.',
    },
    {
      id: 'a2-m12-l1-ex6',
      type: 'error_correction',
      concept: 'verbs + -ing',
      difficulty: 3,
      prompt: 'Corrige el error: "She like swim."',
      promptTranslation: 'A ella le gusta nadar.',
      correctAnswer: 'She likes swimming.',
      acceptedAnswers: ['She likes swimming', 'She likes swimming.', 'she likes swimming'],
      acceptApproximate: true,
      explanation: 'Dos correcciones: con "she" añadimos -s a "like" (likes) y el segundo verbo va en -ing (swimming).',
    },
    {
      id: 'a2-m12-l1-ex7',
      type: 'match',
      concept: 'verbs + -ing',
      difficulty: 2,
      prompt: 'Relaciona cada frase con su traducción.',
      promptTranslation: 'Match each sentence with its translation.',
      correctAnswer: 'I enjoy reading.=Disfruto leyendo; She likes swimming.=A ella le gusta nadar; Do you mind waiting?=¿Te importa esperar?; He finished working at 6.=Él terminó de trabajar a las 6; We hate cleaning.=Odiamos limpiar',
      pairs: [
        { left: 'I enjoy reading.', right: 'Disfruto leyendo.' },
        { left: 'She likes swimming.', right: 'A ella le gusta nadar.' },
        { left: 'Do you mind waiting?', right: '¿Te importa esperar?' },
        { left: 'He finished working at 6.', right: 'Él terminó de trabajar a las 6.' },
        { left: 'We hate cleaning.', right: 'Odiamos limpiar.' },
      ],
      explanation: 'Todas las frases usan la estructura verbo + gerundio (-ing).',
    },
    {
      id: 'a2-m12-l1-ex8',
      type: 'translate',
      concept: 'verbs + -ing',
      difficulty: 3,
      prompt: 'Traduce: "Me gusta leer."',
      promptTranslation: 'I like reading.',
      correctAnswer: 'I like reading.',
      acceptedAnswers: ['I like reading', 'I like reading.', 'i like reading', 'I love reading'],
      acceptApproximate: true,
      explanation: '"Me gusta + verbo" en inglés = like + gerundio. → I like reading.',
    },
    {
      id: 'a2-m12-l1-ex9',
      type: 'true_false',
      concept: 'verbs + -ing',
      difficulty: 2,
      prompt: 'Después de "enjoy" usamos el infinitivo con "to": "I enjoy to read".',
      promptTranslation: 'After "enjoy" we use "to" + verb: "I enjoy to read".',
      correctAnswer: 'false',
      acceptedAnswers: ['False', 'FALSE', 'f'],
      explanation: 'Falso. Después de "enjoy" usamos el gerundio (-ing): I enjoy reading.',
    },
    {
      id: 'a2-m12-l1-ex10',
      type: 'multiple_choice',
      concept: 'verbs + -ing',
      difficulty: 3,
      prompt: 'Completa: "I hate ___ up early."',
      promptTranslation: 'Odio levantarme temprano.',
      correctAnswer: 'getting',
      options: ['getting', 'to get', 'get'],
      explanation: '"Hate" + gerundio: I hate getting up early.',
    },
  ],
  miniTest: [
    {
      id: 'a2-m12-l1-mt1',
      type: 'multiple_choice',
      concept: 'verbs + -ing',
      difficulty: 1,
      prompt: 'Completa: "She loves ___."',
      promptTranslation: 'A ella le encanta bailar.',
      correctAnswer: 'dancing',
      options: ['dancing', 'to dance', 'dance'],
      explanation: '"Love" + gerundio: She loves dancing.',
    },
    {
      id: 'a2-m12-l1-mt2',
      type: 'fill_blank',
      concept: 'verbs + -ing',
      difficulty: 2,
      prompt: 'Completa: "We enjoy ___ time with our friends."',
      promptTranslation: 'Disfrutamos pasando tiempo con nuestros amigos.',
      correctAnswer: 'spending',
      acceptedAnswers: ['spending', 'Spending'],
      explanation: '"Enjoy" + gerundio: enjoy spending time.',
    },
    {
      id: 'a2-m12-l1-mt3',
      type: 'error_correction',
      concept: 'verbs + -ing',
      difficulty: 3,
      prompt: 'Corrige el error: "Do you mind to wait?"',
      promptTranslation: '¿Te importa esperar?',
      correctAnswer: 'Do you mind waiting?',
      acceptedAnswers: ['Do you mind waiting', 'Do you mind waiting?', 'do you mind waiting'],
      acceptApproximate: true,
      explanation: '"Mind" + gerundio, no "to" + verbo: Do you mind waiting?',
    },
    {
      id: 'a2-m12-l1-mt4',
      type: 'translate',
      concept: 'verbs + -ing',
      difficulty: 3,
      prompt: 'Traduce: "Él terminó de trabajar a las 6."',
      promptTranslation: 'He finished working at 6.',
      correctAnswer: 'He finished working at 6.',
      acceptedAnswers: ['He finished working at 6', 'He finished working at 6.', 'he finished working at 6'],
      acceptApproximate: true,
      explanation: '"Terminar de" + verbo = finish + gerundio: He finished working at 6.',
    },
    {
      id: 'a2-m12-l1-mt5',
      type: 'multiple_choice',
      concept: 'verbs + -ing',
      difficulty: 4,
      prompt: '¿Cuál es la frase correcta?',
      promptTranslation: 'Which sentence is correct?',
      correctAnswer: 'My brother hates cleaning his room.',
      options: ['My brother hates to cleaning his room.', 'My brother hates cleaning his room.', 'My brother hate cleaning his room.'],
      explanation: '"Hates" (con -s por brother/he) + gerundio "cleaning": la única correcta.',
    },
  ],
  reviewItems: ['a2-m11-l4'],
  prerequisites: ['a2-m11-l4'],
}
