import type { Lesson } from '../../types'

export const lesson94MiniTest: Lesson = {
  id: 'b1-m9-l4',
  moduleId: 'm9-third-conditional-wishes',
  order: 3,
  title: 'Mini-test: tercer condicional y deseos',
  objective: 'Evaluar el tercer condicional (forma, negativos, preguntas), wish/if only, y la comprensión de una reflexión sobre decisiones pasadas.',
  explanation_es: `Esta es la evaluación final del Módulo 9. Repasemos lo esencial:

**Tercer condicional (hipótesis pasadas):**
- if + had + participio → would have + participio
- If I had studied more, I would have passed.
- En la parte de "if" NO se usa "would": ✅ If I had studied, ❌ If I would have studied.

**Negativos y preguntas:**
- hadn't + participio / wouldn't have + participio
- If you hadn't helped me, I wouldn't have finished.
- Would you have done the same?

**wish / if only (deseos y arrepentimientos):**
- Deseo presente: wish + pasado simple: I wish I had more time.
- Arrepentimiento pasado: wish + past perfect: I wish I hadn't said that.
- Enfático: if only: If only I could speak English fluently.

**Errores típicos a evitar:**
- ❌ If I would have studied → ✅ If I had studied.
- ❌ I would have went → ✅ I would have gone.
- ❌ I wish I have more time → ✅ I wish I had more time.`,
  examples: [
    { english: 'If I had studied more, I would have passed.', spanish: 'Si hubiera estudiado más, habría aprobado.' },
    { english: 'If you hadn\'t helped me, I wouldn\'t have finished.', spanish: 'Si no me hubieras ayudado, no habría terminado.' },
    { english: 'Would you have done the same?', spanish: '¿Habrías hecho lo mismo?' },
    { english: 'I wish I hadn\'t said that.', spanish: 'Ojalá no hubiera dicho eso.' },
    { english: 'If only I could speak English fluently.', spanish: 'Ojalá pudiera hablar inglés con fluidez.' },
  ],
  rule: `**Resumen del módulo:**
- Tercer condicional: if + had + participio → would (not) have + participio.
- Preguntas: Would + sujeto + have + participio...?
- wish + pasado simple = deseo presente; wish + past perfect = arrepentimiento pasado; if only = enfático.`,
  commonMistakes: [
    { wrong: '❌ If I would have studied more, I would have passed.', correct: '✅ If I had studied more, I would have passed.', explanation: 'En la parte de "if" se usa "had + participio", nunca "would have".' },
    { wrong: '❌ I wish I have more time.', correct: '✅ I wish I had more time.', explanation: 'Los deseos presentes usan el pasado simple después de "wish".' },
    { wrong: '❌ I would have went to the party.', correct: '✅ I would have gone to the party.', explanation: 'Después de "would have" va el participio: gone.' },
  ],
  vocabulary: [],
  grammarPoints: [],
  exercises: [
    {
      id: 'b1-m9-l4-ex1',
      type: 'multiple_choice',
      concept: 'module 9 - third conditional form',
      difficulty: 1,
      prompt: 'Completa: "If I ___ known, I would have come."',
      promptTranslation: 'Si hubiera sabido, habría venido.',
      correctAnswer: 'had',
      options: ['had', 'have', 'would'],
      explanation: 'La parte de "if" usa "had + participio": had known.',
    },
    {
      id: 'b1-m9-l4-ex2',
      type: 'fill_blank',
      concept: 'module 9 - would have',
      difficulty: 2,
      prompt: 'Completa: "They would have ___ (buy) the house if it had been cheaper."',
      promptTranslation: 'Habrían comprado la casa si hubiera sido más barata.',
      correctAnswer: 'bought',
      acceptedAnswers: ['bought', 'Bought'],
      explanation: 'Después de "would have" va el participio: "buy" → "bought".',
    },
    {
      id: 'b1-m9-l4-ex3',
      type: 'multiple_choice',
      concept: 'module 9 - wish past simple',
      difficulty: 2,
      prompt: 'Completa: "I wish I ___ speak English better."',
      promptTranslation: 'Ojalá hablara mejor inglés.',
      correctAnswer: 'could',
      options: ['could', 'can', 'will'],
      explanation: 'Deseo presente con "wish": wish + could (pasado de can).',
    },
    {
      id: 'b1-m9-l4-ex4',
      type: 'error_correction',
      concept: 'module 9 - third conditional if would',
      difficulty: 3,
      prompt: 'Corrige el error: "If I would have known, I would have helped."',
      promptTranslation: 'Si hubiera sabido, habría ayudado.',
      correctAnswer: 'If I had known, I would have helped.',
      acceptedAnswers: ['If I had known, I would have helped', 'If I had known, I would have helped.', 'if i had known, i would have helped'],
      acceptApproximate: true,
      explanation: 'En la parte de "if" no se usa "would": If I had known.',
    },
    {
      id: 'b1-m9-l4-ex5',
      type: 'match',
      concept: 'module 9 - third conditional and wishes review',
      difficulty: 3,
      prompt: 'Relaciona cada inicio de frase con su continuación correcta.',
      promptTranslation: 'Match each sentence beginning with its correct ending.',
      correctAnswer: 'If I had studied more=I would have passed.; I wish I had more time=I could relax more.; If you hadn\'t helped me=I wouldn\'t have finished.; I wish I hadn\'t said that=it was a mistake.; If only I could swim=I would join you at the beach.',
      pairs: [
        { left: 'If I had studied more', right: 'I would have passed.' },
        { left: 'I wish I had more time', right: 'I could relax more.' },
        { left: 'If you hadn\'t helped me', right: 'I wouldn\'t have finished.' },
        { left: 'I wish I hadn\'t said that', right: 'it was a mistake.' },
        { left: 'If only I could swim', right: 'I would join you at the beach.' },
      ],
      explanation: 'El tercer condicional combina if + had + participio con would have + participio; wish expresa deseos presentes o arrepentimientos pasados.',
    },
    {
      id: 'b1-m9-l4-ex6',
      type: 'reading',
      concept: 'module 9 - a reflection on past decisions',
      difficulty: 4,
      prompt: 'Lee la reflexión sobre decisiones pasadas y responde las preguntas.',
      reading: {
        text: 'A reflection\nWhen I was younger, I didn\'t take my studies seriously. If I had studied harder, I would have gone to a better university. I wish I had listened to my teachers. However, if I hadn\'t changed my life at 25, I wouldn\'t have met my wife. I wish I could tell my younger self to be patient. In the end, I don\'t regret most of my decisions, because they made me who I am today.',
        translation: 'Una reflexión\nCuando era más joven, no me tomé los estudios en serio. Si hubiera estudiado más, habría ido a una mejor universidad. Ojalá hubiera escuchado a mis profesores. Sin embargo, si no hubiera cambiado mi vida a los 25, no habría conocido a mi mujer. Ojalá pudiera decirle a mi yo más joven que tuviera paciencia. Al final, no me arrepiento de la mayoría de mis decisiones, porque me hicieron quien soy hoy.',
        questions: [
          {
            id: 'b1-m9-l4-ex6-q1',
            type: 'multiple_choice',
            concept: 'module 9 - reading comprehension',
            difficulty: 4,
            prompt: '¿Qué habría pasado si hubiera estudiado más?',
            correctAnswer: 'Habría ido a una mejor universidad.',
            options: ['Habría ido a una mejor universidad.', 'Habría conocido a su mujer antes.', 'No habría cambiado de vida.'],
            explanation: 'El texto dice: "If I had studied harder, I would have gone to a better university."',
          },
          {
            id: 'b1-m9-l4-ex6-q2',
            type: 'multiple_choice',
            concept: 'module 9 - wish past perfect',
            difficulty: 4,
            prompt: '"I wish I had listened to my teachers." ¿Qué expresa esta frase?',
            correctAnswer: 'Un arrepentimiento por el pasado.',
            options: ['Un arrepentimiento por el pasado.', 'Un plan para el futuro.', 'Una obligación diaria.'],
            explanation: '"Wish + past perfect" expresa arrepentimiento por algo del pasado.',
          },
          {
            id: 'b1-m9-l4-ex6-q3',
            type: 'multiple_choice',
            concept: 'module 9 - third conditional negative',
            difficulty: 4,
            prompt: 'Según el texto, ¿qué pasó gracias a cambiar su vida a los 25?',
            correctAnswer: 'Conoció a su mujer.',
            options: ['Conoció a su mujer.', 'Fue a la universidad.', 'Se arrepintió de todo.'],
            explanation: '"If I hadn\'t changed my life at 25, I wouldn\'t have met my wife." → Conocer a su mujer fue consecuencia del cambio.',
          },
          {
            id: 'b1-m9-l4-ex6-q4',
            type: 'multiple_choice',
            concept: 'module 9 - wish could',
            difficulty: 4,
            prompt: '¿Qué desea poder decirle a su yo más joven?',
            correctAnswer: 'Que tuviera paciencia.',
            options: ['Que tuviera paciencia.', 'Que estudiara medicina.', 'Que se mudara antes.'],
            explanation: '"I wish I could tell my younger self to be patient."',
          },
          {
            id: 'b1-m9-l4-ex6-q5',
            type: 'multiple_choice',
            concept: 'module 9 - reading comprehension',
            difficulty: 4,
            prompt: '¿Se arrepiente de la mayoría de sus decisiones?',
            correctAnswer: 'No, porque le hicieron quien es hoy.',
            options: ['No, porque le hicieron quien es hoy.', 'Sí, totalmente.', 'No lo sabe.'],
            explanation: '"In the end, I don\'t regret most of my decisions, because they made me who I am today."',
          },
        ],
      },
      correctAnswer: 'reading complete',
      explanation: 'La reflexión combina el tercer condicional (If I had studied harder, I would have gone...), sus negativas (if I hadn\'t changed...) y wish/if only (I wish I had listened..., I wish I could tell...).',
    },
    {
      id: 'b1-m9-l4-ex7',
      type: 'reorder',
      concept: 'module 9 - third conditional',
      difficulty: 3,
      prompt: 'Ordena las palabras: If / she / known, / had / she / have / would / come',
      promptTranslation: 'Si ella hubiera sabido, habría venido.',
      correctAnswer: 'If she had known, she would have come.',
      words: ['If', 'she', 'had', 'known', 'she', 'would', 'have', 'come'],
      explanation: 'Orden: If + sujeto + had + participio, + sujeto + would have + participio. → If she had known, she would have come.',
    },
    {
      id: 'b1-m9-l4-ex8',
      type: 'translate',
      concept: 'module 9 - third conditional',
      difficulty: 3,
      prompt: 'Traduce: "Si me hubieras ayudado, habría terminado."',
      promptTranslation: 'If you had helped me, I would have finished.',
      correctAnswer: 'If you had helped me, I would have finished.',
      acceptedAnswers: ['If you had helped me, I would have finished', 'If you had helped me, I would have finished.', 'if you had helped me, i would have finished'],
      acceptApproximate: true,
      explanation: '"Hubieras ayudado" = had helped; "habría terminado" = would have finished.',
    },
    {
      id: 'b1-m9-l4-ex9',
      type: 'true_false',
      concept: 'module 9 - wish',
      difficulty: 3,
      prompt: 'La frase "I wish I have more time" es correcta.',
      promptTranslation: '"I wish I have more time" is correct.',
      correctAnswer: 'false',
      acceptedAnswers: ['False', 'FALSE', 'f'],
      explanation: 'Falso. Después de "wish" usamos el pasado simple: I wish I had more time.',
    },
    {
      id: 'b1-m9-l4-ex10',
      type: 'multiple_choice',
      concept: 'module 9 - third conditional negative',
      difficulty: 4,
      prompt: '¿Cuál es la forma negativa correcta de la parte "if"?',
      promptTranslation: 'Which is the correct negative "if" clause?',
      correctAnswer: 'If we hadn\'t missed the train, we would have arrived earlier.',
      options: ['If we hadn\'t missed the train, we would have arrived earlier.', 'If we didn\'t missed the train, we would have arrived earlier.', 'If we wouldn\'t have missed the train, we would have arrived earlier.'],
      explanation: 'La negativa en la parte de "if" es "hadn\'t + participio": hadn\'t missed.',
    },
    {
      id: 'b1-m9-l4-ex11',
      type: 'listening',
      concept: 'module 9 - comprehensive listening',
      difficulty: 4,
      prompt: 'Escuchá el audio y respondé las preguntas (en inglés, sobre lo que dice).',
      correctAnswer: '',
      explanation: 'Un empleado reflexiona sobre decisiones de carrera pasadas combinando tercer condicional y wish.',
      listening: {
        audioText:
          "I\'ve been thinking about my career lately. If I had taken that job offer ten years ago, I would have moved to London. But I turned it down because I wasn\'t brave enough. I wish I had been more courageous. If only I hadn\'t let fear stop me! However, if I hadn\'t stayed here, I wouldn\'t have met my current team, who are amazing. So maybe some decisions work out better than we expect.",
        audioUrl: '/audio/tts/b1-m9-l4-ex11.mp3',
        questions: [
          {
            id: 'b1-m9-l4-ex11-q1',
            type: 'multiple_choice',
            concept: 'listening comprehension',
            difficulty: 3,
            prompt: 'What would have happened if he had taken the job offer?',
            correctAnswer: 'He would have moved to London',
            options: ['He would have moved to London', 'He would have stayed at home', 'He would have travelled worldwide'],
            explanation: '"If I had taken that job offer ten years ago, I would have moved to London."',
          },
          {
            id: 'b1-m9-l4-ex11-q2',
            type: 'true_false',
            concept: 'listening comprehension',
            difficulty: 3,
            prompt: 'He wishes he had been more courageous.',
            correctAnswer: 'true',
            explanation: '"I wish I had been more courageous." — This is a past regret using wish + past perfect.',
          },
          {
            id: 'b1-m9-l4-ex11-q3',
            type: 'multiple_choice',
            concept: 'listening comprehension',
            difficulty: 4,
            prompt: 'Why is he grateful he didn\'t take the job?',
            correctAnswer: 'He wouldn\'t have met his current amazing team',
            options: ['He wouldn\'t have met his current amazing team', 'He saved more money', 'He had more free time'],
            explanation: '"If I hadn\'t stayed here, I wouldn\'t have met my current team, who are amazing."',
          },
        ],
      },
    },
    {
      id: 'b1-m9-l4-ex12',
      type: 'writing',
      concept: 'module 9 - comprehensive writing',
      difficulty: 4,
      prompt: 'Escribi un email reflexivo a un mentor contándole sobre una decisión importante del pasado y qué hubiera pasado si hubieras hecho algo diferente (usá tercer condicional y wish).',
      promptTranslation: 'Write a reflective email to a mentor about an important past decision and what would have happened if you had done something different.',
      correctAnswer: '',
      explanation: 'Un buen texto combina tercer condicional (if + had, would have) y wish/if only, manteniendo un registro más formal que informal pero accesible.',
      taskType: 'email',
      targetReader: 'a mentor',
      register: 'neutral',
      contentPoints: ['Una decisión importante del pasado', 'Hipótesis sobre qué hubiera pasado diferente', 'Reflexión sobre el resultado actual'],
      requiresOwnIdea: true,
      minWords: 70,
      maxWords: 110,
    },
    {
      id: 'b1-m9-l4-ex13',
      type: 'speaking',
      concept: 'module 9 - comprehensive speaking',
      difficulty: 3,
      prompt: 'Escuchá la frase modelo y repetila en voz alta.',
      correctAnswer: 'I wish I had known how important this moment would become, but if I had known, I wouldn\'t have appreciated it the same way.',
      explanation: 'Practicá la combinación de wish + past perfect y tercer condicional en una reflexión más larga, manteniendo la entonación natural.',
      speakingMode: 'repeat',
    },
  ],
  miniTest: [
    {
      id: 'b1-m9-l4-mt1',
      type: 'multiple_choice',
      concept: 'module 9 final - third conditional',
      difficulty: 2,
      prompt: 'Completa: "If I had been there, I ___ you."',
      promptTranslation: 'Si hubiera estado allí, te habría ayudado.',
      correctAnswer: 'would have helped',
      options: ['would have helped', 'had helped', 'will help'],
      explanation: 'Consecuencia en pasado: would have + participio → would have helped.',
    },
    {
      id: 'b1-m9-l4-mt2',
      type: 'fill_blank',
      concept: 'module 9 final - wish',
      difficulty: 2,
      prompt: 'Completa: "I wish I ___ (have) a car."',
      promptTranslation: 'Ojalá tuviera un coche.',
      correctAnswer: 'had',
      acceptedAnswers: ['had', 'Had'],
      explanation: 'Deseo presente: wish + pasado simple (had).',
    },
    {
      id: 'b1-m9-l4-mt3',
      type: 'error_correction',
      concept: 'module 9 final - third conditional participle',
      difficulty: 3,
      prompt: 'Corrige el error: "I would have went home early."',
      promptTranslation: 'Habría ido a casa temprano.',
      correctAnswer: 'I would have gone home early.',
      acceptedAnswers: ['I would have gone home early', 'I would have gone home early.', 'i would have gone home early'],
      acceptApproximate: true,
      explanation: 'Después de "would have" va el participio: "went" → "gone".',
    },
    {
      id: 'b1-m9-l4-mt4',
      type: 'translate',
      concept: 'module 9 final - wish',
      difficulty: 3,
      prompt: 'Traduce: "Ojalá tuviera más tiempo."',
      promptTranslation: 'I wish I had more time.',
      correctAnswer: 'I wish I had more time.',
      acceptedAnswers: ['I wish I had more time', 'I wish I had more time.', 'i wish i had more time'],
      acceptApproximate: true,
      explanation: '"Ojalá tuviera" (deseo presente) = wish + had (pasado simple).',
    },
    {
      id: 'b1-m9-l4-mt5',
      type: 'multiple_choice',
      concept: 'module 9 final - wish past perfect',
      difficulty: 4,
      prompt: '¿Cuál es la frase correcta para expresar arrepentimiento por haber llegado tarde?',
      promptTranslation: 'Which sentence correctly expresses regret about arriving late?',
      correctAnswer: 'I wish I hadn\'t arrived late.',
      options: ["I wish I hadn't arrived late.", "I wish I didn't arrived late.", "I wish I haven't arrived late."],
      explanation: 'El arrepentimiento pasado usa wish + hadn\'t + participio: hadn\'t arrived.',
    },
  ],
  reviewItems: ['b1-m9-l3'],
  prerequisites: ['b1-m9-l3'],
}
