import type { Lesson } from '../../types'

export const lesson84MiniTest: Lesson = {
  id: 'b1-m8-l4',
  moduleId: 'm8-relative-clauses-ext',
  order: 3,
  title: 'Mini-test: oraciones de relativo (extendido)',
  objective: 'Evaluar las oraciones de relativo no definidoras, whose/where/when/why, preposición + whom, y la comprensión de un texto que describe personas y lugares.',
  explanation_es: `Esta es la evaluación final del Módulo 8. Repasemos lo esencial:

**No definidoras (información extra, entre comas):**
- who = personas, which = cosas. NUNCA "that".
- My brother, who lives in London, is a doctor.

**whose / where / when / why:**
- whose = posesión (cuyo/cuya): The man whose car was stolen is angry.
- where = lugar: the town where I grew up.
- when = tiempo: the day when we met.
- why = razón: the reason why he left.

**Preposición + whom (formal):**
- The woman to whom I spoke was kind. (formal)
- The woman who I spoke to was kind. (informal)

**Errores típicos a evitar:**
- ❌ My brother, that lives in London → ✅ My brother, who lives in London.
- ❌ the man who his car → ✅ the man whose car.
- ❌ to who (formal) → ✅ to whom.`,
  examples: [
    { english: 'My brother, who lives in London, is a doctor.', spanish: 'Mi hermano, que vive en Londres, es médico.' },
    { english: 'The man whose car was stolen is angry.', spanish: 'El hombre cuyo coche fue robado está enfadado.' },
    { english: 'That\'s the town where I grew up.', spanish: 'Esa es la ciudad donde crecí.' },
    { english: 'The reason why he left is unknown.', spanish: 'La razón por la que se fue es desconocida.' },
    { english: 'The woman to whom I spoke was kind.', spanish: 'La mujer con la que hablé fue amable.' },
  ],
  rule: `**Resumen del módulo:**
- No definidoras: información extra entre comas, con who/which (nunca that).
- whose (posesión), where (lugar), when (tiempo), why (razón).
- Formal: preposición + whom; informal: who + preposición al final.`,
  commonMistakes: [
    { wrong: '❌ My brother, that lives in London, is a doctor.', correct: '✅ My brother, who lives in London, is a doctor.', explanation: 'En las no definidoras no se usa "that".' },
    { wrong: '❌ The man who his car was stolen is angry.', correct: '✅ The man whose car was stolen is angry.', explanation: 'Para posesión se usa "whose".' },
    { wrong: '❌ The woman to who I spoke was kind.', correct: '✅ The woman to whom I spoke was kind.', explanation: 'Tras preposición, en formal se usa "whom".' },
  ],
  vocabulary: [],
  grammarPoints: [],
  exercises: [
    {
      id: 'b1-m8-l4-ex1',
      type: 'multiple_choice',
      concept: 'module 8 - non-defining who',
      difficulty: 1,
      prompt: 'Completa: "My uncle, ___ retired last year, travels a lot."',
      promptTranslation: 'Mi tío, que se jubiló el año pasado, viaja mucho.',
      correctAnswer: 'who',
      options: ['who', 'which', 'that'],
      explanation: 'Persona en no definidora → who.',
    },
    {
      id: 'b1-m8-l4-ex2',
      type: 'fill_blank',
      concept: 'module 8 - relative whose',
      difficulty: 2,
      prompt: 'Completa: "The woman ___ house is near the beach is my aunt."',
      promptTranslation: 'La mujer cuya casa está cerca de la playa es mi tía.',
      correctAnswer: 'whose',
      acceptedAnswers: ['whose', 'Whose'],
      explanation: 'Posesión → whose + objeto poseído (house).',
    },
    {
      id: 'b1-m8-l4-ex3',
      type: 'multiple_choice',
      concept: 'module 8 - non-defining which',
      difficulty: 2,
      prompt: 'Completa: "The park, ___ is in the centre, is my favourite place."',
      promptTranslation: 'El parque, que está en el centro, es mi lugar favorito.',
      correctAnswer: 'which',
      options: ['which', 'who', 'that'],
      explanation: 'Cosa en no definidora → which.',
    },
    {
      id: 'b1-m8-l4-ex4',
      type: 'error_correction',
      concept: 'module 8 - non-defining that',
      difficulty: 3,
      prompt: 'Corrige el error: "The restaurant, that we love, is closed today."',
      promptTranslation: 'El restaurante, que nos encanta, está cerrado hoy.',
      correctAnswer: 'The restaurant, which we love, is closed today.',
      acceptedAnswers: ['The restaurant, which we love, is closed today', 'The restaurant, which we love, is closed today.', 'the restaurant, which we love, is closed today'],
      acceptApproximate: true,
      explanation: 'En no definidora no se usa "that"; con cosa usamos "which".',
    },
    {
      id: 'b1-m8-l4-ex5',
      type: 'match',
      concept: 'module 8 - relative words review',
      difficulty: 3,
      prompt: 'Relaciona cada palabra de relativo con su ejemplo.',
      promptTranslation: 'Match each relative word with its example.',
      correctAnswer: 'whose=the man whose car was stolen; where=the town where I grew up; when=the day when we met; why=the reason why he left; who=the woman who lives next door',
      pairs: [
        { left: 'whose', right: 'The man ___ car was stolen is angry.' },
        { left: 'where', right: 'That\'s the town ___ I grew up.' },
        { left: 'when', right: 'I remember the day ___ we met.' },
        { left: 'why', right: 'The reason ___ he left is unknown.' },
        { left: 'who', right: 'The woman ___ lives next door is my aunt.' },
      ],
      explanation: 'whose (posesión), where (lugar), when (tiempo), why (razón) y who (persona).',
    },
    {
      id: 'b1-m8-l4-ex6',
      type: 'reading',
      concept: 'module 8 - describing people and places',
      difficulty: 4,
      prompt: 'Lee el texto sobre un barrio y responde las preguntas.',
      reading: {
        text: 'My neighbourhood\nMy neighbourhood is small but lively. There is a bakery, which makes the best bread in town, on the corner. The baker, whose family has worked there for years, is always smiling. I often go to the park where children play in the afternoon. I remember the summer when we first moved here. That is also the reason why I love this place so much.',
        translation: 'Mi barrio\nMi barrio es pequeño pero animado. Hay una panadería, que hace el mejor pan de la ciudad, en la esquina. El panadero, cuya familia ha trabajado allí durante años, siempre está sonriendo. A menudo voy al parque donde juegan los niños por la tarde. Recuerdo el verano cuando nos mudamos aquí por primera vez. Esa es también la razón por la que quiero tanto este lugar.',
        questions: [
          {
            id: 'b1-m8-l4-ex6-q1',
            type: 'multiple_choice',
            concept: 'module 8 - reading comprehension',
            difficulty: 4,
            prompt: '¿Dónde está la panadería?',
            correctAnswer: 'En la esquina.',
            options: ['En la esquina.', 'En el parque.', 'Cerca de la playa.'],
            explanation: 'El texto dice: "There is a bakery, which makes the best bread in town, on the corner."',
          },
          {
            id: 'b1-m8-l4-ex6-q2',
            type: 'multiple_choice',
            concept: 'module 8 - relative whose',
            difficulty: 4,
            prompt: 'En "The baker, whose family has worked there for years", ¿a quién se refiere "whose family"?',
            correctAnswer: 'A la familia del panadero.',
            options: ['A la familia del panadero.', 'A la familia del vecino.', 'A la familia de los niños.'],
            explanation: '"Whose" indica posesión: la familia DEL panadero.',
          },
          {
            id: 'b1-m8-l4-ex6-q3',
            type: 'multiple_choice',
            concept: 'module 8 - relative where',
            difficulty: 4,
            prompt: '¿Qué dice el texto sobre el parque?',
            correctAnswer: 'Que es donde juegan los niños por la tarde.',
            options: ['Que es donde juegan los niños por la tarde.', 'Que está en la esquina.', 'Que hace el mejor pan.'],
            explanation: '"I often go to the park where children play in the afternoon."',
          },
          {
            id: 'b1-m8-l4-ex6-q4',
            type: 'multiple_choice',
            concept: 'module 8 - relative why',
            difficulty: 4,
            prompt: 'Según el texto, ¿por qué quiere tanto el lugar?',
            correctAnswer: 'Por el recuerdo del verano cuando se mudaron.',
            options: ['Por el recuerdo del verano cuando se mudaron.', 'Porque no tiene otra opción.', 'Porque el parque está cerca.'],
            explanation: '"That is also the reason why I love this place so much." La razón es el recuerdo del verano en que se mudaron.',
          },
          {
            id: 'b1-m8-l4-ex6-q5',
            type: 'multiple_choice',
            concept: 'module 8 - relative when',
            difficulty: 4,
            prompt: '¿Qué palabra de relativo describe un tiempo en el texto?',
            correctAnswer: 'when ("the summer when we first moved here")',
            options: ['when ("the summer when we first moved here")', 'whose ("whose family")', 'where ("the park where")'],
            explanation: '"When" se usa con tiempos: I remember the summer when we first moved here.',
          },
        ],
      },
      correctAnswer: 'reading complete',
      explanation: 'El texto usa las oraciones de relativo para describir el barrio: which (la panadería), whose (la familia del panadero), where (el parque), when (el verano) y why (la razón).',
    },
    {
      id: 'b1-m8-l4-ex7',
      type: 'reorder',
      concept: 'module 8 - non-defining',
      difficulty: 3,
      prompt: 'Ordena las palabras: My / who / teacher, / patient / is / explains / very / everything / twice,',
      promptTranslation: 'Mi profesora, que es muy paciente, lo explica todo dos veces.',
      correctAnswer: 'My teacher, who is very patient, explains everything twice.',
      words: ['My', 'teacher', 'who', 'is', 'very', 'patient', 'explains', 'everything', 'twice'],
      explanation: 'No definidora: sujeto + coma + who + frase + coma + verbo principal. → My teacher, who is very patient, explains everything twice.',
    },
    {
      id: 'b1-m8-l4-ex8',
      type: 'translate',
      concept: 'module 8 - preposition whom',
      difficulty: 3,
      prompt: 'Traduce (formal): "La mujer con la que hablé fue amable."',
      promptTranslation: 'The woman to whom I spoke was kind.',
      correctAnswer: 'The woman to whom I spoke was kind.',
      acceptedAnswers: ['The woman to whom I spoke was kind', 'The woman who I spoke to was kind', 'the woman to whom i spoke was kind.'],
      acceptApproximate: true,
      explanation: 'Formal: "to whom I spoke". También vale informal: "who I spoke to".',
    },
    {
      id: 'b1-m8-l4-ex9',
      type: 'true_false',
      concept: 'module 8 - relative where',
      difficulty: 3,
      prompt: 'La frase "That\'s the town where I grew up in" es correcta.',
      promptTranslation: '"That\'s the town where I grew up in" is correct.',
      correctAnswer: 'false',
      acceptedAnswers: ['False', 'FALSE', 'f'],
      explanation: 'Falso. Con "where" no añadimos preposición al final: where I grew up.',
    },
    {
      id: 'b1-m8-l4-ex10',
      type: 'multiple_choice',
      concept: 'module 8 - formal informal',
      difficulty: 4,
      prompt: '¿Cuál es la versión informal de "The man to whom I gave the keys"?',
      promptTranslation: 'Which is the informal version of "The man to whom I gave the keys"?',
      correctAnswer: 'The man who I gave the keys to.',
      options: ['The man who I gave the keys to.', 'The man whom I gave the keys to him.', 'The man to who I gave the keys.'],
      explanation: 'Informal: preposición al final + who: who I gave the keys to.',
    },
    {
      id: 'b1-m8-l4-ex11',
      type: 'listening',
      concept: 'module 8 comprehensive listening',
      difficulty: 4,
      prompt: 'Escuchá el audio sobre una ciudad interesante y respondé las preguntas (en inglés).',
      correctAnswer: '',
      explanation: 'El audio describe una ciudad con varios tipos de oraciones de relativo: no definidoras (with commas), whose (posesión), where/when/why, y contexto formal.',
      listening: {
        audioText:
          "Barcelona is a city where I spent an unforgettable summer. It\'s a place where history meets modern art. The architect whose designs changed the city forever is Antoni Gaudí. His most famous work, which attracts millions of visitors every year, is the Sagrada Familia. The reason why I fell in love with Barcelona is the combination of culture, food, and friendly people. I remember the day when I first visited the Gothic Quarter. The local guide, to whom I asked many questions about the city, was incredibly knowledgeable.",
        questions: [
          {
            id: 'b1-m8-l4-ex11-q1',
            type: 'multiple_choice',
            concept: 'module 8 listening comprehension',
            difficulty: 3,
            prompt: 'What is the Sagrada Familia?',
            correctAnswer: 'A famous work by Gaudí',
            options: ['A famous work by Gaudí', 'A famous restaurant', 'A local newspaper'],
            explanation: '"His most famous work, which attracts millions of visitors every year, is the Sagrada Familia."',
          },
          {
            id: 'b1-m8-l4-ex11-q2',
            type: 'true_false',
            concept: 'module 8 listening comprehension',
            difficulty: 3,
            prompt: 'Antoni Gaudí is the architect whose designs changed Barcelona.',
            correctAnswer: 'true',
            explanation: '"The architect whose designs changed the city forever is Antoni Gaudí."',
          },
          {
            id: 'b1-m8-l4-ex11-q3',
            type: 'multiple_choice',
            concept: 'module 8 listening comprehension',
            difficulty: 4,
            prompt: 'Why did the speaker fall in love with Barcelona?',
            correctAnswer: 'Because of culture, food, and friendly people',
            options: ['Because of culture, food, and friendly people', 'Because of the weather', 'Because of the beaches'],
            explanation: '"The reason why I fell in love with Barcelona is the combination of culture, food, and friendly people."',
          },
        ],
      },
    },
    {
      id: 'b1-m8-l4-ex12',
      type: 'writing',
      concept: 'module 8 comprehensive writing',
      difficulty: 4,
      prompt: 'Escribí un texto sobre un viaje o experiencia especial. Usa al menos 4 tipos diferentes de oraciones de relativo: no definidoras (who/which con comas), whose, where, y when o why.',
      promptTranslation: 'Write about a special trip or experience. Use at least 4 different types of relative clauses: non-defining (who/which with commas), whose, where, and when or why.',
      correctAnswer: '',
      explanation: 'Un excelente texto integra naturalmente varios tipos de oraciones de relativo para describir una experiencia de forma detallada y clara.',
      taskType: 'story',
      targetReader: 'yourself',
      register: 'informal',
      contentPoints: ['La experiencia o viaje especial', 'Al menos 4 tipos de oraciones de relativo: non-defining, whose, where, when/why', 'Detalles que hagan la historia interesante'],
      requiresOwnIdea: true,
      minWords: 80,
      maxWords: 120,
    },
    {
      id: 'b1-m8-l4-ex13',
      type: 'speaking',
      concept: 'module 8 comprehensive speaking',
      difficulty: 3,
      prompt: 'Escuchá la frase modelo y repetila en voz alta.',
      correctAnswer: 'My cousin, whose family moved to Canada last year, works in a company where they value innovation and creativity.',
      explanation: 'Practicá la entonación natural con múltiples cláusulas, manteniendo un flujo conversacional.',
      speakingMode: 'repeat',
    },
  ],
  miniTest: [
    {
      id: 'b1-m8-l4-mt1',
      type: 'multiple_choice',
      concept: 'module 8 final - relative whose',
      difficulty: 2,
      prompt: 'Completa: "The boy ___ bicycle is new is my cousin."',
      promptTranslation: 'El chico cuya bicicleta es nueva es mi primo.',
      correctAnswer: 'whose',
      options: ['whose', 'who', 'where'],
      explanation: 'Posesión → whose + bicycle.',
    },
    {
      id: 'b1-m8-l4-mt2',
      type: 'fill_blank',
      concept: 'module 8 final - relative when',
      difficulty: 2,
      prompt: 'Completa: "Spring is the season ___ everything blooms."',
      promptTranslation: 'La primavera es la estación cuando todo florece.',
      correctAnswer: 'when',
      acceptedAnswers: ['when', 'When'],
      explanation: 'Tiempo → when. → the season when everything blooms.',
    },
    {
      id: 'b1-m8-l4-mt3',
      type: 'error_correction',
      concept: 'module 8 final - non-defining',
      difficulty: 3,
      prompt: 'Corrige el error: "This laptop, that I bought in March, is very fast."',
      promptTranslation: 'Este portátil, que compré en marzo, es muy rápido.',
      correctAnswer: 'This laptop, which I bought in March, is very fast.',
      acceptedAnswers: ['This laptop, which I bought in March, is very fast', 'This laptop, which I bought in March, is very fast.', 'this laptop, which i bought in march, is very fast'],
      acceptApproximate: true,
      explanation: 'En no definidora no se usa "that"; con cosa usamos "which".',
    },
    {
      id: 'b1-m8-l4-mt4',
      type: 'translate',
      concept: 'module 8 final - non-defining who',
      difficulty: 3,
      prompt: 'Traduce: "Mi padre, que trabaja en el extranjero, viene mañana."',
      promptTranslation: 'My father, who works abroad, is coming tomorrow.',
      correctAnswer: 'My father, who works abroad, is coming tomorrow.',
      acceptedAnswers: ['My father, who works abroad, is coming tomorrow', 'My father, who works abroad, is coming tomorrow.', 'my father, who works abroad, is coming tomorrow'],
      acceptApproximate: true,
      explanation: 'Información extra con who + comas: My father, who works abroad, is coming tomorrow.',
    },
    {
      id: 'b1-m8-l4-mt5',
      type: 'multiple_choice',
      concept: 'module 8 final - relative why',
      difficulty: 4,
      prompt: '¿Cuál es la frase correcta?',
      promptTranslation: 'Which sentence is correct?',
      correctAnswer: 'The reason why she resigned was the salary.',
      options: ['The reason why she resigned was the salary.', 'The reason that why she resigned was the salary.', 'The reason where she resigned was the salary.'],
      explanation: 'Con "the reason" usamos "why".',
    },
  ],
  reviewItems: ['b1-m8-l3'],
  prerequisites: ['b1-m8-l3'],
}
