import type { WorkbookPage } from './types'
import type { Exercise } from '../types'

export const a1Workbook: WorkbookPage[] = [
  {
    id: 'a1-wb-1',
    levelId: 'a1',
    unit: 'Unit 1 · Greetings and to be',
    page: 1,
    title: 'Hello! Saludos y presentarse',
    intro: 'En esta página practicamos los saludos en inglés y el verbo "to be" (ser/estar) en afirmativo para presentarnos.',
    exercises: [
      {
        id: 'a1-wb-p1-ex1',
        type: 'match',
        concept: 'greetings vocabulary',
        difficulty: 1,
        prompt: 'Relaciona cada saludo en inglés con su significado en español.',
        correctAnswer: 'match',
        pairs: [
          { left: 'Hello', right: 'Hola' },
          { left: 'Good morning', right: 'Buenos días' },
          { left: 'Goodbye', right: 'Adiós' },
          { left: 'Good night', right: 'Buenas noches' },
          { left: 'How are you?', right: '¿Cómo estás?' },
        ],
        explanation: 'Hello = Hola, Good morning = Buenos días, Goodbye = Adiós, Good night = Buenas noches y How are you? = ¿Cómo estás?',
      },
      {
        id: 'a1-wb-p1-ex2',
        type: 'multiple_choice',
        concept: 'verb to be affirmative',
        difficulty: 1,
        prompt: 'Completa: "I ___ María."',
        promptTranslation: 'Yo soy María.',
        correctAnswer: 'am',
        options: ['am', 'is', 'are'],
        explanation: 'Con "I" usamos "am". → I am María. = Yo soy María.',
      },
      {
        id: 'a1-wb-p1-ex3',
        type: 'fill_blank',
        concept: 'verb to be affirmative',
        difficulty: 1,
        prompt: 'Completa: "She ___ a teacher."',
        promptTranslation: 'Ella es profesora.',
        correctAnswer: 'is',
        acceptedAnswers: ['is'],
        explanation: 'Con "she" usamos "is". → She is a teacher. = Ella es profesora.',
      },
      {
        id: 'a1-wb-p1-ex4',
        type: 'multiple_choice',
        concept: 'verb to be affirmative',
        difficulty: 2,
        prompt: 'Completa: "They ___ from Spain."',
        promptTranslation: 'Ellos son de España.',
        correctAnswer: 'are',
        options: ['is', 'are', 'am'],
        explanation: 'Con "they" (plural) usamos "are". → They are from Spain.',
      },
      {
        id: 'a1-wb-p1-ex5',
        type: 'reorder',
        concept: 'verb to be affirmative - word order',
        difficulty: 2,
        prompt: 'Ordena las palabras para formar una frase: We / are / friends / good',
        promptTranslation: 'Somos buenos amigos.',
        correctAnswer: 'We are good friends.',
        words: ['We', 'are', 'good', 'friends'],
        explanation: 'Orden correcto: sujeto + verbo + adjetivo + sustantivo: We are good friends. = Somos buenos amigos.',
      },
      {
        id: 'a1-wb-p1-ex6',
        type: 'true_false',
        concept: 'greetings vocabulary',
        difficulty: 1,
        prompt: '"Goodbye" means "Hola".',
        correctAnswer: 'false',
        explanation: '"Goodbye" significa "Adiós", no "Hola". "Hola" es "Hello".',
      },
    ],
  },
  {
    id: 'a1-wb-2',
    levelId: 'a1',
    unit: 'Unit 1 · Greetings and to be',
    page: 2,
    title: 'to be: negativo y preguntas',
    intro: 'Practicamos el verbo "to be" en negativo y en preguntas, con sus respuestas cortas.',
    exercises: [
      {
        id: 'a1-wb-p2-ex1',
        type: 'fill_blank',
        concept: 'verb to be negative',
        difficulty: 2,
        prompt: 'Completa: "I ___ from Mexico." (negativo)',
        promptTranslation: 'No soy de México.',
        correctAnswer: 'am not',
        acceptedAnswers: ["am not", "'m not"],
        explanation: 'La negativa de "to be" se forma con "not" después del verbo: I am not from Mexico. = No soy de México.',
      },
      {
        id: 'a1-wb-p2-ex2',
        type: 'multiple_choice',
        concept: 'verb to be questions',
        difficulty: 2,
        prompt: 'Completa: "___ you a student?"',
        promptTranslation: '¿Eres estudiante?',
        correctAnswer: 'Are',
        options: ['Is', 'Are', 'Am'],
        explanation: 'En las preguntas con "you" usamos "are" al principio: Are you a student? = ¿Eres estudiante?',
      },
      {
        id: 'a1-wb-p2-ex3',
        type: 'multiple_choice',
        concept: 'verb to be short answers',
        difficulty: 2,
        prompt: 'Responde a la pregunta "Are you tired?" de forma afirmativa:',
        promptTranslation: '¿Estás cansado? — Sí:',
        correctAnswer: 'Yes, I am.',
        options: ['Yes, I am.', 'Yes, I are.', 'Yes, you are.'],
        explanation: 'La respuesta corta afirmativa para "Are you...?" es "Yes, I am."',
      },
      {
        id: 'a1-wb-p2-ex4',
        type: 'reorder',
        concept: 'verb to be questions - word order',
        difficulty: 3,
        prompt: 'Ordena las palabras para formar una pregunta: Where / you / from / are',
        promptTranslation: '¿De dónde eres?',
        correctAnswer: 'Where are you from?',
        words: ['Where', 'are', 'you', 'from'],
        explanation: 'En las preguntas, "are" va antes del sujeto: Where are you from? = ¿De dónde eres?',
      },
      {
        id: 'a1-wb-p2-ex5',
        type: 'translate',
        concept: 'verb to be negative',
        difficulty: 3,
        prompt: 'Traduce: "No somos estudiantes."',
        correctAnswer: 'We are not students.',
        acceptedAnswers: ['We are not students', "We aren't students", "We're not students", "We aren't students."],
        acceptApproximate: true,
        explanation: '"No somos" = we are not (o we aren\'t / we\'re not). → We are not students.',
      },
      {
        id: 'a1-wb-p2-ex6',
        type: 'error_correction',
        concept: 'verb to be negative',
        difficulty: 3,
        prompt: 'Corrige el error: "He no is happy."',
        correctAnswer: 'He is not happy.',
        acceptedAnswers: ['He is not happy', "He isn't happy"],
        acceptApproximate: true,
        explanation: 'La negativa se forma con "not" después del verbo: He is not happy. No decimos "He no is".',
      },
    ],
  },
  {
    id: 'a1-wb-3',
    levelId: 'a1',
    unit: 'Unit 2 · Articles and plurals',
    page: 3,
    title: 'a/an/the, plurales y this/that',
    intro: 'Practicamos los artículos a/an/the, la formación del plural y los demostrativos this/that.',
    exercises: [
      {
        id: 'a1-wb-p3-ex1',
        type: 'multiple_choice',
        concept: 'articles a/an',
        difficulty: 1,
        prompt: 'Completa: "___ apple" (una manzana)',
        correctAnswer: 'an',
        options: ['a', 'an', 'the'],
        explanation: 'Usamos "an" antes de vocal (a, e, i, o, u): an apple. "A" va antes de consonante: a book.',
      },
      {
        id: 'a1-wb-p3-ex2',
        type: 'fill_blank',
        concept: 'plural nouns',
        difficulty: 1,
        prompt: 'Completa con el plural: "one book, two ___"',
        correctAnswer: 'books',
        acceptedAnswers: ['books'],
        explanation: 'El plural regular se forma añadiendo -s: book → books.',
      },
      {
        id: 'a1-wb-p3-ex3',
        type: 'multiple_choice',
        concept: 'demonstratives this/that',
        difficulty: 2,
        prompt: 'Completa: "___ is my phone here in my hand."',
        correctAnswer: 'This',
        options: ['This', 'That', 'These'],
        explanation: 'Usamos "this" para algo cerca de nosotros. → This is my phone. = Este es mi teléfono.',
      },
      {
        id: 'a1-wb-p3-ex4',
        type: 'select_correct',
        concept: 'article choice a/the',
        difficulty: 3,
        prompt: 'Elige la oración correcta para decir "Tengo un coche":',
        correctAnswer: 'I have a car.',
        options: ['I have the car.', 'I have a car.', 'I have car.'],
        explanation: 'Para hablar de algo en general o por primera vez usamos "a/an": I have a car. La opción con "the" sería para un coche concreto ya conocido, y nunca se omite el artículo.',
      },
      {
        id: 'a1-wb-p3-ex5',
        type: 'match',
        concept: 'plural noun spelling',
        difficulty: 2,
        prompt: 'Relaciona cada sustantivo en singular con su plural.',
        pairs: [
          { left: 'cat', right: 'cats' },
          { left: 'bus', right: 'buses' },
          { left: 'box', right: 'boxes' },
          { left: 'baby', right: 'babies' },
          { left: 'day', right: 'days' },
        ],
        correctAnswer: 'match',
        explanation: 'Reglas del plural: -s (cats), -es tras -s/-x/-ch/-sh (buses, boxes), consonante + y → -ies (babies), pero vocal + y solo -s (days).',
      },
      {
        id: 'a1-wb-p3-ex6',
        type: 'true_false',
        concept: 'demonstratives this/that',
        difficulty: 2,
        prompt: '"This" is for things far from you, and "that" is for things near you.',
        correctAnswer: 'false',
        explanation: 'Es al revés: "this" es para cosas cerca de nosotros y "that" para cosas lejos.',
      },
    ],
  },
  {
    id: 'a1-wb-4',
    levelId: 'a1',
    unit: 'Unit 3 · Possessives and descriptions',
    page: 4,
    title: 'Posesivos, genitivo sajón y descripciones',
    intro: 'Practicamos los posesivos (my, your, his...), el genitivo sajón (\'s) y cómo describir personas con "to be" y adjetivos.',
    exercises: [
      {
        id: 'a1-wb-p4-ex1',
        type: 'match',
        concept: 'possessive adjectives',
        difficulty: 2,
        prompt: 'Relaciona cada pronombre con su adjetivo posesivo.',
        pairs: [
          { left: 'I', right: 'my' },
          { left: 'you', right: 'your' },
          { left: 'he', right: 'his' },
          { left: 'she', right: 'her' },
          { left: 'we', right: 'our' },
        ],
        correctAnswer: 'match',
        explanation: 'Posesivos: I → my, you → your, he → his, she → her, we → our. No cambian con el plural: my books, her friends.',
      },
      {
        id: 'a1-wb-p4-ex2',
        type: 'fill_blank',
        concept: 'possessive s',
        difficulty: 2,
        prompt: 'Completa: "This is ___ book." (el libro de María)',
        correctAnswer: "Maria's",
        acceptedAnswers: ["Maria's", "María's", 'Maria', 'María'],
        explanation: 'El genitivo sajón se forma con nombre + \'s: María\'s book = el libro de María.',
      },
      {
        id: 'a1-wb-p4-ex3',
        type: 'multiple_choice',
        concept: 'possessive adjectives with family',
        difficulty: 2,
        prompt: 'Completa: "Ana is my mother and Juan is ___ father."',
        correctAnswer: 'my',
        options: ['my', 'your', 'her'],
        explanation: 'Ana es mi madre, así que Juan es mi padre: my father. Los posesivos no cambian con el género: my father, my mother.',
      },
      {
        id: 'a1-wb-p4-ex4',
        type: 'error_correction',
        concept: 'possessive s vs of',
        difficulty: 3,
        prompt: 'Corrige el error: "The book of my sister is on the table." (usa el genitivo sajón)',
        correctAnswer: "My sister's book is on the table.",
        acceptedAnswers: ["My sister's book is on the table"],
        acceptApproximate: true,
        explanation: 'Con personas usamos el genitivo sajón en lugar de "of": My sister\'s book = el libro de mi hermana.',
      },
      {
        id: 'a1-wb-p4-ex5',
        type: 'reorder',
        concept: 'descriptions with to be',
        difficulty: 2,
        prompt: 'Ordena las palabras para formar una frase: He / tall / and / is / strong',
        promptTranslation: 'Él es alto y fuerte.',
        correctAnswer: 'He is tall and strong.',
        words: ['He', 'is', 'tall', 'and', 'strong'],
        explanation: 'Descripción con "to be" + adjetivos: He is tall and strong. = Él es alto y fuerte.',
      },
      {
        id: 'a1-wb-p4-ex6',
        type: 'writing',
        concept: 'writing a description',
        difficulty: 3,
        prompt: 'Escribe de 4 a 6 frases en inglés describiendo a un miembro de tu familia: su nombre, cómo es (adjetivos) y su profesión. Usa "to be", adjetivos y posesivos (my, his, her).',
        correctAnswer: '',
        explanation: 'Una buena descripción usa "He/She is..." con adjetivos (tall, nice, happy...), la profesión (a teacher, a doctor) y posesivos (my mother, his name).',
        minWords: 20,
        maxWords: 50,
      },
    ],
  },
  {
    id: 'a1-wb-5',
    levelId: 'a1',
    unit: 'Unit 4 · Present Simple',
    page: 5,
    title: 'Present Simple: afirmativo y negativo',
    intro: 'Practicamos el Present Simple para hablar de rutinas y hábitos, en afirmativo y negativo.',
    exercises: [
      {
        id: 'a1-wb-p5-ex1',
        type: 'multiple_choice',
        concept: 'present simple 3rd person',
        difficulty: 1,
        prompt: 'Completa: "She ___ in a bank."',
        promptTranslation: 'Ella trabaja en un banco.',
        correctAnswer: 'works',
        options: ['work', 'works', 'working'],
        explanation: 'Con "she" (3ª persona) añadimos -s: work → works.',
      },
      {
        id: 'a1-wb-p5-ex2',
        type: 'fill_blank',
        concept: 'present simple negative',
        difficulty: 2,
        prompt: 'Completa: "I ___ like coffee." (no me gusta)',
        promptTranslation: 'No me gusta el café.',
        correctAnswer: 'do not',
        acceptedAnswers: ['do not', "don't"],
        explanation: 'El negativo se forma con do not / don\'t + verbo: I don\'t like coffee.',
      },
      {
        id: 'a1-wb-p5-ex3',
        type: 'fill_blank',
        concept: 'present simple negative 3rd person',
        difficulty: 2,
        prompt: 'Completa: "He ___ like tea." (no le gusta)',
        promptTranslation: 'A él no le gusta el té.',
        correctAnswer: 'does not',
        acceptedAnswers: ['does not', "doesn't"],
        explanation: 'Con he/she/it usamos does not / doesn\'t: He doesn\'t like tea.',
      },
      {
        id: 'a1-wb-p5-ex4',
        type: 'match',
        concept: 'present simple base vs -s',
        difficulty: 2,
        prompt: 'Relaciona cada sujeto con la forma correcta del verbo.',
        pairs: [
          { left: 'I', right: 'play' },
          { left: 'She', right: 'plays' },
          { left: 'They', right: 'play' },
          { left: 'He', right: 'watches' },
          { left: 'We', right: 'study' },
        ],
        correctAnswer: 'match',
        explanation: 'I/You/We/They usan el verbo sin -s; He/She/It añaden -s, -es o -ies según la terminación.',
      },
      {
        id: 'a1-wb-p5-ex5',
        type: 'error_correction',
        concept: 'present simple 3rd person',
        difficulty: 2,
        prompt: 'Corrige el error: "She work in Madrid."',
        correctAnswer: 'She works in Madrid.',
        acceptedAnswers: ['She works in Madrid'],
        acceptApproximate: true,
        explanation: 'Con "she" añadimos -s al verbo: work → works.',
      },
      {
        id: 'a1-wb-p5-ex6',
        type: 'reorder',
        concept: 'present simple word order',
        difficulty: 3,
        prompt: 'Ordena las palabras para formar una frase: I / coffee / every / drink / morning',
        promptTranslation: 'Bebo café todas las mañanas.',
        correctAnswer: 'I drink coffee every morning.',
        words: ['I', 'drink', 'coffee', 'every', 'morning'],
        explanation: 'Orden: sujeto + verbo + objeto + tiempo: I drink coffee every morning. = Bebo café todas las mañanas.',
      },
    ],
  },
  {
    id: 'a1-wb-6',
    levelId: 'a1',
    unit: 'Unit 4 · Present Simple',
    page: 6,
    title: 'Present Simple: preguntas y adverbios de frecuencia',
    intro: 'Practicamos las preguntas con do/does y los adverbios de frecuencia (always, usually, never...).',
    exercises: [
      {
        id: 'a1-wb-p6-ex1',
        type: 'reorder',
        concept: 'present simple questions do',
        difficulty: 2,
        prompt: 'Ordena las palabras para formar una pregunta: you / like / Do / pizza',
        promptTranslation: '¿Te gusta la pizza?',
        correctAnswer: 'Do you like pizza?',
        words: ['Do', 'you', 'like', 'pizza'],
        explanation: 'En las preguntas, "do" va al principio: Do you like pizza? = ¿Te gusta la pizza?',
      },
      {
        id: 'a1-wb-p6-ex2',
        type: 'fill_blank',
        concept: 'present simple questions does',
        difficulty: 2,
        prompt: 'Completa: "___ she work on Saturdays?"',
        promptTranslation: '¿Trabaja ella los sábados?',
        correctAnswer: 'Does',
        acceptedAnswers: ['does'],
        explanation: 'Con he/she/it usamos "does" en las preguntas: Does she work on Saturdays?',
      },
      {
        id: 'a1-wb-p6-ex3',
        type: 'multiple_choice',
        concept: 'adverbs of frequency',
        difficulty: 2,
        prompt: 'Completa: "I ___ get up early." (siempre)',
        promptTranslation: 'Siempre me levanto temprano.',
        correctAnswer: 'always',
        options: ['always', 'never', 'sometimes'],
        explanation: '"Always" = siempre. Los adverbios de frecuencia van antes del verbo principal: I always get up early.',
      },
      {
        id: 'a1-wb-p6-ex4',
        type: 'true_false',
        concept: 'adverbs of frequency vocabulary',
        difficulty: 1,
        prompt: '"Sometimes" means "nunca".',
        correctAnswer: 'false',
        explanation: '"Sometimes" significa "a veces", no "nunca". "Nunca" es "never".',
      },
      {
        id: 'a1-wb-p6-ex5',
        type: 'select_correct',
        concept: 'adverbs of frequency with to be',
        difficulty: 3,
        prompt: 'Elige la oración correcta:',
        correctAnswer: 'I am always happy.',
        options: ['I am always happy.', 'I always am happy.', 'Always I am happy.'],
        explanation: 'Con el verbo "to be", el adverbio va después del verbo: I am always happy. = Siempre estoy feliz.',
      },
      {
        id: 'a1-wb-p6-ex6',
        type: 'fill_blank',
        concept: 'adverbs of frequency vocabulary',
        difficulty: 2,
        prompt: 'Completa: "I ___ eat meat. I don\'t like it." (nunca)',
        promptTranslation: 'Nunca como carne.',
        correctAnswer: 'never',
        acceptedAnswers: ['never'],
        explanation: '"Never" = nunca. → I never eat meat. = Nunca como carne.',
      },
    ],
  },
  {
    id: 'a1-wb-7',
    levelId: 'a1',
    unit: 'Unit 5 · There is/are and prepositions',
    page: 7,
    title: 'Mi casa: There is/are y preposiciones',
    intro: 'Practicamos "there is / there are" (hay) y las preposiciones de lugar (in, on, under, next to...) para hablar de la casa.',
    exercises: [
      {
        id: 'a1-wb-p7-ex1',
        type: 'fill_blank',
        concept: 'there is/are singular',
        difficulty: 1,
        prompt: 'Completa: "There ___ a sofa in the living room."',
        promptTranslation: 'Hay un sofá en la sala de estar.',
        correctAnswer: 'is',
        acceptedAnswers: ['is'],
        explanation: '"A sofa" es singular → there is. → There is a sofa in the living room.',
      },
      {
        id: 'a1-wb-p7-ex2',
        type: 'multiple_choice',
        concept: 'there is/are plural',
        difficulty: 1,
        prompt: 'Completa: "There ___ three chairs in the kitchen."',
        promptTranslation: 'Hay tres sillas en la cocina.',
        correctAnswer: 'are',
        options: ['is', 'are', 'am'],
        explanation: '"Three chairs" es plural → there are.',
      },
      {
        id: 'a1-wb-p7-ex3',
        type: 'match',
        concept: 'prepositions of place',
        difficulty: 1,
        prompt: 'Relaciona cada preposición con su significado en español.',
        pairs: [
          { left: 'in', right: 'en (dentro de)' },
          { left: 'on', right: 'sobre' },
          { left: 'under', right: 'debajo de' },
          { left: 'next to', right: 'al lado de' },
          { left: 'behind', right: 'detrás de' },
        ],
        correctAnswer: 'match',
        explanation: 'in = en/dentro, on = sobre, under = debajo, next to = al lado, behind = detrás.',
      },
      {
        id: 'a1-wb-p7-ex4',
        type: 'reading',
        concept: 'reading: my house',
        difficulty: 3,
        prompt: 'Lee el texto sobre la casa de Sara y responde las preguntas.',
        correctAnswer: 'reading',
        explanation: 'Usa "there is" para singular y "there are" para plural; las preposiciones te dicen dónde está cada cosa.',
        reading: {
          text: `My house
This is my house. There is a big kitchen and a small bathroom. There are two bedrooms upstairs. The cat is under the table in the kitchen. There is a garden behind the house, and there are three trees next to the garden.`,
          translation: `Mi casa
Esta es mi casa. Hay una cocina grande y un baño pequeño. Hay dos dormitorios arriba. El gato está debajo de la mesa, en la cocina. Hay un jardín detrás de la casa y hay tres árboles al lado del jardín.`,
          questions: [
            {
              id: 'a1-wb-p7-ex4-q1',
              type: 'multiple_choice',
              concept: 'reading comprehension — bedrooms',
              difficulty: 2,
              prompt: 'How many bedrooms are there?',
              promptTranslation: '¿Cuántos dormitorios hay?',
              correctAnswer: 'Two.',
              options: ['One.', 'Two.', 'Three.'],
              explanation: 'El texto dice: "There are two bedrooms upstairs." → Two.',
            },
            {
              id: 'a1-wb-p7-ex4-q2',
              type: 'multiple_choice',
              concept: 'reading comprehension — where',
              difficulty: 2,
              prompt: 'Where is the cat?',
              promptTranslation: '¿Dónde está el gato?',
              correctAnswer: 'Under the table.',
              options: ['On the table.', 'Under the table.', 'In the garden.'],
              explanation: 'El texto dice: "The cat is under the table in the kitchen." → Under the table.',
            },
            {
              id: 'a1-wb-p7-ex4-q3',
              type: 'multiple_choice',
              concept: 'reading comprehension — where',
              difficulty: 2,
              prompt: 'Where is the garden?',
              promptTranslation: '¿Dónde está el jardín?',
              correctAnswer: 'Behind the house.',
              options: ['Behind the house.', 'Next to the house.', 'In the kitchen.'],
              explanation: 'El texto dice: "There is a garden behind the house." → Behind the house.',
            },
            {
              id: 'a1-wb-p7-ex4-q4',
              type: 'multiple_choice',
              concept: 'reading comprehension — there are',
              difficulty: 2,
              prompt: 'Are there trees next to the garden?',
              promptTranslation: '¿Hay árboles al lado del jardín?',
              correctAnswer: 'Yes, there are.',
              options: ['Yes, there are.', 'No, there are not.', 'Yes, there is.'],
              explanation: 'El texto dice: "there are three trees next to the garden." → Yes, there are.',
            },
          ],
        },
      },
      {
        id: 'a1-wb-p7-ex5',
        type: 'true_false',
        concept: 'there is/are plural',
        difficulty: 1,
        prompt: '"There are two bedrooms." means there is only one bedroom.',
        correctAnswer: 'false',
        explanation: '"Two bedrooms" = dos dormitorios, así que la frase es falsa.',
      },
      {
        id: 'a1-wb-p7-ex6',
        type: 'reorder',
        concept: 'there is/are word order',
        difficulty: 3,
        prompt: 'Ordena las palabras: There / is / a / lamp / next / to / the / bed',
        promptTranslation: 'Hay una lámpara al lado de la cama.',
        correctAnswer: 'There is a lamp next to the bed.',
        words: ['There', 'is', 'a', 'lamp', 'next', 'to', 'the', 'bed'],
        explanation: 'There is + a lamp + next to the bed. = Hay una lámpara al lado de la cama.',
      },
    ],
  },
  {
    id: 'a1-wb-8',
    levelId: 'a1',
    unit: 'Unit 6 · Food and likes',
    page: 8,
    title: 'Comida: gustos, some y any',
    intro: 'Practicamos cómo hablar de gustos con like/love/hate + -ing y cuándo usar some y any con la comida.',
    exercises: [
      {
        id: 'a1-wb-p8-ex1',
        type: 'multiple_choice',
        concept: 'like + -ing',
        difficulty: 2,
        prompt: 'Completa: "I like ___ pizza."',
        promptTranslation: 'Me gusta comer pizza.',
        correctAnswer: 'eating',
        options: ['eat', 'eating', 'eats'],
        explanation: 'Después de like/love/hate usamos el verbo con -ing: I like eating pizza. = Me gusta comer pizza.',
      },
      {
        id: 'a1-wb-p8-ex2',
        type: 'fill_blank',
        concept: 'love + -ing 3rd person',
        difficulty: 2,
        prompt: 'Completa: "She ___ cooking." (le encanta)',
        promptTranslation: 'A ella le encanta cocinar.',
        correctAnswer: 'loves',
        acceptedAnswers: ['loves'],
        explanation: 'Con "she" añadimos -s: love → loves. → She loves cooking. = A ella le encanta cocinar.',
      },
      {
        id: 'a1-wb-p8-ex3',
        type: 'multiple_choice',
        concept: 'some/any affirmative',
        difficulty: 2,
        prompt: 'Completa: "I have ___ apples in the fridge." (afirmativo)',
        promptTranslation: 'Tengo algunas manzanas en la nevera.',
        correctAnswer: 'some',
        options: ['some', 'any', 'a'],
        explanation: 'En frases afirmativas usamos "some": I have some apples. = Tengo algunas manzanas.',
      },
      {
        id: 'a1-wb-p8-ex4',
        type: 'fill_blank',
        concept: 'some/any negative',
        difficulty: 2,
        prompt: 'Completa: "I don\'t have ___ milk." (negativo)',
        promptTranslation: 'No tengo leche.',
        correctAnswer: 'any',
        acceptedAnswers: ['any'],
        explanation: 'En negativas usamos "any": I don\'t have any milk. = No tengo leche.',
      },
      {
        id: 'a1-wb-p8-ex5',
        type: 'reorder',
        concept: 'some/any word order',
        difficulty: 3,
        prompt: 'Ordena las palabras: We / don\'t / have / any / bread',
        promptTranslation: 'No tenemos pan.',
        correctAnswer: "We don't have any bread.",
        words: ['We', "don't", 'have', 'any', 'bread'],
        explanation: 'Negativo: We don\'t have any bread. En negativas usamos "any".',
      },
      {
        id: 'a1-wb-p8-ex6',
        type: 'true_false',
        concept: 'hate vs love',
        difficulty: 1,
        prompt: '"I hate cooking." means I love cooking.',
        correctAnswer: 'false',
        explanation: '"Hate" significa odiar, lo contrario de "love" (amar): odio cocinar, no me encanta.',
      },
    ],
  },
  {
    id: 'a1-wb-9',
    levelId: 'a1',
    unit: 'Unit 7 · Can and imperatives',
    page: 9,
    title: 'Can/can\'t e imperativos',
    intro: 'Practicamos can/can\'t (poder/saber) para hablar de habilidades y permisos, y las órdenes con el imperativo y Let\'s.',
    exercises: [
      {
        id: 'a1-wb-p9-ex1',
        type: 'multiple_choice',
        concept: 'can ability',
        difficulty: 1,
        prompt: 'Completa: "I ___ swim very well." (sé nadar)',
        correctAnswer: 'can',
        options: ['can', 'cans', 'can to'],
        explanation: '"Can" es un verbo modal: no cambia y va seguido del verbo sin "to": I can swim. = Sé nadar.',
      },
      {
        id: 'a1-wb-p9-ex2',
        type: 'fill_blank',
        concept: "can't negative",
        difficulty: 1,
        prompt: 'Completa: "She ___ play the guitar." (no sabe tocar)',
        promptTranslation: 'Ella no sabe tocar la guitarra.',
        correctAnswer: "can't",
        acceptedAnswers: ["can't", 'cannot'],
        explanation: 'La negativa de "can" es cannot / can\'t: She can\'t play the guitar.',
      },
      {
        id: 'a1-wb-p9-ex3',
        type: 'reorder',
        concept: 'can questions',
        difficulty: 2,
        prompt: 'Ordena las palabras para formar una pregunta: you / Can / help / me',
        promptTranslation: '¿Puedes ayudarme?',
        correctAnswer: 'Can you help me?',
        words: ['Can', 'you', 'help', 'me'],
        explanation: 'En las preguntas, "can" va al principio: Can you help me? = ¿Puedes ayudarme?',
      },
      {
        id: 'a1-wb-p9-ex4',
        type: 'error_correction',
        concept: 'can + base form',
        difficulty: 2,
        prompt: 'Corrige el error: "I can to dance."',
        correctAnswer: 'I can dance.',
        acceptedAnswers: ['I can dance'],
        acceptApproximate: true,
        explanation: 'Después de "can" NO se usa "to": I can dance. = Sé bailar.',
      },
      {
        id: 'a1-wb-p9-ex5',
        type: 'multiple_choice',
        concept: 'imperative',
        difficulty: 1,
        prompt: 'Completa con la orden: "___ the door, please."',
        correctAnswer: 'Open',
        options: ['Open', 'Opens', 'Opening'],
        explanation: 'El imperativo usa el verbo en forma base: Open the door. = Abre la puerta.',
      },
      {
        id: 'a1-wb-p9-ex6',
        type: 'true_false',
        concept: "let's",
        difficulty: 1,
        prompt: '"Let\'s go!" means "¡Vámonos!".',
        correctAnswer: 'true',
        explanation: '"Let\'s" es la contracción de "let us" y sirve para proponer algo juntos: Let\'s go! = ¡Vámonos!',
      },
    ],
  },
  {
    id: 'a1-wb-10',
    levelId: 'a1',
    unit: 'Unit 8 · Present Continuous',
    page: 10,
    title: 'Present Continuous: acciones ahora',
    intro: 'Practicamos el Present Continuous (be + verbo-ing) para hablar de lo que está pasando ahora.',
    exercises: [
      {
        id: 'a1-wb-p10-ex1',
        type: 'multiple_choice',
        concept: 'present continuous am/is/are',
        difficulty: 1,
        prompt: 'Completa: "I ___ watching TV."',
        promptTranslation: 'Estoy viendo la tele.',
        correctAnswer: 'am',
        options: ['am', 'is', 'are'],
        explanation: 'Con "I" usamos "am" + verbo-ing: I am watching TV. = Estoy viendo la tele.',
      },
      {
        id: 'a1-wb-p10-ex2',
        type: 'fill_blank',
        concept: 'present continuous 3rd person',
        difficulty: 1,
        prompt: 'Completa: "She ___ reading a book." (está leyendo)',
        promptTranslation: 'Ella está leyendo un libro.',
        correctAnswer: 'is',
        acceptedAnswers: ['is'],
        explanation: 'Con "she" usamos "is" + verbo-ing: She is reading a book. = Ella está leyendo un libro.',
      },
      {
        id: 'a1-wb-p10-ex3',
        type: 'fill_blank',
        concept: 'present continuous spelling -ing',
        difficulty: 2,
        prompt: 'Completa con la forma en -ing: "They are ___ in the park." (run)',
        promptTranslation: 'Ellos están corriendo en el parque.',
        correctAnswer: 'running',
        acceptedAnswers: ['running'],
        explanation: 'Cuando el verbo termina en consonante + vocal + consonante, doblamos la consonante: run → running.',
      },
      {
        id: 'a1-wb-p10-ex4',
        type: 'match',
        concept: 'present continuous subject + be',
        difficulty: 2,
        prompt: 'Relaciona cada sujeto con la forma correcta del verbo "to be" en Present Continuous.',
        pairs: [
          { left: 'I', right: 'am eating' },
          { left: 'He', right: 'is eating' },
          { left: 'They', right: 'are eating' },
          { left: 'We', right: 'are eating' },
          { left: 'It', right: 'is raining' },
        ],
        correctAnswer: 'match',
        explanation: 'I → am, He/She/It → is, You/We/They → are, siempre + verbo-ing.',
      },
      {
        id: 'a1-wb-p10-ex5',
        type: 'error_correction',
        concept: 'present continuous subject + be',
        difficulty: 2,
        prompt: 'Corrige el error: "He are playing football."',
        correctAnswer: 'He is playing football.',
        acceptedAnswers: ['He is playing football'],
        acceptApproximate: true,
        explanation: 'Con "he" usamos "is", no "are": He is playing football. = Él está jugando al fútbol.',
      },
      {
        id: 'a1-wb-p10-ex6',
        type: 'reorder',
        concept: 'present continuous word order',
        difficulty: 3,
        prompt: 'Ordena las palabras: We / are / studying / English / now',
        promptTranslation: 'Estamos estudiando inglés ahora.',
        correctAnswer: 'We are studying English now.',
        words: ['We', 'are', 'studying', 'English', 'now'],
        explanation: 'Sujeto + be + verbo-ing + complemento + now: We are studying English now. = Estamos estudiando inglés ahora.',
      },
    ],
  },
  {
    id: 'a1-wb-11',
    levelId: 'a1',
    unit: 'Unit 9 · Past Simple',
    page: 11,
    title: 'Past Simple: was/were y verbos regulares',
    intro: 'Practicamos el pasado del verbo "to be" (was/were) y el pasado simple de los verbos regulares (-ed).',
    exercises: [
      {
        id: 'a1-wb-p11-ex1',
        type: 'multiple_choice',
        concept: 'was/were past of to be',
        difficulty: 1,
        prompt: 'Completa: "I ___ at home yesterday."',
        promptTranslation: 'Estuve en casa ayer.',
        correctAnswer: 'was',
        options: ['was', 'were', 'am'],
        explanation: 'Con "I" usamos "was": I was at home yesterday. = Estuve/estaba en casa ayer.',
      },
      {
        id: 'a1-wb-p11-ex2',
        type: 'fill_blank',
        concept: 'was/were past of to be',
        difficulty: 1,
        prompt: 'Completa: "They ___ at the party last night."',
        promptTranslation: 'Ellos estuvieron en la fiesta anoche.',
        correctAnswer: 'were',
        acceptedAnswers: ['were'],
        explanation: 'Con "they" usamos "were": They were at the party. = Ellos estuvieron en la fiesta.',
      },
      {
        id: 'a1-wb-p11-ex3',
        type: 'multiple_choice',
        concept: 'past simple regular -ed',
        difficulty: 1,
        prompt: 'Completa: "Yesterday I ___ (work) from nine to five."',
        promptTranslation: 'Ayer trabajé de nueve a cinco.',
        correctAnswer: 'worked',
        options: ['work', 'worked', 'works'],
        explanation: 'El pasado regular se forma con -ed: work → worked. → Yesterday I worked from nine to five.',
      },
      {
        id: 'a1-wb-p11-ex4',
        type: 'fill_blank',
        concept: 'past simple irregular verb',
        difficulty: 2,
        prompt: 'Completa: "I ___ (go) to the beach last weekend."',
        promptTranslation: 'Fui a la playa el fin de semana pasado.',
        correctAnswer: 'went',
        acceptedAnswers: ['went'],
        explanation: '"Go" es irregular: go → went. → I went to the beach last weekend.',
      },
      {
        id: 'a1-wb-p11-ex5',
        type: 'match',
        concept: 'past simple irregular verbs',
        difficulty: 2,
        prompt: 'Relaciona cada verbo en presente con su forma en pasado.',
        pairs: [
          { left: 'go', right: 'went' },
          { left: 'eat', right: 'ate' },
          { left: 'see', right: 'saw' },
          { left: 'have', right: 'had' },
          { left: 'buy', right: 'bought' },
        ],
        correctAnswer: 'match',
        explanation: 'Verbos irregulares muy comunes: go → went, eat → ate, see → saw, have → had, buy → bought.',
      },
      {
        id: 'a1-wb-p11-ex6',
        type: 'true_false',
        concept: 'was/were past of to be',
        difficulty: 2,
        prompt: '"Was" is the past of "are".',
        correctAnswer: 'false',
        explanation: 'El pasado de "are" es "were". "Was" es el pasado de "am" e "is".',
      },
    ],
  },
  {
    id: 'a1-wb-12',
    levelId: 'a1',
    unit: 'Unit 9 · Past Simple',
    page: 12,
    title: 'Past Simple: negativo y preguntas',
    intro: 'Practicamos el pasado simple en negativo (didn\'t) y en preguntas (Did...?).',
    exercises: [
      {
        id: 'a1-wb-p12-ex1',
        type: 'select_correct',
        concept: 'past simple negative',
        difficulty: 3,
        prompt: 'Elige la oración correcta para decir "No fui a trabajar":',
        correctAnswer: "I didn't go to work.",
        options: ["I didn't went to work.", "I didn't go to work.", "I didn't gone to work."],
        explanation: 'Después de "didn\'t" usamos el verbo en forma base: I didn\'t go to work. = No fui a trabajar.',
      },
      {
        id: 'a1-wb-p12-ex2',
        type: 'fill_blank',
        concept: 'past simple negative',
        difficulty: 2,
        prompt: 'Completa: "She ___ TV last night." (not watch)',
        promptTranslation: 'Ella no vio la tele anoche.',
        correctAnswer: "didn't watch",
        acceptedAnswers: ["didn't watch", 'did not watch'],
        explanation: 'Negativo en pasado: didn\'t + verbo en base: She didn\'t watch TV last night.',
      },
      {
        id: 'a1-wb-p12-ex3',
        type: 'reorder',
        concept: 'past simple questions did',
        difficulty: 3,
        prompt: 'Ordena las palabras para formar una pregunta: you / Did / pizza / eat / yesterday',
        promptTranslation: '¿Comiste pizza ayer?',
        correctAnswer: 'Did you eat pizza yesterday?',
        words: ['Did', 'you', 'eat', 'pizza', 'yesterday'],
        explanation: 'Pregunta en pasado: Did + sujeto + verbo base: Did you eat pizza yesterday?',
      },
      {
        id: 'a1-wb-p12-ex4',
        type: 'multiple_choice',
        concept: 'past simple questions did',
        difficulty: 2,
        prompt: 'Completa: "___ you watch the film? Yes, I did."',
        promptTranslation: '¿Viste la película? Sí.',
        correctAnswer: 'Did',
        options: ['Did', 'Do', 'Were'],
        explanation: 'Para preguntar por algo en pasado usamos "did": Did you watch the film?',
      },
      {
        id: 'a1-wb-p12-ex5',
        type: 'error_correction',
        concept: 'past simple negative',
        difficulty: 3,
        prompt: 'Corrige el error: "She didn\'t liked the movie."',
        correctAnswer: "She didn't like the movie.",
        acceptedAnswers: ["She didn't like the movie"],
        acceptApproximate: true,
        explanation: 'Después de "didn\'t" el verbo vuelve a la forma base: She didn\'t like the movie. = A ella no le gustó la película.',
      },
      {
        id: 'a1-wb-p12-ex6',
        type: 'true_false',
        concept: 'past simple questions did',
        difficulty: 2,
        prompt: '"Did you go?" and "Did you went?" are both correct.',
        correctAnswer: 'false',
        explanation: 'Solo es correcta la primera: Did you go? Tras "did" el verbo va en base, nunca en pasado.',
      },
    ],
  },
  {
    id: 'a1-wb-13',
    levelId: 'a1',
    unit: 'Unit 10 · Going to',
    page: 13,
    title: 'Futuro con going to',
    intro: 'Practicamos "be going to" para hablar de planes e intenciones futuras.',
    exercises: [
      {
        id: 'a1-wb-p13-ex1',
        type: 'multiple_choice',
        concept: 'going to + to be',
        difficulty: 1,
        prompt: 'Completa: "I ___ going to travel next week."',
        promptTranslation: 'Voy a viajar la semana que viene.',
        correctAnswer: 'am',
        options: ['am', 'is', 'are'],
        explanation: 'Con "I" usamos "am": I am going to travel next week. = Voy a viajar la semana que viene.',
      },
      {
        id: 'a1-wb-p13-ex2',
        type: 'fill_blank',
        concept: 'going to + base verb',
        difficulty: 2,
        prompt: 'Completa: "She is going to ___ English." (study)',
        promptTranslation: 'Ella va a estudiar inglés.',
        correctAnswer: 'study',
        acceptedAnswers: ['study'],
        explanation: 'Después de "going to" usamos el verbo en forma base: She is going to study English.',
      },
      {
        id: 'a1-wb-p13-ex3',
        type: 'reorder',
        concept: 'going to negative',
        difficulty: 3,
        prompt: 'Ordena las palabras: We / aren\'t / going / to / stay / at / home',
        promptTranslation: 'No vamos a quedarnos en casa.',
        correctAnswer: "We aren't going to stay at home.",
        words: ['We', "aren't", 'going', 'to', 'stay', 'at', 'home'],
        explanation: 'Negativo: We aren\'t going to stay at home. = No vamos a quedarnos en casa.',
      },
      {
        id: 'a1-wb-p13-ex4',
        type: 'error_correction',
        concept: 'going to + base verb',
        difficulty: 3,
        prompt: 'Corrige el error: "He is going to working tomorrow."',
        correctAnswer: 'He is going to work tomorrow.',
        acceptedAnswers: ['He is going to work tomorrow'],
        acceptApproximate: true,
        explanation: 'Después de "going to" va el verbo en forma base, no en -ing: He is going to work tomorrow.',
      },
      {
        id: 'a1-wb-p13-ex5',
        type: 'multiple_choice',
        concept: 'going to questions',
        difficulty: 2,
        prompt: 'Completa: "___ you going to come to the party?"',
        promptTranslation: '¿Vas a venir a la fiesta?',
        correctAnswer: 'Are',
        options: ['Are', 'Is', 'Am'],
        explanation: 'Con "you" usamos "are": Are you going to come to the party?',
      },
      {
        id: 'a1-wb-p13-ex6',
        type: 'true_false',
        concept: 'going to meaning',
        difficulty: 2,
        prompt: '"We\'re going to visit grandma" means the visit is in the past.',
        correctAnswer: 'false',
        explanation: '"Going to" expresa futuro (planes): significa que vamos a visitar a la abuela, no que ya ocurrió.',
      },
    ],
  },
  {
    id: 'a1-wb-14',
    levelId: 'a1',
    unit: 'Unit 11 · Review and reading',
    page: 14,
    title: 'Repaso final y lectura',
    intro: 'Repasamos todo el nivel A1 y leemos un texto que mezcla varias unidades.',
    exercises: [
      {
        id: 'a1-wb-p14-ex1',
        type: 'reading',
        concept: 'reading: review text',
        difficulty: 4,
        prompt: 'Lee el texto sobre Laura y responde las preguntas.',
        correctAnswer: 'reading',
        explanation: 'El texto mezcla: present simple (get up, likes), to be (am, is), there is/are, can, past simple (visited, ate, watched) y going to. Lee con atención los detalles.',
        reading: {
          text: `My name is Laura and I am from Argentina. I live in a small flat with my family. There are three rooms in the flat: a living room, a kitchen and a bedroom. In the living room there is a sofa and a TV.

Every morning I get up at seven and I have breakfast with my brother. He likes coffee, but I don't like it. I drink tea. I go to work by bus. I can speak English and Spanish, but I can't drive a car.

Last weekend I visited my grandparents. We ate lunch together and we watched a film. Next month I am going to start English classes because I want to travel to England.

I love my family very much!`,
          translation: `Mi nombre es Laura y soy de Argentina. Vivo en un piso pequeño con mi familia. Hay tres habitaciones en el piso: una sala de estar, una cocina y un dormitorio. En la sala de estar hay un sofá y una televisión.

Cada mañana me levanto a las siete y desayuno con mi hermano. A él le gusta el café, pero a mí no. Bebo té. Voy al trabajo en autobús. Puedo hablar inglés y español, pero no sé conducir un coche.

El fin de semana pasado visité a mis abuelos. Comimos juntos y vimos una película. El próximo mes voy a empezar clases de inglés porque quiero viajar a Inglaterra.

¡Quiero mucho a mi familia!`,
          questions: [
            {
              id: 'a1-wb-p14-ex1-q1',
              type: 'multiple_choice',
              concept: 'reading comprehension — to be',
              difficulty: 2,
              prompt: 'Where is Laura from?',
              promptTranslation: '¿De dónde es Laura?',
              correctAnswer: 'Argentina.',
              options: ['Argentina.', 'Spain.', 'England.'],
              explanation: 'El texto dice: "I am from Argentina." → Argentina.',
            },
            {
              id: 'a1-wb-p14-ex1-q2',
              type: 'multiple_choice',
              concept: 'reading comprehension — there are',
              difficulty: 2,
              prompt: 'How many rooms are there in the flat?',
              promptTranslation: '¿Cuántas habitaciones hay en el piso?',
              correctAnswer: 'Three.',
              options: ['Two.', 'Three.', 'Four.'],
              explanation: 'El texto dice: "There are three rooms in the flat." → Three.',
            },
            {
              id: 'a1-wb-p14-ex1-q3',
              type: 'multiple_choice',
              concept: 'reading comprehension — present simple',
              difficulty: 2,
              prompt: 'What does Laura drink in the morning?',
              promptTranslation: '¿Qué bebe Laura por la mañana?',
              correctAnswer: 'Tea.',
              options: ['Coffee.', 'Tea.', 'Milk.'],
              explanation: 'El texto dice: "I drink tea." → Tea.',
            },
            {
              id: 'a1-wb-p14-ex1-q4',
              type: 'multiple_choice',
              concept: 'reading comprehension — can/can\'t',
              difficulty: 2,
              prompt: 'Can Laura drive a car?',
              promptTranslation: '¿Sabe Laura conducir un coche?',
              correctAnswer: "No, she can't.",
              options: ['Yes, she can.', "No, she can't.", 'Yes, she is.'],
              explanation: 'El texto dice: "I can\'t drive a car." → No, she can\'t.',
            },
            {
              id: 'a1-wb-p14-ex1-q5',
              type: 'multiple_choice',
              concept: 'reading comprehension — past simple',
              difficulty: 2,
              prompt: 'What did Laura do last weekend?',
              promptTranslation: '¿Qué hizo Laura el fin de semana pasado?',
              correctAnswer: 'She visited her grandparents.',
              options: ['She visited her grandparents.', 'She went to England.', 'She started English classes.'],
              explanation: 'El texto dice: "Last weekend I visited my grandparents." → She visited her grandparents.',
            },
            {
              id: 'a1-wb-p14-ex1-q6',
              type: 'multiple_choice',
              concept: 'reading comprehension — going to',
              difficulty: 2,
              prompt: 'What is Laura going to do next month?',
              promptTranslation: '¿Qué va a hacer Laura el próximo mes?',
              correctAnswer: 'Start English classes.',
              options: ['Start English classes.', 'Travel to England.', 'Visit her grandparents.'],
              explanation: 'El texto dice: "Next month I am going to start English classes." → Start English classes.',
            },
          ],
        },
      },
      {
        id: 'a1-wb-p14-ex2',
        type: 'select_correct',
        concept: 'review: present simple negative',
        difficulty: 3,
        prompt: 'Elige la oración correcta:',
        correctAnswer: "He doesn't like tea.",
        options: ["He doesn't likes tea.", "He doesn't like tea.", "He don't like tea."],
        explanation: 'Negativo en 3ª persona: doesn\'t + verbo en base: He doesn\'t like tea. (Sin -s en el verbo.)',
      },
      {
        id: 'a1-wb-p14-ex3',
        type: 'fill_blank',
        concept: 'review: some/any in questions',
        difficulty: 2,
        prompt: 'Completa: "Is there ___ milk in the fridge?"',
        promptTranslation: '¿Hay leche en la nevera?',
        correctAnswer: 'any',
        acceptedAnswers: ['any'],
        explanation: 'En preguntas usamos "any": Is there any milk? = ¿Hay leche?',
      },
      {
        id: 'a1-wb-p14-ex4',
        type: 'match',
        concept: 'review: tenses',
        difficulty: 3,
        prompt: 'Relaciona cada frase con el tiempo verbal que usa.',
        pairs: [
          { left: 'I am a student.', right: 'present simple (to be)' },
          { left: 'She works in a bank.', right: 'present simple' },
          { left: 'They are playing now.', right: 'present continuous' },
          { left: 'We visited Paris.', right: 'past simple' },
          { left: 'I\'m going to cook tonight.', right: 'going to (future)' },
        ],
        correctAnswer: 'match',
        explanation: 'to be en presente: am/is/are; present simple: rutinas; present continuous: ahora; past simple: ayer/pasado; going to: planes futuros.',
      },
      {
        id: 'a1-wb-p14-ex5',
        type: 'writing',
        concept: 'writing: my week',
        difficulty: 3,
        prompt: 'Escribe un texto corto en inglés sobre tu semana: qué haces normalmente (present simple), qué hiciste el fin de semana pasado (past simple) y qué vas a hacer el próximo fin de semana (going to).',
        correctAnswer: '',
        explanation: 'Un buen texto usa los tres tiempos: present simple (I get up, I work), past simple (I visited, I watched) y going to (I\'m going to...). Usa conectores simples como and, but, because.',
        minWords: 30,
        maxWords: 50,
      },
    ],
  },
]