import type { WorkbookPage } from './types'

export const a2Workbook: WorkbookPage[] = [
  {
    id: 'a2-wb-1',
    levelId: 'a2',
    unit: 'Unit 1 · Comparativos y superlativos',
    page: 1,
    title: 'Comparativos y superlativos',
    intro:
      'Compará personas y cosas con -er / more (comparativos), the -est / the most (superlativos) y as...as (igualdad).',
    exercises: [
      {
        id: 'a2-wb-p1-ex1',
        type: 'multiple_choice',
        concept: 'comparativos -er',
        difficulty: 1,
        prompt: 'Completa con el comparativo correcto: "My brother is ___ than me." (tall)',
        correctAnswer: 'taller',
        options: ['taller', 'more tall', 'tallest'],
        explanation: '"Tall" es un adjetivo corto de una sílaba: tall + -er = taller. → My brother is taller than me.',
      },
      {
        id: 'a2-wb-p1-ex2',
        type: 'fill_blank',
        concept: 'comparativos con more',
        difficulty: 2,
        prompt: 'Completa con el comparativo: "This restaurant is ___ than the other one." (expensive)',
        correctAnswer: 'more expensive',
        acceptedAnswers: ['more expensive', 'More expensive'],
        explanation: '"Expensive" es un adjetivo largo (tres sílabas), así que usamos "more": more expensive.',
      },
      {
        id: 'a2-wb-p1-ex3',
        type: 'match',
        concept: 'formas comparativas y superlativas',
        difficulty: 2,
        prompt: 'Une cada adjetivo con su forma correcta (comparativo o superlativo).',
        correctAnswer: 'match',
        pairs: [
          { left: 'big', right: 'bigger' },
          { left: 'good', right: 'better' },
          { left: 'bad', right: 'worse' },
          { left: 'easy', right: 'easier' },
          { left: 'beautiful', right: 'the most beautiful' },
          { left: 'far', right: 'farther' },
        ],
        explanation:
          'big → bigger (corto, -er), good → better y bad → worse (irregulares), easy → easier (y → ier), beautiful → the most beautiful (largo), far → farther (irregular).',
      },
      {
        id: 'a2-wb-p1-ex4',
        type: 'fill_blank',
        concept: 'superlativos the -est',
        difficulty: 2,
        prompt: 'Completa con el superlativo: "Mount Everest is ___ mountain in the world." (high)',
        correctAnswer: 'the highest',
        acceptedAnswers: ['the highest', 'The highest', 'highest'],
        explanation: 'Los superlativos cortos usan "the" + adjetivo + -est: high → the highest. → Mount Everest is the highest mountain in the world.',
      },
      {
        id: 'a2-wb-p1-ex5',
        type: 'error_correction',
        concept: 'nunca doble comparativo',
        difficulty: 3,
        prompt: 'Corrige el error: "This hotel is more cheaper than that one."',
        correctAnswer: 'This hotel is cheaper than that one.',
        acceptedAnswers: [
          'This hotel is cheaper than that one',
          'This hotel is cheaper than that one.',
          'this hotel is cheaper than that one',
        ],
        acceptApproximate: true,
        explanation: '"Cheap" es corto: usamos -er (cheaper). Nunca combinamos "more" con "-er" (más barato = cheaper).',
      },
      {
        id: 'a2-wb-p1-ex6',
        type: 'translate',
        concept: 'as...as (igualdad)',
        difficulty: 3,
        prompt: 'Traduce: "Mi coche es tan rápido como el tuyo."',
        correctAnswer: 'My car is as fast as yours.',
        acceptedAnswers: ['My car is as fast as yours', 'My car is as fast as yours.', 'my car is as fast as yours'],
        acceptApproximate: true,
        explanation: 'Para igualdad usamos "as + adjetivo + as": tan rápido como = as fast as. "El tuyo" = yours.',
      },
    ],
  },
  {
    id: 'a2-wb-2',
    levelId: 'a2',
    unit: 'Unit 2 · Present Perfect',
    page: 2,
    title: 'Present Perfect: for/since, ever/never, just/already/yet',
    intro:
      'Practicá el Present Perfect: have/has + participio, con for/since, ever/never y just/already/yet.',
    exercises: [
      {
        id: 'a2-wb-p2-ex1',
        type: 'multiple_choice',
        concept: 'for vs since',
        difficulty: 2,
        prompt: 'Completa: "I have lived here ___ 2015."',
        correctAnswer: 'since',
        options: ['since', 'for', 'from'],
        explanation: '"Since" se usa con un punto de inicio en el tiempo (2015). "For" se usa con una duración (for three years).',
      },
      {
        id: 'a2-wb-p2-ex2',
        type: 'fill_blank',
        concept: 'ever / never',
        difficulty: 1,
        prompt: 'Completa la pregunta: "Have you ___ been to London?"',
        correctAnswer: 'ever',
        acceptedAnswers: ['ever', 'Ever'],
        explanation: '"Ever" (alguna vez) se usa en preguntas: Have you ever been to London?',
      },
      {
        id: 'a2-wb-p2-ex3',
        type: 'multiple_choice',
        concept: 'just / already / yet',
        difficulty: 2,
        prompt: 'Completa la negativa: "I haven\'t finished my homework ___."',
        correctAnswer: 'yet',
        options: ['yet', 'just', 'already'],
        explanation: '"Yet" (todavía) va al final de las negativas: I haven\'t finished my homework yet.',
      },
      {
        id: 'a2-wb-p2-ex4',
        type: 'reorder',
        concept: 'posición de just',
        difficulty: 3,
        prompt: 'Ordena las palabras para formar una frase: has / The train / just / arrived',
        correctAnswer: 'The train has just arrived.',
        words: ['The train', 'has', 'just', 'arrived'],
        explanation: 'Orden: sujeto + have/has + just + participio. → The train has just arrived.',
      },
      {
        id: 'a2-wb-p2-ex5',
        type: 'error_correction',
        concept: 'present perfect con yet',
        difficulty: 3,
        prompt: 'Corrige el error: "I didn\'t eat breakfast yet."',
        correctAnswer: 'I haven\'t eaten breakfast yet.',
        acceptedAnswers: [
          'I haven\'t eaten breakfast yet',
          'I haven\'t eaten breakfast yet.',
          'i haven\'t eaten breakfast yet',
        ],
        acceptApproximate: true,
        explanation: 'Con "yet" en negativa usamos el Present Perfect: haven\'t + participio (eaten). En A2 no usamos "didn\'t...yet".',
      },
      {
        id: 'a2-wb-p2-ex6',
        type: 'reading',
        concept: 'present perfect reading',
        difficulty: 4,
        prompt: 'Lee el texto sobre las vacaciones de Pedro y responde las preguntas.',
        correctAnswer: 'reading complete',
        reading: {
          text: 'Pedro has just come back from a trip to New York. He has visited the Statue of Liberty and he has walked through Central Park.\nHe has never been to the United States before, so everything was new for him. He has known his American friend Tom since 2018. Tom has lived in New York for ten years and he showed Pedro the city.\nPedro has already bought souvenirs for his family. He has not tried a hot dog yet, but he wants to try one before he goes home.',
          translation:
            'Pedro acaba de volver de un viaje a Nueva York. Ha visitado la Estatua de la Libertad y ha paseado por Central Park.\nNunca había estado antes en Estados Unidos, así que todo era nuevo para él. Conoce a su amigo estadounidense Tom desde 2018. Tom vive en Nueva York desde hace diez años y le enseñó la ciudad.\nPedro ya ha comprado recuerdos para su familia. Todavía no ha probado un perrito caliente, pero quiere probar uno antes de volver a casa.',
          questions: [
            {
              id: 'a2-wb-p2-ex6-q1',
              type: 'multiple_choice',
              concept: 'just reading',
              difficulty: 4,
              prompt: '¿Qué ha hecho Pedro recientemente?',
              correctAnswer: 'ha vuelto de un viaje a Nueva York',
              options: [
                'ha vuelto de un viaje a Nueva York',
                'ha comprado una casa en Nueva York',
                'ha empezado un curso de inglés',
              ],
              explanation: 'El texto dice: "Pedro has just come back from a trip to New York" (has just come back = acaba de volver).',
            },
            {
              id: 'a2-wb-p2-ex6-q2',
              type: 'multiple_choice',
              concept: 'never reading',
              difficulty: 4,
              prompt: '¿Había estado Pedro antes en Estados Unidos?',
              correctAnswer: 'No, nunca',
              options: ['No, nunca', 'Sí, varias veces', 'Sí, el año pasado'],
              explanation: 'El texto dice: "He has never been to the United States before" (nunca había estado antes).',
            },
            {
              id: 'a2-wb-p2-ex6-q3',
              type: 'multiple_choice',
              concept: 'since reading',
              difficulty: 4,
              prompt: '¿Desde cuándo conoce Pedro a su amigo Tom?',
              correctAnswer: 'desde 2018',
              options: ['desde 2018', 'desde hace diez años', 'desde que vivía en Nueva York'],
              explanation: 'El texto dice: "He has known his American friend Tom since 2018" (since + punto de inicio).',
            },
            {
              id: 'a2-wb-p2-ex6-q4',
              type: 'multiple_choice',
              concept: 'for reading',
              difficulty: 4,
              prompt: '¿Cuánto tiempo lleva Tom viviendo en Nueva York?',
              correctAnswer: 'diez años',
              options: ['diez años', 'dos años', 'cinco años'],
              explanation: 'El texto dice: "Tom has lived in New York for ten years" (for + duración).',
            },
            {
              id: 'a2-wb-p2-ex6-q5',
              type: 'multiple_choice',
              concept: 'already / yet reading',
              difficulty: 4,
              prompt: '¿Qué ha hecho Pedro con los recuerdos para su familia?',
              correctAnswer: 'ya los ha comprado',
              options: ['ya los ha comprado', 'todavía no los ha comprado', 'los ha perdido'],
              explanation: 'El texto dice: "Pedro has already bought souvenirs for his family" (already = ya, en afirmativa).',
            },
          ],
        },
        explanation:
          'El texto usa el Present Perfect para experiencias y acciones recientes: has just come back, has already bought, has never been, has known... since, has lived... for.',
      },
    ],
  },
  {
    id: 'a2-wb-3',
    levelId: 'a2',
    unit: 'Unit 3 · Past Continuous',
    page: 3,
    title: 'Past Continuous y contraste con Past Simple',
    intro:
      'Practicá el pasado continuo (was/were + verbo -ing) para acciones en desarrollo en el pasado y su contraste con el pasado simple.',
    exercises: [
      {
        id: 'a2-wb-p3-ex1',
        type: 'multiple_choice',
        concept: 'was vs were',
        difficulty: 1,
        prompt: 'Completa: "They ___ watching TV at 8 p.m."',
        correctAnswer: 'were',
        options: ['were', 'was', 'is'],
        explanation: '"They" es plural → were. → They were watching TV at 8 p.m.',
      },
      {
        id: 'a2-wb-p3-ex2',
        type: 'fill_blank',
        concept: 'was/were + -ing',
        difficulty: 2,
        prompt: 'Completa con la forma correcta: "I ___ a book when you called." (read)',
        correctAnswer: 'was reading',
        acceptedAnswers: ['was reading', 'Was reading'],
        explanation: '"I" + was + verbo -ing (read → reading): I was reading a book when you called.',
      },
      {
        id: 'a2-wb-p3-ex3',
        type: 'reorder',
        concept: 'past continuous estructura',
        difficulty: 3,
        prompt: 'Ordena las palabras para formar una frase: cooking / she / was / dinner / at 6 o\'clock',
        correctAnswer: 'She was cooking dinner at 6 o\'clock.',
        words: ['She', 'was', 'cooking', 'dinner', 'at 6 o\'clock'],
        explanation: 'Orden: sujeto + was/were + verbo -ing + complemento. → She was cooking dinner at 6 o\'clock.',
      },
      {
        id: 'a2-wb-p3-ex4',
        type: 'select_correct',
        concept: 'past simple vs past continuous',
        difficulty: 3,
        prompt: 'Selecciona la frase correcta que combina pasado simple y continuo.',
        correctAnswer: 'When I arrived, she was cooking dinner.',
        options: [
          'When I arrived, she was cooking dinner.',
          'When I was arriving, she cooked dinner.',
          'When I arrived, she is cooking dinner.',
        ],
        explanation:
          'La acción que interrumpe (arrived) va en pasado simple; la acción en curso (was cooking) va en pasado continuo.',
      },
      {
        id: 'a2-wb-p3-ex5',
        type: 'error_correction',
        concept: 'pasado continuo correcto',
        difficulty: 3,
        prompt: 'Corrige el error: "He were sleeping when the phone rang."',
        correctAnswer: 'He was sleeping when the phone rang.',
        acceptedAnswers: [
          'He was sleeping when the phone rang',
          'He was sleeping when the phone rang.',
          'he was sleeping when the phone rang',
        ],
        acceptApproximate: true,
        explanation: '"He" es singular → was, no were. → He was sleeping when the phone rang.',
      },
      {
        id: 'a2-wb-p3-ex6',
        type: 'true_false',
        concept: 'uso del past continuous',
        difficulty: 2,
        prompt: '"We use the Past Continuous for finished actions at a specific time in the past."',
        correctAnswer: 'false',
        acceptedAnswers: ['False', 'FALSE', 'Falso', 'false.'],
        explanation:
          'Es FALSO. El pasado continuo describe acciones EN DESARROLLO (en progreso) en un momento del pasado; las acciones terminadas usan el pasado simple.',
      },
    ],
  },
  {
    id: 'a2-wb-4',
    levelId: 'a2',
    unit: 'Unit 4 · Futuro',
    page: 4,
    title: 'Futuro: will, going to y presente continuo',
    intro:
      'Practicá las tres formas de expresar el futuro en A2: will (decisiones y predicciones), going to (planes e intenciones) y el presente continuo (planes fijos).',
    exercises: [
      {
        id: 'a2-wb-p4-ex1',
        type: 'multiple_choice',
        concept: 'will para decisiones espontáneas',
        difficulty: 1,
        prompt: 'Completa: "I\'m tired. I ___ go to bed early tonight."',
        correctAnswer: 'will',
        options: ['will', 'am going to', 'am'],
        explanation: '"Will" se usa para decisiones espontáneas tomadas en el momento de hablar: I will go to bed early.',
      },
      {
        id: 'a2-wb-p4-ex2',
        type: 'fill_blank',
        concept: 'going to para planes',
        difficulty: 2,
        prompt: 'Completa con going to: "She ___ study medicine next year." (is going to)',
        correctAnswer: 'is going to',
        acceptedAnswers: ['is going to', 'Is going to'],
        explanation: '"Going to" expresa un plan o intención ya decidida: She is going to study medicine next year.',
      },
      {
        id: 'a2-wb-p4-ex3',
        type: 'multiple_choice',
        concept: 'presente continuo de futuro',
        difficulty: 2,
        prompt: 'Completa con el presente continuo de futuro: "We ___ to the beach on Saturday." (go)',
        correctAnswer: 'are going',
        options: ['are going', 'will go', 'go'],
        explanation:
          'El presente continuo (am/is/are + -ing) expresa un plan fijo con hora o lugar: We are going to the beach on Saturday.',
      },
      {
        id: 'a2-wb-p4-ex4',
        type: 'reorder',
        concept: 'going to estructura',
        difficulty: 3,
        prompt: 'Ordena las palabras para formar una frase: going to / a new car / buy / They / are',
        correctAnswer: 'They are going to buy a new car.',
        words: ['They', 'are', 'going to', 'buy', 'a new car'],
        explanation: 'Orden: sujeto + am/is/are + going to + verbo base. → They are going to buy a new car.',
      },
      {
        id: 'a2-wb-p4-ex5',
        type: 'select_correct',
        concept: 'will vs going to',
        difficulty: 4,
        prompt: 'Selecciona la frase correcta para hablar de una predicción con evidencia (nubes):',
        correctAnswer: 'Look at the clouds! It is going to rain.',
        options: [
          'Look at the clouds! It is going to rain.',
          'Look at the clouds! It rains.',
          'Look at the clouds! It is raining tomorrow.',
        ],
        explanation:
          'Cuando hay evidencia visible (nubes), usamos "going to" para predecir: It is going to rain.',
      },
      {
        id: 'a2-wb-p4-ex6',
        type: 'translate',
        concept: 'will en promesas',
        difficulty: 3,
        prompt: 'Traduce: "Te ayudaré con tu tarea."',
        correctAnswer: 'I will help you with your homework.',
        acceptedAnswers: [
          'I will help you with your homework',
          'I will help you with your homework.',
          'i will help you with your homework',
        ],
        acceptApproximate: true,
        explanation: '"Ayudaré" = I will help (promesa u ofrecimiento con will). "Con tu tarea" = with your homework.',
      },
    ],
  },
  {
    id: 'a2-wb-5',
    levelId: 'a2',
    unit: 'Unit 5 · Obligación y consejo',
    page: 5,
    title: 'Obligación y consejo: must, have to y should',
    intro:
      'Practicá cómo expresar obligación (must, have to), ausencia de obligación (don\'t have to) y consejo (should).',
    exercises: [
      {
        id: 'a2-wb-p5-ex1',
        type: 'multiple_choice',
        concept: 'must vs don\'t have to',
        difficulty: 2,
        prompt: 'Completa: "You ___ pay. The concert is free."',
        correctAnswer: 'don\'t have to',
        options: ['don\'t have to', 'mustn\'t', 'must'],
        explanation:
          '"Don\'t have to" = no es necesario (no hay obligación). "Mustn\'t" = está prohibido. Como el concierto es gratis, no hay que pagar: don\'t have to.',
      },
      {
        id: 'a2-wb-p5-ex2',
        type: 'fill_blank',
        concept: 'have to',
        difficulty: 1,
        prompt: 'Completa: "She has to ___ a uniform at work." (wear)',
        correctAnswer: 'wear',
        acceptedAnswers: ['wear', 'Wear'],
        explanation: 'Después de "has to" usamos el verbo en forma base: has to wear a uniform.',
      },
      {
        id: 'a2-wb-p5-ex3',
        type: 'match',
        concept: 'modales de obligación y consejo',
        difficulty: 2,
        prompt: 'Une cada modal con su significado correcto.',
        correctAnswer: 'match',
        pairs: [
          { left: 'must', right: 'obligación fuerte' },
          { left: 'have to', right: 'obligación (regla o necesidad)' },
          { left: 'don\'t have to', right: 'no es necesario' },
          { left: 'should', right: 'consejo o recomendación' },
          { left: 'mustn\'t', right: 'prohibido' },
        ],
        explanation:
          'must = obligación fuerte; have to = obligación por regla o necesidad; don\'t have to = no es necesario; should = consejo; mustn\'t = prohibición.',
      },
      {
        id: 'a2-wb-p5-ex4',
        type: 'true_false',
        concept: 'should para consejo',
        difficulty: 2,
        prompt: '"We use should to give advice or recommendations."',
        correctAnswer: 'true',
        acceptedAnswers: ['True', 'TRUE', 'Verdadero', 'true.'],
        explanation: 'Es VERDADERO. "Should" se usa para dar consejos o recomendaciones: You should drink more water.',
      },
      {
        id: 'a2-wb-p5-ex5',
        type: 'error_correction',
        concept: 'should + forma base',
        difficulty: 3,
        prompt: 'Corrige el error: "You should to study more for the exam."',
        correctAnswer: 'You should study more for the exam.',
        acceptedAnswers: [
          'You should study more for the exam',
          'You should study more for the exam.',
          'you should study more for the exam',
        ],
        acceptApproximate: true,
        explanation: 'Después de "should" usamos la forma base del verbo, sin "to": should study (no "should to study").',
      },
      {
        id: 'a2-wb-p5-ex6',
        type: 'writing',
        concept: 'consejos con should',
        difficulty: 4,
        prompt:
          'Escribí un correo breve a un amigo que está estresado con el trabajo. Dale al menos tres consejos usando should y mencioná una obligación con have to.',
        correctAnswer:
          'Hi Luis, I think you should rest more. You should sleep eight hours every night. You don\'t have to answer emails on Sunday, and you should ask your boss for help. Take care, Ana.',
        taskType: 'email',
        targetReader: 'a friend',
        register: 'informal',
        contentPoints: ['Al menos tres consejos con should', 'Una frase con have to / don\'t have to'],
        requiresOwnIdea: true,
        minWords: 40,
        maxWords: 80,
        explanation:
          'Un buen correo usa should + forma base para los consejos, incluye al menos una frase con have to/don\'t have to y mantiene un tono informal y amable.',
      },
    ],
  },
  {
    id: 'a2-wb-6',
    levelId: 'a2',
    unit: 'Unit 6 · Posibilidad y permiso',
    page: 6,
    title: 'Posibilidad y permiso: can, could, may y might',
    intro:
      'Practicá cómo expresar capacidad (can/could), posibilidad (may/might) y pedir permiso de forma educada.',
    exercises: [
      {
        id: 'a2-wb-p6-ex1',
        type: 'multiple_choice',
        concept: 'can vs could (capacidad)',
        difficulty: 1,
        prompt: 'Completa: "When I was five, I ___ swim."',
        correctAnswer: 'could',
        options: ['could', 'can', 'may'],
        explanation: '"Could" es el pasado de "can" para capacidad: cuando tenía cinco años podía nadar.',
      },
      {
        id: 'a2-wb-p6-ex2',
        type: 'fill_blank',
        concept: 'may / might (posibilidad)',
        difficulty: 2,
        prompt: 'Completa: "It ___ rain later. Take an umbrella." (posibilidad)',
        correctAnswer: 'might',
        acceptedAnswers: ['might', 'may', 'Might', 'May'],
        explanation: '"May" y "might" expresan posibilidad. "Might" es un poco menos seguro: It might rain later.',
      },
      {
        id: 'a2-wb-p6-ex3',
        type: 'select_correct',
        concept: 'permiso con may',
        difficulty: 2,
        prompt: 'Selecciona la forma correcta y educada de pedir permiso.',
        correctAnswer: 'May I open the window?',
        options: ['May I open the window?', 'I may open the window?', 'I open may the window?'],
        explanation:
          'Para pedir permiso con "may" la pregunta es: May + sujeto + verbo... → May I open the window?',
      },
      {
        id: 'a2-wb-p6-ex4',
        type: 'match',
        concept: 'peticiones y respuestas',
        difficulty: 3,
        prompt: 'Une cada petición con su respuesta adecuada.',
        correctAnswer: 'match',
        pairs: [
          { left: 'Can I borrow your pen?', right: 'Sure, here you are.' },
          { left: 'Could you help me, please?', right: 'Of course, no problem.' },
          { left: 'May I come in?', right: 'Yes, please.' },
          { left: 'Can you speak louder?', right: 'Sorry, is this better?' },
        ],
        explanation:
          'Can/could/may se usan para pedir; las respuestas educadas confirman o piden disculpas de forma amable.',
      },
      {
        id: 'a2-wb-p6-ex5',
        type: 'error_correction',
        concept: 'may / might + forma base',
        difficulty: 3,
        prompt: 'Corrige el error: "She might to come to the party."',
        correctAnswer: 'She might come to the party.',
        acceptedAnswers: [
          'She might come to the party',
          'She might come to the party.',
          'she might come to the party',
        ],
        acceptApproximate: true,
        explanation: 'Después de may/might/can/could usamos la forma base del verbo, sin "to": might come.',
      },
      {
        id: 'a2-wb-p6-ex6',
        type: 'translate',
        concept: 'could en el pasado',
        difficulty: 3,
        prompt: 'Traduce: "Cuando era niño, podía jugar al fútbol todos los días."',
        correctAnswer: 'When I was a child, I could play football every day.',
        acceptedAnswers: [
          'When I was a child, I could play football every day',
          'When I was a child, I could play football every day.',
          'when I was a child, I could play football every day',
        ],
        acceptApproximate: true,
        explanation: '"Cuando era niño" = When I was a child; "podía" = could + forma base (play); "todos los días" = every day.',
      },
    ],
  },
  {
    id: 'a2-wb-7',
    levelId: 'a2',
    unit: 'Unit 7 · Condicionales 0 y 1',
    page: 7,
    title: 'Condicionales cero y primero',
    intro:
      'Practicá el condicional cero (verdades generales: if + presente / presente) y el primero (futuro posible: if + presente / will).',
    exercises: [
      {
        id: 'a2-wb-p7-ex1',
        type: 'multiple_choice',
        concept: 'zero conditional',
        difficulty: 1,
        prompt: 'Completa el condicional cero: "If you heat ice, it ___."',
        correctAnswer: 'melts',
        options: ['melts', 'will melt', 'would melt'],
        explanation:
          'El condicional cero usa presente + presente para verdades generales: If you heat ice, it melts.',
      },
      {
        id: 'a2-wb-p7-ex2',
        type: 'fill_blank',
        concept: 'first conditional',
        difficulty: 2,
        prompt: 'Completa el condicional primero: "If it rains tomorrow, we ___ stay at home." (will)',
        correctAnswer: 'will',
        acceptedAnswers: ['will', 'Will'],
        explanation:
          'El condicional primero es if + presente + will + verbo base: If it rains tomorrow, we will stay at home.',
      },
      {
        id: 'a2-wb-p7-ex3',
        type: 'reorder',
        concept: 'primer condicional estructura',
        difficulty: 3,
        prompt: 'Ordena las palabras para formar una frase: you / If / study / will / pass / you / the exam',
        correctAnswer: 'If you study, you will pass the exam.',
        words: ['If', 'you', 'study,', 'you', 'will', 'pass', 'the exam'],
        explanation:
          'Orden: If + sujeto + presente + coma + sujeto + will + verbo base. → If you study, you will pass the exam.',
      },
      {
        id: 'a2-wb-p7-ex4',
        type: 'select_correct',
        concept: 'zero vs first conditional',
        difficulty: 4,
        prompt: 'Selecciona la frase correcta para hablar de una situación real y posible en el futuro:',
        correctAnswer: 'If I have time, I will call you tonight.',
        options: [
          'If I have time, I will call you tonight.',
          'If I will have time, I call you tonight.',
          'If I had time, I will call you tonight.',
        ],
        explanation:
          'En el condicional primero nunca usamos "will" en la parte del "if": if + presente + will + verbo base.',
      },
      {
        id: 'a2-wb-p7-ex5',
        type: 'error_correction',
        concept: 'will en la parte if',
        difficulty: 4,
        prompt: 'Corrige el error: "If I will be late, I will text you."',
        correctAnswer: 'If I am late, I will text you.',
        acceptedAnswers: [
          'If I am late, I will text you',
          'If I am late, I will text you.',
          'if I am late, I will text you',
        ],
        acceptApproximate: true,
        explanation: 'Después de "if" en el condicional primero usamos presente (am), nunca "will": If I am late...',
      },
      {
        id: 'a2-wb-p7-ex6',
        type: 'translate',
        concept: 'zero conditional',
        difficulty: 3,
        prompt: 'Traduce: "Si estudias todos los días, aprendes más rápido."',
        correctAnswer: 'If you study every day, you learn faster.',
        acceptedAnswers: [
          'If you study every day, you learn faster',
          'If you study every day, you learn faster.',
          'if you study every day, you learn faster',
        ],
        acceptApproximate: true,
        explanation:
          'Es una verdad general → condicional cero: If + presente (study) + presente (learn). "Más rápido" = faster.',
      },
    ],
  },
  {
    id: 'a2-wb-8',
    levelId: 'a2',
    unit: 'Unit 8 · Oraciones relativas',
    page: 8,
    title: 'Oraciones relativas: who, which, that y where',
    intro:
      'Practicá las oraciones relativas para describir personas (who), cosas (which/that) y lugares (where).',
    exercises: [
      {
        id: 'a2-wb-p8-ex1',
        type: 'multiple_choice',
        concept: 'who para personas',
        difficulty: 1,
        prompt: 'Completa: "The woman ___ lives next door is a doctor."',
        correctAnswer: 'who',
        options: ['who', 'which', 'where'],
        explanation: '"Who" se usa para personas: The woman who lives next door is a doctor.',
      },
      {
        id: 'a2-wb-p8-ex2',
        type: 'fill_blank',
        concept: 'which / that para cosas',
        difficulty: 2,
        prompt: 'Completa: "This is the book ___ I told you about." (which/that)',
        correctAnswer: 'which',
        acceptedAnswers: ['which', 'that', 'Which', 'That'],
        explanation: '"Which" o "that" se usan para cosas: the book which/that I told you about.',
      },
      {
        id: 'a2-wb-p8-ex3',
        type: 'fill_blank',
        concept: 'where para lugares',
        difficulty: 2,
        prompt: 'Completa: "That\'s the restaurant ___ we ate last night."',
        correctAnswer: 'where',
        acceptedAnswers: ['where', 'Where'],
        explanation: '"Where" se usa para lugares: the restaurant where we ate last night.',
      },
      {
        id: 'a2-wb-p8-ex4',
        type: 'reorder',
        concept: 'oración relativa',
        difficulty: 3,
        prompt: 'Ordena las palabras para formar una frase: is / The boy / who / my cousin / playing football',
        correctAnswer: 'The boy who is playing football is my cousin.',
        words: ['The boy', 'who', 'is', 'playing', 'football', 'is my cousin'],
        explanation:
          'Orden: sustantivo + who + verbo + resto + verbo principal. → The boy who is playing football is my cousin.',
      },
      {
        id: 'a2-wb-p8-ex5',
        type: 'match',
        concept: 'unir oraciones con relativas',
        difficulty: 3,
        prompt: 'Une cada oración con su versión con relativa.',
        correctAnswer: 'match',
        pairs: [
          { left: 'I have a friend. She speaks three languages.', right: 'I have a friend who speaks three languages.' },
          { left: 'This is the phone. I bought it yesterday.', right: 'This is the phone which I bought yesterday.' },
          { left: 'This is the park. We play there.', right: 'This is the park where we play.' },
          { left: 'The dog is brown. It lives next door.', right: 'The dog which lives next door is brown.' },
        ],
        explanation:
          'who → personas, which → cosas, where → lugares. La relativa une dos frases en una sola sin repetir el sustantivo.',
      },
      {
        id: 'a2-wb-p8-ex6',
        type: 'error_correction',
        concept: 'who vs which',
        difficulty: 3,
        prompt: 'Corrige el error: "The man which works here is very kind."',
        correctAnswer: 'The man who works here is very kind.',
        acceptedAnswers: [
          'The man who works here is very kind',
          'The man who works here is very kind.',
          'the man who works here is very kind',
        ],
        acceptApproximate: true,
        explanation: 'Para personas usamos "who", no "which": The man who works here is very kind.',
      },
    ],
  },
  {
    id: 'a2-wb-9',
    levelId: 'a2',
    unit: 'Unit 9 · Voz pasiva',
    page: 9,
    title: 'Voz pasiva en presente y pasado',
    intro:
      'Practicá la voz pasiva en presente (is/are + participio) y en pasado (was/were + participio).',
    exercises: [
      {
        id: 'a2-wb-p9-ex1',
        type: 'multiple_choice',
        concept: 'pasiva en presente',
        difficulty: 1,
        prompt: 'Completa: "Coffee ___ grown in Colombia."',
        correctAnswer: 'is',
        options: ['is', 'are', 'am'],
        explanation: '"Coffee" es singular → is + participio. → Coffee is grown in Colombia.',
      },
      {
        id: 'a2-wb-p9-ex2',
        type: 'fill_blank',
        concept: 'pasiva en pasado',
        difficulty: 2,
        prompt: 'Completa con la pasiva en pasado: "The letters ___ sent yesterday." (send)',
        correctAnswer: 'were sent',
        acceptedAnswers: ['were sent', 'Were sent', 'was sent'],
        explanation: '"The letters" es plural y es pasado → were + participio (sent). → The letters were sent yesterday.',
      },
      {
        id: 'a2-wb-p9-ex3',
        type: 'reorder',
        concept: 'pasiva estructura',
        difficulty: 3,
        prompt: 'Ordena las palabras para formar una frase: in Spain / paella / is / made',
        correctAnswer: 'Paella is made in Spain.',
        words: ['Paella', 'is', 'made', 'in Spain'],
        explanation: 'Orden: sujeto + is/are + participio + complemento. → Paella is made in Spain.',
      },
      {
        id: 'a2-wb-p9-ex4',
        type: 'select_correct',
        concept: 'pasiva en pasado',
        difficulty: 3,
        prompt: 'Selecciona la frase pasiva correcta en pasado:',
        correctAnswer: 'This house was built in 1990.',
        options: [
          'This house was built in 1990.',
          'This house is built in 1990.',
          'This house was build in 1990.',
        ],
        explanation:
          'Pasado pasivo: was/were + participio (built, no build). "This house" es singular → was.',
      },
      {
        id: 'a2-wb-p9-ex5',
        type: 'error_correction',
        concept: 'participio en la pasiva',
        difficulty: 3,
        prompt: 'Corrige el error: "English is spoke in many countries."',
        correctAnswer: 'English is spoken in many countries.',
        acceptedAnswers: [
          'English is spoken in many countries',
          'English is spoken in many countries.',
          'english is spoken in many countries',
        ],
        acceptApproximate: true,
        explanation: 'En la pasiva usamos el participio "spoken" (speak → spoken), no el pasado simple "spoke".',
      },
      {
        id: 'a2-wb-p9-ex6',
        type: 'translate',
        concept: 'pasiva en pasado',
        difficulty: 4,
        prompt: 'Traduce: "Esta película fue hecha en 2015."',
        correctAnswer: 'This film was made in 2015.',
        acceptedAnswers: [
          'This film was made in 2015',
          'This film was made in 2015.',
          'this film was made in 2015',
        ],
        acceptApproximate: true,
        explanation: '"Fue hecha" = was made (pasiva en pasado, make → made). "Esta película" = This film.',
      },
    ],
  },
  {
    id: 'a2-wb-10',
    levelId: 'a2',
    unit: 'Unit 10 · Pronombres reflexivos',
    page: 10,
    title: 'Pronombres reflexivos y each other',
    intro:
      'Practicá los pronombres reflexivos (myself, yourself, himself...) y la diferencia con each other.',
    exercises: [
      {
        id: 'a2-wb-p10-ex1',
        type: 'multiple_choice',
        concept: 'reflexivos básicos',
        difficulty: 1,
        prompt: 'Completa: "I looked at ___ in the mirror."',
        correctAnswer: 'myself',
        options: ['myself', 'yourself', 'himself'],
        explanation: '"I" → myself: I looked at myself in the mirror.',
      },
      {
        id: 'a2-wb-p10-ex2',
        type: 'fill_blank',
        concept: 'reflexivos por persona',
        difficulty: 2,
        prompt: 'Completa con el reflexivo correcto: "She cooked dinner ___."',
        correctAnswer: 'herself',
        acceptedAnswers: ['herself', 'Herself'],
        explanation: '"She" → herself: She cooked dinner herself.',
      },
      {
        id: 'a2-wb-p10-ex3',
        type: 'fill_blank',
        concept: 'by + reflexivo (solo)',
        difficulty: 3,
        prompt: 'Completa: "He lives ___." (solo)',
        correctAnswer: 'by himself',
        acceptedAnswers: ['by himself', 'By himself'],
        explanation: '"By + reflexivo" significa "solo/a": He lives by himself.',
      },
      {
        id: 'a2-wb-p10-ex4',
        type: 'select_correct',
        concept: 'each other vs reflexivo',
        difficulty: 3,
        prompt: 'Selecciona la frase correcta:',
        correctAnswer: 'They talk to each other every day.',
        options: [
          'They talk to each other every day.',
          'They talk to themselves every day.',
          'They talk to themselves each other every day.',
        ],
        explanation:
          '"Each other" indica acción recíproca (se hablan el uno al otro). El reflexivo (themselves) sería hablarse a sí mismos.',
      },
      {
        id: 'a2-wb-p10-ex5',
        type: 'error_correction',
        concept: 'reflexivo correcto',
        difficulty: 3,
        prompt: 'Corrige el error: "We enjoyed ourselves at the party."',
        correctAnswer: 'We enjoyed ourselves at the party.',
        acceptedAnswers: [
          'We enjoyed ourselves at the party',
          'We enjoyed ourselves at the party.',
          'we enjoyed ourselves at the party',
        ],
        acceptApproximate: true,
        explanation:
          'La frase es correcta: enjoy + reflexivo es la forma natural (divertirse). Si el ejercicio pedía corregir, aquí no hay error: se mantiene "ourselves".',
      },
      {
        id: 'a2-wb-p10-ex6',
        type: 'translate',
        concept: 'by + reflexivo',
        difficulty: 4,
        prompt: 'Traduce: "Ella hizo el pastel sola."',
        correctAnswer: 'She made the cake by herself.',
        acceptedAnswers: [
          'She made the cake by herself',
          'She made the cake by herself.',
          'she made the cake by herself',
        ],
        acceptApproximate: true,
        explanation: '"Sola" = by herself. → She made the cake by herself.',
      },
    ],
  },
  {
    id: 'a2-wb-11',
    levelId: 'a2',
    unit: 'Unit 11 · Estilo indirecto',
    page: 11,
    title: 'Estilo indirecto básico: say y tell',
    intro:
      'Practicá cómo contar lo que dijo otra persona: say / tell y el cambio de tiempos en el estilo indirecto.',
    exercises: [
      {
        id: 'a2-wb-p11-ex1',
        type: 'multiple_choice',
        concept: 'say vs tell',
        difficulty: 1,
        prompt: 'Completa: "She ___ me that she was tired."',
        correctAnswer: 'told',
        options: ['told', 'said', 'telled'],
        explanation: '"Tell + persona" (le dijo a alguien): She told me that she was tired. Con "say" no usamos la persona después.',
      },
      {
        id: 'a2-wb-p11-ex2',
        type: 'fill_blank',
        concept: 'reportado con say',
        difficulty: 2,
        prompt: 'Completa el estilo indirecto: "He said that he ___ hungry." (was)',
        correctAnswer: 'was',
        acceptedAnswers: ['was', 'Was'],
        explanation: 'Al pasar a estilo indirecto, "I am" se convierte en "he was": He said that he was hungry.',
      },
      {
        id: 'a2-wb-p11-ex3',
        type: 'reorder',
        concept: 'estilo indirecto estructura',
        difficulty: 3,
        prompt: 'Ordena las palabras para formar una frase: said / he / that / was / She / tired',
        correctAnswer: 'She said that he was tired.',
        words: ['She', 'said', 'that', 'he', 'was', 'tired'],
        explanation: 'Orden: sujeto + said + that + sujeto + verbo en pasado. → She said that he was tired.',
      },
      {
        id: 'a2-wb-p11-ex4',
        type: 'select_correct',
        concept: 'cambio de tiempos',
        difficulty: 4,
        prompt: 'Selecciona el estilo indirecto correcto de: "I am busy", dijo Ana.',
        correctAnswer: 'Ana said that she was busy.',
        options: ['Ana said that she was busy.', 'Ana said that she is busy.', 'Ana said that I was busy.'],
        explanation:
          'En estilo indirecto retrocedemos el tiempo: "I am" → she was. El pronombre también cambia (I → she).',
      },
      {
        id: 'a2-wb-p11-ex5',
        type: 'error_correction',
        concept: 'say sin persona',
        difficulty: 3,
        prompt: 'Corrige el error: "She told me that she was happy."',
        correctAnswer: 'She told me that she was happy.',
        acceptedAnswers: [
          'She told me that she was happy',
          'She told me that she was happy.',
          'she told me that she was happy',
        ],
        acceptApproximate: true,
        explanation:
          'La frase es correcta: tell + me + that... es la estructura adecuada. No hay error que corregir aquí.',
      },
      {
        id: 'a2-wb-p11-ex6',
        type: 'translate',
        concept: 'estilo indirecto',
        difficulty: 4,
        prompt: 'Traduce: "Él dijo que vivía en Madrid."',
        correctAnswer: 'He said that he lived in Madrid.',
        acceptedAnswers: [
          'He said that he lived in Madrid',
          'He said that he lived in Madrid.',
          'he said that he lived in Madrid',
        ],
        acceptApproximate: true,
        explanation: '"Dijo que" = said that; "vivía" (present simple "I live" reportado) → lived. → He said that he lived in Madrid.',
      },
    ],
  },
  {
    id: 'a2-wb-12',
    levelId: 'a2',
    unit: 'Unit 12 · Gerundios e infinitivos',
    page: 12,
    title: 'Gerundios, infinitivos y phrasal verbs',
    intro:
      'Practicá verbos seguidos de gerundio (-ing), verbos seguidos de infinitivo (to + verbo) y phrasal verbs comunes.',
    exercises: [
      {
        id: 'a2-wb-p12-ex1',
        type: 'multiple_choice',
        concept: 'verbo + gerundio',
        difficulty: 1,
        prompt: 'Completa: "I enjoy ___ new people." (meet)',
        correctAnswer: 'meeting',
        options: ['meeting', 'to meet', 'meet'],
        explanation: 'El verbo "enjoy" va seguido de gerundio: enjoy + -ing → I enjoy meeting new people.',
      },
      {
        id: 'a2-wb-p12-ex2',
        type: 'fill_blank',
        concept: 'verbo + infinitivo',
        difficulty: 2,
        prompt: 'Completa con la forma correcta: "She wants ___ English in London." (study)',
        correctAnswer: 'to study',
        acceptedAnswers: ['to study', 'To study'],
        explanation: 'El verbo "want" va seguido de infinitivo: want + to + verbo → She wants to study English.',
      },
      {
        id: 'a2-wb-p12-ex3',
        type: 'match',
        concept: 'phrasal verbs',
        difficulty: 2,
        prompt: 'Une cada phrasal verb con su significado.',
        correctAnswer: 'match',
        pairs: [
          { left: 'get up', right: 'levantarse' },
          { left: 'turn on', right: 'encender' },
          { left: 'look for', right: 'buscar' },
          { left: 'give up', right: 'rendirse' },
          { left: 'put on', right: 'ponerse (ropa)' },
        ],
        explanation:
          'get up = levantarse, turn on = encender, look for = buscar, give up = rendirse, put on = ponerse la ropa.',
      },
      {
        id: 'a2-wb-p12-ex4',
        type: 'fill_blank',
        concept: 'phrasal verbs en contexto',
        difficulty: 3,
        prompt: 'Completa con el phrasal verb correcto: "I can\'t find my keys. I need to ___ them." (buscar)',
        correctAnswer: 'look for',
        acceptedAnswers: ['look for', 'Look for'],
        explanation: 'Buscar = look for. Como no encuentras las llaves, tienes que buscarlas: I need to look for them.',
      },
      {
        id: 'a2-wb-p12-ex5',
        type: 'error_correction',
        concept: 'verbo + gerundio',
        difficulty: 3,
        prompt: 'Corrige el error: "I finish to work at 6 p.m."',
        correctAnswer: 'I finish working at 6 p.m.',
        acceptedAnswers: [
          'I finish working at 6 p.m',
          'I finish working at 6 p.m.',
          'i finish working at 6 p.m.',
        ],
        acceptApproximate: true,
        explanation: 'El verbo "finish" va seguido de gerundio: finish + -ing → I finish working at 6 p.m.',
      },
      {
        id: 'a2-wb-p12-ex6',
        type: 'writing',
        concept: 'relato con phrasal verbs',
        difficulty: 4,
        prompt:
          'Escribí una historia breve sobre tu rutina de la mañana. Usá al menos tres phrasal verbs (por ejemplo: get up, turn on, put on, look for, give up) y una frase con enjoy + -ing.',
        correctAnswer:
          'I get up at seven o\'clock. I turn on the radio and I put on my clothes. I make coffee and I look for my keys. I enjoy listening to music in the morning.',
        taskType: 'story',
        targetReader: 'your teacher',
        register: 'neutral',
        contentPoints: ['Al menos tres phrasal verbs', 'Una frase con enjoy + -ing'],
        requiresOwnIdea: true,
        minWords: 40,
        maxWords: 70,
        explanation:
          'Un buen relato usa phrasal verbs de forma natural (get up, turn on, put on, look for) e incluye al menos una frase con verb + -ing (enjoy listening).',
      },
    ],
  },
  {
    id: 'a2-wb-13',
    levelId: 'a2',
    unit: 'Unit 13 · Repaso',
    page: 13,
    title: 'Repaso general y lectura final',
    intro:
      'Repasá los contenidos del nivel A2 con ejercicios variados y una lectura final que combina varias unidades.',
    exercises: [
      {
        id: 'a2-wb-p13-ex1',
        type: 'multiple_choice',
        concept: 'repaso: comparativos',
        difficulty: 2,
        prompt: 'Completa: "This film is ___ than the one we saw last week." (interesting)',
        correctAnswer: 'more interesting',
        options: ['more interesting', 'interesting', 'most interesting'],
        explanation: '"Interesting" es largo → more interesting. Comparativo: more + adjetivo + than.',
      },
      {
        id: 'a2-wb-p13-ex2',
        type: 'fill_blank',
        concept: 'repaso: present perfect',
        difficulty: 2,
        prompt: 'Completa con el Present Perfect: "I ___ never been to Italy." (have/has)',
        correctAnswer: 'have',
        acceptedAnswers: ['have', 'Have'],
        explanation: '"I" → have: I have never been to Italy.',
      },
      {
        id: 'a2-wb-p13-ex3',
        type: 'reading',
        concept: 'reading final de repaso',
        difficulty: 4,
        prompt: 'Lee el texto sobre la mudanza de Marta y responde las preguntas.',
        correctAnswer: 'reading complete',
        reading: {
          text: 'Marta moved to a new city last month. She was looking for a new flat for weeks, and finally she found a beautiful one near the station. The flat was built in 1990, but it is very modern now.\nThe neighbours are friendly. The man who lives upstairs has lived there for twenty years. He told Marta that the area is very quiet. Marta thinks that her new flat is bigger than her old one, and it is also cheaper.\nMarta is going to visit her parents next weekend. She has not made new friends yet, but she is going to join a yoga class, where she can meet people who live nearby. She believes that if she goes to the class, she will feel at home soon.',
          translation:
            'Marta se mudó a una nueva ciudad el mes pasado. Estuvo buscando un piso nuevo durante semanas y finalmente encontró uno precioso cerca de la estación. El piso se construyó en 1990, pero ahora es muy moderno.\nLos vecinos son simpáticos. El hombre que vive arriba lleva veinte años viviendo allí. Le dijo a Marta que la zona es muy tranquila. Marta cree que su piso nuevo es más grande que el antiguo, y también es más barato.\nMarta va a visitar a sus padres el próximo fin de semana. Todavía no ha hecho amigos nuevos, pero va a apuntarse a una clase de yoga, donde puede conocer a gente que vive cerca. Cree que si va a la clase, pronto se sentirá como en casa.',
          questions: [
            {
              id: 'a2-wb-p13-ex3-q1',
              type: 'multiple_choice',
              concept: 'repaso: past continuous',
              difficulty: 4,
              prompt: '¿Qué estaba haciendo Marta antes de encontrar su piso?',
              correctAnswer: 'estaba buscando un piso nuevo',
              options: ['estaba buscando un piso nuevo', 'estaba trabajando', 'estaba de vacaciones'],
              explanation: 'El texto dice: "She was looking for a new flat for weeks" (was looking = pasado continuo).',
            },
            {
              id: 'a2-wb-p13-ex3-q2',
              type: 'multiple_choice',
              concept: 'repaso: voz pasiva',
              difficulty: 4,
              prompt: '¿Cuándo se construyó el piso de Marta?',
              correctAnswer: 'en 1990',
              options: ['en 1990', 'el mes pasado', 'hace veinte años'],
              explanation: 'El texto dice: "The flat was built in 1990" (was built = voz pasiva en pasado).',
            },
            {
              id: 'a2-wb-p13-ex3-q3',
              type: 'multiple_choice',
              concept: 'repaso: relativa + present perfect',
              difficulty: 4,
              prompt: '¿Cuánto tiempo lleva viviendo allí el vecino?',
              correctAnswer: 'veinte años',
              options: ['veinte años', 'dos años', 'diez años'],
              explanation: 'El texto dice: "has lived there for twenty years" (Present Perfect con for).',
            },
            {
              id: 'a2-wb-p13-ex3-q4',
              type: 'multiple_choice',
              concept: 'repaso: comparativos',
              difficulty: 4,
              prompt: '¿Cómo es el piso nuevo comparado con el antiguo?',
              correctAnswer: 'más grande y más barato',
              options: ['más grande y más barato', 'más pequeño y más caro', 'más grande pero más caro'],
              explanation: 'El texto dice: "bigger than her old one, and it is also cheaper" (comparativos).',
            },
            {
              id: 'a2-wb-p13-ex3-q5',
              type: 'multiple_choice',
              concept: 'repaso: going to',
              difficulty: 4,
              prompt: '¿Qué va a hacer Marta el próximo fin de semana?',
              correctAnswer: 'visitar a sus padres',
              options: ['visitar a sus padres', 'mudarse de nuevo', 'viajar a Italia'],
              explanation: 'El texto dice: "Marta is going to visit her parents next weekend" (going to para planes).',
            },
            {
              id: 'a2-wb-p13-ex3-q6',
              type: 'multiple_choice',
              concept: 'repaso: condicional primero',
              difficulty: 4,
              prompt: 'Según Marta, ¿qué pasará si va a la clase de yoga?',
              correctAnswer: 'se sentirá como en casa',
              options: ['se sentirá como en casa', 'hará muchos amigos y no volverá', 'no le gustará la ciudad'],
              explanation: 'El texto dice: "if she goes to the class, she will feel at home soon" (condicional primero).',
            },
          ],
        },
        explanation:
          'El texto repasa el nivel A2: pasado continuo (was looking), voz pasiva (was built), Present Perfect (has lived for), comparativos (bigger, cheaper), going to (is going to visit) y el condicional primero (if she goes... she will feel).',
      },
      {
        id: 'a2-wb-p13-ex4',
        type: 'true_false',
        concept: 'repaso: modales',
        difficulty: 2,
        prompt: '"You mustn\'t smoke here. It means smoking is prohibited."',
        correctAnswer: 'true',
        acceptedAnswers: ['True', 'TRUE', 'Verdadero', 'true.'],
        explanation: 'Es VERDADERO. "Mustn\'t" expresa prohibición: no se puede fumar aquí.',
      },
      {
        id: 'a2-wb-p13-ex5',
        type: 'error_correction',
        concept: 'repaso: reflexivos',
        difficulty: 3,
        prompt: 'Corrige el error: "My sister and I enjoyed ourself at the concert."',
        correctAnswer: 'My sister and I enjoyed ourselves at the concert.',
        acceptedAnswers: [
          'My sister and I enjoyed ourselves at the concert',
          'My sister and I enjoyed ourselves at the concert.',
          'my sister and i enjoyed ourselves at the concert',
        ],
        acceptApproximate: true,
        explanation: 'Con "my sister and I" (nosotros) usamos "ourselves", no "ourself" (que no existe).',
      },
      {
        id: 'a2-wb-p13-ex6',
        type: 'translate',
        concept: 'repaso: estilo indirecto',
        difficulty: 4,
        prompt: 'Traduce: "Ella dijo que llegaría tarde."',
        correctAnswer: 'She said that she would be late.',
        acceptedAnswers: [
          'She said that she would be late',
          'She said that she would be late.',
          'she said that she would be late',
        ],
        acceptApproximate: true,
        explanation:
          '"Dijo que" = said that; "llegaría" (will → would en estilo indirecto) = would be late. → She said that she would be late.',
      },
    ],
  },
]