import type { WorkbookPage } from './types'

export const b1Workbook: WorkbookPage[] = [
  {
    id: 'b1-wb-1',
    levelId: 'b1',
    unit: 'Unit 1 · Second Conditional',
    page: 1,
    title: 'Second Conditional: hipótesis imaginarias',
    intro:
      'Practicamos if + past simple + would/could para hablar de situaciones imaginarias en el presente, y la estructura "If I were you" para dar consejos.',
    exercises: [
      {
        id: 'b1-wb-p1-ex1',
        type: 'multiple_choice',
        concept: 'second conditional: if + past simple',
        difficulty: 2,
        prompt: 'Completa: "If I ___ more money, I would buy a house."',
        promptTranslation: 'Si tuviera más dinero, compraría una casa.',
        correctAnswer: 'had',
        options: ['had', 'have', 'will have'],
        explanation:
          'En el segundo condicional, después de "if" usamos past simple (had), aunque hablemos de una situación imaginaria en el presente. → If I had more money, I would buy a house.',
      },
      {
        id: 'b1-wb-p1-ex2',
        type: 'fill_blank',
        concept: 'second conditional: if I were you',
        difficulty: 2,
        prompt: 'Completa con la forma correcta: "If I ___ (be) you, I wouldn\'t call her."',
        promptTranslation: 'Si yo fuera tú, no la llamaría.',
        correctAnswer: 'were',
        acceptedAnswers: ['were', 'was'],
        explanation:
          'Con I/he/she/it en una hipótesis usamos "were" (forma subjuntiva correcta): If I were you. "Was" se oye en conversación informal, pero "were" es lo recomendable.',
      },
      {
        id: 'b1-wb-p1-ex3',
        type: 'match',
        concept: 'second conditional: condition and result',
        difficulty: 2,
        prompt: 'Relaciona cada condición con su resultado hipotético.',
        pairs: [
          { left: 'If I were you,', right: 'I would apply for the job.' },
          { left: 'If she spoke English,', right: 'she could travel to London alone.' },
          { left: 'If we had a car,', right: 'we would drive to the coast.' },
          { left: 'If he knew the answer,', right: 'he would raise his hand.' },
          { left: 'If I won the lottery,', right: 'I would help my family.' },
        ],
        correctAnswer: 'match',
        explanation:
          'Cada condición (if + past simple) se une con un resultado en would/could + verbo base. El sujeto se mantiene coherente en ambas partes.',
      },
      {
        id: 'b1-wb-p1-ex4',
        type: 'error_correction',
        concept: 'second conditional: no would after if',
        difficulty: 3,
        prompt: 'Corrige el error: "If I would have a dog, I would walk it every day."',
        correctAnswer: 'If I had a dog, I would walk it every day.',
        acceptedAnswers: [
          'If I had a dog, I would walk it every day',
          'If I had a dog, I would walk it every day.',
          'If I had a dog, I\'d walk it every day',
          'If I had a dog, I\'d walk it every day.',
        ],
        acceptApproximate: true,
        explanation:
          'Después de "if" usamos past simple (had), nunca "would". El "would" solo aparece en la parte principal de la frase.',
      },
      {
        id: 'b1-wb-p1-ex5',
        type: 'translate',
        concept: 'second conditional: giving advice',
        difficulty: 3,
        prompt: 'Traduce: "Si yo fuera tú, hablaría con mi jefe."',
        correctAnswer: 'If I were you, I would talk to my boss.',
        acceptedAnswers: [
          'If I were you, I would talk to my boss',
          'If I were you, I would talk to my boss.',
          'If I were you, I\'d talk to my boss',
          'If I were you, I\'d talk to my boss.',
          'If I was you, I would talk to my boss',
          'If I was you, I would talk to my boss.',
        ],
        acceptApproximate: true,
        explanation:
          '"Si yo fuera tú" = If I were you. "hablaría" = I would talk (would + verbo base). "con mi jefe" = to my boss.',
      },
      {
        id: 'b1-wb-p1-ex6',
        type: 'true_false',
        concept: 'second conditional: meaning',
        difficulty: 2,
        prompt: '"If I were you, I wouldn\'t eat that." significa que la persona me recomienda comer eso.',
        correctAnswer: 'false',
        explanation:
          'Falso. "Wouldn\'t" es la forma negativa: el consejo es NO comer eso. La frase significa "Si yo fuera tú, no comería eso".',
      },
    ],
  },
  {
    id: 'b1-wb-2',
    levelId: 'b1',
    unit: 'Unit 2 · Past Perfect y tiempos narrativos',
    page: 2,
    title: 'Past Perfect y tiempos narrativos',
    intro:
      'Practicamos had + past participle para la acción más antigua de dos en el pasado y su uso en narraciones con before, after, by the time y when.',
    exercises: [
      {
        id: 'b1-wb-p2-ex1',
        type: 'multiple_choice',
        concept: 'past perfect: had + participle',
        difficulty: 2,
        prompt: 'Completa: "When I arrived, the film ___ already started."',
        promptTranslation: 'Cuando llegué, la película ya había empezado.',
        correctAnswer: 'had',
        options: ['had', 'has', 'have'],
        explanation:
          'La película empezó antes de mi llegada → la acción más antigua va en past perfect: had + participio (started).',
      },
      {
        id: 'b1-wb-p2-ex2',
        type: 'fill_blank',
        concept: 'past perfect: irregular participles',
        difficulty: 2,
        prompt: 'Completa con el past participle: "She had ___ (write) the email before lunch."',
        promptTranslation: 'Ella había escrito el correo antes del almuerzo.',
        correctAnswer: 'written',
        acceptedAnswers: ['written'],
        explanation:
          '"Write" es irregular: write → wrote → written. Con "had" usamos siempre el past participle: had written.',
      },
      {
        id: 'b1-wb-p2-ex3',
        type: 'reorder',
        concept: 'past perfect: by the time',
        difficulty: 3,
        prompt: 'Ordena las palabras para formar una frase:',
        promptTranslation: 'Para cuando llegué, ellos ya habían salido.',
        words: ['By', 'the', 'time', 'I', 'arrived,', 'they', 'had', 'already', 'left.'],
        correctAnswer: 'By the time I arrived, they had already left.',
        explanation:
          '"By the time" + past simple (arrived) + past perfect (had left): la acción más antigua es la de salir, por eso va en past perfect.',
      },
      {
        id: 'b1-wb-p2-ex4',
        type: 'reading',
        concept: 'reading: narrative with past perfect',
        difficulty: 4,
        prompt: 'Lee la historia de Ana y responde las preguntas.',
        correctAnswer: 'reading',
        explanation:
          'En la historia, el past perfect marca las acciones anteriores: had started, had played, had missed, had saved, had finished, had eaten. Las acciones más recientes van en past simple (went, arrived, found, got).',
        reading: {
          text: `Last Saturday, Ana went to a concert. When she arrived at the stadium, the show had already started and the band had played two songs. She was a little upset because she had missed the beginning, but she quickly found her friends, who had saved her a seat.

After the concert had finished, they went to a pizzeria. Ana had never eaten there before, so everything was new for her. By the time she got home, it was almost one o'clock in the morning.`,
          translation: `El sábado pasado, Ana fue a un concierto. Cuando llegó al estadio, el espectáculo ya había empezado y la banda había tocado dos canciones. Estaba un poco disgustada porque se había perdido el principio, pero rápidamente encontró a sus amigos, que le habían guardado un asiento.

Después de que terminó el concierto, fueron a una pizzería. Ana nunca había comido allí antes, así que todo era nuevo para ella. Para cuando llegó a casa, eran casi la una de la madrugada.`,
          questions: [
            {
              id: 'b1-wb-p2-ex4-q1',
              type: 'multiple_choice',
              concept: 'reading comprehension — past perfect',
              difficulty: 3,
              prompt: 'What had happened when Ana arrived at the stadium?',
              promptTranslation: '¿Qué había pasado cuando Ana llegó al estadio?',
              correctAnswer: 'The show had already started.',
              options: ['The show had already started.', 'The show had finished.', 'Her friends had left.'],
              explanation: 'El texto dice: "When she arrived at the stadium, the show had already started."',
            },
            {
              id: 'b1-wb-p2-ex4-q2',
              type: 'multiple_choice',
              concept: 'reading comprehension — past perfect',
              difficulty: 2,
              prompt: 'How many songs had the band played?',
              promptTranslation: '¿Cuántas canciones había tocado la banda?',
              correctAnswer: 'Two.',
              options: ['Two.', 'Three.', 'One.'],
              explanation: 'El texto dice: "the band had played two songs."',
            },
            {
              id: 'b1-wb-p2-ex4-q3',
              type: 'multiple_choice',
              concept: 'reading comprehension — reason',
              difficulty: 3,
              prompt: 'Why was Ana upset?',
              promptTranslation: '¿Por qué estaba Ana disgustada?',
              correctAnswer: 'She had missed the beginning.',
              options: ['She had missed the beginning.', 'She had lost her friends.', 'She didn\'t like the band.'],
              explanation: 'El texto dice: "She was a little upset because she had missed the beginning."',
            },
            {
              id: 'b1-wb-p2-ex4-q4',
              type: 'multiple_choice',
              concept: 'reading comprehension — past perfect',
              difficulty: 3,
              prompt: 'Had Ana eaten at the pizzeria before?',
              promptTranslation: '¿Había comido Ana antes en la pizzería?',
              correctAnswer: 'No, she had never eaten there.',
              options: ['No, she had never eaten there.', 'Yes, many times.', 'Only once.'],
              explanation: 'El texto dice: "Ana had never eaten there before, so everything was new for her."',
            },
          ],
        },
      },
      {
        id: 'b1-wb-p2-ex5',
        type: 'error_correction',
        concept: 'past perfect: participle vs past simple',
        difficulty: 3,
        prompt: 'Corrige el error: "I had saw that film twice before."',
        correctAnswer: 'I had seen that film twice before.',
        acceptedAnswers: ['I had seen that film twice before', 'I had seen that film twice before.'],
        acceptApproximate: true,
        explanation:
          'El past participle de "see" es "seen", no "saw". Con "had" siempre usamos el participle: had seen.',
      },
      {
        id: 'b1-wb-p2-ex6',
        type: 'true_false',
        concept: 'past perfect: sequence of events',
        difficulty: 2,
        prompt: 'En "After she had left, we talked", la acción de hablar ocurrió antes que la de irse.',
        correctAnswer: 'false',
        explanation:
          'Falso. El past perfect (had left) es la acción más antigua: primero se fue ella y después hablamos nosotros.',
      },
    ],
  },
  {
    id: 'b1-wb-3',
    levelId: 'b1',
    unit: 'Unit 3 · Present Perfect Continuous',
    page: 3,
    title: 'Present Perfect Continuous',
    intro:
      'Practicamos have/has + been + verbo -ing para acciones que empezaron en el pasado y continúan, y para acciones recientes con efecto visible, con for y since.',
    exercises: [
      {
        id: 'b1-wb-p3-ex1',
        type: 'multiple_choice',
        concept: 'present perfect continuous: form',
        difficulty: 1,
        prompt: 'Completa: "I have ___ working here for five years."',
        promptTranslation: 'Llevo cinco años trabajando aquí.',
        correctAnswer: 'been',
        options: ['been', 'being', 'be'],
        explanation:
          'La estructura es have + been + verbo -ing: I have been working here for five years. Nunca "have being".',
      },
      {
        id: 'b1-wb-p3-ex2',
        type: 'fill_blank',
        concept: 'present perfect continuous: -ing spelling',
        difficulty: 2,
        prompt: 'Completa con el verbo en -ing: "She has been ___ (swim) all morning."',
        promptTranslation: 'Ella ha estado nadando toda la mañana.',
        correctAnswer: 'swimming',
        acceptedAnswers: ['swimming'],
        explanation:
          'Después de "been" el verbo lleva -ing. "Swim" termina en consonante + vocal + consonante, así que doblamos la -m: swimming.',
      },
      {
        id: 'b1-wb-p3-ex3',
        type: 'select_correct',
        concept: 'present perfect continuous: question',
        difficulty: 3,
        prompt: 'Elige la pregunta correcta en present perfect continuous:',
        promptTranslation: '¿Has estado durmiendo bien últimamente?',
        correctAnswer: 'Have you been sleeping well lately?',
        options: [
          'Have you been sleeping well lately?',
          'Have you been sleep well lately?',
          'Have you being sleeping well lately?',
        ],
        explanation:
          'La pregunta se forma con Have + sujeto + been + verbo -ing (sleeping). "Been sleep" y "being sleeping" son incorrectos.',
      },
      {
        id: 'b1-wb-p3-ex4',
        type: 'translate',
        concept: 'present perfect continuous: since',
        difficulty: 3,
        prompt: 'Traduce: "He estado esperando el autobús desde las ocho."',
        correctAnswer: 'I have been waiting for the bus since eight o\'clock.',
        acceptedAnswers: [
          'I have been waiting for the bus since eight o\'clock',
          'I have been waiting for the bus since eight o\'clock.',
          'I\'ve been waiting for the bus since eight o\'clock',
          'I\'ve been waiting for the bus since eight o\'clock.',
        ],
        acceptApproximate: true,
        explanation:
          '"He estado esperando" = I have been waiting. "desde las ocho" = since eight o\'clock (since + punto de inicio).',
      },
      {
        id: 'b1-wb-p3-ex5',
        type: 'error_correction',
        concept: 'present perfect continuous: been vs being',
        difficulty: 4,
        prompt: 'Corrige el error: "My hands are dirty because I have being working in the garden."',
        correctAnswer: 'My hands are dirty because I have been working in the garden.',
        acceptedAnswers: [
          'My hands are dirty because I have been working in the garden',
          'My hands are dirty because I have been working in the garden.',
        ],
        acceptApproximate: true,
        explanation:
          'La estructura es have + been + -ing, nunca "have being". El efecto visible (manos sucias) se explica con present perfect continuous.',
      },
      {
        id: 'b1-wb-p3-ex6',
        type: 'true_false',
        concept: 'present perfect continuous: for vs since',
        difficulty: 2,
        prompt: '"It has been raining since three hours" es una frase correcta.',
        correctAnswer: 'false',
        explanation:
          'Falso. Con una duración (three hours) usamos "for": for three hours. "Since" va con un punto de inicio: since three o\'clock.',
      },
    ],
  },
  {
    id: 'b1-wb-4',
    levelId: 'b1',
    unit: 'Unit 4 · Modals of deduction',
    page: 4,
    title: 'Modals of deduction',
    intro:
      'Practicamos must, can\'t, may y might para deducir y especular en presente (must be, can\'t be) y en pasado (must have, can\'t have).',
    exercises: [
      {
        id: 'b1-wb-p4-ex1',
        type: 'multiple_choice',
        concept: 'modals of deduction: present',
        difficulty: 2,
        prompt: 'Completa: "The lights are on, so Tom ___ be at home."',
        promptTranslation: 'Las luces están encendidas, así que Tom debe de estar en casa.',
        correctAnswer: 'must',
        options: ['must', "can't", 'might not'],
        explanation:
          '"Must" expresa una deducción lógica con mucha seguridad: si las luces están encendidas, Tom debe de estar en casa.',
      },
      {
        id: 'b1-wb-p4-ex2',
        type: 'fill_blank',
        concept: 'modals of deduction: can\'t',
        difficulty: 2,
        prompt: 'Completa: "She can\'t ___ (be) at work; today is Sunday."',
        promptTranslation: 'Ella no puede estar en el trabajo; hoy es domingo.',
        correctAnswer: 'be',
        acceptedAnswers: ['be'],
        explanation:
          'Después de un modal usamos la forma base: can\'t be. Es una deducción negativa segura: es imposible que esté en el trabajo.',
      },
      {
        id: 'b1-wb-p4-ex3',
        type: 'match',
        concept: 'modals of deduction: degree of certainty',
        difficulty: 3,
        prompt: 'Relaciona cada modal con el grado de certeza que expresa.',
        pairs: [
          { left: 'must be', right: 'deducción muy segura (casi seguro)' },
          { left: 'can\'t be', right: 'deducción negativa segura (imposible)' },
          { left: 'may be', right: 'posibilidad (quizá, podría ser)' },
          { left: 'might be', right: 'posibilidad menos segura (tal vez)' },
          { left: 'could be', right: 'posibilidad (puede ser)' },
        ],
        correctAnswer: 'match',
        explanation:
          'must = certeza casi total; can\'t = certeza de que NO es; may/might/could = posibilidad con distintos grados de seguridad.',
      },
      {
        id: 'b1-wb-p4-ex4',
        type: 'select_correct',
        concept: 'modals of deduction: past',
        difficulty: 4,
        prompt: 'Elige la frase correcta para deducir sobre el pasado:',
        promptTranslation: 'Debe de haber perdido el tren.',
        correctAnswer: 'He must have missed the train.',
        options: ['He must have missed the train.', 'He must has missed the train.', 'He must missed the train.'],
        explanation:
          'Para deducir sobre el pasado usamos modal + have + participio: must have missed. "Must has" y "must missed" son incorrectos.',
      },
      {
        id: 'b1-wb-p4-ex5',
        type: 'error_correction',
        concept: 'modals of deduction: past',
        difficulty: 4,
        prompt: 'Corrige el error: "She can\'t has forgotten your birthday."',
        correctAnswer: "She can't have forgotten your birthday.",
        acceptedAnswers: ["She can't have forgotten your birthday", "She can't have forgotten your birthday."],
        acceptApproximate: true,
        explanation:
          'Tras un modal en deducción pasada usamos "have" + participio: can\'t have forgotten. Nunca "can\'t has".',
      },
      {
        id: 'b1-wb-p4-ex6',
        type: 'true_false',
        concept: 'modals of deduction: must have vs had to',
        difficulty: 3,
        prompt: '"He must have worked late" significa que estaba obligado a trabajar hasta tarde.',
        correctAnswer: 'false',
        explanation:
          'Falso. "Must have worked" es una deducción (seguro que trabajó hasta tarde). La obligación pasada se expresa con "had to work late".',
      },
    ],
  },
  {
    id: 'b1-wb-5',
    levelId: 'b1',
    unit: 'Unit 5 · Futuro: Future Perfect & Continuous + grados de certeza',
    page: 5,
    title: 'Future Perfect, Future Continuous y grados de certeza',
    intro:
      'Practicamos will have + participio (future perfect), will be + -ing (future continuous) y los adverbios de certeza (definitely, probably, might).',
    exercises: [
      {
        id: 'b1-wb-p5-ex1',
        type: 'multiple_choice',
        concept: 'future perfect: form',
        difficulty: 2,
        prompt: 'Completa: "By 2030, I will ___ finished university."',
        promptTranslation: 'Para 2030, habré terminado la universidad.',
        correctAnswer: 'have',
        options: ['have', 'has', 'had'],
        explanation:
          'El future perfect se forma con will + have + participio: will have finished. Habla de una acción completada antes de un momento futuro.',
      },
      {
        id: 'b1-wb-p5-ex2',
        type: 'fill_blank',
        concept: 'future continuous: form',
        difficulty: 2,
        prompt: 'Completa: "This time tomorrow, I will be ___ (fly) to Rome."',
        promptTranslation: 'Mañana a esta hora, estaré volando a Roma.',
        correctAnswer: 'flying',
        acceptedAnswers: ['flying'],
        explanation:
          'El future continuous se forma con will be + verbo -ing: will be flying. Describe una acción en curso en un momento futuro.',
      },
      {
        id: 'b1-wb-p5-ex3',
        type: 'reorder',
        concept: 'future continuous: word order',
        difficulty: 3,
        prompt: 'Ordena las palabras para formar una frase:',
        promptTranslation: 'A esta hora la semana que viene, estaremos haciendo un examen.',
        words: ['This', 'time', 'next', 'week,', 'we', 'will', 'be', 'taking', 'an', 'exam.'],
        correctAnswer: 'This time next week, we will be taking an exam.',
        explanation:
          'Estructura: this time + tiempo + will be + verbo -ing. → This time next week, we will be taking an exam.',
      },
      {
        id: 'b1-wb-p5-ex4',
        type: 'translate',
        concept: 'future perfect: translate',
        difficulty: 3,
        prompt: 'Traduce: "Para las nueve, habré terminado la cena."',
        correctAnswer: 'By nine o\'clock, I will have finished dinner.',
        acceptedAnswers: [
          'By nine o\'clock, I will have finished dinner',
          'By nine o\'clock, I will have finished dinner.',
          'By 9 o\'clock, I will have finished dinner',
          'By 9 o\'clock, I will have finished dinner.',
          'By nine, I\'ll have finished dinner',
          'By nine, I\'ll have finished dinner.',
        ],
        acceptApproximate: true,
        explanation:
          '"Para las nueve" = by nine o\'clock. "habré terminado" = I will have finished (future perfect: will + have + participio).',
      },
      {
        id: 'b1-wb-p5-ex5',
        type: 'select_correct',
        concept: 'degrees of certainty',
        difficulty: 3,
        prompt: 'Elige la frase que expresa más certeza sobre el futuro:',
        correctAnswer: 'It will definitely rain tomorrow.',
        options: ['It will definitely rain tomorrow.', 'It might rain tomorrow.', 'It could rain tomorrow.'],
        explanation:
          '"Definitely" (sin duda) expresa el grado más alto de certeza. "Might" y "could" expresan posibilidad, con mucha menos seguridad.',
      },
      {
        id: 'b1-wb-p5-ex6',
        type: 'true_false',
        concept: 'future perfect vs future continuous',
        difficulty: 3,
        prompt:
          '"I will be working at 8 p.m." habla de una acción en progreso a las 8 de la tarde, mientras que "I will have finished by 8 p.m." habla de una acción ya terminada a esa hora.',
        correctAnswer: 'true',
        explanation:
          'Correcto. El future continuous describe una acción en curso en un momento del futuro; el future perfect describe una acción completada antes de ese momento.',
      },
    ],
  },
  {
    id: 'b1-wb-6',
    levelId: 'b1',
    unit: 'Unit 6 · Pasiva extendida',
    page: 6,
    title: 'Pasiva extendida: presente, pasado y futuro',
    intro:
      'Practicamos la voz pasiva en varios tiempos (is/are, was/were, will be + participio) y con modales, para dar importancia a la acción y no a quien la realiza.',
    exercises: [
      {
        id: 'b1-wb-p6-ex1',
        type: 'multiple_choice',
        concept: 'passive: present',
        difficulty: 1,
        prompt: 'Completa: "English ___ spoken in many countries."',
        promptTranslation: 'El inglés se habla en muchos países.',
        correctAnswer: 'is',
        options: ['is', 'are', 'was'],
        explanation:
          '"English" es singular y hablamos de un hecho general en presente → is + participio: is spoken.',
      },
      {
        id: 'b1-wb-p6-ex2',
        type: 'fill_blank',
        concept: 'passive: past',
        difficulty: 2,
        prompt: 'Completa: "The pyramids ___ built thousands of years ago."',
        promptTranslation: 'Las pirámides se construyeron hace miles de años.',
        correctAnswer: 'were',
        acceptedAnswers: ['were'],
        explanation:
          '"The pyramids" es plural y es pasado → were + participio (built): The pyramids were built thousands of years ago.',
      },
      {
        id: 'b1-wb-p6-ex3',
        type: 'reorder',
        concept: 'passive: future',
        difficulty: 3,
        prompt: 'Ordena las palabras para formar una frase en pasiva:',
        promptTranslation: 'El nuevo hospital se inaugurará el año que viene.',
        words: ['The', 'new', 'hospital', 'will', 'be', 'opened', 'next', 'year.'],
        correctAnswer: 'The new hospital will be opened next year.',
        explanation:
          'Pasiva en futuro: will be + participio (opened). → The new hospital will be opened next year.',
      },
      {
        id: 'b1-wb-p6-ex4',
        type: 'match',
        concept: 'passive: active to passive',
        difficulty: 3,
        prompt: 'Relaciona cada frase activa con su versión en pasiva.',
        pairs: [
          { left: 'People grow rice in China.', right: 'Rice is grown in China.' },
          { left: 'Someone stole my bike.', right: 'My bike was stolen.' },
          { left: 'They will build a new bridge.', right: 'A new bridge will be built.' },
          { left: 'We clean the office every day.', right: 'The office is cleaned every day.' },
          { left: 'Someone has broken the window.', right: 'The window has been broken.' },
        ],
        correctAnswer: 'match',
        explanation:
          'En la pasiva, el objeto de la activa pasa a ser el sujeto: is/are + participio (presente), was/were + participio (pasado), will be + participio (futuro), have/has been + participio (present perfect).',
      },
      {
        id: 'b1-wb-p6-ex5',
        type: 'error_correction',
        concept: 'passive: participle',
        difficulty: 3,
        prompt: 'Corrige el error: "This film was make in 2015."',
        correctAnswer: 'This film was made in 2015.',
        acceptedAnswers: ['This film was made in 2015', 'This film was made in 2015.'],
        acceptApproximate: true,
        explanation: 'En la pasiva usamos el participio (made), no la forma base (make). → This film was made in 2015.',
      },
      {
        id: 'b1-wb-p6-ex6',
        type: 'translate',
        concept: 'passive: with a modal',
        difficulty: 4,
        prompt: 'Traduce: "Este problema debe resolverse pronto."',
        correctAnswer: 'This problem must be solved soon.',
        acceptedAnswers: [
          'This problem must be solved soon',
          'This problem must be solved soon.',
          'This problem has to be solved soon',
          'This problem has to be solved soon.',
        ],
        acceptApproximate: true,
        explanation:
          'Pasiva con modal: modal + be + participio. "debe resolverse" = must be solved (o has to be solved). "pronto" = soon.',
      },
    ],
  },
  {
    id: 'b1-wb-7',
    levelId: 'b1',
    unit: 'Unit 7 · Estilo indirecto',
    page: 7,
    title: 'Estilo indirecto: statements, questions y commands',
    intro:
      'Practicamos cómo contar lo que alguien dijo: cambios de tiempos y pronombres, preguntas reportadas y órdenes con tell + to.',
    exercises: [
      {
        id: 'b1-wb-p7-ex1',
        type: 'multiple_choice',
        concept: 'reported speech: say vs tell',
        difficulty: 2,
        prompt: 'Completa: "She ___ me that she was tired."',
        promptTranslation: 'Ella me dijo que estaba cansada.',
        correctAnswer: 'told',
        options: ['told', 'said', 'telled'],
        explanation:
          'Usamos "tell + persona": told me. Con "said" no ponemos la persona directamente después: She said (that) she was tired.',
      },
      {
        id: 'b1-wb-p7-ex2',
        type: 'fill_blank',
        concept: 'reported speech: backshift',
        difficulty: 3,
        prompt: 'Completa el estilo indirecto: "I am happy", dijo Luis. → Luis said that he ___ happy.',
        promptTranslation: 'Luis dijo que estaba feliz.',
        correctAnswer: 'was',
        acceptedAnswers: ['was'],
        explanation:
          'En estilo indirecto retrocedemos el tiempo: "I am" → he was. Los pronombres también cambian: I → he.',
      },
      {
        id: 'b1-wb-p7-ex3',
        type: 'reorder',
        concept: 'reported speech: structure',
        difficulty: 3,
        prompt: 'Ordena las palabras para formar una frase en estilo indirecto:',
        promptTranslation: 'Él dijo que iba a venir a la fiesta.',
        words: ['He', 'said', 'that', 'he', 'was', 'going', 'to', 'come', 'to', 'the', 'party.'],
        correctAnswer: 'He said that he was going to come to the party.',
        explanation:
          'Estructura: sujeto + said + that + sujeto + verbo en pasado. "I am going" reportado → he was going.',
      },
      {
        id: 'b1-wb-p7-ex4',
        type: 'select_correct',
        concept: 'reported questions',
        difficulty: 4,
        prompt: 'Elige la pregunta reportada correcta:',
        promptTranslation: 'Ella me preguntó dónde trabajaba.',
        correctAnswer: 'She asked me where I worked.',
        options: ['She asked me where I worked.', 'She asked me where did I work.', 'She asked me where I work.'],
        explanation:
          'Las preguntas reportadas no invierten sujeto y verbo, y el tiempo retrocede: "Where do you work?" → She asked me where I worked.',
      },
      {
        id: 'b1-wb-p7-ex5',
        type: 'error_correction',
        concept: 'reported commands',
        difficulty: 4,
        prompt: 'Corrige el error: "She told me to not be late."',
        correctAnswer: 'She told me not to be late.',
        acceptedAnswers: ['She told me not to be late', 'She told me not to be late.'],
        acceptApproximate: true,
        explanation:
          'Las órdenes reportadas usan tell + persona + (not) to + verbo: not to be late, no "to not be late".',
      },
      {
        id: 'b1-wb-p7-ex6',
        type: 'translate',
        concept: 'reported speech: translate',
        difficulty: 4,
        prompt: 'Traduce: "Me dijo que me llamaría más tarde."',
        correctAnswer: 'She told me she would call me later.',
        acceptedAnswers: [
          'She told me she would call me later',
          'She told me she would call me later.',
          'He told me he would call me later',
          'He told me he would call me later.',
        ],
        acceptApproximate: true,
        explanation:
          '"Me dijo" = told me. "que me llamaría" = that she would call me (will → would en estilo indirecto). "más tarde" = later.',
      },
    ],
  },
  {
    id: 'b1-wb-8',
    levelId: 'b1',
    unit: 'Unit 8 · Relativas extendidas',
    page: 8,
    title: 'Relativas extendidas: whose, where, when, why, whom',
    intro:
      'Practicamos los pronombres relativos avanzados: whose (posesión), where (lugar), when (tiempo), why (razón) y whom (persona, formal).',
    exercises: [
      {
        id: 'b1-wb-p8-ex1',
        type: 'multiple_choice',
        concept: 'relative clauses: whose',
        difficulty: 2,
        prompt: 'Completa: "That\'s the man ___ car was stolen."',
        promptTranslation: 'Ese es el hombre cuyo coche fue robado.',
        correctAnswer: 'whose',
        options: ['whose', "who's", 'which'],
        explanation:
          '"Whose" expresa posesión (cuyo/a): the man whose car = el hombre cuyo coche. Cuidado: who\'s = who is.',
      },
      {
        id: 'b1-wb-p8-ex2',
        type: 'fill_blank',
        concept: 'relative clauses: where',
        difficulty: 2,
        prompt: 'Completa: "This is the town ___ I grew up."',
        promptTranslation: 'Esta es la ciudad donde crecí.',
        correctAnswer: 'where',
        acceptedAnswers: ['where'],
        explanation: '"Where" se usa para lugares: the town where I grew up = la ciudad donde crecí.',
      },
      {
        id: 'b1-wb-p8-ex3',
        type: 'match',
        concept: 'relative pronouns: use',
        difficulty: 3,
        prompt: 'Relaciona cada pronombre relativo con su uso.',
        pairs: [
          { left: 'who', right: 'personas (sujeto)' },
          { left: 'whom', right: 'personas (objeto, formal)' },
          { left: 'whose', right: 'posesión (cuyo/a)' },
          { left: 'where', right: 'lugares' },
          { left: 'when', right: 'tiempo' },
          { left: 'why', right: 'razón o motivo' },
        ],
        correctAnswer: 'match',
        explanation:
          'who = personas; whom = personas como objeto (más formal); whose = posesión; where = lugares; when = tiempo; why = razón.',
      },
      {
        id: 'b1-wb-p8-ex4',
        type: 'reorder',
        concept: 'non-defining relative clauses',
        difficulty: 3,
        prompt: 'Ordena las palabras para formar una frase con relativa explicativa:',
        promptTranslation: 'Mi hermana, que vive en París, viene a visitarnos.',
        words: ['My', 'sister,', 'who', 'lives', 'in', 'Paris,', 'is', 'coming', 'to', 'visit', 'us.'],
        correctAnswer: 'My sister, who lives in Paris, is coming to visit us.',
        explanation:
          'La relativa explicativa (no definitoria) va entre comas y añade información extra: My sister, who lives in Paris, is coming to visit us.',
      },
      {
        id: 'b1-wb-p8-ex5',
        type: 'error_correction',
        concept: 'relative clauses: who vs which',
        difficulty: 3,
        prompt: 'Corrige el error: "The teacher which explained the lesson is very patient."',
        correctAnswer: 'The teacher who explained the lesson is very patient.',
        acceptedAnswers: [
          'The teacher who explained the lesson is very patient',
          'The teacher who explained the lesson is very patient.',
        ],
        acceptApproximate: true,
        explanation:
          'Para personas usamos "who", no "which": The teacher who explained the lesson is very patient.',
      },
      {
        id: 'b1-wb-p8-ex6',
        type: 'translate',
        concept: 'relative clauses: the reason why',
        difficulty: 4,
        prompt: 'Traduce: "No entiendo la razón por la que se fue."',
        correctAnswer: 'I don\'t understand the reason why she left.',
        acceptedAnswers: [
          'I don\'t understand the reason why she left',
          'I don\'t understand the reason why she left.',
          'I don\'t understand the reason why he left',
          'I don\'t understand the reason why he left.',
        ],
        acceptApproximate: true,
        explanation:
          '"la razón por la que" = the reason why. "se fue" = she/he left. → I don\'t understand the reason why she left.',
      },
    ],
  },
  {
    id: 'b1-wb-9',
    levelId: 'b1',
    unit: 'Unit 9 · Third Conditional y deseos (wish / if only)',
    page: 9,
    title: 'Third Conditional y deseos: wish / if only',
    intro:
      'Practicamos el tercer condicional (if + had + participio, would have + participio) para hipótesis pasadas y los deseos con wish e if only.',
    exercises: [
      {
        id: 'b1-wb-p9-ex1',
        type: 'multiple_choice',
        concept: 'third conditional: result',
        difficulty: 3,
        prompt: 'Completa: "If I had studied more, I ___ have passed."',
        promptTranslation: 'Si hubiera estudiado más, habría aprobado.',
        correctAnswer: 'would',
        options: ['would', 'will', 'did'],
        explanation:
          'En el resultado del tercer condicional usamos would have + participio: I would have passed.',
      },
      {
        id: 'b1-wb-p9-ex2',
        type: 'fill_blank',
        concept: 'third conditional: had + participle',
        difficulty: 3,
        prompt: 'Completa con la forma correcta: "If they had ___ (leave) earlier, they would have arrived on time."',
        promptTranslation: 'Si hubieran salido antes, habrían llegado a tiempo.',
        correctAnswer: 'left',
        acceptedAnswers: ['left'],
        explanation:
          'En la condición usamos had + participio. "Leave" es irregular: leave → left → left. → had left.',
      },
      {
        id: 'b1-wb-p9-ex3',
        type: 'select_correct',
        concept: 'wish + past simple',
        difficulty: 3,
        prompt: 'Elige la frase correcta para expresar un deseo sobre el presente:',
        promptTranslation: 'Ojalá hablara inglés mejor.',
        correctAnswer: 'I wish I spoke English better.',
        options: ['I wish I spoke English better.', 'I wish I speak English better.', 'I wish I will speak English better.'],
        explanation:
          'Tras "wish" para deseos presentes usamos past simple: I wish I spoke English better. Hablamos de algo que no es real ahora.',
      },
      {
        id: 'b1-wb-p9-ex4',
        type: 'reorder',
        concept: 'if only + past perfect',
        difficulty: 4,
        prompt: 'Ordena las palabras para formar una frase con "if only":',
        promptTranslation: 'Ojalá no hubiera dicho eso.',
        words: ['If', 'only', 'I', 'hadn\'t', 'said', 'that.'],
        correctAnswer: "If only I hadn't said that.",
        explanation:
          'If only + past perfect (hadn\'t said) expresa un deseo o arrepentimiento sobre el pasado. → If only I hadn\'t said that.',
      },
      {
        id: 'b1-wb-p9-ex5',
        type: 'error_correction',
        concept: 'third conditional: no would after if',
        difficulty: 4,
        prompt: 'Corrige el error: "If I would have known, I would have come."',
        correctAnswer: 'If I had known, I would have come.',
        acceptedAnswers: ['If I had known, I would have come', 'If I had known, I would have come.'],
        acceptApproximate: true,
        explanation:
          'En la parte de "if" nunca usamos "would": if I had known. El "would have" solo va en la parte del resultado.',
      },
      {
        id: 'b1-wb-p9-ex6',
        type: 'translate',
        concept: 'wish + past perfect (regret)',
        difficulty: 4,
        prompt: 'Traduce: "Ojalá hubiera estudiado más para el examen."',
        correctAnswer: 'I wish I had studied more for the exam.',
        acceptedAnswers: [
          'I wish I had studied more for the exam',
          'I wish I had studied more for the exam.',
          'I wish I\'d studied more for the exam',
          'I wish I\'d studied more for the exam.',
        ],
        acceptApproximate: true,
        explanation:
          '"Ojalá hubiera estudiado" = I wish I had studied (wish + past perfect para deseos pasados). "más" = more. "para el examen" = for the exam.',
      },
    ],
  },
  {
    id: 'b1-wb-10',
    levelId: 'b1',
    unit: 'Unit 10 · Gerundios vs infinitivos',
    page: 10,
    title: 'Gerundios vs infinitivos',
    intro:
      'Practicamos verbos que van seguidos de gerundio (-ing) y verbos que van seguidos de infinitivo (to + verbo), incluyendo los que cambian de significado.',
    exercises: [
      {
        id: 'b1-wb-p10-ex1',
        type: 'multiple_choice',
        concept: 'verb + gerund',
        difficulty: 1,
        prompt: 'Completa: "I enjoy ___ new places."',
        promptTranslation: 'Disfruto visitando lugares nuevos.',
        correctAnswer: 'visiting',
        options: ['visiting', 'to visit', 'visit'],
        explanation: 'El verbo "enjoy" va seguido de gerundio: enjoy + -ing. → I enjoy visiting new places.',
      },
      {
        id: 'b1-wb-p10-ex2',
        type: 'fill_blank',
        concept: 'verb + infinitive',
        difficulty: 2,
        prompt: 'Completa con la forma correcta: "She decided ___ (start) a new course."',
        promptTranslation: 'Ella decidió empezar un curso nuevo.',
        correctAnswer: 'to start',
        acceptedAnswers: ['to start'],
        explanation: 'El verbo "decide" va seguido de infinitivo: decide + to + verbo. → She decided to start a new course.',
      },
      {
        id: 'b1-wb-p10-ex3',
        type: 'match',
        concept: 'verbs + -ing or + to',
        difficulty: 3,
        prompt: 'Relaciona cada verbo con la forma que le sigue.',
        pairs: [
          { left: 'enjoy', right: '-ing (gerundio)' },
          { left: 'want', right: 'to + verbo (infinitivo)' },
          { left: 'finish', right: '-ing (gerundio)' },
          { left: 'promise', right: 'to + verbo (infinitivo)' },
          { left: 'suggest', right: '-ing (gerundio)' },
          { left: 'hope', right: 'to + verbo (infinitivo)' },
        ],
        correctAnswer: 'match',
        explanation:
          'Con -ing: enjoy, finish, suggest, mind, avoid. Con infinitivo: want, decide, promise, hope, learn. Hay que memorizarlos.',
      },
      {
        id: 'b1-wb-p10-ex4',
        type: 'select_correct',
        concept: 'stop + -ing vs stop + to',
        difficulty: 4,
        prompt: 'Elige la frase correcta para decir que dejó de fumar:',
        correctAnswer: 'He stopped smoking last year.',
        options: ['He stopped smoking last year.', 'He stopped to smoke last year.', 'He stop smoking last year.'],
        explanation:
          '"Stop + -ing" = dejar de hacer algo (dejó de fumar). "Stop + to + verbo" = parar para hacer otra cosa. Aquí el sentido es dejar de fumar: stopped smoking.',
      },
      {
        id: 'b1-wb-p10-ex5',
        type: 'error_correction',
        concept: 'suggest + gerund',
        difficulty: 3,
        prompt: 'Corrige el error: "I suggest to go by train."',
        correctAnswer: 'I suggest going by train.',
        acceptedAnswers: ['I suggest going by train', 'I suggest going by train.'],
        acceptApproximate: true,
        explanation: 'El verbo "suggest" va seguido de gerundio: suggest + -ing. → I suggest going by train.',
      },
      {
        id: 'b1-wb-p10-ex6',
        type: 'writing',
        concept: 'writing: hobbies with -ing and to',
        difficulty: 4,
        prompt:
          'Escribe una historia breve en inglés sobre una afición o actividad que disfrutas. Usa al menos dos verbos + -ing (enjoy, love, finish, suggest...) y dos verbos + infinitivo (want, decide, hope, plan...).',
        correctAnswer:
          'I really enjoy playing football with my friends. We usually finish practicing at eight, and then I decide to have a pizza. I also hope to learn the guitar one day, and I want to take classes next year.',
        taskType: 'story',
        targetReader: 'your teacher',
        register: 'neutral',
        contentPoints: ['Al menos dos verbos + -ing', 'Al menos dos verbos + infinitivo'],
        requiresOwnIdea: true,
        minWords: 50,
        maxWords: 90,
        explanation:
          'Una buena historia usa verbos + -ing (enjoy playing, finish practicing) y verbos + infinitivo (decide to have, hope to learn, want to take), y mantiene un relato coherente en presente simple.',
      },
    ],
  },
  {
    id: 'b1-wb-11',
    levelId: 'b1',
    unit: 'Unit 11 · Conectores',
    page: 11,
    title: 'Conectores: although, however, so/because/because of, so/such/too/enough',
    intro:
      'Practicamos los conectores para unir ideas: contraste (although, however), causa y consecuencia (so, because, because of) e intensificadores (so, such, too, enough).',
    exercises: [
      {
        id: 'b1-wb-p11-ex1',
        type: 'multiple_choice',
        concept: 'although / even though',
        difficulty: 2,
        prompt: 'Completa: "___ it was raining, we went for a walk."',
        promptTranslation: 'Aunque llovía, fuimos a dar un paseo.',
        correctAnswer: 'Although',
        options: ['Although', 'Because', 'So'],
        explanation:
          '"Although" introduce un contraste (aunque): aunque llovía, fuimos a caminar. "Because" sería causa y "so" consecuencia.',
      },
      {
        id: 'b1-wb-p11-ex2',
        type: 'fill_blank',
        concept: 'however',
        difficulty: 3,
        prompt: 'Completa: "The hotel was expensive. ___, the room was beautiful."',
        promptTranslation: 'El hotel era caro. Sin embargo, la habitación era preciosa.',
        correctAnswer: 'However',
        acceptedAnswers: ['However', 'however'],
        explanation:
          '"However" (sin embargo) introduce un contraste entre dos frases y va seguido de coma al inicio de la segunda.',
      },
      {
        id: 'b1-wb-p11-ex3',
        type: 'match',
        concept: 'connectors: meaning',
        difficulty: 2,
        prompt: 'Relaciona cada conector con su significado.',
        pairs: [
          { left: 'although', right: 'aunque' },
          { left: 'however', right: 'sin embargo' },
          { left: 'because', right: 'porque' },
          { left: 'so', right: 'así que' },
          { left: 'because of', right: 'debido a' },
          { left: 'too', right: 'demasiado' },
        ],
        correctAnswer: 'match',
        explanation:
          'although = aunque; however = sin embargo; because = porque; so = así que; because of = debido a; too = demasiado.',
      },
      {
        id: 'b1-wb-p11-ex4',
        type: 'select_correct',
        concept: 'so / such / too / enough',
        difficulty: 4,
        prompt: 'Elige la frase correcta:',
        promptTranslation: 'La película era tan aburrida que me dormí.',
        correctAnswer: 'The film was so boring that I fell asleep.',
        options: [
          'The film was so boring that I fell asleep.',
          'The film was such boring that I fell asleep.',
          'The film was too boring that I fell asleep.',
        ],
        explanation:
          '"So + adjetivo + that" expresa consecuencia: tan aburrida que... "Such" se usa con sustantivos (such a boring film) y "too" no va seguido de "that + resultado".',
      },
      {
        id: 'b1-wb-p11-ex5',
        type: 'reorder',
        concept: 'because of',
        difficulty: 3,
        prompt: 'Ordena las palabras para formar una frase:',
        promptTranslation: 'El partido se canceló debido a la lluvia.',
        words: ['The', 'match', 'was', 'cancelled', 'because', 'of', 'the', 'rain.'],
        correctAnswer: 'The match was cancelled because of the rain.',
        explanation:
          '"Because of" va seguido de un sustantivo (the rain), a diferencia de "because" que va seguido de una oración.',
      },
      {
        id: 'b1-wb-p11-ex6',
        type: 'true_false',
        concept: 'connectors: too vs enough',
        difficulty: 3,
        prompt: '"The coffee is too hot to drink" significa que el café está lo suficientemente caliente para beber.',
        correctAnswer: 'false',
        explanation:
          'Falso. "Too hot" = demasiado caliente (más de lo necesario), así que no se puede beber. Para decir "lo suficientemente" usaríamos "hot enough".',
      },
    ],
  },
  {
    id: 'b1-wb-12',
    levelId: 'b1',
    unit: 'Unit 12 · used to / would + tag questions',
    page: 12,
    title: 'used to / would y tag questions',
    intro:
      'Practicamos used to y would para hábitos y estados pasados, y las tag questions (preguntas de confirmación al final de la frase).',
    exercises: [
      {
        id: 'b1-wb-p12-ex1',
        type: 'multiple_choice',
        concept: 'used to: past habits',
        difficulty: 2,
        prompt: 'Completa: "I ___ play the piano when I was a child."',
        promptTranslation: 'Tocaba el piano cuando era niño.',
        correctAnswer: 'used to',
        options: ['used to', 'use to', 'am used to'],
        explanation:
          '"Used to + verbo base" describe un hábito o estado del pasado que ya no existe: I used to play the piano.',
      },
      {
        id: 'b1-wb-p12-ex2',
        type: 'fill_blank',
        concept: 'used to: negative',
        difficulty: 3,
        prompt: 'Completa: "She didn\'t ___ like coffee, but now she loves it."',
        promptTranslation: 'Antes no le gustaba el café, pero ahora le encanta.',
        correctAnswer: 'use',
        acceptedAnswers: ['use'],
        explanation:
          'En negativo con "didn\'t" usamos la forma base: didn\'t use to. Nunca "didn\'t used to".',
      },
      {
        id: 'b1-wb-p12-ex3',
        type: 'reorder',
        concept: 'used to: word order',
        difficulty: 3,
        prompt: 'Ordena las palabras para formar una frase:',
        promptTranslation: 'Mis abuelos solían vivir en el campo.',
        words: ['My', 'grandparents', 'used', 'to', 'live', 'in', 'the', 'countryside.'],
        correctAnswer: 'My grandparents used to live in the countryside.',
        explanation: 'Estructura: sujeto + used to + verbo base. → My grandparents used to live in the countryside.',
      },
      {
        id: 'b1-wb-p12-ex4',
        type: 'match',
        concept: 'tag questions: auxiliary',
        difficulty: 3,
        prompt: 'Relaciona cada frase con su tag question correcta.',
        pairs: [
          { left: 'You are tired,', right: 'aren\'t you?' },
          { left: 'She works here,', right: 'doesn\'t she?' },
          { left: 'They didn\'t come,', right: 'did they?' },
          { left: 'He can swim,', right: 'can\'t he?' },
          { left: 'We have met before,', right: 'haven\'t we?' },
        ],
        correctAnswer: 'match',
        explanation:
          'La tag question repite el auxiliar con el signo contrario: afirmativa → tag negativa; negativa → tag afirmativa. Usa el mismo tiempo y persona.',
      },
      {
        id: 'b1-wb-p12-ex5',
        type: 'error_correction',
        concept: 'tag questions: form',
        difficulty: 4,
        prompt: 'Corrige el error: "You like pizza, aren\'t you?"',
        correctAnswer: "You like pizza, don't you?",
        acceptedAnswers: ["You like pizza, don't you", "You like pizza, don't you."],
        acceptApproximate: true,
        explanation:
          'Con "like" (present simple) la tag usa el auxiliar "do/does": You like pizza, don\'t you? "Aren\'t you" solo sirve con el verbo "to be".',
      },
      {
        id: 'b1-wb-p12-ex6',
        type: 'true_false',
        concept: 'used to vs would',
        difficulty: 3,
        prompt:
          '"Would" puede usarse para describir hábitos pasados, igual que "used to", pero no sirve para estados pasados como "I would have a car".',
        correctAnswer: 'true',
        explanation:
          'Correcto. "Would" describe hábitos pasados (We would play every day) pero no estados: para estados pasados usamos "used to" (I used to have a car).',
      },
    ],
  },
  {
    id: 'b1-wb-13',
    levelId: 'b1',
    unit: 'Unit 13 · Repaso y reading final',
    page: 13,
    title: 'Repaso final y lectura',
    intro:
      'Repasamos todo el nivel B1 con una lectura que combina varias unidades y ejercicios variados.',
    exercises: [
      {
        id: 'b1-wb-p13-ex1',
        type: 'reading',
        concept: 'reading: B1 review',
        difficulty: 4,
        prompt: 'Lee el texto sobre Marta y responde las preguntas.',
        correctAnswer: 'reading',
        explanation:
          'El texto mezcla todo el nivel B1: present perfect continuous, wish + past, future perfect, relative clauses (which, whose, where), third conditional, used to y tag questions.',
        reading: {
          text: `Marta has been learning English for three years, and next year she is going to take a B1 exam. When she started, she couldn't understand anything, but now she can follow films without subtitles. She says that if she had started earlier, she would have been more confident. She often wishes she lived in an English-speaking country, where she could practice every day.

Last month, her teacher told her that she needed to improve her vocabulary. Since then, she has been reading one article every day. The articles, which she finds online, are about technology and travel. Marta admits that the vocabulary is sometimes too difficult, but she doesn't give up. By the time she takes the exam, she will have read more than thirty articles. Her brother, whose English is excellent, sometimes helps her with the difficult words.

Marta is sure that if she studies hard, she will pass the exam. She used to feel nervous about tests, but now she feels more relaxed. She isn't afraid of failing anymore, is she? Well, maybe a little.`,
          translation: `Marta lleva tres años aprendiendo inglés, y el año que viene va a hacer un examen de B1. Cuando empezó, no podía entender nada, pero ahora puede seguir películas sin subtítulos. Dice que si hubiera empezado antes, habría tenido más confianza. A menudo desea vivir en un país de habla inglesa, donde podría practicar todos los días.

El mes pasado, su profesora le dijo que necesitaba mejorar su vocabulario. Desde entonces, ha estado leyendo un artículo cada día. Los artículos, que encuentra en internet, tratan sobre tecnología y viajes. Marta admite que el vocabulario a veces es demasiado difícil, pero no se rinde. Para cuando haga el examen, habrá leído más de treinta artículos. Su hermano, cuyo inglés es excelente, a veces la ayuda con las palabras difíciles.

Marta está segura de que si estudia mucho, aprobará el examen. Solía ponerse nerviosa con los exámenes, pero ahora se siente más tranquila. Ya no tiene miedo de suspender, ¿verdad? Bueno, quizá un poco.`,
          questions: [
            {
              id: 'b1-wb-p13-ex1-q1',
              type: 'multiple_choice',
              concept: 'reading comprehension — present perfect continuous',
              difficulty: 3,
              prompt: 'How long has Marta been learning English?',
              promptTranslation: '¿Cuánto tiempo lleva Marta aprendiendo inglés?',
              correctAnswer: 'For three years.',
              options: ['For three years.', 'Since last month.', 'For one year.'],
              explanation:
                'El texto dice: "Marta has been learning English for three years." (present perfect continuous + for.)',
            },
            {
              id: 'b1-wb-p13-ex1-q2',
              type: 'multiple_choice',
              concept: 'reading comprehension — wish + past',
              difficulty: 3,
              prompt: 'What does Marta wish?',
              promptTranslation: '¿Qué desea Marta?',
              correctAnswer: 'She wishes she lived in an English-speaking country.',
              options: [
                'She wishes she lived in an English-speaking country.',
                'She wishes she had stopped learning English.',
                'She wishes her brother helped her more.',
              ],
              explanation:
                'El texto dice: "She often wishes she lived in an English-speaking country." (wish + past simple.)',
            },
            {
              id: 'b1-wb-p13-ex1-q3',
              type: 'multiple_choice',
              concept: 'reading comprehension — present perfect continuous',
              difficulty: 3,
              prompt: 'What has Marta been doing since last month?',
              promptTranslation: '¿Qué ha estado haciendo Marta desde el mes pasado?',
              correctAnswer: 'Reading one article every day.',
              options: [
                'Reading one article every day.',
                'Taking a B1 exam every week.',
                'Watching films without subtitles.',
              ],
              explanation: 'El texto dice: "Since then, she has been reading one article every day."',
            },
            {
              id: 'b1-wb-p13-ex1-q4',
              type: 'multiple_choice',
              concept: 'reading comprehension — future perfect',
              difficulty: 4,
              prompt: 'How many articles will she have read by the time she takes the exam?',
              promptTranslation: '¿Cuántos artículos habrá leído para cuando haga el examen?',
              correctAnswer: 'More than thirty.',
              options: ['More than thirty.', 'Exactly thirty.', 'Fifteen.'],
              explanation:
                'El texto dice: "By the time she takes the exam, she will have read more than thirty articles." (future perfect.)',
            },
            {
              id: 'b1-wb-p13-ex1-q5',
              type: 'multiple_choice',
              concept: 'reading comprehension — used to',
              difficulty: 3,
              prompt: 'How did Marta use to feel about tests?',
              promptTranslation: '¿Cómo solía sentirse Marta con los exámenes?',
              correctAnswer: 'Nervous.',
              options: ['Nervous.', 'Relaxed.', 'Confident.'],
              explanation:
                'El texto dice: "She used to feel nervous about tests, but now she feels more relaxed." (used to = hábito pasado.)',
            },
            {
              id: 'b1-wb-p13-ex1-q6',
              type: 'multiple_choice',
              concept: 'reading comprehension — third conditional',
              difficulty: 4,
              prompt: 'What would have happened if Marta had started earlier?',
              promptTranslation: '¿Qué habría pasado si Marta hubiera empezado antes?',
              correctAnswer: 'She would have been more confident.',
              options: [
                'She would have been more confident.',
                'She would have failed the exam.',
                'She would have stopped studying.',
              ],
              explanation:
                'El texto dice: "If she had started earlier, she would have been more confident." (third conditional.)',
            },
          ],
        },
      },
      {
        id: 'b1-wb-p13-ex2',
        type: 'multiple_choice',
        concept: 'review: modals of deduction',
        difficulty: 3,
        prompt: 'Completa: "That man looks tired. He ___ have been working all night."',
        promptTranslation: 'Ese hombre parece cansado. Debe de haber estado trabajando toda la noche.',
        correctAnswer: 'must',
        options: ['must', "can't", 'might'],
        explanation:
          '"Must have been working" es una deducción segura sobre el pasado: seguro que estuvo trabajando toda la noche.',
      },
      {
        id: 'b1-wb-p13-ex3',
        type: 'fill_blank',
        concept: 'review: passive',
        difficulty: 3,
        prompt: 'Completa: "This cheese ___ (make) in France."',
        promptTranslation: 'Este queso se fabrica en Francia.',
        correctAnswer: 'is made',
        acceptedAnswers: ['is made'],
        explanation: 'Pasiva en presente: is + participio (made). → This cheese is made in France.',
      },
      {
        id: 'b1-wb-p13-ex4',
        type: 'match',
        concept: 'review: B1 structures',
        difficulty: 3,
        prompt: 'Relaciona cada frase con la estructura que usa.',
        pairs: [
          { left: 'If I were you, I would rest.', right: 'second conditional (advice)' },
          { left: 'She told me she was busy.', right: 'reported speech' },
          { left: 'The town where I grew up', right: 'relative clause (place)' },
          { left: 'I wish I had gone.', right: 'wish + past perfect (regret)' },
          { left: 'I used to play football.', right: 'used to (past habit)' },
          { left: 'Although it was cold, we went out.', right: 'connector (contrast)' },
        ],
        correctAnswer: 'match',
        explanation:
          'Segundo condicional: if + past simple + would. Estilo indirecto: told + that. Relativa de lugar: where. Deseo pasado: wish + past perfect. Hábito pasado: used to. Contraste: although.',
      },
      {
        id: 'b1-wb-p13-ex5',
        type: 'true_false',
        concept: 'review: tag questions',
        difficulty: 3,
        prompt: '"He hasn\'t called yet, has he?" es una tag question correcta.',
        correctAnswer: 'true',
        explanation:
          'Correcto. La frase es negativa (hasn\'t) y la tag es afirmativa (has he), usando el mismo auxiliar y tiempo. Es una tag question bien formada.',
      },
    ],
  },
  {
    id: 'b1-wb-14',
    levelId: 'b1',
    unit: 'Unit 13 · Writing final',
    page: 14,
    title: 'Escribir: article, email y review',
    intro:
      'Escribimos tres textos completos en inglés usando las estructuras del nivel B1: un article, un email y una review.',
    exercises: [
      {
        id: 'b1-wb-p14-ex1',
        type: 'writing',
        concept: 'writing: article',
        difficulty: 4,
        prompt:
          'Escribe un artículo en inglés para una revista de estudiantes titulado "My plans for next year". Usa el future perfect (will have + participle), el future continuous (will be + -ing) y un conector de contraste (although, however).',
        correctAnswer:
          'Next year will be a very busy year for me. By June, I will have finished my course, and I will be working in a new job in the summer. I will be living in a different city, although I will still visit my family every month. I hope I will have learned to drive by the end of the year.',
        taskType: 'article',
        targetReader: 'students in an English magazine',
        register: 'neutral',
        contentPoints: ['Una frase con future perfect', 'Una frase con future continuous', 'Un conector de contraste (although / however)'],
        requiresOwnIdea: true,
        minWords: 60,
        maxWords: 110,
        explanation:
          'Un buen artículo tiene un título, usa will have + participio (will have finished) y will be + -ing (will be working, will be living), e incluye un conector de contraste (although) para enlazar ideas.',
      },
      {
        id: 'b1-wb-p14-ex2',
        type: 'writing',
        concept: 'writing: email with advice',
        difficulty: 4,
        prompt:
          'Escribe un correo informal a un amigo que está pensando en aprender inglés. Dale consejos usando el segundo condicional ("If I were you, I would...") y cuéntale cómo solías sentirte tú cuando empezaste (used to).',
        correctAnswer:
          'Hi Lucas! I think you should start your English course soon. If I were you, I would practice every day, even for twenty minutes. I used to feel nervous when I started, and I used to worry about making mistakes. But I didn\'t give up. If you study a little every day, you will improve quickly. Tell me how it goes! Ana',
        taskType: 'email',
        targetReader: 'a friend',
        register: 'informal',
        contentPoints: ['Un consejo con "If I were you, I would..."', 'Dos frases con used to', 'Tono informal y amable'],
        requiresOwnIdea: true,
        minWords: 60,
        maxWords: 110,
        explanation:
          'Un buen correo usa "If I were you, I would..." para dar consejo, "used to" para hablar de hábitos y estados pasados (I used to feel nervous), y mantiene un tono informal propio de un mensaje a un amigo.',
      },
      {
        id: 'b1-wb-p14-ex3',
        type: 'writing',
        concept: 'writing: review',
        difficulty: 4,
        prompt:
          'Escribe una reseña breve en inglés de una película, un libro o una serie que hayas visto o leído recientemente. Usa el present perfect (I have seen...), el past simple para contar la trama (the story was...) y un conector de causa o contraste (because, however).',
        correctAnswer:
          'I have recently seen a film called "The Silent Forest". The story was about a family that moved to a small village. I liked it because the acting was excellent. The ending was a little sad, however, and I didn\'t expect it. I would definitely recommend this film if you enjoy dramas.',
        taskType: 'review',
        targetReader: 'readers of a student magazine',
        register: 'neutral',
        contentPoints: ['Una frase con present perfect', 'La trama en past simple', 'Un conector (because / however)'],
        requiresOwnIdea: true,
        minWords: 60,
        maxWords: 100,
        explanation:
          'Una buena reseña menciona qué has visto (I have seen...) con present perfect, describe la trama en past simple (the story was...) e incluye conectores (because, however) para enlazar las ideas y dar tu opinión.',
      },
    ],
  },
]
