import type { WorkbookPage } from './types'
import type { Exercise } from '../types'

export const b2Workbook: WorkbookPage[] = [
  {
    id: 'b2-wb-1',
    levelId: 'b2',
    unit: 'Unit 1 · Modal Perfects',
    page: 1,
    title: 'Modal Perfects: deducciones sobre el pasado',
    intro: 'Practicá must have, can\'t have, may/might/could have y las expresiones modales con "be" para deducir sobre el pasado y expresar expectativas.',
    exercises: [
      {
        id: 'b2-wb-p1-ex1',
        type: 'multiple_choice',
        concept: 'must have deduction',
        difficulty: 3,
        prompt: 'Completa: "The lights are off. They ___ gone out."',
        promptTranslation: 'Las luces están apagadas. Deben de haber salido.',
        correctAnswer: 'must have',
        options: ['must have', 'may have', 'should have'],
        explanation: 'La prueba (luces apagadas) apunta a una deducción segura: must have + participio (gone). "May have" solo expresaría posibilidad.',
      },
      {
        id: 'b2-wb-p1-ex2',
        type: 'fill_blank',
        concept: "can't have negative deduction",
        difficulty: 3,
        prompt: 'Completa con el modal correcto: "She ___ have finished already; it\'s only been five minutes."',
        promptTranslation: 'No puede haber terminado ya; solo pasaron cinco minutos.',
        correctAnswer: "can't",
        acceptedAnswers: ["can't", "cannot", "couldn't", "could not", "can not"],
        explanation: 'Para negar una deducción segura sobre el pasado usamos can\'t (o couldn\'t) + have + participio. Nunca "mustn\'t have".',
      },
      {
        id: 'b2-wb-p1-ex3',
        type: 'error_correction',
        concept: "mustn't have vs can't have",
        difficulty: 4,
        prompt: 'Corrige el error: "He mustn\'t have seen the sign, he didn\'t stop."',
        correctAnswer: "He can't have seen the sign, he didn't stop.",
        acceptedAnswers: [
          "He can't have seen the sign, he didn't stop",
          "He can't have seen the sign, he didn't stop.",
          "He couldn't have seen the sign, he didn't stop",
          "He couldn't have seen the sign, he didn't stop.",
        ],
        acceptApproximate: true,
        explanation: 'La negación de una deducción segura no es "mustn\'t have": es "can\'t have" o "couldn\'t have".',
      },
      {
        id: 'b2-wb-p1-ex4',
        type: 'reorder',
        concept: 'must have word order',
        difficulty: 3,
        prompt: 'Ordena las palabras para formar una deducción segura:',
        promptTranslation: 'Debe de haberse olvidado de sus llaves.',
        words: ['He', 'must', 'have', 'forgotten', 'his', 'keys.'],
        correctAnswer: 'He must have forgotten his keys.',
        explanation: 'Orden: sujeto + must + have + participio pasado + complemento. → He must have forgotten his keys.',
      },
      {
        id: 'b2-wb-p1-ex5',
        type: 'match',
        concept: 'modal perfect meanings',
        difficulty: 4,
        prompt: 'Relacioná cada modal perfect con su significado en español.',
        correctAnswer: 'match',
        pairs: [
          { left: 'may have left', right: 'pudo haberse ido (posibilidad)' },
          { left: 'could have studied', right: 'habría podido estudiar (capacidad no usada)' },
          { left: 'should have called', right: 'debería haber llamado (crítica)' },
          { left: 'must have known', right: 'debió de saber (certeza)' },
          { left: 'would have helped', right: 'habría ayudado (condicional hipotético)' },
        ],
        explanation: 'Cada modal perfect tiene un matiz: may/might = posibilidad, could = capacidad pasada no realizada, should = crítica, must = certeza, would = hipótesis condicional.',
      },
      {
        id: 'b2-wb-p1-ex6',
        type: 'true_false',
        concept: 'be bound to expectation',
        difficulty: 3,
        prompt: '"He is bound to succeed" means we are sure he will succeed.',
        correctAnswer: 'true',
        explanation: 'Verdadero. "Be bound to" expresa inevitabilidad: estamos seguros de que algo pasará. → Está destinado a triunfar.',
      },
    ],
  },
  {
    id: 'b2-wb-2',
    levelId: 'b2',
    unit: 'Unit 2 · Causative & Advanced Passive',
    page: 2,
    title: 'Causativo: have/get something done',
    intro: 'Practicá el causativo (have/get something done, get someone to do) y la pasiva avanzada con tiempos compuestos y modales.',
    exercises: [
      {
        id: 'b2-wb-p2-ex1',
        type: 'multiple_choice',
        concept: 'have something done',
        difficulty: 3,
        prompt: 'Completa: "I need to ___ my car serviced before the trip."',
        promptTranslation: 'Necesito llevar mi coche a revisar antes del viaje.',
        correctAnswer: 'have',
        options: ['have', 'make', 'let'],
        explanation: 'Con el causativo "have something done" expresamos que otra persona hace el servicio por nosotros: have my car serviced.',
      },
      {
        id: 'b2-wb-p2-ex2',
        type: 'fill_blank',
        concept: 'get someone to do',
        difficulty: 4,
        prompt: 'Completa con la forma correcta de "fix": "She finally got the technician ___ the laptop."',
        promptTranslation: 'Finalmente logró que el técnico arreglara la computadora.',
        correctAnswer: 'to fix',
        acceptedAnswers: ['to fix', 'to repair', 'fix'],
        explanation: 'Con "get someone to do something" el verbo va en infinitivo con to: got the technician to fix. (En cambio, con "have": have the technician fix, sin to).',
      },
      {
        id: 'b2-wb-p2-ex3',
        type: 'error_correction',
        concept: 'present continuous passive',
        difficulty: 4,
        prompt: 'Corrige el error: "The report is being write by the assistant."',
        correctAnswer: 'The report is being written by the assistant.',
        acceptedAnswers: [
          'The report is being written by the assistant',
          'The report is being written by the assistant.',
        ],
        acceptApproximate: true,
        explanation: 'La pasiva continua se forma con is being + participio pasado: is being written (no "write").',
      },
      {
        id: 'b2-wb-p2-ex4',
        type: 'reorder',
        concept: 'passive modal perfect',
        difficulty: 5,
        prompt: 'Ordena las palabras para formar una deducción pasiva:',
        promptTranslation: 'La ventana debe de haber sido rota por alguien.',
        words: ['The', 'window', 'must', 'have', 'been', 'broken', 'by', 'someone.'],
        correctAnswer: 'The window must have been broken by someone.',
        explanation: 'Orden: sujeto + must + have + been + participio + by + agente. → The window must have been broken by someone.',
      },
      {
        id: 'b2-wb-p2-ex5',
        type: 'select_correct',
        concept: 'impersonal passive',
        difficulty: 5,
        prompt: 'Seleccioná la frase con la pasiva impersonal correcta:',
        correctAnswer: 'It is said that the company is moving offices.',
        options: [
          'It is said that the company is moving offices.',
          'It is said that the company moves offices.',
          'It says that the company is moving offices.',
          'The company is said that it is moving offices.',
        ],
        explanation: 'La pasiva impersonal con "it" se construye: It is said that + cláusula. No se usa "It says that..." en este sentido ni "is said that".',
      },
      {
        id: 'b2-wb-p2-ex6',
        type: 'writing',
        concept: 'causative writing',
        difficulty: 4,
        prompt: 'Escribí un breve informe (report) para tu jefe sobre el estado de la oficina: listá qué cosas hay que arreglar o cambiar usando el causativo (have/get something done). Incluí al menos 3 estructuras causativas.',
        promptTranslation: 'Write a short report to your boss about the office: list what needs to be repaired or changed using causative structures.',
        correctAnswer: 'The office needs a few improvements. We are going to have the air conditioning serviced before summer, and we should get the lift checked next month. We also need to have the carpets cleaned because they are quite worn. I suggest we get the IT team to install new screens in the meeting room.',
        taskType: 'report',
        targetReader: 'your boss',
        register: 'neutral',
        contentPoints: ['Al menos 3 estructuras causativas (have/get something done)', 'Un registro formal neutro', 'Una recomendación o sugerencia final'],
        requiresOwnIdea: true,
        minWords: 70,
        maxWords: 110,
        explanation: 'Un buen informe usa have/get something done de forma natural (have the air conditioning serviced, get the lift checked, have the carpets cleaned) y mantiene un registro profesional.',
      },
    ],
  },
  {
    id: 'b2-wb-3',
    levelId: 'b2',
    unit: 'Unit 3 · Advanced Reported Speech',
    page: 3,
    title: 'Estilo indirecto avanzado: reporting verbs',
    intro: 'Practicá los verbos de reporte con sus patrones (-ing, to-infinitivo, objeto + to) y el backshift de tiempos.',
    exercises: [
      {
        id: 'b2-wb-p3-ex1',
        type: 'multiple_choice',
        concept: 'suggest + -ing',
        difficulty: 4,
        prompt: 'Completa: "She suggested ___ a taxi to the airport."',
        promptTranslation: 'Ella sugirió tomar un taxi al aeropuerto.',
        correctAnswer: 'taking',
        options: ['taking', 'to take', 'take'],
        explanation: '"Suggest" se construye con gerundio (-ing), no con to-infinitivo: suggested taking a taxi.',
      },
      {
        id: 'b2-wb-p3-ex2',
        type: 'fill_blank',
        concept: 'promise + to-infinitive',
        difficulty: 3,
        prompt: 'Completa con la forma correcta de "send": "He promised ___ the documents by Friday."',
        promptTranslation: 'Prometió enviar los documentos antes del viernes.',
        correctAnswer: 'to send',
        acceptedAnswers: ['to send', 'to deliver', 'send'],
        explanation: '"Promise" se construye con to-infinitivo: promised to send the documents.',
      },
      {
        id: 'b2-wb-p3-ex3',
        type: 'error_correction',
        concept: 'reported negative command',
        difficulty: 4,
        prompt: 'Corrige el error: "She told him don\'t open the window."',
        correctAnswer: 'She told him not to open the window.',
        acceptedAnswers: [
          'She told him not to open the window',
          'She told him not to open the window.',
        ],
        acceptApproximate: true,
        explanation: 'Las órdenes negativas en estilo indirecto: tell + objeto + not to + infinitivo. Nunca "told him don\'t".',
      },
      {
        id: 'b2-wb-p3-ex4',
        type: 'match',
        concept: 'reporting verb patterns',
        difficulty: 5,
        prompt: 'Relacioná cada verbo de reporte con su patrón correcto.',
        correctAnswer: 'match',
        pairs: [
          { left: 'deny', right: '+ -ing (She denied stealing.)' },
          { left: 'agree', right: '+ to-infinitivo (He agreed to help.)' },
          { left: 'warn', right: '+ objeto + to-infinitivo (They warned us to be careful.)' },
          { left: 'refuse', right: '+ to-infinitivo (She refused to answer.)' },
          { left: 'admit', right: '+ -ing (He admitted breaking it.)' },
        ],
        explanation: 'deny/admit + -ing; agree/refuse + to-infinitivo; warn/persuade/convince + objeto + to-infinitivo.',
      },
      {
        id: 'b2-wb-p3-ex5',
        type: 'select_correct',
        concept: 'reporting clause position',
        difficulty: 5,
        prompt: 'Seleccioná la frase con la posición de cláusula de reporte más adecuada para un texto formal:',
        correctAnswer: 'The results, the researchers explained, are still preliminary.',
        options: [
          'The results, the researchers explained, are still preliminary.',
          'The results, the researchers explained are still preliminary.',
          'The results are still preliminary the researchers explained.',
          'Are still preliminary the results, explained the researchers.',
        ],
        explanation: 'La posición media (entre sujeto y verbo) es típica de la escritura formal: The results, the researchers explained, are still preliminary.',
      },
      {
        id: 'b2-wb-p3-ex6',
        type: 'true_false',
        concept: 'backshift optionality',
        difficulty: 3,
        prompt: '"She said she is feeling better" is possible if the situation is still true now.',
        correctAnswer: 'true',
        explanation: 'Verdadero. El backshift (tiempo hacia atrás) es habitual pero opcional si la situación sigue siendo verdadera en el presente: she said she is feeling better.',
      },
    ],
  },
  {
    id: 'b2-wb-4',
    levelId: 'b2',
    unit: 'Unit 4 · Relative Clauses & Noun Phrases',
    page: 4,
    title: 'Relativas avanzadas: whose, preposición + which/whom, relativas reducidas',
    intro: 'Practicá "whose", el registro formal con preposición + which/whom, las relativas evaluativas y las relativas reducidas.',
    exercises: [
      {
        id: 'b2-wb-p4-ex1',
        type: 'multiple_choice',
        concept: 'whose relative',
        difficulty: 3,
        prompt: 'Completa: "The writer ___ book won the prize lives in Madrid."',
        promptTranslation: 'El escritor cuyo libro ganó el premio vive en Madrid.',
        correctAnswer: 'whose',
        options: ['whose', 'who', 'which'],
        explanation: '"Whose" expresa posesión: the writer whose book (cuyo libro) won the prize.',
      },
      {
        id: 'b2-wb-p4-ex2',
        type: 'fill_blank',
        concept: 'preposition + which',
        difficulty: 4,
        prompt: 'Completa con la forma más formal: "The issue ___ which we are concerned is the budget."',
        promptTranslation: 'El tema que nos preocupa es el presupuesto.',
        correctAnswer: 'about',
        acceptedAnswers: ['about', 'with', 'on'],
        explanation: 'En registro formal, la preposición va antes de which: the issue about which we are concerned (el tema del que estamos preocupados).',
      },
      {
        id: 'b2-wb-p4-ex3',
        type: 'reorder',
        concept: 'preposition + whom',
        difficulty: 5,
        prompt: 'Ordena las palabras para formar una frase formal:',
        promptTranslation: 'La persona con la que hablamos es la directora.',
        words: ['The', 'person', 'with', 'whom', 'we', 'spoke', 'is', 'the', 'director.'],
        correctAnswer: 'The person with whom we spoke is the director.',
        explanation: 'En estilo formal: preposición + whom. → The person with whom we spoke is the director.',
      },
      {
        id: 'b2-wb-p4-ex4',
        type: 'error_correction',
        concept: "whose vs who's",
        difficulty: 3,
        prompt: 'Corrige el error: "That\'s the student who\'s laptop was stolen."',
        correctAnswer: 'That\'s the student whose laptop was stolen.',
        acceptedAnswers: [
          'That\'s the student whose laptop was stolen',
          'That\'s the student whose laptop was stolen.',
        ],
        acceptApproximate: true,
        explanation: '"Who\'s" = who is. Para posesión usamos "whose": the student whose laptop (cuyo portátil).',
      },
      {
        id: 'b2-wb-p4-ex5',
        type: 'match',
        concept: 'compound adjectives',
        difficulty: 4,
        prompt: 'Relacioná cada adjetivo compuesto con su significado.',
        correctAnswer: 'match',
        pairs: [
          { left: 'a long-lasting battery', right: 'una batería de larga duración' },
          { left: 'a good-looking man', right: 'un hombre atractivo' },
          { left: 'a well-known writer', right: 'un escritor muy conocido' },
          { left: 'a five-star hotel', right: 'un hotel de cinco estrellas' },
          { left: 'a hard-working student', right: 'un estudiante trabajador' },
        ],
        explanation: 'Los adjetivos compuestos con guion se usan como atributos: a long-lasting battery, a well-known writer, a five-star hotel, etc.',
      },
      {
        id: 'b2-wb-p4-ex6',
        type: 'select_correct',
        concept: 'reduced relative clauses',
        difficulty: 4,
        prompt: 'Seleccioná la versión REDUCIDA correcta de "The man who is standing by the door is my uncle."',
        correctAnswer: 'The man standing by the door is my uncle.',
        options: [
          'The man standing by the door is my uncle.',
          'The man stand by the door is my uncle.',
          'The man who standing by the door is my uncle.',
          'The standing man by the door is my uncle.',
        ],
        explanation: 'La relativa activa se reduce quitando "who is": The man standing by the door. No "who standing" ni "stand".',
      },
    ],
  },
  {
    id: 'b2-wb-5',
    levelId: 'b2',
    unit: 'Unit 5 · Participle Clauses',
    page: 5,
    title: 'Cláusulas de participio: -ing y -ed',
    intro: 'Practicá las cláusulas de participio para expresar razón, tiempo y circunstancia, y los verbos de percepción + -ing.',
    exercises: [
      {
        id: 'b2-wb-p5-ex1',
        type: 'multiple_choice',
        concept: '-ing participle clause',
        difficulty: 4,
        prompt: 'Completa: "___ tired, she went straight to bed."',
        promptTranslation: 'Como se sentía cansada, se fue directamente a la cama.',
        correctAnswer: 'Feeling',
        options: ['Feeling', 'Felt', 'To feel'],
        explanation: 'La cláusula de participio -ing expresa causa: Feeling tired (como se sentía cansada), se fue a la cama.',
      },
      {
        id: 'b2-wb-p5-ex2',
        type: 'fill_blank',
        concept: 'after having + past participle',
        difficulty: 4,
        prompt: 'Completa: "___ having finished the report, she left the office."',
        promptTranslation: 'Después de haber terminado el informe, salió de la oficina.',
        correctAnswer: 'After',
        acceptedAnswers: ['After', 'after'],
        explanation: 'Para referencia pasada: After having finished the report... (Después de haber terminado el informe...).',
      },
      {
        id: 'b2-wb-p5-ex3',
        type: 'error_correction',
        concept: '-ing vs -ed participle',
        difficulty: 5,
        prompt: 'Corrige el error: "Driven fast, the driver lost control of the car." (el conductor iba rápido)',
        correctAnswer: 'Driving fast, the driver lost control of the car.',
        acceptedAnswers: [
          'Driving fast, the driver lost control of the car',
          'Driving fast, the driver lost control of the car.',
        ],
        acceptApproximate: true,
        explanation: 'Si el sujeto hace la acción (el conductor conducía), usamos -ing: Driving fast. "Driven" sería pasivo (el coche conducido).',
      },
      {
        id: 'b2-wb-p5-ex4',
        type: 'reorder',
        concept: 'perception verb + object + -ing',
        difficulty: 4,
        prompt: 'Ordena las palabras para formar una frase:',
        promptTranslation: 'La vi cruzando la calle.',
        words: ['I', 'saw', 'her', 'crossing', 'the', 'street.'],
        correctAnswer: 'I saw her crossing the street.',
        explanation: 'Verbo de percepción + objeto + -ing: I saw her crossing the street (la vi cruzando).',
      },
      {
        id: 'b2-wb-p5-ex5',
        type: 'select_correct',
        concept: 'bare infinitive vs -ing after sense verbs',
        difficulty: 5,
        prompt: 'Seleccioná la frase que describe que viste TODO el proceso de principio a fin:',
        correctAnswer: 'I watched the chef prepare the whole meal.',
        options: [
          'I watched the chef prepare the whole meal.',
          'I watched the chef preparing the whole meal, from the beginning to the end.',
          'I watched the chef to prepare the whole meal.',
          'I watched the chef prepared the whole meal.',
        ],
        explanation: 'Con verbos de percepción, el infinitivo sin to describe la acción completa; el -ing describe la acción en curso: I watched the chef prepare (todo el proceso).',
      },
      {
        id: 'b2-wb-p5-ex6',
        type: 'reading',
        concept: 'participle clauses reading',
        difficulty: 4,
        prompt: 'Lee el texto sobre un voluntario en una reserva natural y responde las preguntas.',
        correctAnswer: 'reading complete',
        reading: {
          text: 'Walking through the reserve at dawn, Marcos counted the birds that had arrived overnight. Exhausted but excited, he wrote down every species he recognised.\nHaving finished the count, he returned to the camp to prepare breakfast. While waiting for the water to boil, he heard a strange noise coming from the trees. Looking up, he saw a group of monkeys jumping from branch to branch.\nSurprised by the sight, he took several photos. Later, writing his field notes, he realised that this was the first time he had seen those monkeys in that area. He decided to stay one more week, convinced that the reserve still had many secrets to reveal.',
          translation: 'Caminando por la reserva al amanecer, Marcos contó las aves que habían llegado durante la noche. Agotado pero emocionado, anotó cada especie que reconocía.\nHabiendo terminado el recuento, volvió al campamento para preparar el desayuno. Mientras esperaba que hirviera el agua, escuchó un ruido extraño que venía de los árboles. Al levantar la vista, vio un grupo de monos saltando de rama en rama.\nSorprendido por la vista, tomó varias fotos. Más tarde, mientras escribía sus notas de campo, se dio cuenta de que era la primera vez que veía esos monos en esa zona. Decidió quedarse una semana más, convencido de que la reserva aún tenía muchos secretos por revelar.',
          questions: [
            {
              id: 'b2-wb-p5-ex6-q1',
              type: 'multiple_choice',
              concept: 'participle reading',
              difficulty: 4,
              prompt: 'What did Marcos do walking through the reserve at dawn?',
              correctAnswer: 'He counted the birds that had arrived overnight.',
              options: [
                'He counted the birds that had arrived overnight.',
                'He cooked breakfast in the forest.',
                'He looked for monkeys near the camp.',
              ],
              explanation: 'El texto empieza: "Walking through the reserve at dawn, Marcos counted the birds that had arrived overnight."',
            },
            {
              id: 'b2-wb-p5-ex6-q2',
              type: 'multiple_choice',
              concept: 'participle reading',
              difficulty: 4,
              prompt: 'What was Marcos doing when he heard the strange noise?',
              correctAnswer: 'He was waiting for the water to boil.',
              options: [
                'He was waiting for the water to boil.',
                'He was counting birds again.',
                'He was taking photos of the camp.',
              ],
              explanation: '"While waiting for the water to boil, he heard a strange noise coming from the trees."',
            },
            {
              id: 'b2-wb-p5-ex6-q3',
              type: 'multiple_choice',
              concept: 'participle reading',
              difficulty: 4,
              prompt: 'What did Marcos see looking up?',
              correctAnswer: 'A group of monkeys jumping from branch to branch.',
              options: [
                'A group of monkeys jumping from branch to branch.',
                'A rare bird he had never seen.',
                'Another volunteer arriving at the camp.',
              ],
              explanation: '"Looking up, he saw a group of monkeys jumping from branch to branch."',
            },
            {
              id: 'b2-wb-p5-ex6-q4',
              type: 'true_false',
              concept: 'participle reading',
              difficulty: 3,
              prompt: 'Marcos had seen those monkeys in that area before.',
              correctAnswer: 'false',
              explanation: 'El texto dice: "this was the first time he had seen those monkeys in that area."',
            },
            {
              id: 'b2-wb-p5-ex6-q5',
              type: 'multiple_choice',
              concept: 'participle reading',
              difficulty: 4,
              prompt: 'Why did Marcos decide to stay one more week?',
              correctAnswer: 'Because he believed the reserve still had secrets to reveal.',
              options: [
                'Because he believed the reserve still had secrets to reveal.',
                'Because his friends arrived at the camp.',
                'Because the water supply ran out.',
              ],
              explanation: '"He decided to stay one more week, convinced that the reserve still had many secrets to reveal."',
            },
          ],
        },
        explanation: 'El texto usa cláusulas de participio para dar fluidez: Walking through the reserve, Having finished the count, Looking up, Surprised by the sight, writing his field notes.',
      },
    ],
  },
  {
    id: 'b2-wb-6',
    levelId: 'b2',
    unit: 'Unit 6 · Advanced Conditionals',
    page: 6,
    title: 'Condicionales avanzadas y wish/if only',
    intro: 'Practicá las conjunciones condicionales (unless, as long as, provided that), las condicionales mixtas y wish/if only para el pasado.',
    exercises: [
      {
        id: 'b2-wb-p6-ex1',
        type: 'multiple_choice',
        concept: 'unless conditional conjunction',
        difficulty: 3,
        prompt: 'Completa: "You won\'t pass the exam ___ you study harder."',
        promptTranslation: 'No aprobarás el examen a menos que estudies más.',
        correctAnswer: 'unless',
        options: ['unless', 'as long as', 'provided that'],
        explanation: '"Unless" = a menos que / si no: no aprobarás si no estudias más. "As long as" y "provided that" significan "siempre que".',
      },
      {
        id: 'b2-wb-p6-ex2',
        type: 'fill_blank',
        concept: 'mixed conditional',
        difficulty: 5,
        prompt: 'Completa con la forma correcta de "be": "If I had studied medicine, I ___ a doctor now."',
        promptTranslation: 'Si hubiera estudiado medicina, ahora sería médico.',
        correctAnswer: 'would be',
        acceptedAnswers: ['would be', 'would be a doctor', 'I would be'],
        explanation: 'Condicional mixta: condición pasada (had studied) + resultado presente (would be). No "would have been" porque el resultado es ahora.',
      },
      {
        id: 'b2-wb-p6-ex3',
        type: 'error_correction',
        concept: 'wish + past perfect regret',
        difficulty: 4,
        prompt: 'Corrige el error: "I wish I studied harder for the exam last week."',
        correctAnswer: 'I wish I had studied harder for the exam last week.',
        acceptedAnswers: [
          'I wish I had studied harder for the exam last week',
          'I wish I had studied harder for the exam last week.',
        ],
        acceptApproximate: true,
        explanation: 'Para expresar arrepentimiento sobre el pasado: wish + past perfect (had studied). En este contexto, "I wish I studied" no expresa el pasado real.',
      },
      {
        id: 'b2-wb-p6-ex4',
        type: 'reorder',
        concept: 'provided that conditional',
        difficulty: 4,
        prompt: 'Ordena las palabras para formar una frase:',
        promptTranslation: 'Iré siempre que me pagues la entrada.',
        words: ["I'll", 'come', 'provided', 'that', 'you', 'pay', 'for', 'the', 'ticket.'],
        correctAnswer: "I'll come provided that you pay for the ticket.",
        explanation: '"Provided that" = siempre que: I\'ll come provided that you pay for the ticket.',
      },
      {
        id: 'b2-wb-p6-ex5',
        type: 'match',
        concept: 'conditional conjunctions',
        difficulty: 4,
        prompt: 'Relacioná cada conjunción condicional con su significado.',
        correctAnswer: 'match',
        pairs: [
          { left: 'unless', right: 'a menos que / si no' },
          { left: 'as long as', right: 'siempre que' },
          { left: 'provided that', right: 'a condición de que' },
          { left: 'once', right: 'una vez que' },
          { left: 'supposing', right: 'suponiendo que' },
        ],
        explanation: 'Cada conjunción introduce una condición específica: unless (negativa), as long as / provided that (condición necesaria), once (punto de partida), supposing (hipótesis).',
      },
      {
        id: 'b2-wb-p6-ex6',
        type: 'writing',
        concept: 'conditionals writing',
        difficulty: 5,
        prompt: 'Escribí un ensayo (essay) breve: "If you could change one decision you made in the past, what would it be and why?" Usá al menos dos condicionales mixtas o wish/if only + past perfect.',
        promptTranslation: 'Write a short essay: "If you could change one decision you made in the past, what would it be and why?" Use at least two mixed conditionals or wish/if only + past perfect.',
        correctAnswer: 'If I could change one decision, I would not have given up learning the piano when I was twelve. I wish I had been more patient with myself. If I had continued practising, I would be able to play for my friends today. Now I am determined not to make the same mistake again.',
        taskType: 'essay',
        targetReader: 'your teacher',
        register: 'neutral',
        contentPoints: ['Al menos dos estructuras de wish/if only + past perfect o condicional mixta', 'Una conclusión clara', 'Un registro adecuado a un ensayo escolar'],
        requiresOwnIdea: true,
        minWords: 90,
        maxWords: 140,
        explanation: 'Un buen ensayo combina wish + past perfect (I wish I had been more patient) con una condicional mixta (If I had continued practising, I would be able to play now).',
      },
    ],
  },
  {
    id: 'b2-wb-7',
    levelId: 'b2',
    unit: 'Unit 7 · Emphasis & Inversion',
    page: 7,
    title: 'Énfasis e inversión',
    intro: 'Practicá la inversión negativa (never, no sooner...than, hardly), not only...but also y las focus structures.',
    exercises: [
      {
        id: 'b2-wb-p7-ex1',
        type: 'multiple_choice',
        concept: 'negative inversion present perfect',
        difficulty: 4,
        prompt: 'Completa: "Never ___ I seen such a beautiful sunset."',
        promptTranslation: 'Nunca vi una puesta de sol tan hermosa.',
        correctAnswer: 'have',
        options: ['have', 'had', 'did'],
        explanation: 'Con "never" al inicio invertimos: auxiliar + sujeto. "Never have I seen..." (present perfect, sujeto I → have).',
      },
      {
        id: 'b2-wb-p7-ex2',
        type: 'fill_blank',
        concept: 'no sooner...than',
        difficulty: 5,
        prompt: 'Completa: "No sooner ___ she arrived than the phone rang."',
        promptTranslation: 'Apenas llegó cuando sonó el teléfono.',
        correctAnswer: 'had',
        acceptedAnswers: ['had', 'had she'],
        explanation: '"No sooner...than" usa past perfect con inversión: No sooner had she arrived than the phone rang.',
      },
      {
        id: 'b2-wb-p7-ex3',
        type: 'error_correction',
        concept: 'not only...but also inversion',
        difficulty: 5,
        prompt: 'Corrige el error: "Not only she sings, but she also plays the guitar."',
        correctAnswer: 'Not only does she sing, but she also plays the guitar.',
        acceptedAnswers: [
          'Not only does she sing, but she also plays the guitar',
          'Not only does she sing, but she also plays the guitar.',
        ],
        acceptApproximate: true,
        explanation: 'Con "not only" al inicio invertimos con auxiliar: Not only does she sing (no "Not only she sings").',
      },
      {
        id: 'b2-wb-p7-ex4',
        type: 'reorder',
        concept: 'neither...nor',
        difficulty: 4,
        prompt: 'Ordena las palabras para formar una frase:',
        promptTranslation: 'Ni el director ni los empleados estaban contentos.',
        words: ['Neither', 'the', 'manager', 'nor', 'the', 'staff', 'were', 'satisfied.'],
        correctAnswer: 'Neither the manager nor the staff were satisfied.',
        explanation: '"Neither...nor" une dos negaciones: Neither the manager nor the staff were satisfied.',
      },
      {
        id: 'b2-wb-p7-ex5',
        type: 'select_correct',
        concept: 'focus structure',
        difficulty: 4,
        prompt: 'Seleccioná la frase con la focus structure correcta:',
        correctAnswer: 'The point is that we need more time to finish.',
        options: [
          'The point is that we need more time to finish.',
          'The point is we needing more time to finish.',
          'The point that we need more time to finish.',
          'It is the point we need more time to finish that.',
        ],
        explanation: 'La focus structure con "the point is" se completa con "that" + cláusula: The point is that we need more time to finish.',
      },
      {
        id: 'b2-wb-p7-ex6',
        type: 'true_false',
        concept: 'not until inversion',
        difficulty: 5,
        prompt: '"Not until I saw the bill did I realise how expensive it was." uses correct inversion.',
        correctAnswer: 'true',
        explanation: 'Verdadero. "Not until" al inicio provoca inversión: Not until I saw the bill did I realise (no "I realised").',
      },
    ],
  },
  {
    id: 'b2-wb-8',
    levelId: 'b2',
    unit: 'Unit 8 · Advanced Comparison',
    page: 8,
    title: 'Comparación avanzada',
    intro: 'Practicá los modificadores de comparativos (far, slightly, considerably), the more...the more, as if y enough.',
    exercises: [
      {
        id: 'b2-wb-p8-ex1',
        type: 'multiple_choice',
        concept: 'modifying comparatives',
        difficulty: 3,
        prompt: 'Completa con el modificador que expresa una GRAN diferencia: "This hotel is ___ more expensive than the other one."',
        promptTranslation: 'Este hotel es considerablemente más caro que el otro.',
        correctAnswer: 'considerably',
        options: ['considerably', 'slightly', 'a little'],
        explanation: '"Considerably" (= considerablemente) expresa una gran diferencia; "slightly" y "a little" expresan una diferencia pequeña.',
      },
      {
        id: 'b2-wb-p8-ex2',
        type: 'fill_blank',
        concept: 'the more...the more',
        difficulty: 4,
        prompt: 'Completa: "The ___ you practise, the better you will speak."',
        promptTranslation: 'Cuanto más practiques, mejor hablarás.',
        correctAnswer: 'more',
        acceptedAnswers: ['more', 'harder', 'most'],
        explanation: 'Estructura proporcional: The more you practise, the better you will speak. (Cuanto más practiques, mejor hablarás.)',
      },
      {
        id: 'b2-wb-p8-ex3',
        type: 'error_correction',
        concept: 'as if unreal past',
        difficulty: 5,
        prompt: 'Corrige el error: "He spends money as if he is a millionaire." (but he is not)',
        correctAnswer: 'He spends money as if he were a millionaire.',
        acceptedAnswers: [
          'He spends money as if he were a millionaire',
          'He spends money as if he were a millionaire.',
          'He spends money as if he was a millionaire',
          'He spends money as if he was a millionaire.',
        ],
        acceptApproximate: true,
        explanation: 'Tras "as if" para una comparación no real usamos el pasado (con "were" como subjuntivo en registros formales): as if he were a millionaire.',
      },
      {
        id: 'b2-wb-p8-ex4',
        type: 'reorder',
        concept: 'enough + to-infinitive',
        difficulty: 3,
        prompt: 'Ordena las palabras para formar una frase:',
        promptTranslation: 'No tiene edad suficiente para conducir.',
        words: ['She', 'is', 'not', 'old', 'enough', 'to', 'drive.'],
        correctAnswer: 'She is not old enough to drive.',
        explanation: 'Orden: adjetivo + enough + to-infinitivo: old enough to drive (edad suficiente para conducir).',
      },
      {
        id: 'b2-wb-p8-ex5',
        type: 'match',
        concept: 'comparison expressions',
        difficulty: 4,
        prompt: 'Relacioná cada expresión de comparación con su uso.',
        correctAnswer: 'match',
        pairs: [
          { left: 'by far the best', right: 'con diferencia el mejor (superlativo enfático)' },
          { left: 'the same as', right: 'igual que (identidad)' },
          { left: 'rather a long trip', right: 'un viaje bastante largo (formal)' },
          { left: 'much more interesting', right: 'mucho más interesante (gran diferencia)' },
          { left: 'as if nothing had happened', right: 'como si no hubiera pasado nada (hipótesis)' },
        ],
        explanation: 'Cada expresión tiene un matiz: by far (enfático), the same as (identidad), rather a (formal), much (gran diferencia), as if (hipótesis).',
      },
      {
        id: 'b2-wb-p8-ex6',
        type: 'writing',
        concept: 'comparison writing',
        difficulty: 4,
        prompt: 'Escribí una reseña (review) de una película o serie que hayas visto. Comparala con otra (usá modificadores como far o slightly more) e incluí al menos una estructura "the more...the more" o "as if".',
        promptTranslation: 'Write a review of a film or series you have watched. Compare it with another one and use at least one "the more...the more" or "as if" structure.',
        correctAnswer: 'The film was far more interesting than I expected. The acting was slightly better than in the sequel, and the ending was by far the most surprising part. The more I think about it, the more I want to watch it again. It felt as if the director had known exactly what the audience wanted.',
        taskType: 'review',
        targetReader: 'a film blog',
        register: 'neutral',
        contentPoints: ['Al menos un modificador de comparativo (far/slightly/much)', 'Una estructura "the more...the more" o "as if"', 'Una opinión clara con justificación'],
        requiresOwnIdea: true,
        minWords: 80,
        maxWords: 130,
        explanation: 'Una buena reseña compara con modificadores (far more interesting, slightly better, by far) e incluye la estructura proporcional o de hipótesis.',
      },
    ],
  },
  {
    id: 'b2-wb-9',
    levelId: 'b2',
    unit: 'Unit 9 · Verb Patterns & Phrasal Verbs',
    page: 9,
    title: 'Patrones verbales y phrasal verbs',
    intro: 'Practicá los verbos con cambio de significado (-ing vs to), los phrasal verbs separables e inseparables y los de tres partes.',
    exercises: [
      {
        id: 'b2-wb-p9-ex1',
        type: 'multiple_choice',
        concept: 'stop + to-infinitive',
        difficulty: 4,
        prompt: 'Completa: "He stopped ___ to buy a coffee." (hizo una pausa en su caminata)',
        promptTranslation: 'Se detuvo para comprar un café.',
        correctAnswer: 'to buy',
        options: ['to buy', 'buying', 'buy'],
        explanation: '"Stop to buy" = se detuvo para comprar (pausa). "Stop buying" = dejó de comprar. Aquí la pausa: to buy.',
      },
      {
        id: 'b2-wb-p9-ex2',
        type: 'fill_blank',
        concept: 'remember + -ing',
        difficulty: 4,
        prompt: 'Completa con la forma correcta de "lock": "I remember ___ the door, I locked it this morning."',
        promptTranslation: 'Recuerdo haber cerrado la puerta, la cerré esta mañana.',
        correctAnswer: 'locking',
        acceptedAnswers: ['locking', 'locking the door'],
        explanation: '"Remember + -ing" = recordar algo que ya pasó: I remember locking the door (recuerdo haberla cerrado).',
      },
      {
        id: 'b2-wb-p9-ex3',
        type: 'error_correction',
        concept: 'separable phrasal verb with pronoun',
        difficulty: 4,
        prompt: 'Corrige el error: "Please turn on it." (it = the TV)',
        correctAnswer: 'Please turn it on.',
        acceptedAnswers: [
          'Please turn it on',
          'Please turn it on.',
          'Turn it on',
          'Turn it on.',
        ],
        acceptApproximate: true,
        explanation: 'Con un pronombre objeto, el phrasal separable obligatoriamente se separa: turn it on (nunca "turn on it").',
      },
      {
        id: 'b2-wb-p9-ex4',
        type: 'reorder',
        concept: 'phrasal-prepositional verb',
        difficulty: 4,
        prompt: 'Ordena las palabras para formar una frase:',
        promptTranslation: 'Tengo muchas ganas de conocerte.',
        words: ["I'm", 'looking', 'forward', 'to', 'meeting', 'you.'],
        correctAnswer: "I'm looking forward to meeting you.",
        explanation: 'Verbo de tres partes: look forward to + -ing. → I\'m looking forward to meeting you.',
      },
      {
        id: 'b2-wb-p9-ex5',
        type: 'match',
        concept: 'phrasal verb meanings',
        difficulty: 3,
        prompt: 'Relacioná cada phrasal verb con su significado.',
        correctAnswer: 'match',
        pairs: [
          { left: 'come across', right: 'encontrarse con (por casualidad)' },
          { left: 'put up with', right: 'aguantar, tolerar' },
          { left: 'run out of', right: 'quedarse sin' },
          { left: 'get over', right: 'superar (una enfermedad o problema)' },
          { left: 'deal with', right: 'ocuparse de, gestionar' },
        ],
        explanation: 'come across = encontrarse algo por casualidad; put up with = aguantar; run out of = quedarse sin; get over = superar; deal with = gestionar.',
      },
      {
        id: 'b2-wb-p9-ex6',
        type: 'select_correct',
        concept: 'inseparable phrasal verb',
        difficulty: 3,
        prompt: 'Seleccioná la frase correcta:',
        correctAnswer: 'She looks after her younger brother every day.',
        options: [
          'She looks after her younger brother every day.',
          'She looks her younger brother after every day.',
          'She looks after him her younger brother every day.',
          'She looks her younger brother every day after.',
        ],
        explanation: '"Look after" es inseparable: el objeto va después de la partícula (look after her brother). Solo los separables permiten intercalar el objeto.',
      },
    ],
  },
  {
    id: 'b2-wb-10',
    levelId: 'b2',
    unit: 'Unit 10 · Future Perspectives',
    page: 10,
    title: 'Perspectivas de futuro',
    intro: 'Practicá el future perfect continuous, el future continuous en preguntas corteses y el futuro en el pasado.',
    exercises: [
      {
        id: 'b2-wb-p10-ex1',
        type: 'multiple_choice',
        concept: 'future perfect continuous',
        difficulty: 5,
        prompt: 'Completa: "By this time next year, I ___ here for ten years."',
        promptTranslation: 'Para esta época el año que viene, llevaré diez años trabajando aquí.',
        correctAnswer: 'will have been working',
        options: ['will have been working', 'will work', 'will have worked'],
        explanation: 'Future perfect continuous = will have been + -ing, para duración acumulada hasta un punto futuro: will have been working here for ten years.',
      },
      {
        id: 'b2-wb-p10-ex2',
        type: 'fill_blank',
        concept: 'future perfect continuous form',
        difficulty: 5,
        prompt: 'Completa con la forma correcta de "study": "By June, she ___ been studying English for two years."',
        promptTranslation: 'Para junio, llevará dos años estudiando inglés.',
        correctAnswer: 'will have been studying',
        acceptedAnswers: ['will have been studying', 'will have been studying English for two years'],
        explanation: 'Forma: will + have + been + -ing → will have been studying. (Duración acumulada hasta junio.)',
      },
      {
        id: 'b2-wb-p10-ex3',
        type: 'error_correction',
        concept: 'was about to + infinitive',
        difficulty: 4,
        prompt: 'Corrige el error: "I was about to left when the phone rang."',
        correctAnswer: 'I was about to leave when the phone rang.',
        acceptedAnswers: [
          'I was about to leave when the phone rang',
          'I was about to leave when the phone rang.',
        ],
        acceptApproximate: true,
        explanation: '"Be about to" va seguido del infinitivo base: was about to leave (estaba a punto de irme), no "about to left".',
      },
      {
        id: 'b2-wb-p10-ex4',
        type: 'reorder',
        concept: 'future continuous question',
        difficulty: 4,
        prompt: 'Ordena las palabras para formar una pregunta cortés:',
        promptTranslation: '¿Estarás usando el coche mañana por la mañana?',
        words: ['Will', 'you', 'be', 'using', 'the', 'car', 'tomorrow', 'morning?'],
        correctAnswer: 'Will you be using the car tomorrow morning?',
        explanation: 'Pregunta con future continuous: Will + sujeto + be + -ing? → Will you be using the car tomorrow morning?',
      },
      {
        id: 'b2-wb-p10-ex5',
        type: 'match',
        concept: 'future forms uses',
        difficulty: 4,
        prompt: 'Relacioná cada forma con su uso.',
        correctAnswer: 'match',
        pairs: [
          { left: 'will have finished', right: 'acción completada antes de un punto futuro' },
          { left: 'will be working', right: 'acción en curso en un momento futuro' },
          { left: 'was about to leave', right: 'acción inminente en el pasado' },
          { left: 'is due to arrive', right: 'horario planificado' },
          { left: 'will have been living', right: 'duración acumulada hasta el futuro' },
        ],
        explanation: 'Cada forma expresa una perspectiva distinta: perfect (completada), continuous (en curso), was about to (inminente en el pasado), due to (programado), perfect continuous (duración acumulada).',
      },
      {
        id: 'b2-wb-p10-ex6',
        type: 'true_false',
        concept: 'future perfect continuous meaning',
        difficulty: 4,
        prompt: '"By midnight, the team will have been working for twelve hours." means the team will stop at midnight.',
        correctAnswer: 'false',
        explanation: 'Falso. La frase solo indica la duración acumulada (12 horas) hasta medianoche; no dice que el equipo vaya a parar en ese momento.',
      },
    ],
  },
  {
    id: 'b2-wb-11',
    levelId: 'b2',
    unit: 'Unit 11 · Discourse & Hedging',
    page: 11,
    title: 'Marcadores del discurso y hedging',
    intro: 'Practicá los marcadores de discurso, las conjunciones complejas, el hedging y los pronombres genéricos.',
    exercises: [
      {
        id: 'b2-wb-p11-ex1',
        type: 'multiple_choice',
        concept: 'discourse markers contrast',
        difficulty: 3,
        prompt: 'Completa con el marcador correcto para CONTRASTAR: "The plan is expensive. ___, it is the only viable option."',
        promptTranslation: 'El plan es caro. No obstante, es la única opción viable.',
        correctAnswer: 'Nevertheless',
        options: ['Nevertheless', 'To begin with', 'In conclusion'],
        explanation: '"Nevertheless" (= no obstante) introduce un contraste. "To begin with" inicia y "In conclusion" cierra un texto.',
      },
      {
        id: 'b2-wb-p11-ex2',
        type: 'fill_blank',
        concept: 'hedging It is + adjective + that',
        difficulty: 4,
        prompt: 'Completa para suavizar la afirmación: "It is ___ that the project will be delayed."',
        promptTranslation: 'Es posible que el proyecto se retrase.',
        correctAnswer: 'possible',
        acceptedAnswers: ['possible', 'likely', 'unlikely'],
        explanation: 'El hedging con "It is + adjetivo + that..." suaviza la afirmación: It is possible that the project will be delayed (Es posible que...).',
      },
      {
        id: 'b2-wb-p11-ex3',
        type: 'error_correction',
        concept: 'despite the fact that',
        difficulty: 4,
        prompt: 'Corrige el error: "Despite the fact the weather was bad, the event was a success."',
        correctAnswer: 'Despite the fact that the weather was bad, the event was a success.',
        acceptedAnswers: [
          'Despite the fact that the weather was bad, the event was a success',
          'Despite the fact that the weather was bad, the event was a success.',
        ],
        acceptApproximate: true,
        explanation: 'La conjunción completa es "despite the fact that + cláusula": Despite the fact that the weather was bad...',
      },
      {
        id: 'b2-wb-p11-ex4',
        type: 'reorder',
        concept: 'generic pronoun one',
        difficulty: 5,
        prompt: 'Ordena las palabras para formar una frase formal:',
        promptTranslation: 'Uno debería ser consciente de sus propias limitaciones.',
        words: ['One', 'should', 'be', 'aware', 'of', "one's", 'own', 'limitations.'],
        correctAnswer: 'One should be aware of one\'s own limitations.',
        explanation: 'En registro formal, "one" se usa como pronombre genérico: One should be aware of one\'s own limitations. (Uno debería ser consciente de sus propias limitaciones).',
      },
      {
        id: 'b2-wb-p11-ex5',
        type: 'match',
        concept: 'discourse markers functions',
        difficulty: 3,
        prompt: 'Relacioná cada marcador de discurso con su función.',
        correctAnswer: 'match',
        pairs: [
          { left: 'To begin with', right: 'introducir el primer punto' },
          { left: 'By contrast', right: 'contrastar con lo anterior' },
          { left: 'In conclusion', right: 'cerrar o resumir' },
          { left: 'In addition', right: 'añadir información' },
          { left: 'As a result', right: 'expresar consecuencia' },
        ],
        explanation: 'Cada marcador estructura el discurso: To begin with (inicio), By contrast (contraste), In conclusion (cierre), In addition (adición), As a result (consecuencia).',
      },
      {
        id: 'b2-wb-p11-ex6',
        type: 'writing',
        concept: 'discourse markers writing',
        difficulty: 4,
        prompt: 'Escribí un artículo (article) breve para una revista escolar titulado "Is remote work the future?" Usá al menos 2 marcadores de discurso (To begin with, By contrast, In conclusion...) y 2 ejemplos de hedging (It is likely/possible that...).',
        promptTranslation: 'Write a short article for a school magazine titled "Is remote work the future?" Use at least 2 discourse markers and 2 examples of hedging.',
        correctAnswer: 'To begin with, remote work has changed how we think about the office. It is likely that many companies will keep flexible policies in the future. By contrast, some workers still prefer the structure of an office. In addition, not everyone has a suitable space at home. It is possible that a hybrid model will become the norm. In conclusion, the future of work will probably be a balance between both worlds.',
        taskType: 'article',
        targetReader: 'a school magazine',
        register: 'neutral',
        contentPoints: ['Al menos 2 marcadores de discurso', 'Al menos 2 ejemplos de hedging', 'Una opinión clara'],
        requiresOwnIdea: true,
        minWords: 90,
        maxWords: 140,
        explanation: 'Un buen artículo usa marcadores para estructurar (To begin with, By contrast, In conclusion) y hedging para matizar (It is likely/possible that...).',
      },
    ],
  },
  {
    id: 'b2-wb-12',
    levelId: 'b2',
    unit: 'Unit 12 · Review',
    page: 12,
    title: 'Repaso final: lectura y escritura',
    intro: 'Repasá el nivel B2 con una lectura final y ejercicios variados que combinan varias unidades.',
    exercises: [
      {
        id: 'b2-wb-p12-ex1',
        type: 'reading',
        concept: 'final review reading',
        difficulty: 4,
        prompt: 'Lee el texto sobre los retos del trabajo desde casa y responde las preguntas.',
        correctAnswer: 'reading complete',
        reading: {
          text: 'Working from home has transformed the way many people live, but it has not been an easy change for everyone. Having spent years commuting, some employees now find themselves missing the structure of the office.\nThe more time people spend at home, the harder it is to separate work from personal life. According to a recent survey, many workers admit that they check their emails even after dinner. Unless companies set clear boundaries, the problem is unlikely to disappear.\nOn the other hand, remote work has clear advantages. It is said that productivity has increased in some sectors, and many employees have had their commute time replaced by leisure. Nevertheless, experts suggest that the future is probably a hybrid model, where neither the office nor the home is the only workplace.',
          translation: 'El trabajo desde casa ha transformado la forma en que muchas personas viven, pero no ha sido un cambio fácil para todos. Tras años de ir y volver al trabajo, algunos empleados ahora se encuentran extrañando la estructura de la oficina.\nCuanto más tiempo pasa la gente en casa, más difícil es separar el trabajo de la vida personal. Según una encuesta reciente, muchos trabajadores admiten que revisan sus correos incluso después de la cena. A menos que las empresas establezcan límites claros, es poco probable que el problema desaparezca.\nPor otro lado, el trabajo remoto tiene ventajas claras. Se dice que la productividad ha aumentado en algunos sectores, y muchos empleados han visto su tiempo de desplazamiento sustituido por tiempo de ocio. No obstante, los expertos sugieren que el futuro es probablemente un modelo híbrido, donde ni la oficina ni el hogar sea el único lugar de trabajo.',
          questions: [
            {
              id: 'b2-wb-p12-ex1-q1',
              type: 'multiple_choice',
              concept: 'final review reading',
              difficulty: 4,
              prompt: 'What do some employees miss after working from home?',
              correctAnswer: 'The structure of the office.',
              options: [
                'The structure of the office.',
                'The time spent commuting.',
                'The higher salary they had before.',
              ],
              explanation: 'El texto dice: "some employees now find themselves missing the structure of the office."',
            },
            {
              id: 'b2-wb-p12-ex1-q2',
              type: 'multiple_choice',
              concept: 'final review reading',
              difficulty: 4,
              prompt: 'According to the text, what happens the more time people spend at home?',
              correctAnswer: 'It becomes harder to separate work from personal life.',
              options: [
                'It becomes harder to separate work from personal life.',
                'They become more productive automatically.',
                'They stop checking their emails.',
              ],
              explanation: '"The more time people spend at home, the harder it is to separate work from personal life." (the more...the more)',
            },
            {
              id: 'b2-wb-p12-ex1-q3',
              type: 'multiple_choice',
              concept: 'final review reading',
              difficulty: 4,
              prompt: 'What do many workers admit in the survey?',
              correctAnswer: 'That they check their emails after dinner.',
              options: [
                'That they check their emails after dinner.',
                'That they never use their phone at home.',
                'That they prefer working at weekends.',
              ],
              explanation: '"many workers admit that they check their emails even after dinner" (admit + that clause).',
            },
            {
              id: 'b2-wb-p12-ex1-q4',
              type: 'multiple_choice',
              concept: 'final review reading',
              difficulty: 4,
              prompt: 'According to the text, what is the future likely to be?',
              correctAnswer: 'A hybrid model where neither the office nor the home is the only workplace.',
              options: [
                'A hybrid model where neither the office nor the home is the only workplace.',
                'A return to full-time office work.',
                'A completely remote world with no offices.',
              ],
              explanation: '"the future is probably a hybrid model, where neither the office nor the home is the only workplace."',
            },
          ],
        },
        explanation: 'El texto final integra contenidos B2: cláusula de participio (Having spent years commuting), the more...the more, hedging (It is said that, unlikely to), unless, neither...nor y nevertheless.',
      },
      {
        id: 'b2-wb-p12-ex2',
        type: 'true_false',
        concept: 'review modal perfects',
        difficulty: 3,
        prompt: '"They must have arrived early" expresses a strong deduction about the past.',
        correctAnswer: 'true',
        explanation: 'Verdadero. "Must have + participio" expresa una deducción segura sobre el pasado.',
      },
      {
        id: 'b2-wb-p12-ex3',
        type: 'fill_blank',
        concept: 'review causative',
        difficulty: 4,
        prompt: 'Completa con la forma correcta de "paint": "We are having the house ___ next month."',
        promptTranslation: 'Vamos a hacer que pinten la casa el mes que viene.',
        correctAnswer: 'painted',
        acceptedAnswers: ['painted', 'painted next month'],
        explanation: 'Causativo: have + objeto + participio → having the house painted (mandando a pintar la casa).',
      },
      {
        id: 'b2-wb-p12-ex4',
        type: 'error_correction',
        concept: 'review reporting verbs',
        difficulty: 4,
        prompt: 'Corrige el error: "She suggested to go to the cinema."',
        correctAnswer: 'She suggested going to the cinema.',
        acceptedAnswers: [
          'She suggested going to the cinema',
          'She suggested going to the cinema.',
        ],
        acceptApproximate: true,
        explanation: '"Suggest" se construye con gerundio, no con to-infinitivo: suggested going to the cinema.',
      },
      {
        id: 'b2-wb-p12-ex5',
        type: 'writing',
        concept: 'final essay writing',
        difficulty: 5,
        prompt: 'Escribí el ensayo final: "The advantages of learning languages outweigh the disadvantages." Usá al menos: una cláusula de participio, una condicional (o wish), un marcador de discurso y un ejemplo de hedging.',
        promptTranslation: 'Write the final essay: "The advantages of learning languages outweigh the disadvantages." Use at least one participle clause, one conditional (or wish), one discourse marker and one hedging example.',
        correctAnswer: 'To begin with, learning a new language opens doors both professionally and personally. Having travelled to different countries, I can confirm that speaking the local language changes every experience. If I had started learning English earlier, I would probably have more opportunities now. It is widely believed that bilingual people think more flexibly. In conclusion, although it requires effort, learning languages is clearly worth it.',
        taskType: 'essay',
        targetReader: 'your teacher',
        register: 'neutral',
        contentPoints: ['Una cláusula de participio (Having travelled...)', 'Una condicional o wish', 'Un marcador de discurso (To begin with, In conclusion...)', 'Un ejemplo de hedging (It is widely believed that...)'],
        requiresOwnIdea: true,
        minWords: 100,
        maxWords: 160,
        explanation: 'El ensayo final integra varias estructuras B2: participio (Having travelled), condicional mixta (If I had started... I would probably have...), marcador (To begin with, In conclusion) y hedging (It is widely believed that).',
      },
    ],
  },
]
