import type { Lesson } from '../../types'

export const lesson104MiniTest: Lesson = {
  id: 'b1-m10-l4',
  moduleId: 'm10-gerunds-vs-infinitives',
  order: 3,
  title: 'Mini-test: gerundios e infinitivos',
  objective: 'Evaluar todo el módulo: verbos que aceptan -ing y "to", verbos que cambian de significado, y la estructura verbo + objeto + to.',
  explanation_es: `Esta es la evaluación final del Módulo 10. Repasemos lo esencial:

1) Verbos que aceptan -ing o "to" SIN cambiar el significado: love, like, hate, prefer, begin, start.
- I love reading. = I love to read.
- She started working. = She started to work.

2) Verbos que CAMBIAN de significado según la forma: stop, remember, forget, try.
- -ing mira al PASADO: I stopped smoking. = Dejé de fumar. / I remember locking the door. = Recuerdo haberla cerrado.
- "to" mira al FUTURO: I stopped to smoke. = Me detuve para fumar. / Remember to lock the door. = No olvides cerrarla.

3) Verbo + persona + to + verbo: want, need, tell, ask, advise, encourage.
- I want you to help me. = Quiero que me ayudes.
- She advised him to rest. = Ella le aconsejó que descansara.

Errores típicos:
- ❌ I want that you help me → ✅ I want you to help me.
- ❌ I enjoy to read → ✅ I enjoy reading.
- ❌ I stopped to smoke = dejar de fumar → ❌ (¡significa "me detuve para fumar"!)`,
  examples: [
    { english: 'I love reading / I love to read.', spanish: 'Me encanta leer.' },
    { english: 'I stopped smoking.', spanish: 'Dejé de fumar.' },
    { english: 'Remember to lock the door.', spanish: 'No olvides cerrar la puerta.' },
    { english: 'I want you to help me.', spanish: 'Quiero que me ayudes.' },
    { english: 'She advised him to rest.', spanish: 'Ella le aconsejó que descansara.' },
    { english: 'Try drinking tea.', spanish: 'Prueba a beber té.' },
  ],
  rule: `**Resumen del módulo:**
- love/like/hate/prefer/begin/start + -ing o "to": mismo significado.
- stop/remember/forget/try + -ing = pasado (algo hecho/costumbre); + to = futuro (algo por hacer).
- want/need/tell/ask/advise/encourage + persona + to + verbo.
- enjoy + -ing (solo -ing).`,
  commonMistakes: [
    { wrong: '❌ I want that you help me.', correct: '✅ I want you to help me.', explanation: 'La estructura correcta es verbo + persona + to + verbo, sin "that".' },
    { wrong: '❌ I enjoy to watch films.', correct: '✅ I enjoy watching films.', explanation: '"enjoy" solo acepta -ing.' },
    { wrong: '❌ I stopped to smoke significa que dejé de fumar.', correct: '✅ I stopped smoking significa que dejé de fumar.', explanation: '"Stop + to" significa detenerse para fumar; "stop + -ing" significa dejar de fumar.' },
    { wrong: '❌ She encouraged that I continue.', correct: '✅ She encouraged me to continue.', explanation: 'encourage + persona + to + verbo: encouraged me to continue.' },
  ],
  vocabulary: [],
  grammarPoints: [],
  exercises: [
    {
      id: 'b1-m10-l4-ex1',
      type: 'multiple_choice',
      concept: 'module 10 - love/like + ing or to',
      difficulty: 1,
      prompt: 'Completa con una forma correcta: "I like ___ (read) before bed."',
      promptTranslation: 'Me gusta leer antes de acostarme.',
      correctAnswer: 'reading',
      options: ['reading', 'read', 'to reading'],
      explanation: 'like acepta -ing o "to + verbo": like reading o like to read.',
    },
    {
      id: 'b1-m10-l4-ex2',
      type: 'fill_blank',
      concept: 'module 10 - stop + ing',
      difficulty: 2,
      prompt: 'Completa: "He stopped ___ (smoke) last year." (dejó de fumar)',
      promptTranslation: 'Él dejó de fumar el año pasado.',
      correctAnswer: 'smoking',
      acceptedAnswers: ['smoking', 'to smoke'],
      explanation: 'Dejar de hacer algo = stop + -ing: stopped smoking. (También sería "to smoke", pero significa "se detuvo para fumar".)',
    },
    {
      id: 'b1-m10-l4-ex3',
      type: 'multiple_choice',
      concept: 'module 10 - want + object + to',
      difficulty: 2,
      prompt: 'Completa: "I want ___ to come with me."',
      promptTranslation: 'Quiero que vengas conmigo.',
      correctAnswer: 'you',
      options: ['you', 'that', 'your'],
      explanation: 'want + persona + to + verbo: want you to come. Sin "that".',
    },
    {
      id: 'b1-m10-l4-ex4',
      type: 'error_correction',
      concept: 'module 10 - enjoy only -ing',
      difficulty: 3,
      prompt: 'Corrige el error: "My grandmother enjoys to cook for the family."',
      promptTranslation: 'A mi abuela le encanta cocinar para la familia.',
      correctAnswer: 'My grandmother enjoys cooking for the family.',
      acceptedAnswers: ['My grandmother enjoys cooking for the family', 'My grandmother enjoys cooking for the family.', 'my grandmother enjoys cooking for the family'],
      acceptApproximate: true,
      explanation: '"enjoy" solo acepta -ing: enjoys cooking.',
    },
    {
      id: 'b1-m10-l4-ex5',
      type: 'true_false',
      concept: 'module 10 - remember + ing',
      difficulty: 3,
      prompt: '"I remember turning off the lights" significa que todavía tengo que apagarlas.',
      promptTranslation: '"I remember turning off the lights" means I still have to turn them off.',
      correctAnswer: 'false',
      acceptedAnswers: ['False', 'FALSE', 'f'],
      explanation: 'Falso. remember + -ing = recordar algo ya hecho. Ya las apagué y lo recuerdo.',
    },
    {
      id: 'b1-m10-l4-ex6',
      type: 'reading',
      concept: 'module 10 - a reading about changing habits',
      difficulty: 4,
      prompt: 'Lee el texto sobre hábitos saludables y responde las preguntas.',
      promptTranslation: 'Read the text about healthy habits and answer the questions.',
      reading: {
        text: 'A healthier year\nLast January, Ana decided to make some changes. She stopped eating fast food and began cooking at home. Her doctor advised her to exercise, so she started running every morning. At first, she tried going to the gym, but she preferred running outside. She also wants her family to eat better, so she tells her husband to buy more vegetables. Ana says: "I remember feeling tired all the time before. Now I try to sleep eight hours every night, and I love waking up early." She encourages her friends to try her new habits too.',
        translation: 'Un año más saludable\nEl pasado enero, Ana decidió hacer algunos cambios. Dejó de comer comida rápida y empezó a cocinar en casa. Su médico le aconsejó que hiciera ejercicio, así que empezó a correr cada mañana. Al principio probó a ir al gimnasio, pero prefería correr al aire libre. También quiere que su familia coma mejor, así que le dice a su marido que compre más verduras. Ana dice: "Recuerdo sentirme cansada todo el tiempo antes. Ahora intento dormir ocho horas cada noche, y me encanta despertarme temprano". Anima a sus amigas a probar sus nuevos hábitos también.',
        questions: [
          {
            id: 'b1-m10-l4-ex6-q1',
            type: 'multiple_choice',
            concept: 'module 10 - stop + ing comprehension',
            difficulty: 4,
            prompt: '¿Qué dejó de hacer Ana?',
            correctAnswer: 'Comer comida rápida.',
            options: ['Comer comida rápida.', 'Dormir ocho horas.', 'Salir a correr.'],
            explanation: 'El texto dice: "She stopped eating fast food."',
          },
          {
            id: 'b1-m10-l4-ex6-q2',
            type: 'multiple_choice',
            concept: 'module 10 - advise + object + to',
            difficulty: 4,
            prompt: '¿Qué le aconsejó el médico a Ana?',
            correctAnswer: 'Que hiciera ejercicio.',
            options: ['Que hiciera ejercicio.', 'Que comiera comida rápida.', 'Que durmiera menos.'],
            explanation: '"Her doctor advised her to exercise." → advise + persona + to.',
          },
          {
            id: 'b1-m10-l4-ex6-q3',
            type: 'multiple_choice',
            concept: 'module 10 - try + ing',
            difficulty: 4,
            prompt: '¿Qué probó Ana al principio?',
            correctAnswer: 'Ir al gimnasio.',
            options: ['Ir al gimnasio.', 'Comer comida rápida.', 'Correr por la noche.'],
            explanation: '"She tried going to the gym." → try + -ing = probar algo.',
          },
          {
            id: 'b1-m10-l4-ex6-q4',
            type: 'multiple_choice',
            concept: 'module 10 - tell + object + to',
            difficulty: 4,
            prompt: '¿Qué le dice Ana a su marido?',
            correctAnswer: 'Que compre más verduras.',
            options: ['Que compre más verduras.', 'Que corra con ella.', 'Que duerma más.'],
            explanation: '"She tells her husband to buy more vegetables." → tell + persona + to.',
          },
          {
            id: 'b1-m10-l4-ex6-q5',
            type: 'multiple_choice',
            concept: 'module 10 - remember + ing',
            difficulty: 4,
            prompt: '¿Qué recuerda Ana de su pasado?',
            correctAnswer: 'Sentirse cansada todo el tiempo.',
            options: ['Sentirse cansada todo el tiempo.', 'Despertarse temprano.', 'Cocinar en casa.'],
            explanation: '"I remember feeling tired all the time before." → remember + -ing = recordar algo ya vivido.',
          },
        ],
      },
      correctAnswer: 'reading complete',
      explanation: 'El texto practica stop + -ing (stopped eating), advise + persona + to (advised her to exercise), start + -ing (started running), try + -ing (tried going), prefer + -ing (preferred running), want + persona + to (wants her family to eat), tell + persona + to (tells her husband to buy), remember + -ing (remember feeling) y encourage + persona + to (encourages her friends to try).',
    },
    {
      id: 'b1-m10-l4-ex7',
      type: 'reorder',
      concept: 'module 10 - verb + object + to',
      difficulty: 3,
      prompt: 'Ordena las palabras: asked / teacher / The / us / to / in / speak / English',
      promptTranslation: 'La profesora nos pidió que habláramos en inglés.',
      correctAnswer: 'The teacher asked us to speak in English.',
      words: ['The', 'teacher', 'asked', 'us', 'to', 'speak', 'in', 'English'],
      explanation: 'Orden: sujeto + ask + persona + to + verbo + complemento. → The teacher asked us to speak in English.',
    },
    {
      id: 'b1-m10-l4-ex8',
      type: 'translate',
      concept: 'module 10 - stop + ing',
      difficulty: 3,
      prompt: 'Traduce: "Dejé de beber café."',
      promptTranslation: 'I stopped drinking coffee.',
      correctAnswer: 'I stopped drinking coffee.',
      acceptedAnswers: ['I stopped drinking coffee', 'I stopped drinking coffee.', 'i stopped drinking coffee'],
      acceptApproximate: true,
      explanation: '"Dejar de hacer algo" = stop + -ing: stopped drinking coffee.',
    },
    {
      id: 'b1-m10-l4-ex9',
      type: 'match',
      concept: 'module 10 - review matching',
      difficulty: 3,
      prompt: 'Relaciona cada frase con su significado.',
      promptTranslation: 'Match each sentence with its meaning.',
      correctAnswer: 'I love cooking.=Me encanta cocinar.; I want you to help me.=Quiero que me ayudes.; I stopped to buy water.=Me detuve para comprar agua.; Remember to call her.=No olvides llamarla.; She encouraged me to continue.=Me animó a continuar.',
      pairs: [
        { left: 'I love cooking.', right: 'Me encanta cocinar.' },
        { left: 'I want you to help me.', right: 'Quiero que me ayudes.' },
        { left: 'I stopped to buy water.', right: 'Me detuve para comprar agua.' },
        { left: 'Remember to call her.', right: 'No olvides llamarla.' },
        { left: 'She encouraged me to continue.', right: 'Me animó a continuar.' },
      ],
      explanation: 'Repaso de las tres estructuras del módulo: -ing/"to" con mismo significado, verbos que cambian de sentido, y verbo + objeto + to.',
    },
    {
      id: 'b1-m10-l4-ex10',
      type: 'multiple_choice',
      concept: 'module 10 - meaning-changing verbs',
      difficulty: 4,
      prompt: '¿Qué frase significa "Se detuvo para hablar con su jefe"?',
      promptTranslation: 'Which sentence means "he stopped in order to talk to his boss"?',
      correctAnswer: 'He stopped to talk to his boss.',
      options: ['He stopped to talk to his boss.', 'He stopped talking to his boss.', 'He stops talking to his boss.'],
      explanation: 'Detenerse PARA hacer algo = stop + to + verbo: stopped to talk.',
    },
    {
      id: 'b1-m10-l4-ex11',
      type: 'listening',
      concept: 'module 10 final - comprehensive listening',
      difficulty: 4,
      prompt: 'Escuchá el audio y respondé las preguntas (en inglés, sobre lo que dice).',
      correctAnswer: '',
      explanation: 'A comprehensive review listening where different people talk about their hobbies, habits, and things they want others to do, using gerunds and infinitives throughout.',
      listening: {
        audioText:
          "Hi, I'm David. I love painting, and I started taking art classes last year. I also prefer working with oils. My friends want me to exhibit my work, but I\'m not ready yet. Hi, I\'m Emma. I hate cleaning the house, so I tried hiring a cleaner. It helped! I also stopped smoking two years ago. My doctor advised me to exercise, so I began jogging every morning. Hi, I\'m James. I remember starting my business five years ago. Now my company needs employees to work harder. I tell them to take breaks. I also encourage my team to try new ideas. I love what I do.",
        audioUrl: '/audio/tts/b1-m10-l4-ex11.mp3',
        questions: [
          {
            id: 'b1-m10-l4-ex11-q1',
            type: 'multiple_choice',
            concept: 'module 10 - love + ing and start + to',
            difficulty: 4,
            prompt: 'What does David love doing?',
            correctAnswer: 'Painting',
            options: ['Drawing', 'Painting', 'Sculpting'],
            explanation: '"I love painting, and I started taking art classes last year."',
          },
          {
            id: 'b1-m10-l4-ex11-q2',
            type: 'true_false',
            concept: 'module 10 - stop + ing',
            difficulty: 3,
            prompt: 'Emma stopped smoking two years ago.',
            correctAnswer: 'true',
            explanation: '"I also stopped smoking two years ago."',
          },
          {
            id: 'b1-m10-l4-ex11-q3',
            type: 'multiple_choice',
            concept: 'module 10 - advise + object + to and begin + to',
            difficulty: 4,
            prompt: 'What did Emma\'s doctor advise her to do?',
            correctAnswer: 'Exercise',
            options: ['Rest', 'Exercise', 'Eat less'],
            explanation: '"My doctor advised me to exercise, so I began jogging every morning."',
          },
        ],
      },
    },
    {
      id: 'b1-m10-l4-ex12',
      type: 'writing',
      concept: 'module 10 final - comprehensive writing',
      difficulty: 4,
      prompt: 'Escribile un email a un amigo contándole sobre tus hábitos, lo que intentas hacer, lo que quieres que haga contigo y algo que olvidaste hacer.',
      promptTranslation: 'Write an email to a friend about your habits, what you are trying to do, what you want them to do with you, and something you forgot to do.',
      correctAnswer: '',
      explanation: 'A good email demonstrates mastery of all three structures: verbs + -ing/to (love/hate/prefer), meaning-changing verbs (stop/try/forget/remember), and verb + object + to (want/advise).',
      taskType: 'email',
      targetReader: 'a friend',
      register: 'informal',
      contentPoints: ['Mention at least one personal habit or activity you love/hate/prefer', 'Mention what you are trying to do', 'Include something you want or need them to do with you', 'Mention something you forgot to do'],
      requiresOwnIdea: true,
      minWords: 80,
      maxWords: 120,
    },
    {
      id: 'b1-m10-l4-ex13',
      type: 'speaking',
      concept: 'module 10 final - comprehensive speaking',
      difficulty: 4,
      prompt: 'Escuchá la frase modelo y repetila en voz alta.',
      correctAnswer: 'I love studying, I stopped procrastinating, and I want you to join me.',
      explanation: 'This final speaking exercise combines all three structures from the module: love + -ing, stop + -ing (past habit), and want + object + to. Pay attention to natural linking and appropriate stress in a longer sentence.',
      speakingMode: 'repeat',
    },
  ],
  miniTest: [
    {
      id: 'b1-m10-l4-mt1',
      type: 'multiple_choice',
      concept: 'module 10 final - prefer + ing',
      difficulty: 1,
      prompt: 'Completa: "I prefer ___ (travel) by train."',
      promptTranslation: 'Prefiero viajar en tren.',
      correctAnswer: 'travelling',
      options: ['travelling', 'travel', 'to travelling'],
      explanation: 'prefer + -ing (travelling) o prefer + to (to travel).',
    },
    {
      id: 'b1-m10-l4-mt2',
      type: 'fill_blank',
      concept: 'module 10 final - try + to',
      difficulty: 2,
      prompt: 'Completa: "Please try ___ (open) the window."',
      promptTranslation: 'Por favor, intenta abrir la ventana.',
      correctAnswer: 'to open',
      acceptedAnswers: ['to open', 'To open'],
      explanation: 'Intentar algo difícil = try + to + verbo: try to open.',
    },
    {
      id: 'b1-m10-l4-mt3',
      type: 'error_correction',
      concept: 'module 10 final - no "that"',
      difficulty: 3,
      prompt: 'Corrige el error: "My parents want that I study medicine."',
      promptTranslation: 'Mis padres quieren que estudie medicina.',
      correctAnswer: 'My parents want me to study medicine.',
      acceptedAnswers: ['My parents want me to study medicine', 'My parents want me to study medicine.', 'my parents want me to study medicine'],
      acceptApproximate: true,
      explanation: 'want + persona + to + verbo: want me to study. Sin "that".',
    },
    {
      id: 'b1-m10-l4-mt4',
      type: 'translate',
      concept: 'module 10 final - remember + to',
      difficulty: 3,
      prompt: 'Traduce: "No olvides enviar el email."',
      promptTranslation: 'Remember to send the email.',
      correctAnswer: 'Remember to send the email.',
      acceptedAnswers: ['Remember to send the email', 'Remember to send the email.', 'remember to send the email'],
      acceptApproximate: true,
      explanation: 'Recordatorio de algo pendiente = remember + to + verbo: remember to send.',
    },
    {
      id: 'b1-m10-l4-mt5',
      type: 'multiple_choice',
      concept: 'module 10 final - meaning-changing verbs',
      difficulty: 4,
      prompt: '¿Qué significa "I tried to fix the computer but it was broken"?',
      promptTranslation: 'What does the sentence mean?',
      correctAnswer: 'Intenté arreglar el ordenador, pero estaba roto.',
      options: ['Intenté arreglar el ordenador, pero estaba roto.', 'Probé a arreglar el ordenador y funcionó.', 'Olvidé arreglar el ordenador.'],
      explanation: 'try + to = intentar algo difícil. Intentó arreglarlo, pero no pudo porque estaba roto.',
    },
  ],
  reviewItems: ['b1-m10-l3'],
  prerequisites: ['b1-m10-l3'],
}
