import type { Lesson } from '../../types'

export const lesson101VerbsIngTo: Lesson = {
  id: 'b1-m10-l1',
  moduleId: 'm10-gerunds-vs-infinitives',
  order: 0,
  title: 'Verbos con -ing o "to" (mismo significado)',
  objective: 'Aprender que verbos como love, like, hate, prefer, begin y start aceptan tanto -ing como "to" sin cambiar el significado, y saber elegir la forma más natural.',
  explanation_es: `En inglés hay verbos que pueden ir seguidos de DOS formas del verbo: el gerundio (-ing) o el infinitivo (to + verbo). Cuando hablamos de gustos y preferencias, ambas formas son correctas y significan lo mismo.

Mira estos verbos: love (encantar), like (gustar), hate (odiar), prefer (preferir), begin (empezar) y start (empezar, comenzar). Todos pueden combinarse con -ing o con "to":

- I love reading. = I love to read. = Me encanta leer.
- She started working. = She started to work. = Ella empezó a trabajar.

Con love, like, hate y prefer, la forma en -ing es un poco más común en el inglés británico y suena más natural en conversación. Con begin y start, ambas formas se usan igual.

Solo cambia el estilo, NO el significado. No es un error usar cualquiera de las dos formas.

¡OJO! Esto NO funciona con todos los verbos. Algunos verbos SOLO aceptan -ing (como enjoy, finish, mind) y otros SOLO aceptan "to" (como want, decide, hope). En esta lección nos centramos en los verbos que aceptan las dos.`,
  examples: [
    { english: 'I love reading / I love to read.', spanish: 'Me encanta leer.', note: 'love + -ing o to: mismo significado.' },
    { english: 'She likes swimming / She likes to swim.', spanish: 'A ella le gusta nadar.' },
    { english: 'We hate waiting / We hate to wait.', spanish: 'Odiamos esperar.' },
    { english: 'They prefer cooking / They prefer to cook at home.', spanish: 'Prefieren cocinar en casa.' },
    { english: 'She started working / She started to work in June.', spanish: 'Ella empezó a trabajar en junio.' },
    { english: 'He began learning / He began to learn English last year.', spanish: 'Él empezó a aprender inglés el año pasado.' },
  ],
  rule: `Con love, like, hate, prefer, begin y start podemos usar:
- verbo + -ing: I like reading.
- verbo + to + infinitivo: I like to read.
Ambas formas son correctas y significan lo mismo. Con los verbos de gusto (love/like/hate/prefer) la forma -ing suele sonar más natural; con begin/start las dos se usan por igual.`,
  formation: {
    title: 'Cómo se combinan los verbos con -ing o "to"',
    intro: 'love, like, hate, prefer, begin y start aceptan dos formas: verbo + -ing o verbo + to + infinitivo. Con estos verbos ambas son correctas y significan lo mismo.',
    patterns: [
      {
        name: 'Verbo + -ing',
        formula: 'love/like/hate/prefer/begin/start + verbo + -ing + complemento',
        examples: [
          { english: 'I love reading.', spanish: 'Me encanta leer.' },
          { english: 'She started working.', spanish: 'Ella empezó a trabajar.' },
        ],
        note: 'Con los verbos de gusto (love/like/hate/prefer), la forma -ing suele sonar más natural en conversación.',
      },
      {
        name: 'Verbo + to + infinitivo',
        formula: 'love/like/hate/prefer/begin/start + to + verbo base + complemento',
        examples: [
          { english: 'I love to read.', spanish: 'Me encanta leer.' },
          { english: 'She started to work in June.', spanish: 'Ella empezó a trabajar en junio.' },
        ],
        note: 'Con begin y start, las dos formas se usan por igual.',
      },
    ],
    notes: [
      'Solo cambia el estilo, NO el significado: I like swimming = I like to swim.',
      'Esto NO funciona con todos los verbos: "enjoy", "finish" y "mind" solo aceptan -ing; "want", "decide" y "hope" solo aceptan "to".',
      'Nunca mezcles las dos formas: "to reading" no existe.',
    ],
  },
  commonMistakes: [
    { wrong: '❌ I enjoy to read.', correct: '✅ I enjoy reading.', explanation: '"enjoy" solo acepta -ing. El truco de esta lección (las dos formas) aplica solo a love/like/hate/prefer/begin/start, no a todos los verbos.' },
    { wrong: '❌ I want reading a book.', correct: '✅ I want to read a book.', explanation: '"want" solo acepta "to + verbo". No todos los verbos admiten las dos formas.' },
    { wrong: '❌ She is loving to read.', correct: '✅ She loves reading / She loves to read.', explanation: 'love no se usa en forma continua (is loving) para expresar gusto; usamos love + -ing o love + to.' },
  ],
  vocabulary: [
    { word: 'love', translation_es: 'encantar, amar', level: 'B1', category: 'verbs', partOfSpeech: 'verb', example: 'I love cooking Italian food.', exampleTranslation: 'Me encanta cocinar comida italiana.' },
    { word: 'prefer', translation_es: 'preferir', level: 'B1', category: 'verbs', partOfSpeech: 'verb', example: 'I prefer walking to taking the bus.', exampleTranslation: 'Prefiero caminar a coger el autobús.' },
    { word: 'begin', translation_es: 'empezar', level: 'B1', category: 'verbs', partOfSpeech: 'verb', example: 'He began working at seven.', exampleTranslation: 'Él empezó a trabajar a las siete.' },
    { word: 'start', translation_es: 'empezar, comenzar', level: 'B1', category: 'verbs', partOfSpeech: 'verb', example: 'We started to plan the trip.', exampleTranslation: 'Empezamos a planear el viaje.' },
    { word: 'hate', translation_es: 'odiar', level: 'B1', category: 'verbs', partOfSpeech: 'verb', example: 'They hate driving in the city.', exampleTranslation: 'Odian conducir en la ciudad.' },
  ],
  grammarPoints: [
    {
      id: 'gp-verbs-ing-to-similar',
      level: 'B1',
      name: 'Verbs + -ing or to (similar meaning)',
      explanation_es: 'love, like, hate, prefer, begin y start aceptan tanto -ing como to + verbo sin cambiar el significado. La forma -ing suena más natural con verbos de gusto.',
      formula: 'love/like/hate/prefer/begin/start + -ing  |  love/like/hate/prefer/begin/start + to + verbo',
      examples: ['I love reading.', 'I love to read.', 'She started working.', 'She started to work.'],
    },
  ],
  exercises: [
    {
      id: 'b1-m10-l1-ex1',
      type: 'multiple_choice',
      concept: 'love/like/hate/prefer + ing or to',
      difficulty: 1,
      prompt: 'Completa con una forma correcta: "I love ___ (read) novels."',
      promptTranslation: 'Me encanta leer novelas.',
      correctAnswer: 'reading',
      options: ['reading', 'read', 'to reading'],
      explanation: '"love" acepta -ing o "to + verbo": love reading o love to read. "reading" es correcto; "to reading" no existe.',
    },
    {
      id: 'b1-m10-l1-ex2',
      type: 'multiple_choice',
      concept: 'love/like/hate/prefer + ing or to',
      difficulty: 1,
      prompt: '¿Cuál de las siguientes frases es CORRECTA?',
      promptTranslation: 'Which sentence is correct?',
      correctAnswer: 'They prefer to cook at home.',
      options: ['They prefer to cook at home.', 'They prefer to cooking at home.', 'They prefer cook at home.'],
      explanation: '"prefer" acepta "to + verbo" o "-ing": prefer to cook o prefer cooking. "to cooking" y "prefer cook" son incorrectos.',
    },
    {
      id: 'b1-m10-l1-ex3',
      type: 'fill_blank',
      concept: 'start/begin + ing or to',
      difficulty: 2,
      prompt: 'Completa: "She started ___ (work) here in 2019."',
      promptTranslation: 'Ella empezó a trabajar aquí en 2019.',
      correctAnswer: 'working',
      acceptedAnswers: ['working', 'to work', 'Work'],
      explanation: '"started" acepta -ing o "to + verbo": started working o started to work. Ambas respuestas son correctas.',
    },
    {
      id: 'b1-m10-l1-ex4',
      type: 'true_false',
      concept: 'love + ing or to — same meaning',
      difficulty: 2,
      prompt: '"I hate waiting" y "I hate to wait" significan lo mismo.',
      promptTranslation: '"I hate waiting" and "I hate to wait" mean the same thing.',
      correctAnswer: 'true',
      acceptedAnswers: ['True', 'TRUE', 't'],
      explanation: 'Verdadero: con love/like/hate/prefer, las formas -ing y "to" tienen el mismo significado.',
    },
    {
      id: 'b1-m10-l1-ex5',
      type: 'error_correction',
      concept: 'enjoy only takes -ing',
      difficulty: 3,
      prompt: 'Corrige el error: "I enjoy to watch football."',
      promptTranslation: 'Disfruto viendo el fútbol.',
      correctAnswer: 'I enjoy watching football.',
      acceptedAnswers: ['I enjoy watching football', 'I enjoy watching football.', 'i enjoy watching football'],
      acceptApproximate: true,
      explanation: '"enjoy" solo admite -ing: enjoy watching. La doble forma (-ing / to) solo aplica a love, like, hate, prefer, begin y start.',
    },
    {
      id: 'b1-m10-l1-ex6',
      type: 'translate',
      concept: 'prefer + ing or to',
      difficulty: 3,
      prompt: 'Traduce: "Prefiero beber café."',
      promptTranslation: 'I prefer drinking coffee.',
      correctAnswer: 'I prefer drinking coffee.',
      acceptedAnswers: ['I prefer drinking coffee', 'I prefer drinking coffee.', 'I prefer to drink coffee', 'I prefer to drink coffee.', 'i prefer drinking coffee'],
      acceptApproximate: true,
      explanation: '"Prefiero beber" = prefer drinking o prefer to drink. Ambas formas son correctas.',
    },
    {
      id: 'b1-m10-l1-ex7',
      type: 'match',
      concept: 'verbs + ing or to — matching',
      difficulty: 3,
      prompt: 'Relaciona cada verbo con un ejemplo correcto.',
      promptTranslation: 'Match each verb with a correct example.',
      correctAnswer: 'love=I love dancing salsa.; begin=He began learning English.; prefer=We prefer to eat at home.; hate=She hates getting up early.; start=They started working yesterday.',
      pairs: [
        { left: 'love', right: 'I love dancing salsa.' },
        { left: 'begin', right: 'He began learning English.' },
        { left: 'prefer', right: 'We prefer to eat at home.' },
        { left: 'hate', right: 'She hates getting up early.' },
        { left: 'start', right: 'They started working yesterday.' },
      ],
      explanation: 'love, like, hate, prefer, begin y start aceptan tanto -ing como "to + verbo"; las frases mostradas son ejemplos correctos de cada combinación.',
    },
    {
      id: 'b1-m10-l1-ex8',
      type: 'reorder',
      concept: 'like + ing',
      difficulty: 3,
      prompt: 'Ordena las palabras: She / likes / listening / music / to',
      promptTranslation: 'A ella le gusta escuchar música.',
      correctAnswer: 'She likes listening to music.',
      words: ['She', 'likes', 'listening', 'to', 'music'],
      explanation: 'Orden: sujeto + like(s) + verbo en -ing + to + complemento. → She likes listening to music.',
    },
    {
      id: 'b1-m10-l1-ex9',
      type: 'multiple_choice',
      concept: 'begin + ing or to',
      difficulty: 3,
      prompt: 'Completa con una forma CORRECTA: "He began ___ the guitar at 15."',
      promptTranslation: 'Él empezó a tocar la guitarra a los 15.',
      correctAnswer: 'playing / to play',
      options: ['playing / to play', 'played', 'play'],
      explanation: '"began" acepta -ing o "to + verbo": began playing o began to play. "played" y "play" no funcionan tras "began".',
    },
    {
      id: 'b1-m10-l1-ex10',
      type: 'listening',
      concept: 'love/like/hate + ing listening',
      difficulty: 3,
      prompt: 'Escuchá el audio y respondé las preguntas (en inglés, sobre lo que dice).',
      correctAnswer: '',
      explanation: 'Three people talk about their favorite and least favorite activities. Tom loves playing tennis, Sarah hates waiting in queues, and Mark started learning photography last year.',
      listening: {
        audioText:
          "Hi, I'm Tom. I absolutely love playing tennis. I started playing when I was young, and I've never stopped. I prefer playing outdoors because I like breathing fresh air. What about you? Hi, I'm Sarah. I hate waiting in queues at the supermarket. It's so boring. I also hate being stuck in traffic. My friends like shopping on weekends, but I prefer ordering online from home. Hi, I'm Mark. I love photography. I started learning photography two years ago, and now I begin my day by taking photos. I hate taking bad photos, though.",
        audioUrl: '/audio/tts/b1-m10-l1-ex10.mp3',
        questions: [
          {
            id: 'b1-m10-l1-ex10-q1',
            type: 'multiple_choice',
            concept: 'listening comprehension - love + ing',
            difficulty: 2,
            prompt: 'What sport does Tom love?',
            correctAnswer: 'Tennis',
            options: ['Tennis', 'Football', 'Basketball'],
            explanation: '"I absolutely love playing tennis."',
          },
          {
            id: 'b1-m10-l1-ex10-q2',
            type: 'true_false',
            concept: 'listening comprehension - hate + ing',
            difficulty: 2,
            prompt: 'Sarah likes waiting in queues.',
            correctAnswer: 'false',
            explanation: '"I hate waiting in queues at the supermarket. It\'s so boring."',
          },
          {
            id: 'b1-m10-l1-ex10-q3',
            type: 'multiple_choice',
            concept: 'listening comprehension - begin + ing',
            difficulty: 3,
            prompt: 'How long has Mark been learning photography?',
            correctAnswer: 'Two years',
            options: ['One year', 'Two years', 'Three years'],
            explanation: '"I started learning photography two years ago."',
          },
        ],
      },
    },
    {
      id: 'b1-m10-l1-ex11',
      type: 'writing',
      concept: 'love/like/hate + ing writing',
      difficulty: 3,
      prompt: 'Escribile un email informal a tu amigo contándole qué actividades te encanta, odias o preferís hacer.',
      promptTranslation: 'Write an informal email to a friend about activities you love, hate or prefer doing.',
      correctAnswer: '',
      explanation: 'A good email uses several sentences with love/like/hate/prefer + -ing or to + verbo, maintains an informal register appropriate for a friend, and covers the content points.',
      taskType: 'email',
      targetReader: 'a friend',
      register: 'informal',
      contentPoints: ['At least two activities you love or like doing', 'At least one activity you hate or prefer not to do'],
      requiresOwnIdea: true,
      minWords: 60,
      maxWords: 100,
    },
    {
      id: 'b1-m10-l1-ex12',
      type: 'speaking',
      concept: 'love/like/hate + ing pronunciation',
      difficulty: 2,
      prompt: 'Escuchá la frase modelo y repetila en voz alta.',
      correctAnswer: 'I love reading, and she prefers to cook.',
      explanation: 'Practice the pronunciation of "love" (/lʌv/) and "prefer" (/prɪˈfɜr/), and pay attention to linking the gerund (-ing) smoothly to the preceding verb.',
      speakingMode: 'repeat',
    },
  ],
  miniTest: [
    {
      id: 'b1-m10-l1-mt1',
      type: 'multiple_choice',
      concept: 'like + ing or to',
      difficulty: 1,
      prompt: 'Completa: "I like ___ (swim) in summer."',
      promptTranslation: 'Me gusta nadar en verano.',
      correctAnswer: 'swimming',
      options: ['swimming', 'swim', 'to swimming'],
      explanation: '"like" acepta -ing (swimming) o "to + verbo" (to swim).',
    },
    {
      id: 'b1-m10-l1-mt2',
      type: 'fill_blank',
      concept: 'hate + ing',
      difficulty: 2,
      prompt: 'Completa: "We hate ___ (clean) the kitchen."',
      promptTranslation: 'Odiamos limpiar la cocina.',
      correctAnswer: 'cleaning',
      acceptedAnswers: ['cleaning', 'to clean'],
      explanation: '"hate" acepta -ing (cleaning) o "to + verbo" (to clean).',
    },
    {
      id: 'b1-m10-l1-mt3',
      type: 'true_false',
      concept: 'enjoy only -ing',
      difficulty: 2,
      prompt: 'La frase "She enjoys to cook" es correcta.',
      promptTranslation: 'The sentence "She enjoys to cook" is correct.',
      correctAnswer: 'false',
      acceptedAnswers: ['False', 'FALSE', 'f'],
      explanation: 'Falso. "enjoy" solo acepta -ing: She enjoys cooking.',
    },
    {
      id: 'b1-m10-l1-mt4',
      type: 'translate',
      concept: 'love + ing or to',
      difficulty: 3,
      prompt: 'Traduce: "Me encanta viajar."',
      promptTranslation: 'I love travelling.',
      correctAnswer: 'I love travelling.',
      acceptedAnswers: ['I love travelling', 'I love travelling.', 'I love to travel', 'I love to travel.', 'i love travelling'],
      acceptApproximate: true,
      explanation: '"Me encanta viajar" = I love travelling o I love to travel. Ambas son correctas.',
    },
    {
      id: 'b1-m10-l1-mt5',
      type: 'multiple_choice',
      concept: 'prefer + ing or to',
      difficulty: 3,
      prompt: '¿Cuál es la forma correcta? "They ___ walking to work."',
      promptTranslation: 'Prefieren ir al trabajo andando.',
      correctAnswer: 'prefer',
      options: ['prefer', 'prefers', 'are prefer'],
      explanation: 'Con "they" usamos "prefer" (sin -s), y "walking" es el gerundio que sigue a "prefer".',
    },
  ],
  reviewItems: ['b1-m9-l4'],
  prerequisites: ['b1-m9-l4'],
}
