import type { Lesson } from '../../types'

export const lesson124MiniTest: Lesson = {
  id: 'b1-m12-l4',
  moduleId: 'm12-used-to-tags',
  order: 3,
  title: 'Mini-test: used to / would + tag questions',
  objective: 'Evaluar todo el módulo: used to (hábitos y estados del pasado), would para hábitos en narraciones, y tag questions.',
  explanation_es: `Esta es la evaluación final del Módulo 12. Repasemos lo esencial:

1) used to (hábitos y estados pasados que ya no son ciertos):
- Afirmativo: used to + verbo: I used to play football.
- Negativo: didn't use to + verbo: We didn't use to have internet.
- Pregunta: Did + sujeto + use to + verbo?: Did you use to smoke?

2) would (hábitos pasados en narraciones, tono nostálgico):
- would + verbo en forma base (sin "to"): I would go fishing every summer.
- Solo hábitos, NO estados: ❌ She would live in Barcelona → ✅ She used to live in Barcelona.

3) Tag questions (¿verdad?, ¿no es cierto?):
- Afirmativa + tag negativa: You are Spanish, aren't you?
- Negativa + tag afirmativa: It isn't cold, is it?
- Usan el mismo auxiliar/modal y el pronombre correcto: doesn't she? / haven't they? / can't you?

Errores típicos:
- ❌ I didn't used to → ✅ I didn't use to.
- ❌ I would to go → ✅ I would go.
- ❌ You don't like it, don't you? → ✅ You don't like it, do you?`,
  examples: [
    { english: 'I used to play football when I was a kid.', spanish: 'Solía jugar al fútbol cuando era niño.' },
    { english: 'Did you use to smoke?', spanish: '¿Solías fumar?' },
    { english: 'When I was young, I would go fishing every summer.', spanish: 'Cuando era joven, solía ir a pescar cada verano.' },
    { english: 'She used to live in Barcelona.', spanish: 'Ella vivía en Barcelona.' },
    { english: 'You are Spanish, aren\'t you?', spanish: 'Tú eres español, ¿verdad?' },
    { english: 'It isn\'t cold, is it?', spanish: 'No hace frío, ¿verdad?' },
  ],
  rule: `**Resumen del módulo:**
- used to + verbo (pasado): afirmativo used to / negativo didn't use to / pregunta Did...use to?
- would + forma base: hábitos pasados en narración (no estados).
- Tag questions: afirmativa + tag negativa / negativa + tag afirmativa.`,
  commonMistakes: [
    { wrong: '❌ I didn\'t used to smoke.', correct: '✅ I didn\'t use to smoke.', explanation: 'Después de "didn\'t" usamos "use to" (sin -d).' },
    { wrong: '❌ I would to go fishing.', correct: '✅ I would go fishing.', explanation: 'Tras "would" va la forma base sin "to".' },
    { wrong: '❌ You don\'t like it, don\'t you?', correct: '✅ You don\'t like it, do you?', explanation: 'Negativa + tag afirmativa: do you?' },
    { wrong: '❌ She would live in Barcelona.', correct: '✅ She used to live in Barcelona.', explanation: '"would" no expresa estados; solo hábitos.' },
  ],
  vocabulary: [],
  grammarPoints: [],
  exercises: [
    {
      id: 'b1-m12-l4-ex1',
      type: 'multiple_choice',
      concept: 'module 12 - used to affirmative',
      difficulty: 1,
      prompt: 'Completa: "I ___ to play football when I was a kid."',
      promptTranslation: 'Solía jugar al fútbol cuando era niño.',
      correctAnswer: 'used',
      options: ['used', 'use', 'using'],
      explanation: 'Afirmativo: used to + verbo.',
    },
    {
      id: 'b1-m12-l4-ex2',
      type: 'fill_blank',
      concept: 'module 12 - negative use to',
      difficulty: 2,
      prompt: 'Completa: "We didn\'t ___ to have internet."',
      promptTranslation: 'No solíamos tener internet.',
      correctAnswer: 'use',
      acceptedAnswers: ['use', 'Use'],
      explanation: 'Negativo: didn\'t + use to (sin -d).',
    },
    {
      id: 'b1-m12-l4-ex3',
      type: 'multiple_choice',
      concept: 'module 12 - would + base form',
      difficulty: 2,
      prompt: 'Completa: "She ___ always wake up early."',
      promptTranslation: 'Ella siempre se despertaba temprano.',
      correctAnswer: 'would',
      options: ['would', 'used to', 'will'],
      explanation: 'Hábito pasado en narración: would + always + verbo.',
    },
    {
      id: 'b1-m12-l4-ex4',
      type: 'error_correction',
      concept: 'module 12 - didn\'t use to',
      difficulty: 3,
      prompt: 'Corrige el error: "They didn\'t used to eat meat."',
      promptTranslation: 'No solían comer carne.',
      correctAnswer: 'They didn\'t use to eat meat.',
      acceptedAnswers: ['They didn\'t use to eat meat', 'They didn\'t use to eat meat.', 'they didn\'t use to eat meat'],
      acceptApproximate: true,
      explanation: 'Tras "didn\'t" la forma es "use to": didn\'t use to eat.',
    },
    {
      id: 'b1-m12-l4-ex5',
      type: 'reading',
      concept: 'module 12 - a memoir',
      difficulty: 4,
      prompt: 'Lee la memoria de infancia y responde las preguntas.',
      promptTranslation: 'Read the childhood memoir and answer the questions.',
      reading: {
        text: 'Remembering my grandfather\nI remember my grandfather very well. He used to have a small farm near the river, and every summer I would spend my holidays there. We would wake up at six o\'clock, and he would tell me stories about his youth while we had breakfast. My grandmother used to bake bread every morning; the whole house would smell wonderful. When I was a child, I didn\'t use to like vegetables, so my grandmother would hide them in my soup. Years later, she told me: "You used to be a clever child!" Now that I am an adult, I still visit the farm. It isn\'t the same, but I love it, don\'t I? Well, I certainly do.',
        translation: 'Recordando a mi abuelo\nRecuerdo muy bien a mi abuelo. Solía tener una pequeña granja cerca del río, y cada verano pasaba mis vacaciones allí. Nos despertábamos a las seis, y él me contaba historias sobre su juventud mientras desayunábamos. Mi abuela solía hacer pan cada mañana; toda la casa olía de maravilla. Cuando era niño, no solía gustarme las verduras, así que mi abuela las escondía en mi sopa. Años después, me dijo: "¡Eras un niño listo!" Ahora que soy adulto, todavía visito la granja. No es lo mismo, pero me encanta, ¿a que sí? Pues, ciertamente sí.',
        questions: [
          {
            id: 'b1-m12-l4-ex5-q1',
            type: 'multiple_choice',
            concept: 'module 12 - used to for states',
            difficulty: 4,
            prompt: '¿Qué tenía el abuelo cerca del río?',
            correctAnswer: 'Una pequeña granja.',
            options: ['Una pequeña granja.', 'Una panadería.', 'Un restaurante.'],
            explanation: '"He used to have a small farm near the river." (estado pasado → used to).',
          },
          {
            id: 'b1-m12-l4-ex5-q2',
            type: 'multiple_choice',
            concept: 'module 12 - would for habits',
            difficulty: 4,
            prompt: '¿Qué hacían por las mañanas en la granja?',
            correctAnswer: 'Se despertaban a las seis y desayunaban con historias.',
            options: ['Se despertaban a las seis y desayunaban con historias.', 'Trabajaban en el río.', 'Escondían verduras en el jardín.'],
            explanation: '"We would wake up at six... and he would tell me stories... while we had breakfast." (hábitos → would).',
          },
          {
            id: 'b1-m12-l4-ex5-q3',
            type: 'multiple_choice',
            concept: 'module 12 - used to negative',
            difficulty: 4,
            prompt: '¿Qué no solía gustarle al narrador?',
            correctAnswer: 'Las verduras.',
            options: ['Las verduras.', 'Las historias.', 'El pan.'],
            explanation: '"I didn\'t use to like vegetables." (negativo → didn\'t use to).',
          },
          {
            id: 'b1-m12-l4-ex5-q4',
            type: 'multiple_choice',
            concept: 'module 12 - reading comprehension',
            difficulty: 4,
            prompt: '¿Qué hacía la abuela con las verduras?',
            correctAnswer: 'Las escondía en la sopa.',
            options: ['Las escondía en la sopa.', 'Las tiraba al río.', 'Las vendía en el mercado.'],
            explanation: '"My grandmother would hide them in my soup."',
          },
          {
            id: 'b1-m12-l4-ex5-q5',
            type: 'multiple_choice',
            concept: 'module 12 - tag question',
            difficulty: 4,
            prompt: 'En la última frase, "I love it, don\'t I?" es una tag question. ¿Qué expresa?',
            correctAnswer: 'Pedir confirmación de que le encanta.',
            options: ['Pedir confirmación de que le encanta.', 'Expresar una obligación.', 'Hablar de un estado del pasado.'],
            explanation: 'La tag question confirma la información: afirmativa + tag negativa (don\'t I?).',
          },
        ],
      },
      correctAnswer: 'reading complete',
      explanation: 'El texto practica used to para estados (used to have a small farm, used to be clever), used to en negativo (didn\'t use to like), would para hábitos en narración (would spend, would wake up, would tell, would smell, would hide) y una tag question (I love it, don\'t I?).',
    },
    {
      id: 'b1-m12-l4-ex6',
      type: 'reorder',
      concept: 'module 12 - used to question',
      difficulty: 3,
      prompt: 'Ordena las palabras: Did / you / use / to / smoke?',
      promptTranslation: '¿Solías fumar?',
      correctAnswer: 'Did you use to smoke?',
      words: ['Did', 'you', 'use', 'to', 'smoke?'],
      explanation: 'Pregunta: Did + sujeto + use to + verbo. → Did you use to smoke?',
    },
    {
      id: 'b1-m12-l4-ex7',
      type: 'translate',
      concept: 'module 12 - used to negative',
      difficulty: 3,
      prompt: 'Traduce: "No solíamos tener internet."',
      promptTranslation: 'We didn\'t use to have internet.',
      correctAnswer: 'We didn\'t use to have internet.',
      acceptedAnswers: ['We didn\'t use to have internet', 'We didn\'t use to have internet.', 'we didn\'t use to have internet'],
      acceptApproximate: true,
      explanation: 'Negativo: didn\'t + use to + verbo.',
    },
    {
      id: 'b1-m12-l4-ex8',
      type: 'match',
      concept: 'module 12 - review matching',
      difficulty: 3,
      prompt: 'Relaciona cada frase con su traducción.',
      promptTranslation: 'Match each sentence with its translation.',
      correctAnswer: 'I used to play football.=Solía jugar al fútbol.; She would always wake up early.=Ella siempre se despertaba temprano.; Did you use to smoke?=¿Solías fumar?; You are Spanish, aren\'t you?=Eres español, ¿verdad?; It isn\'t cold, is it?=No hace frío, ¿verdad?',
      pairs: [
        { left: 'I used to play football.', right: 'Solía jugar al fútbol.' },
        { left: 'She would always wake up early.', right: 'Ella siempre se despertaba temprano.' },
        { left: 'Did you use to smoke?', right: '¿Solías fumar?' },
        { left: 'You are Spanish, aren\'t you?', right: 'Eres español, ¿verdad?' },
        { left: 'It isn\'t cold, is it?', right: 'No hace frío, ¿verdad?' },
      ],
      explanation: 'Repaso de used to (afirmativo, pregunta), would (hábitos) y tag questions (afirmativa + negativa, negativa + afirmativa).',
    },
    {
      id: 'b1-m12-l4-ex9',
      type: 'true_false',
      concept: 'module 12 - would for states',
      difficulty: 3,
      prompt: 'Podemos usar "would" para expresar estados del pasado como "tener" o "vivir".',
      promptTranslation: 'We can use "would" to express past states like "having" or "living".',
      correctAnswer: 'false',
      acceptedAnswers: ['False', 'FALSE', 'f'],
      explanation: 'Falso. "would" solo expresa hábitos. Para estados pasados usamos "used to".',
    },
    {
      id: 'b1-m12-l4-ex10',
      type: 'multiple_choice',
      concept: 'module 12 - tag question opposite signs',
      difficulty: 4,
      prompt: 'Completa: "They haven\'t finished, ___ they?"',
      promptTranslation: 'No han terminado, ¿verdad?',
      correctAnswer: 'have',
      options: ['have', 'haven\'t', 'do'],
      explanation: 'Oración negativa ("haven\'t") → tag afirmativa con el mismo auxiliar: have they?',
    },
    {
      id: 'b1-m12-l4-ex11',
      type: 'listening',
      concept: 'module 12 - integrated listening',
      difficulty: 4,
      prompt: 'Escuchá el audio y respondé las preguntas (en inglés, sobre lo que dice).',
      correctAnswer: '',
      explanation: 'Un podcast sobre los cambios en la vida de una persona: sus hábitos de la infancia (used to/would), y confirmaciones sobre su presente (tag questions).',
      listening: {
        audioText:
          "Hello, this is My Story podcast. Today I\'m talking to Lisa about her journey. So Lisa, you grew up in the countryside, didn\'t you? Yes, when I was young, I used to wake up very early and I would help my parents on the farm. My siblings and I would run around the fields all day. We didn\'t use to have much money, but we were happy. Now you live in the city, don\'t you? That\'s right. I moved here five years ago. I work in a big office, and I haven\'t looked back since. You miss the countryside sometimes, don\'t you? Of course I do! But life moves on, doesn\'t it?",
        questions: [
          {
            id: 'b1-m12-l4-ex11-q1',
            type: 'multiple_choice',
            concept: 'module 12 - integrated comprehension',
            difficulty: 3,
            prompt: 'Where did Lisa grow up?',
            correctAnswer: 'In the countryside',
            options: ['In the countryside', 'In a big city', 'On an island'],
            explanation: '"You grew up in the countryside, didn\'t you?"',
          },
          {
            id: 'b1-m12-l4-ex11-q2',
            type: 'true_false',
            concept: 'module 12 - would for habits',
            difficulty: 3,
            prompt: 'Lisa used to have a lot of money when she was young.',
            correctAnswer: 'false',
            explanation: '"We didn\'t use to have much money, but we were happy."',
          },
          {
            id: 'b1-m12-l4-ex11-q3',
            type: 'multiple_choice',
            concept: 'module 12 - tag questions in context',
            difficulty: 4,
            prompt: 'How long ago did Lisa move to the city?',
            correctAnswer: 'Five years ago',
            options: ['Two years ago', 'Five years ago', 'Ten years ago'],
            explanation: '"I moved here five years ago."',
          },
        ],
      },
    },
    {
      id: 'b1-m12-l4-ex12',
      type: 'writing',
      concept: 'module 12 - integrated writing',
      difficulty: 4,
      prompt: 'Escribí una carta informal a un viejo amigo contando sobre tus hábitos pasados (used to/would) y confirmando algunos cambios en tu vida (con tag questions).',
      promptTranslation: 'Write an informal letter to an old friend about your past habits and confirming changes in your life.',
      correctAnswer: '',
      explanation: 'Un buen texto integra los tres temas del módulo: used to para hábitos/estados, would para narración nostálgica, y tag questions para confirmar información.',
      taskType: 'email',
      targetReader: 'an old friend',
      register: 'informal',
      contentPoints: ['Descripciones de hábitos pasados usando used to/would', 'Al menos una tag question'],
      requiresOwnIdea: true,
      minWords: 60,
      maxWords: 100,
    },
    {
      id: 'b1-m12-l4-ex13',
      type: 'speaking',
      concept: 'module 12 - integrated speaking',
      difficulty: 3,
      prompt: 'Escuchá la frase modelo y repetila en voz alta.',
      correctAnswer: 'I used to live near the beach, but now I work in the city, don\'t I?',
      explanation: 'Practicá la pronunciación integrando used to, una transición con "but" y una tag question al final.',
      speakingMode: 'repeat',
    },
  ],
  miniTest: [
    {
      id: 'b1-m12-l4-mt1',
      type: 'multiple_choice',
      concept: 'module 12 final - used to',
      difficulty: 1,
      prompt: 'Completa: "She ___ to live in Barcelona."',
      promptTranslation: 'Ella vivía en Barcelona.',
      correctAnswer: 'used',
      options: ['used', 'use', 'using'],
      explanation: 'Estado pasado: used to live.',
    },
    {
      id: 'b1-m12-l4-mt2',
      type: 'fill_blank',
      concept: 'module 12 final - would',
      difficulty: 2,
      prompt: 'Completa: "He would ___ (tell) us stories."',
      promptTranslation: 'Él nos contaba historias.',
      correctAnswer: 'tell',
      acceptedAnswers: ['tell', 'Tell'],
      explanation: 'would + forma base (sin "to"): would tell.',
    },
    {
      id: 'b1-m12-l4-mt3',
      type: 'error_correction',
      concept: 'module 12 final - tag question',
      difficulty: 3,
      prompt: 'Corrige el error: "You don\'t like it, don\'t you?"',
      promptTranslation: 'No te gusta, ¿verdad?',
      correctAnswer: 'You don\'t like it, do you?',
      acceptedAnswers: ['You don\'t like it, do you?', 'You don\'t like it, do you', 'you don\'t like it, do you?'],
      acceptApproximate: true,
      explanation: 'Negativa → tag afirmativa: do you?',
    },
    {
      id: 'b1-m12-l4-mt4',
      type: 'translate',
      concept: 'module 12 final - would',
      difficulty: 3,
      prompt: 'Traduce: "Solía ir a pescar cada verano."',
      promptTranslation: 'I would go fishing every summer.',
      correctAnswer: 'I would go fishing every summer.',
      acceptedAnswers: ['I would go fishing every summer', 'I would go fishing every summer.', 'I used to go fishing every summer', 'i would go fishing every summer'],
      acceptApproximate: true,
      explanation: 'Hábito pasado en narración: would go fishing (o used to go fishing).',
    },
    {
      id: 'b1-m12-l4-mt5',
      type: 'multiple_choice',
      concept: 'module 12 final - which is correct',
      difficulty: 4,
      prompt: '¿Cuál es la frase correcta?',
      promptTranslation: 'Which sentence is correct?',
      correctAnswer: 'You can swim, can\'t you?',
      options: ['You can swim, can\'t you?', 'You can swim, do you?', 'You can swim, can you?'],
      explanation: 'Modal "can" en afirmativa → tag negativa: can\'t you?',
    },
  ],
  reviewItems: ['b1-m12-l3'],
  prerequisites: ['b1-m12-l3'],
}
