import type { Exam } from '../types'

// B1 Preliminary (PET) — formato Cambridge English, adaptado a esta app.
// Estructura de papeles (el Speaking, no evaluado en esta versión):
//  • Reading  (Paper 1): Part 1 avisos, Part 2 matching, Part 3 texto largo MCQ,
//    Part 4 gapped text, Part 5 MC cloze, Part 6 open cloze
//  • Writing  (Paper 2): Part 1 sentence transformations, Part 2 open task (email/artículo/historia)
//  • Listening(Paper 3): Part 1 MCQ cortos, Part 2 MCQ monólogo, Part 3 gap-fill, Part 4 T/F
export const b1FinalExam: Exam = {
  id: 'b1-final',
  levelId: 'b1',
  title: 'Examen Final B1 (Preliminary)',
  description:
    'Examen final B1 siguiendo la estructura del Cambridge English Preliminary (PET): comprensión de lectura, expresión escrita y comprensión auditiva. El speaking no se evalúa en esta versión.',
  sections: [
    {
      name: 'Reading',
      weight: 35,
      exercises: [
        // ---- Part 1: avisos y textos cortos (MCQ) ----
        {
          id: 'b1-final-r-p1-1',
          type: 'multiple_choice',
          concept: 'reading notices',
          difficulty: 2,
          prompt: 'Ves este aviso: "NO PARKING: Residents only". ¿Qué significa?',
          correctAnswer: 'Solo los residentes pueden estacionar aquí.',
          options: [
            'Solo los residentes pueden estacionar aquí.',
            'Nadie puede estacionar aquí nunca.',
            'Los visitantes pueden estacionar gratis.',
          ],
          explanation: 'El aviso indica que el estacionamiento está prohibido salvo para residentes.',
        },
        {
          id: 'b1-final-r-p1-2',
          type: 'multiple_choice',
          concept: 'reading notices',
          difficulty: 2,
          prompt: 'Ves este cartel: "SALE: 50% off all shoes this weekend only". ¿Qué significa?',
          correctAnswer: 'Los zapatos tienen 50% de descuento solo este fin de semana.',
          options: [
            'Los zapatos tienen 50% de descuento solo este fin de semana.',
            'Los zapatos siempre tienen 50% de descuento.',
            'Solo un tipo de zapato tiene descuento.',
          ],
          explanation: '"This weekend only" indica que la oferta es temporal y aplica a todos los zapatos.',
        },
        {
          id: 'b1-final-r-p1-3',
          type: 'multiple_choice',
          concept: 'reading notices',
          difficulty: 2,
          prompt: 'Ves esta etiqueta: "Keep refrigerated after opening". ¿Qué debes hacer?',
          correctAnswer: 'Guardar el producto en la heladera después de abrirlo.',
          options: [
            'Guardar el producto en la heladera después de abrirlo.',
            'Tirar el producto después de abrirlo.',
            'Cocinar el producto antes de abrirlo.',
          ],
          explanation: '"Keep refrigerated" = conservar en frío, "after opening" = después de abrir.',
        },
        {
          id: 'b1-final-r-p1-4',
          type: 'multiple_choice',
          concept: 'reading notices',
          difficulty: 2,
          prompt: 'Ves este mensaje: "Meeting moved to 3 p.m. Please bring your report." ¿Qué debes hacer?',
          correctAnswer: 'Ir a la reunión a las 3 p.m. con tu informe.',
          options: [
            'Ir a la reunión a las 3 p.m. con tu informe.',
            'Cancelar la reunión de las 3 p.m.',
            'Enviar tu informe por correo antes de las 3 p.m.',
          ],
          explanation: 'El aviso informa un cambio de horario y pide llevar el informe a la reunión.',
        },
        {
          id: 'b1-final-r-p1-5',
          type: 'multiple_choice',
          concept: 'reading notices',
          difficulty: 2,
          prompt: 'Ves esta señal: "Mind the gap". ¿Dónde la ves normalmente?',
          correctAnswer: 'En el metro o tren, para avisar del espacio entre el tren y el andén.',
          options: [
            'En el metro o tren, para avisar del espacio entre el tren y el andén.',
            'En un supermercado, sobre las góndolas.',
            'En un parque, junto a los juegos infantiles.',
          ],
          explanation: '"Mind the gap" es el clásico aviso de las estaciones de metro/tren.',
        },

        // ---- Part 2: matching personas con textos ----
        {
          id: 'b1-final-r-p2',
          type: 'match',
          concept: 'reading matching',
          difficulty: 3,
          prompt: 'Relacioná cada persona con el texto que mejor se adapta a sus intereses.',
          correctAnswer: 'matching complete',
          pairs: [
            { left: 'Ana: quiere aprender a cocinar platos rápidos.', right: 'Curso "Cenas en 20 minutos"' },
            { left: 'Pedro: busca trabajo de medio tiempo por las mañanas.', right: 'Aviso: "Se busca repartidor, turno mañana"' },
            { left: 'Lucía: quiere mejorar su inglés conversando.', right: 'Club de conversación en inglés, los jueves' },
            { left: 'Marco: necesita arreglar su bicicleta.', right: 'Taller de bicicletas: reparación en el día' },
          ],
          explanation: 'Cada persona se empareja con el texto que cubre exactamente su necesidad.',
        },

        // ---- Part 3: texto largo con MCQ ----
        {
          id: 'b1-final-r-p3',
          type: 'reading',
          concept: 'reading comprehension',
          difficulty: 3,
          prompt: 'Lee el texto y responde las preguntas.',
          reading: {
            text:
              'Last Saturday, the small town of Oakville celebrated its annual food festival. More than three thousand people visited the main square, where local restaurants offered dishes from all over the world. The most popular stand was the Italian one, which sold fresh pasta made in front of the visitors. The festival also included cooking workshops for children and a competition for the best homemade cake. Maria, who organised the event, said she was very happy with the result and that they were already planning next year\'s festival.',
            translation:
              'El sábado pasado, la pequeña ciudad de Oakville celebró su festival anual de comida. Más de tres mil personas visitaron la plaza principal, donde restaurantes locales ofrecieron platos de todo el mundo. El puesto más popular fue el italiano, que vendía pasta fresca hecha delante de los visitantes. El festival también incluyó talleres de cocina para niños y un concurso del mejor pastel casero. María, quien organizó el evento, dijo que estaba muy contenta con el resultado y que ya estaban planeando el festival del próximo año.',
            questions: [
              {
                id: 'b1-final-r-p3-q1',
                type: 'multiple_choice',
                concept: 'reading comprehension',
                difficulty: 3,
                prompt: '¿Cuántas personas visitaron el festival?',
                correctAnswer: 'Más de tres mil.',
                options: ['Más de tres mil.', 'Trescientas.', 'Tres millones.'],
                explanation: 'El texto dice "More than three thousand people visited the main square".',
              },
              {
                id: 'b1-final-r-p3-q2',
                type: 'multiple_choice',
                concept: 'reading comprehension',
                difficulty: 3,
                prompt: '¿Qué tenía de especial el puesto italiano?',
                correctAnswer: 'Hacían la pasta delante de los visitantes.',
                options: [
                  'Hacían la pasta delante de los visitantes.',
                  'Era el único que vendía comida.',
                  'Solo vendía pasteles.',
                ],
                explanation: 'El texto dice que vendían "fresh pasta made in front of the visitors".',
              },
              {
                id: 'b1-final-r-p3-q3',
                type: 'multiple_choice',
                concept: 'reading comprehension',
                difficulty: 3,
                prompt: '¿Qué actividades había para los niños?',
                correctAnswer: 'Talleres de cocina.',
                options: ['Talleres de cocina.', 'Un concierto.', 'Una carrera.'],
                explanation: 'El texto menciona "cooking workshops for children".',
              },
              {
                id: 'b1-final-r-p3-q4',
                type: 'multiple_choice',
                concept: 'reading comprehension',
                difficulty: 3,
                prompt: '¿Qué piensa Maria, la organizadora?',
                correctAnswer: 'Está contenta y ya planea el próximo festival.',
                options: [
                  'Está contenta y ya planea el próximo festival.',
                  'Está cansada y no repetirá el evento.',
                  'Está enojada porque hubo pocas personas.',
                ],
                explanation: 'El texto dice que "was very happy with the result and that they were already planning next year\'s festival".',
              },
            ],
          },
          correctAnswer: 'reading complete',
          explanation: 'Comprensión lectora de un texto narrativo sobre un evento local.',
        },

        // ---- Part 4: gapped text (elegir oración que completa cada espacio) ----
        {
          id: 'b1-final-r-p4',
          type: 'reading',
          concept: 'reading gapped text',
          difficulty: 4,
          prompt: 'Seis oraciones han sido quitadas del texto. Elegí para cada espacio la oración que mejor lo completa.',
          reading: {
            text:
              'James decided to start running last spring. [1] ___ At first, he could only run for ten minutes without stopping. [2] ___ He also bought a pair of proper running shoes. [3] ___ Now, after six months, he runs five kilometres every morning. [4] ___ His doctor says that running has improved his health a lot. [5] ___',
            translation:
              'James decidió empezar a correr la primavera pasada. [1] ___ Al principio solo podía correr diez minutos sin parar. [2] ___ También compró un par de zapatillas adecuadas. [3] ___ Ahora, después de seis meses, corre cinco kilómetros cada mañana. [4] ___ Su doctor dice que correr ha mejorado mucho su salud. [5] ___',
            questions: [
              {
                id: 'b1-final-r-p4-q1',
                type: 'select_correct',
                concept: 'reading gapped text',
                difficulty: 4,
                prompt: 'Elegí la oración para el espacio [1]:',
                correctAnswer: 'He wanted to get fit after a long winter.',
                options: [
                  'He wanted to get fit after a long winter.',
                  'The weather was terrible that weekend.',
                  'He sold his car to pay for lessons.',
                  'Running is the cheapest sport in the world.',
                ],
                explanation: 'Después de "start running last spring", lo lógico es explicar su motivación: quería ponerse en forma.',
              },
              {
                id: 'b1-final-r-p4-q2',
                type: 'select_correct',
                concept: 'reading gapped text',
                difficulty: 4,
                prompt: 'Elegí la oración para el espacio [2]:',
                correctAnswer: 'He joined a running club to stay motivated.',
                options: [
                  'He joined a running club to stay motivated.',
                  'His friends prefer to watch football on TV.',
                  'The park was closed for repairs.',
                  'He had never liked vegetables.',
                ],
                explanation: 'Tras mencionar las dificultades iniciales, unirse a un club es un paso lógico para mejorar.',
              },
              {
                id: 'b1-final-r-p4-q3',
                type: 'select_correct',
                concept: 'reading gapped text',
                difficulty: 4,
                prompt: 'Elegí la oración para el espacio [3]:',
                correctAnswer: 'The new shoes made a big difference.',
                options: [
                  'The new shoes made a big difference.',
                  'He stopped running completely.',
                  'His mother cooked dinner every night.',
                  'Traffic was heavy in the city.',
                ],
                explanation: 'Se acaba de mencionar la compra de zapatillas; esta oración explica su efecto.',
              },
              {
                id: 'b1-final-r-p4-q4',
                type: 'select_correct',
                concept: 'reading gapped text',
                difficulty: 4,
                prompt: 'Elegí la oración para el espacio [4]:',
                correctAnswer: 'He feels much more energetic than before.',
                options: [
                  'He feels much more energetic than before.',
                  'He decided to give up running.',
                  'His shoes are still in the shop.',
                  'He moved to a different city.',
                ],
                explanation: 'Después de describir su progreso, la consecuencia personal (más energía) encaja aquí.',
              },
              {
                id: 'b1-final-r-p4-q5',
                type: 'select_correct',
                concept: 'reading gapped text',
                difficulty: 4,
                prompt: 'Elegí la oración para el espacio [5]:',
                correctAnswer: 'In fact, he has already signed up for a race.',
                options: [
                  'In fact, he has already signed up for a race.',
                  'He never goes outside anymore.',
                  'The doctor told him to stop running.',
                  'He forgot his running shoes at home.',
                ],
                explanation: 'La mención de su buena salud prepara un cierre positivo: ya se anotó en una carrera.',
              },
            ],
          },
          correctAnswer: 'reading complete',
          explanation: 'Gapped text: elegir la oración que da coherencia lógica al texto.',
        },

        // ---- Part 5: MC cloze (gramática y vocabulario) ----
        {
          id: 'b1-final-r-p5-1',
          type: 'select_correct',
          concept: 'mc cloze',
          difficulty: 3,
          prompt: 'Elegí la palabra correcta: "I have lived in this city ___ 2015."',
          correctAnswer: 'since',
          options: ['since', 'for', 'ago'],
          explanation: '"Since" se usa con un punto de inicio (2015); "for" con duración.',
        },
        {
          id: 'b1-final-r-p5-2',
          type: 'select_correct',
          concept: 'mc cloze',
          difficulty: 3,
          prompt: 'Elegí la palabra correcta: "She is interested ___ learning French."',
          correctAnswer: 'in',
          options: ['in', 'on', 'at'],
          explanation: 'La preposición correcta tras "interested" es "in": interested in.',
        },
        {
          id: 'b1-final-r-p5-3',
          type: 'select_correct',
          concept: 'mc cloze',
          difficulty: 3,
          prompt: 'Elegí la palabra correcta: "We ___ watch TV when the phone rang."',
          correctAnswer: 'were watching',
          options: ['were watching', 'watched', 'have watched'],
          explanation: 'Past continuous describe la acción en progreso interrumpida por otra (past simple).',
        },
        {
          id: 'b1-final-r-p5-4',
          type: 'select_correct',
          concept: 'mc cloze',
          difficulty: 3,
          prompt: 'Elegí la palabra correcta: "This is the book ___ I told you about."',
          correctAnswer: 'that',
          options: ['that', 'who', 'whose'],
          explanation: '"That" es relativo correcto para cosas: the book that I told you about.',
        },
        {
          id: 'b1-final-r-p5-5',
          type: 'select_correct',
          concept: 'mc cloze',
          difficulty: 3,
          prompt: 'Elegí la palabra correcta: "If it rains tomorrow, we ___ at home."',
          correctAnswer: 'will stay',
          options: ['will stay', 'would stay', 'stayed'],
          explanation: 'Primer condicional: if + present, will + infinitivo.',
        },

        // ---- Part 6: open cloze (escribir la palabra) ----
        {
          id: 'b1-final-r-p6-1',
          type: 'fill_blank',
          concept: 'open cloze',
          difficulty: 3,
          prompt: 'Escribí la palabra que falta: "I\'m going to the supermarket ___ I need some bread."',
          correctAnswer: 'because',
          acceptedAnswers: ['because'],
          explanation: 'El conector "because" introduce la razón.',
        },
        {
          id: 'b1-final-r-p6-2',
          type: 'fill_blank',
          concept: 'open cloze',
          difficulty: 3,
          prompt: 'Escribí la palabra que falta: "She doesn\'t eat meat, ___ she? No, she doesn\'t."',
          correctAnswer: 'does',
          acceptedAnswers: ['does'],
          explanation: 'Question tag con "doesn\'t" (negativa) → "does" (afirmativa).',
        },
        {
          id: 'b1-final-r-p6-3',
          type: 'fill_blank',
          concept: 'open cloze',
          difficulty: 3,
          prompt: 'Escribí la palabra que falta: "This house is bigger ___ mine."',
          correctAnswer: 'than',
          acceptedAnswers: ['than'],
          explanation: 'Comparativo: bigger than.',
        },
        {
          id: 'b1-final-r-p6-4',
          type: 'fill_blank',
          concept: 'open cloze',
          difficulty: 3,
          prompt: 'Escribí la palabra que falta: "___ you like a cup of tea? Yes, please."',
          correctAnswer: 'Would',
          acceptedAnswers: ['Would'],
          explanation: '"Would you like...?" es la forma educada de ofrecer algo.',
        },
        {
          id: 'b1-final-r-p6-5',
          type: 'fill_blank',
          concept: 'open cloze',
          difficulty: 3,
          prompt: 'Escribí la palabra que falta: "She has lived here ___ five years."',
          correctAnswer: 'for',
          acceptedAnswers: ['for'],
          explanation: '"For" indica duración (five years); "since" un punto de inicio.',
        },
      ],
    },
    {
      name: 'Writing',
      weight: 30,
      exercises: [
        // ---- Part 1: sentence transformations ----
        {
          id: 'b1-final-w-p1-1',
          type: 'fill_blank',
          concept: 'sentence transformation',
          difficulty: 3,
          prompt: 'Completá la segunda frase para que signifique lo mismo (escribí 1–3 palabras): "I started learning English two years ago." → "I ___ learning English for two years."',
          correctAnswer: 'have been',
          acceptedAnswers: ['have been', 'have been learning', 've been'],
          explanation: 'De past simple + ago se transforma a present perfect continuous con for.',
        },
        {
          id: 'b1-final-w-p1-2',
          type: 'fill_blank',
          concept: 'sentence transformation',
          difficulty: 3,
          prompt: 'Completá la segunda frase: "It\'s necessary to buy a ticket." → "You ___ buy a ticket."',
          correctAnswer: 'must',
          acceptedAnswers: ['must', 'have to'],
          explanation: '"It\'s necessary to" = "must" / "have to".',
        },
        {
          id: 'b1-final-w-p1-3',
          type: 'fill_blank',
          concept: 'sentence transformation',
          difficulty: 3,
          prompt: 'Completá la segunda frase: "My brother is shorter than me." → "I ___ taller than my brother."',
          correctAnswer: 'am',
          acceptedAnswers: ['am', 'am much'],
          explanation: 'La comparación inversa: si él es más bajo, yo soy más alto.',
        },
        {
          id: 'b1-final-w-p1-4',
          type: 'fill_blank',
          concept: 'sentence transformation',
          difficulty: 3,
          prompt: 'Completá la segunda frase: "The last time I saw him was in 2020." → "I haven\'t seen him ___ 2020."',
          correctAnswer: 'since',
          acceptedAnswers: ['since'],
          explanation: '"The last time... was in 2020" = "I haven\'t seen him since 2020".',
        },
        {
          id: 'b1-final-w-p1-5',
          type: 'fill_blank',
          concept: 'sentence transformation',
          difficulty: 3,
          prompt: 'Completá la segunda frase: "We can\'t swim." → "We don\'t know how ___ swim."',
          correctAnswer: 'to',
          acceptedAnswers: ['to'],
          explanation: '"Know how to" + infinitivo expresa saber hacer algo.',
        },

        // ---- Part 2: open task ----
        {
          id: 'b1-final-w-p2',
          type: 'writing',
          concept: 'writing email',
          difficulty: 4,
          prompt: 'Escribile un email a tu amigo/a Ben contándole sobre un curso que empezaste a hacer (por ejemplo de inglés, cocina o deporte). Incluí: qué curso es, por qué lo empezaste y qué te gusta de él. Escribí alrededor de 100 palabras.',
          promptTranslation: 'Write an email to your friend Ben telling him about a course you have started.',
          correctAnswer: '',
          explanation: 'Un buen email informal: saludo, desarrollo con la información pedida y despedida natural, con registro coloquial y conectores sencillos (because, and, but, also).',
          taskType: 'email',
          targetReader: 'a friend',
          register: 'informal',
          contentPoints: ['Qué curso es y cuándo empezó', 'Por qué lo empezaste', 'Qué te gusta de él'],
          requiresOwnIdea: true,
          minWords: 80,
          maxWords: 120,
        },
      ],
    },
    {
      name: 'Listening',
      weight: 35,
      exercises: [
        // ---- Part 1: diálogos cortos con MCQ ----
        {
          id: 'b1-final-l-p1',
          type: 'listening',
          concept: 'listening mcq',
          difficulty: 3,
          prompt: 'Escuchá los cinco diálogos cortos y respondé.',
          correctAnswer: '',
          explanation: 'Comprensión de diálogos breves: identificar información puntual de cada intercambio.',
          listening: {
            audioText:
              'One: Where should we meet? At the cinema at six? — No, the film starts at seven. Let\'s meet at the café at half past six. — Good idea. Two: Would you like chicken or fish for dinner? — Actually, I\'m vegetarian, remember? Let\'s have pasta. Three: How was your exam? — Not bad, but I\'m a bit tired. I studied all night. Four: Can you help me carry this box? — Sure, it looks heavy! Five: What time does the train leave? — At nine fifteen, so we have time for coffee.',
            audioUrl: '/audio/tts/b1-final-l-p1.mp3',
            questions: [
              {
                id: 'b1-final-l-p1-q1',
                type: 'multiple_choice',
                concept: 'listening mcq',
                difficulty: 3,
                prompt: 'Where do they agree to meet?',
                correctAnswer: 'At the café',
                options: ['At the café', 'At the cinema', 'At the station'],
                explanation: '"Let\'s meet at the café at half past six."',
              },
              {
                id: 'b1-final-l-p1-q2',
                type: 'multiple_choice',
                concept: 'listening mcq',
                difficulty: 3,
                prompt: 'What will they have for dinner?',
                correctAnswer: 'Pasta',
                options: ['Pasta', 'Chicken', 'Fish'],
                explanation: '"I\'m vegetarian... Let\'s have pasta."',
              },
              {
                id: 'b1-final-l-p1-q3',
                type: 'multiple_choice',
                concept: 'listening mcq',
                difficulty: 3,
                prompt: 'How did the student feel after the exam?',
                correctAnswer: 'Tired',
                options: ['Tired', 'Angry', 'Excited'],
                explanation: '"Not bad, but I\'m a bit tired. I studied all night."',
              },
              {
                id: 'b1-final-l-p1-q4',
                type: 'multiple_choice',
                concept: 'listening mcq',
                difficulty: 3,
                prompt: 'What does the second person say about the box?',
                correctAnswer: 'It looks heavy',
                options: ['It looks heavy', 'It is empty', 'It is broken'],
                explanation: '"Sure, it looks heavy!"',
              },
              {
                id: 'b1-final-l-p1-q5',
                type: 'multiple_choice',
                concept: 'listening mcq',
                difficulty: 3,
                prompt: 'What time does the train leave?',
                correctAnswer: 'At nine fifteen',
                options: ['At nine fifteen', 'At half past nine', 'At six thirty'],
                explanation: '"At nine fifteen, so we have time for coffee."',
              },
            ],
          },
        },

        // ---- Part 2: monólogo con MCQ ----
        {
          id: 'b1-final-l-p2',
          type: 'listening',
          concept: 'listening monologue',
          difficulty: 3,
          prompt: 'Escuchá a Laura hablar sobre su trabajo y respondé.',
          correctAnswer: '',
          explanation: 'Comprensión de un monólogo: identificar el tema, un problema y la solución.',
          listening: {
            audioText:
              'I work in a bookshop in the city centre. Last month, we had a problem with our deliveries: books arrived late, and customers were unhappy. My manager asked me to phone the delivery company every morning, and it worked. Now the books arrive on time, and the customers are happy again. I really enjoy my job because I love reading and I can recommend books to people every day.',
            audioUrl: '/audio/tts/b1-final-l-p2.mp3',
            questions: [
              {
                id: 'b1-final-l-p2-q1',
                type: 'multiple_choice',
                concept: 'listening monologue',
                difficulty: 3,
                prompt: 'Where does Laura work?',
                correctAnswer: 'In a bookshop',
                options: ['In a bookshop', 'In a delivery company', 'In a library'],
                explanation: '"I work in a bookshop in the city centre."',
              },
              {
                id: 'b1-final-l-p2-q2',
                type: 'multiple_choice',
                concept: 'listening monologue',
                difficulty: 3,
                prompt: 'What was the problem last month?',
                correctAnswer: 'Books arrived late',
                options: ['Books arrived late', 'The shop was closed', 'Customers stopped buying'],
                explanation: '"Books arrived late, and customers were unhappy."',
              },
              {
                id: 'b1-final-l-p2-q3',
                type: 'multiple_choice',
                concept: 'listening monologue',
                difficulty: 3,
                prompt: 'What was the solution?',
                correctAnswer: 'Calling the delivery company every morning',
                options: [
                  'Calling the delivery company every morning',
                  'Changing the shop\'s opening hours',
                  'Buying more books',
                ],
                explanation: '"My manager asked me to phone the delivery company every morning, and it worked."',
              },
            ],
          },
        },

        // ---- Part 3: gap-fill (escribir una palabra) ----
        {
          id: 'b1-final-l-p3',
          type: 'listening',
          concept: 'listening gap fill',
          difficulty: 4,
          prompt: 'Escuchá la información del centro deportivo y completá cada espacio con una palabra.',
          correctAnswer: '',
          explanation: 'Gap-fill: extraer información concreta (nombres, números, días) del audio.',
          listening: {
            audioText:
              'Welcome to the Riverside Sports Centre. Our opening hours are from seven in the morning to ten at night, Monday to Sunday. The swimming pool is open all day, and the gym has thirty machines. Swimming lessons for beginners start every Monday at six. If you want to book a tennis court, please call us on 5-4-3-2-1-0. Thank you.',
            audioUrl: '/audio/tts/b1-final-l-p3.mp3',
            questions: [
              {
                id: 'b1-final-l-p3-q1',
                type: 'fill_blank',
                concept: 'listening gap fill',
                difficulty: 4,
                prompt: 'The sports centre opens at ___.',
                correctAnswer: 'seven',
                acceptedAnswers: ['seven', '7', 'seven in the morning'],
                explanation: '"From seven in the morning to ten at night."',
              },
              {
                id: 'b1-final-l-p3-q2',
                type: 'fill_blank',
                concept: 'listening gap fill',
                difficulty: 4,
                prompt: 'The gym has ___ machines.',
                correctAnswer: 'thirty',
                acceptedAnswers: ['thirty', '30'],
                explanation: '"The gym has thirty machines."',
              },
              {
                id: 'b1-final-l-p3-q3',
                type: 'fill_blank',
                concept: 'listening gap fill',
                difficulty: 4,
                prompt: 'Swimming lessons start every ___.',
                correctAnswer: 'Monday',
                acceptedAnswers: ['Monday', 'monday'],
                explanation: '"Swimming lessons for beginners start every Monday at six."',
              },
              {
                id: 'b1-final-l-p3-q4',
                type: 'fill_blank',
                concept: 'listening gap fill',
                difficulty: 4,
                prompt: 'To book a tennis court, call the number ending in ___.',
                correctAnswer: '0',
                acceptedAnswers: ['0', 'zero'],
                explanation: 'El número para reservar cancha de tenis termina en 0 (543210).',
              },
            ],
          },
        },

        // ---- Part 4: diálogo con T/F ----
        {
          id: 'b1-final-l-p4',
          type: 'listening',
          concept: 'listening true false',
          difficulty: 3,
          prompt: 'Escuchá el diálogo entre Mark y Emma y decidí si cada afirmación es verdadera o falsa.',
          correctAnswer: '',
          explanation: 'Comprensión de un diálogo: distinguir lo que se dice y lo que no.',
          listening: {
            audioText:
              'Mark: Hi Emma! Did you enjoy your holiday in the mountains? Emma: Yes, it was great! We went hiking every day. Mark: Nice! And did you stay in a hotel? Emma: No, we rented a small cabin near the lake. It was very quiet. Mark: Did you take any cooking classes like you planned? Emma: No, we didn\'t have time. But we tried a lot of local food at the restaurants. Mark: And did it rain? Emma: Only on the last day. The rest of the week was sunny.',
            audioUrl: '/audio/tts/b1-final-l-p4.mp3',
            questions: [
              {
                id: 'b1-final-l-p4-q1',
                type: 'true_false',
                concept: 'listening true false',
                difficulty: 3,
                prompt: 'Emma went hiking every day of her holiday.',
                correctAnswer: 'true',
                explanation: '"We went hiking every day."',
              },
              {
                id: 'b1-final-l-p4-q2',
                type: 'true_false',
                concept: 'listening true false',
                difficulty: 3,
                prompt: 'Emma stayed in a big hotel in the mountains.',
                correctAnswer: 'false',
                explanation: '"No, we rented a small cabin near the lake."',
              },
              {
                id: 'b1-final-l-p4-q3',
                type: 'true_false',
                concept: 'listening true false',
                difficulty: 3,
                prompt: 'Emma took cooking classes during the holiday.',
                correctAnswer: 'false',
                explanation: '"No, we didn\'t have time."',
              },
              {
                id: 'b1-final-l-p4-q4',
                type: 'true_false',
                concept: 'listening true false',
                difficulty: 3,
                prompt: 'It rained only on the last day of the holiday.',
                correctAnswer: 'true',
                explanation: '"Only on the last day. The rest of the week was sunny."',
              },
            ],
          },
        },
      ],
    },
  ],
}