import type { Exam } from '../types'

// B2 First (FCE) — formato Cambridge English, adaptado a esta app.
// Estructura de papeles (el Speaking, no evaluado en esta versión):
//  • Reading & Use of English (Paper 1): Part 1 MC cloze, Part 2 open cloze,
//    Part 3 word formation, Part 4 key word transformation, Part 5 texto largo MCQ,
//    Part 6 gapped text, Part 7 multiple matching
//  • Writing (Paper 2): Part 1 essay obligatorio, Part 2 una tarea a elegir (article/review/report)
//  • Listening (Paper 3): Part 1 MCQ cortos, Part 2 sentence completion,
//    Part 3 MCQ texto largo, Part 4 multiple matching
export const b2FinalExam: Exam = {
  id: 'b2-final',
  levelId: 'b2',
  title: 'Examen Final B2 (First)',
  description:
    'Examen final B2 siguiendo la estructura del Cambridge English First (FCE): reading & use of English, expresión escrita y comprensión auditiva. El speaking no se evalúa en esta versión.',
  sections: [
    {
      name: 'Reading & Use of English',
      weight: 40,
      exercises: [
        // ---- Part 1: MC cloze (4 opciones) ----
        {
          id: 'b2-final-ru-p1-1',
          type: 'select_correct',
          concept: 'mc cloze',
          difficulty: 4,
          prompt: 'Elegí la opción correcta: "The company ___ a new marketing strategy last year."',
          correctAnswer: 'adopted',
          options: ['adopted', 'adopted to', 'was adopting of'],
          explanation: '"Adopt a strategy" es la colocación correcta (verbo + objeto directo).',
        },
        {
          id: 'b2-final-ru-p1-2',
          type: 'select_correct',
          concept: 'mc cloze',
          difficulty: 4,
          prompt: 'Elegí la opción correcta: "She\'s very good ___ remembering names."',
          correctAnswer: 'at',
          options: ['at', 'in', 'on'],
          explanation: '"Good at" + gerundio es la colocación correcta.',
        },
        {
          id: 'b2-final-ru-p1-3',
          type: 'select_correct',
          concept: 'mc cloze',
          difficulty: 4,
          prompt: 'Elegí la opción correcta: "We need to ___ the problem before it gets worse."',
          correctAnswer: 'deal with',
          options: ['deal with', 'deal about', 'deal of'],
          explanation: '"Deal with" (phrasal verb) significa ocuparse de algo.',
        },
        {
          id: 'b2-final-ru-p1-4',
          type: 'select_correct',
          concept: 'mc cloze',
          difficulty: 4,
          prompt: 'Elegí la opción correcta: "Despite the rain, the event went ___ as planned."',
          correctAnswer: 'ahead',
          options: ['ahead', 'away', 'up'],
          explanation: '"Go ahead" = continuar; "despite" marca el contraste.',
        },
        {
          id: 'b2-final-ru-p1-5',
          type: 'select_correct',
          concept: 'mc cloze',
          difficulty: 4,
          prompt: 'Elegí la opción correcta: "The results were ___ than we had expected."',
          correctAnswer: 'better',
          options: ['better', 'more better', 'best'],
          explanation: 'Comparativo de "good" es "better"; no se combina con "more".',
        },
        {
          id: 'b2-final-ru-p1-6',
          type: 'select_correct',
          concept: 'mc cloze',
          difficulty: 4,
          prompt: 'Elegí la opción correcta: "I look forward ___ from you soon."',
          correctAnswer: 'to hearing',
          options: ['to hearing', 'to hear', 'hear'],
          explanation: '"Look forward to" va seguido de gerundio: to hearing.',
        },

        // ---- Part 2: open cloze (escribir una palabra) ----
        {
          id: 'b2-final-ru-p2-1',
          type: 'fill_blank',
          concept: 'open cloze',
          difficulty: 4,
          prompt: 'Escribí la palabra que falta: "The film was so boring ___ I left before the end."',
          correctAnswer: 'that',
          acceptedAnswers: ['that'],
          explanation: '"So + adjetivo + that" expresa consecuencia: so boring that I left.',
        },
        {
          id: 'b2-final-ru-p2-2',
          type: 'fill_blank',
          concept: 'open cloze',
          difficulty: 4,
          prompt: 'Escribí la palabra que falta: "___ had I sat down when the phone rang."',
          correctAnswer: 'No',
          acceptedAnswers: ['No', 'Hardly'],
          explanation: '"No sooner / Hardly... when" expresa una acción inmediatamente seguida de otra.',
        },
        {
          id: 'b2-final-ru-p2-3',
          type: 'fill_blank',
          concept: 'open cloze',
          difficulty: 4,
          prompt: 'Escribí la palabra que falta: "You ___ have told me about the meeting earlier!"',
          correctAnswer: 'should',
          acceptedAnswers: ['should'],
          explanation: '"Should have + participio" expresa reproche sobre el pasado.',
        },
        {
          id: 'b2-final-ru-p2-4',
          type: 'fill_blank',
          concept: 'open cloze',
          difficulty: 4,
          prompt: 'Escribí la palabra que falta: "Not ___ did she apologise, but she also offered to pay."',
          correctAnswer: 'only',
          acceptedAnswers: ['only'],
          explanation: '"Not only... but also" con inversión es la estructura correcta.',
        },
        {
          id: 'b2-final-ru-p2-5',
          type: 'fill_blank',
          concept: 'open cloze',
          difficulty: 4,
          prompt: 'Escribí la palabra que falta: "The more you practise, ___ better you become."',
          correctAnswer: 'the',
          acceptedAnswers: ['the'],
          explanation: 'Comparativo proporcional: "The more... the better..."',
        },
        {
          id: 'b2-final-ru-p2-6',
          type: 'fill_blank',
          concept: 'open cloze',
          difficulty: 4,
          prompt: 'Escribí la palabra que falta: "I\'d rather you ___ smoke in here, please."',
          correctAnswer: 'didn\'t',
          acceptedAnswers: ['didn\'t', 'did not'],
          explanation: '"I\'d rather you + past" expresa preferencia sobre la acción de otra persona.',
        },

        // ---- Part 3: word formation ----
        {
          id: 'b2-final-ru-p3-1',
          type: 'fill_blank',
          concept: 'word formation',
          difficulty: 4,
          prompt: 'Formá la palabra correcta a partir de "DECIDE": "Her ___ to study abroad surprised everyone."',
          correctAnswer: 'decision',
          acceptedAnswers: ['decision'],
          explanation: 'De "decide" (verbo) → "decision" (sustantivo).',
        },
        {
          id: 'b2-final-ru-p3-2',
          type: 'fill_blank',
          concept: 'word formation',
          difficulty: 4,
          prompt: 'Formá la palabra correcta a partir de "ENVIRONMENT": "We should be more ___ conscious."',
          correctAnswer: 'environmentally',
          acceptedAnswers: ['environmentally'],
          explanation: 'De "environment" → "environmentally" (adverbio) modificando "conscious".',
        },
        {
          id: 'b2-final-ru-p3-3',
          type: 'fill_blank',
          concept: 'word formation',
          difficulty: 4,
          prompt: 'Formá la palabra correcta a partir de "CREATE": "This artist is known for her ___."',
          correctAnswer: 'creativity',
          acceptedAnswers: ['creativity'],
          explanation: 'De "create" → "creativity" (sustantivo abstracto con -ity).',
        },
        {
          id: 'b2-final-ru-p3-4',
          type: 'fill_blank',
          concept: 'word formation',
          difficulty: 4,
          prompt: 'Formá la palabra correcta a partir de "RELY": "The system proved to be extremely ___."',
          correctAnswer: 'reliable',
          acceptedAnswers: ['reliable'],
          explanation: 'De "rely" → "reliable" (adjetivo, "confiable").',
        },
        {
          id: 'b2-final-ru-p3-5',
          type: 'fill_blank',
          concept: 'word formation',
          difficulty: 4,
          prompt: 'Formá la palabra correcta a partir de "COMPETE": "The ___ is very strong in this market."',
          correctAnswer: 'competition',
          acceptedAnswers: ['competition'],
          explanation: 'De "compete" → "competition" (sustantivo).',
        },
        {
          id: 'b2-final-ru-p3-6',
          type: 'fill_blank',
          concept: 'word formation',
          difficulty: 4,
          prompt: 'Formá la palabra correcta a partir de "HEALTH": "A ___ diet is important for everyone."',
          correctAnswer: 'healthy',
          acceptedAnswers: ['healthy'],
          explanation: 'De "health" → "healthy" (adjetivo).',
        },

        // ---- Part 4: key word transformation ----
        {
          id: 'b2-final-ru-p4-1',
          type: 'fill_blank',
          concept: 'key word transformation',
          difficulty: 4,
          prompt: 'Completá la segunda frase (2–5 palabras) usando "REGARD". No cambies la palabra: "They think very highly of her." → "She is ___ very highly."',
          correctAnswer: 'highly regarded as',
          acceptedAnswers: [
            'highly regarded as',
            'highly regarded',
            'regarded highly',
            'held in high regard',
          ],
          explanation: '"Think highly of" = "be highly regarded" / "be regarded highly".',
        },
        {
          id: 'b2-final-ru-p4-2',
          type: 'fill_blank',
          concept: 'key word transformation',
          difficulty: 4,
          prompt: 'Completá la segunda frase (2–5 palabras) usando "EVER": "This is the best coffee I\'ve tried." → "I ___ such good coffee before."',
          correctAnswer: 'have never tried',
          acceptedAnswers: ['have never tried', 'have never drunk', 'have never tasted', 'never have tried'],
          explanation: 'El superlativo con "ever" se transforma a "have never tried before".',
        },
        {
          id: 'b2-final-ru-p4-3',
          type: 'fill_blank',
          concept: 'key word transformation',
          difficulty: 4,
          prompt: 'Completá la segunda frase (2–5 palabras) usando "HAD": "I didn\'t bring an umbrella, so I got wet." → "If I ___ an umbrella, I wouldn\'t have got wet."',
          correctAnswer: 'had brought',
          acceptedAnswers: ['had brought'],
          explanation: 'Tercer condicional: "If I had brought..."',
        },
        {
          id: 'b2-final-ru-p4-4',
          type: 'fill_blank',
          concept: 'key word transformation',
          difficulty: 4,
          prompt: 'Completá la segunda frase (2–5 palabras) usando "SUCH": "The book was so interesting that I read it twice." → "It was ___ interesting book that I read it twice."',
          correctAnswer: 'such an',
          acceptedAnswers: ['such an'],
          explanation: '"So + adj" → "such a/an + noun": such an interesting book.',
        },
        {
          id: 'b2-final-ru-p4-5',
          type: 'fill_blank',
          concept: 'key word transformation',
          difficulty: 4,
          prompt: 'Completá la segunda frase (2–5 palabras) usando "PREFER": "I\'d rather stay at home than go out." → "I ___ at home to going out."',
          correctAnswer: 'prefer staying',
          acceptedAnswers: ['prefer staying', 'prefer to stay', 'prefer being'],
          explanation: '"Would rather... than" = "prefer + gerund/infinitive + to".',
        },
        {
          id: 'b2-final-ru-p4-6',
          type: 'fill_blank',
          concept: 'key word transformation',
          difficulty: 4,
          prompt: 'Completá la segunda frase (2–5 palabras) usando "WONDER": "Do you know where the station is?" → "I ___ where the station is."',
          correctAnswer: 'was wondering',
          acceptedAnswers: ['was wondering', 'am wondering'],
          explanation: 'Preguntas indirectas: "I was wondering where..." (más cortés).',
        },

        // ---- Part 5: texto largo con MCQ ----
        {
          id: 'b2-final-ru-p5',
          type: 'reading',
          concept: 'reading comprehension',
          difficulty: 4,
          prompt: 'Lee el texto y responde las preguntas.',
          reading: {
            text:
              'The concept of a "digital detox" has become increasingly popular in recent years. Supporters argue that constant connection to smartphones reduces our attention span and affects the quality of our personal relationships. However, experts warn that the idea of completely disconnecting is unrealistic for most people, who need their devices for work and daily communication. Instead of a total ban, they recommend "digital mindfulness": setting specific times to check messages and leaving the phone outside the bedroom at night. According to a recent study, people who followed these simple rules for a month reported sleeping better and feeling less anxious.',
            translation:
              'El concepto de "desintoxicación digital" se ha vuelto cada vez más popular en los últimos años. Los partidarios argumentan que la conexión constante a los teléfonos reduce nuestra capacidad de atención y afecta la calidad de nuestras relaciones personales. Sin embargo, los expertos advierten que la idea de desconectarse por completo no es realista para la mayoría de las personas, que necesitan sus dispositivos para trabajar y comunicarse diariamente. En lugar de una prohibición total, recomiendan la "atención plena digital": establecer horarios específicos para revisar mensajes y dejar el teléfono fuera del dormitorio por la noche. Según un estudio reciente, las personas que siguieron estas reglas simples durante un mes informaron dormir mejor y sentirse menos ansiosas.',
            questions: [
              {
                id: 'b2-final-ru-p5-q1',
                type: 'multiple_choice',
                concept: 'reading comprehension',
                difficulty: 4,
                prompt: 'What do supporters of the digital detox claim?',
                correctAnswer: 'That constant connection reduces our attention span and affects relationships.',
                options: [
                  'That constant connection reduces our attention span and affects relationships.',
                  'That smartphones are the only cause of stress at work.',
                  'That everyone should stop working completely.',
                ],
                explanation: 'El texto dice que reduce "our attention span and affects the quality of our personal relationships".',
              },
              {
                id: 'b2-final-ru-p5-q2',
                type: 'multiple_choice',
                concept: 'reading comprehension',
                difficulty: 4,
                prompt: 'Why do experts consider a total disconnection unrealistic?',
                correctAnswer: 'Because most people need devices for work and daily communication.',
                options: [
                  'Because most people need devices for work and daily communication.',
                  'Because phones are too expensive to replace.',
                  'Because no one wants to follow rules.',
                ],
                explanation: 'Porque "most people... need their devices for work and daily communication".',
              },
              {
                id: 'b2-final-ru-p5-q3',
                type: 'multiple_choice',
                concept: 'reading comprehension',
                difficulty: 4,
                prompt: 'What do experts recommend instead of a total ban?',
                correctAnswer: 'Digital mindfulness: setting times to check messages and leaving the phone out of the bedroom.',
                options: [
                  'Digital mindfulness: setting times to check messages and leaving the phone out of the bedroom.',
                  'Buying a simpler phone without internet.',
                  'Using social media only at weekends.',
                ],
                explanation: 'Recomiendan "digital mindfulness" con esas dos reglas concretas.',
              },
              {
                id: 'b2-final-ru-p5-q4',
                type: 'multiple_choice',
                concept: 'reading comprehension',
                difficulty: 4,
                prompt: 'What did the people in the study report after a month?',
                correctAnswer: 'Sleeping better and feeling less anxious.',
                options: [
                  'Sleeping better and feeling less anxious.',
                  'Working more hours and feeling tired.',
                  'Spending more time online than before.',
                ],
                explanation: 'Informaron "sleeping better and feeling less anxious".',
              },
            ],
          },
          correctAnswer: 'reading complete',
          explanation: 'Comprensión de un texto argumentativo con marcadores de discurso (However, According to).',
        },

        // ---- Part 6: gapped text (elegir oración que completa cada espacio) ----
        {
          id: 'b2-final-ru-p6',
          type: 'reading',
          concept: 'reading gapped text',
          difficulty: 5,
          prompt: 'Siete oraciones han sido quitadas del texto. Elegí para cada espacio la oración que mejor lo completa.',
          reading: {
            text:
              'When the team started their research project, they had no idea how long it would take. [1] ___ The first months were spent collecting data from hundreds of participants. [2] ___ However, the results were worth the effort. [3] ___ The team realised that their findings could help thousands of families. [4] ___ As a result, they decided to publish an early report. [5] ___ Now, two years later, the project is considered one of the most important in its field.',
            translation:
              'Cuando el equipo empezó su proyecto de investigación, no tenían idea de cuánto tiempo llevaría. [1] ___ Los primeros meses se dedicaron a recopilar datos de cientos de participantes. [2] ___ Sin embargo, los resultados valieron la pena. [3] ___ El equipo se dio cuenta de que sus hallazgos podían ayudar a miles de familias. [4] ___ Como resultado, decidieron publicar un informe temprano. [5] ___ Ahora, dos años después, el proyecto es considerado uno de los más importantes de su campo.',
            questions: [
              {
                id: 'b2-final-ru-p6-q1',
                type: 'select_correct',
                concept: 'reading gapped text',
                difficulty: 5,
                prompt: 'Elegí la oración para el espacio [1]:',
                correctAnswer: 'What began as a simple question became a three-year journey.',
                options: [
                  'What began as a simple question became a three-year journey.',
                  'The laboratory was closed for the summer.',
                  'Funding was never a problem for them.',
                  'All participants lived in the same city.',
                  'They bought new computers for the office.',
                ],
                explanation: 'La oración introduce la duración del proyecto, que desarrolla el texto.',
              },
              {
                id: 'b2-final-ru-p6-q2',
                type: 'select_correct',
                concept: 'reading gapped text',
                difficulty: 5,
                prompt: 'Elegí la oración para el espacio [2]:',
                correctAnswer: 'Analysing the information took another six months.',
                options: [
                  'Analysing the information took another six months.',
                  'The participants were all children.',
                  'Nobody wanted to join the team.',
                  'The results were published immediately.',
                  'The city changed its transport system.',
                ],
                explanation: 'Tras "collecting data", lo siguiente es analizar los datos, con duración adicional.',
              },
              {
                id: 'b2-final-ru-p6-q3',
                type: 'select_correct',
                concept: 'reading gapped text',
                difficulty: 5,
                prompt: 'Elegí la oración para el espacio [3]:',
                correctAnswer: 'The data revealed a clear pattern nobody had noticed before.',
                options: [
                  'The data revealed a clear pattern nobody had noticed before.',
                  'The team decided to abandon the research.',
                  'The results were completely random.',
                  'There were no participants left.',
                  'The building was too small.',
                ],
                explanation: 'Se describe el hallazgo que justifica el esfuerzo, seguido del beneficio.',
              },
              {
                id: 'b2-final-ru-p6-q4',
                type: 'select_correct',
                concept: 'reading gapped text',
                difficulty: 5,
                prompt: 'Elegí la oración para el espacio [4]:',
                correctAnswer: 'This discovery had practical applications beyond the laboratory.',
                options: [
                  'This discovery had practical applications beyond the laboratory.',
                  'The laboratory had no windows.',
                  'The team preferred working alone.',
                  'The research had no clear purpose.',
                  'The data was deleted by mistake.',
                ],
                explanation: 'Conecta el hallazgo con su utilidad práctica para las familias.',
              },
              {
                id: 'b2-final-ru-p6-q5',
                type: 'select_correct',
                concept: 'reading gapped text',
                difficulty: 5,
                prompt: 'Elegí la oración para el espacio [5]:',
                correctAnswer: 'The report attracted attention from experts around the world.',
                options: [
                  'The report attracted attention from experts around the world.',
                  'The report was never finished.',
                  'The team sold their equipment.',
                  'The results disappeared.',
                  'The project was cancelled.',
                ],
                explanation: 'El informe publicado genera reconocimiento, que explica el éxito final del proyecto.',
              },
            ],
          },
          correctAnswer: 'reading complete',
          explanation: 'Gapped text: reconstruir la coherencia narrativa de un texto académico.',
        },

        // ---- Part 7: multiple matching (emparejar afirmaciones con textos) ----
        {
          id: 'b2-final-ru-p7',
          type: 'match',
          concept: 'reading multiple matching',
          difficulty: 5,
          prompt: 'Cuatro personas hablan de sus hábitos de lectura. Relacioná cada afirmación con la persona que la hace.',
          correctAnswer: 'matching complete',
          pairs: [
            { left: 'Leo e-books para no ocupar espacio en casa.', right: 'Sara' },
            { left: 'Solo leo libros en papel, no me acostumbro al e-reader.', right: 'Tom' },
            { left: 'Combino audiolibros en el coche y papel en casa.', right: 'Mia' },
            { left: 'Leo libros técnicos principalmente, por mi trabajo.', right: 'David' },
            { left: 'Elijo el formato según el tipo de libro.', right: 'Mia' },
            { left: 'El e-reader me parece frío; prefiero el olor del papel.', right: 'Tom' },
          ],
          explanation: 'Multiple matching: cada afirmación describe el hábito de una de las cuatro personas.',
        },
      ],
    },
    {
      name: 'Writing',
      weight: 25,
      exercises: [
        // ---- Part 1: essay obligatorio ----
        {
          id: 'b2-final-w-p1',
          type: 'writing',
          concept: 'writing essay',
          difficulty: 5,
          prompt: 'Escribí un ensayo (140–190 palabras) sobre este tema: "Should teenagers have their own smartphones?" Incluí tu opinión y argumentos a favor y en contra.',
          promptTranslation: 'Write an essay on the topic: "Should teenagers have their own smartphones?"',
          correctAnswer: '',
          explanation: 'Un ensayo B2 First: introducción que presenta el tema, dos párrafos con argumentos a favor y en contra, y una conclusión con tu opinión. Usá conectores formales (However, Furthermore, On the other hand, In conclusion).',
          taskType: 'essay',
          targetReader: 'the teacher',
          register: 'formal',
          contentPoints: ['Introducción clara del tema', 'Un argumento a favor', 'Un argumento en contra', 'Conclusión con tu opinión'],
          requiresOwnIdea: true,
          minWords: 140,
          maxWords: 190,
        },

        // ---- Part 2: elegir una tarea (article / review / report) ----
        {
          id: 'b2-final-w-p2a',
          type: 'writing',
          concept: 'writing review',
          difficulty: 5,
          prompt: 'Elegí esta tarea: escribí una reseña (140–190 palabras) de una película o serie que hayas visto recientemente para la revista de tu escuela. Incluí una valoración y recomendación.',
          promptTranslation: 'Write a review of a film or series you have watched recently.',
          correctAnswer: '',
          explanation: 'Una reseña B2 First: título atractivo, descripción breve sin spoilers, tu opinión con ejemplos y una recomendación final con registro adecuado.',
          taskType: 'review',
          targetReader: 'a school magazine',
          register: 'neutral',
          contentPoints: ['Qué película/serie es y de qué trata', 'Tu opinión con al menos un ejemplo', 'Una recomendación final'],
          requiresOwnIdea: true,
          minWords: 140,
          maxWords: 190,
        },
      ],
    },
    {
      name: 'Listening',
      weight: 35,
      exercises: [
        // ---- Part 1: diálogos cortos con MCQ ----
        {
          id: 'b2-final-l-p1',
          type: 'listening',
          concept: 'listening mcq',
          difficulty: 4,
          prompt: 'Escuchá los cinco diálogos cortos y respondé.',
          correctAnswer: '',
          explanation: 'Comprensión de intercambios breves: identificar actitud, intención e información puntual.',
          listening: {
            audioText:
              'One: Shall we book the tickets online? — I\'d rather go to the box office, we can choose better seats. Two: How did the presentation go? — Honestly, I\'m relieved it\'s over. The projector kept failing. Three: Do you think we should invest in the new software? — It depends. It\'s expensive, but it could save us hours each week. Four: Are you coming to the party on Friday? — I\'m not sure yet. I might have to work late. Five: What do you think of the new manager? — She\'s demanding, but I respect her fairness.',
            audioUrl: '/audio/tts/b2-final-l-p1.mp3',
            questions: [
              {
                id: 'b2-final-l-p1-q1',
                type: 'multiple_choice',
                concept: 'listening mcq',
                difficulty: 4,
                prompt: 'Why does the second speaker prefer the box office?',
                correctAnswer: 'To choose better seats',
                options: ['To choose better seats', 'To save money', 'To avoid queues'],
                explanation: '"I\'d rather go to the box office, we can choose better seats."',
              },
              {
                id: 'b2-final-l-p1-q2',
                type: 'multiple_choice',
                concept: 'listening mcq',
                difficulty: 4,
                prompt: 'How does the second speaker feel about the presentation?',
                correctAnswer: 'Relieved it is over',
                options: ['Relieved it is over', 'Proud of the result', 'Disappointed with the audience'],
                explanation: '"Honestly, I\'m relieved it\'s over."',
              },
              {
                id: 'b2-final-l-p1-q3',
                type: 'multiple_choice',
                concept: 'listening mcq',
                difficulty: 4,
                prompt: 'What is the second speaker\'s opinion about the software?',
                correctAnswer: 'It is expensive but could save time',
                options: ['It is expensive but could save time', 'It is too risky to buy', 'It is not worth considering'],
                explanation: '"It\'s expensive, but it could save us hours each week."',
              },
              {
                id: 'b2-final-l-p1-q4',
                type: 'multiple_choice',
                concept: 'listening mcq',
                difficulty: 4,
                prompt: 'Why might the second speaker miss the party?',
                correctAnswer: 'They may have to work late',
                options: ['They may have to work late', 'They are going away', 'They dislike the host'],
                explanation: '"I might have to work late."',
              },
              {
                id: 'b2-final-l-p1-q5',
                type: 'multiple_choice',
                concept: 'listening mcq',
                difficulty: 4,
                prompt: 'What does the second speaker think of the new manager?',
                correctAnswer: 'Demanding but fair',
                options: ['Demanding but fair', 'Too strict with everyone', 'Not very organised'],
                explanation: '"She\'s demanding, but I respect her fairness."',
              },
            ],
          },
        },

        // ---- Part 2: sentence completion (escribir 1–3 palabras) ----
        {
          id: 'b2-final-l-p2',
          type: 'listening',
          concept: 'listening sentence completion',
          difficulty: 5,
          prompt: 'Escuchá el anuncio de una escuela de verano y completá cada oración con 1–3 palabras.',
          correctAnswer: '',
          explanation: 'Sentence completion: extraer datos concretos (números, fechas, días, horas) del anuncio.',
          listening: {
            audioText:
              'Welcome to the Bluewater Summer School. This year we are offering courses for students aged 14 to 17. The art course starts on the 3rd of July and runs for three weeks. The science course is more popular, so we recommend booking before the end of May. Classes run from nine in the morning until three in the afternoon, with a lunch break at twelve. The cost of the full programme is four hundred and fifty pounds, which includes all materials. For more information, contact us at info at bluewater dot com.',
            audioUrl: '/audio/tts/b2-final-l-p2.mp3',
            questions: [
              {
                id: 'b2-final-l-p2-q1',
                type: 'fill_blank',
                concept: 'listening sentence completion',
                difficulty: 5,
                prompt: 'The courses are for students aged 14 to ___.',
                correctAnswer: '17',
                acceptedAnswers: ['17', 'seventeen'],
                explanation: '"For students aged 14 to 17."',
              },
              {
                id: 'b2-final-l-p2-q2',
                type: 'fill_blank',
                concept: 'listening sentence completion',
                difficulty: 5,
                prompt: 'The art course starts on the 3rd of ___.',
                correctAnswer: 'July',
                acceptedAnswers: ['July', 'july'],
                explanation: '"The art course starts on the 3rd of July."',
              },
              {
                id: 'b2-final-l-p2-q3',
                type: 'fill_blank',
                concept: 'listening sentence completion',
                difficulty: 5,
                prompt: 'It is recommended to book the science course before the end of ___.',
                correctAnswer: 'May',
                acceptedAnswers: ['May', 'may'],
                explanation: '"We recommend booking before the end of May."',
              },
              {
                id: 'b2-final-l-p2-q4',
                type: 'fill_blank',
                concept: 'listening sentence completion',
                difficulty: 5,
                prompt: 'There is a lunch break at ___.',
                correctAnswer: 'twelve',
                acceptedAnswers: ['twelve', '12', 'noon', 'midday'],
                explanation: '"With a lunch break at twelve."',
              },
              {
                id: 'b2-final-l-p2-q5',
                type: 'fill_blank',
                concept: 'listening sentence completion',
                difficulty: 5,
                prompt: 'The full programme costs ___ pounds.',
                correctAnswer: '450',
                acceptedAnswers: ['450', 'four hundred and fifty', 'four hundred fifty'],
                explanation: '"Four hundred and fifty pounds."',
              },
            ],
          },
        },

        // ---- Part 3: texto largo con MCQ ----
        {
          id: 'b2-final-l-p3',
          type: 'listening',
          concept: 'listening long text',
          difficulty: 5,
          prompt: 'Escuchá la entrevista a una fotógrafa y respondé.',
          correctAnswer: '',
          explanation: 'Comprensión de una entrevista: actitud, razones y detalles sobre el trabajo de la hablante.',
          listening: {
            audioText:
              'Interviewer: You\'ve been a wildlife photographer for over twenty years. What first attracted you to it? Photographer: As a child I loved spending time outdoors, but it was a documentary about African animals that made me want to capture those moments myself. Interviewer: What\'s the biggest challenge? Photographer: Patience, without doubt. You can wait for days for one perfect shot, and the animal may never appear. But that\'s also the magic of it. Interviewer: What advice would you give to beginners? Photographer: Don\'t buy expensive equipment immediately. Learn to see light and composition first. The best camera is the one you have with you.',
            audioUrl: '/audio/tts/b2-final-l-p3.mp3',
            questions: [
              {
                id: 'b2-final-l-p3-q1',
                type: 'multiple_choice',
                concept: 'listening long text',
                difficulty: 5,
                prompt: 'What made the photographer want to start?',
                correctAnswer: 'A documentary about African animals',
                options: ['A documentary about African animals', 'A photography course at school', 'A gift of a camera from her parents'],
                explanation: '"It was a documentary about African animals that made me want to capture those moments."',
              },
              {
                id: 'b2-final-l-p3-q2',
                type: 'multiple_choice',
                concept: 'listening long text',
                difficulty: 5,
                prompt: 'What does she consider the biggest challenge?',
                correctAnswer: 'Patience',
                options: ['Patience', 'The cost of equipment', 'Bad weather'],
                explanation: '"Patience, without doubt."',
              },
              {
                id: 'b2-final-l-p3-q3',
                type: 'multiple_choice',
                concept: 'listening long text',
                difficulty: 5,
                prompt: 'What advice does she give to beginners?',
                correctAnswer: 'Learn about light and composition before buying expensive equipment',
                options: [
                  'Learn about light and composition before buying expensive equipment',
                  'Buy the most expensive camera available',
                  'Copy the style of famous photographers',
                ],
                explanation: '"Don\'t buy expensive equipment immediately. Learn to see light and composition first."',
              },
            ],
          },
        },

        // ---- Part 4: multiple matching (emparejar hablantes) ----
        {
          id: 'b2-final-l-p4',
          type: 'listening',
          concept: 'listening multiple matching',
          difficulty: 5,
          prompt: 'Cinco personas hablan sobre cómo aprenden idiomas. Elegí la frase que describe el método de cada hablante.',
          correctAnswer: '',
          explanation: 'Multiple matching: identificar el método principal de cada hablante.',
          listening: {
            audioText:
              'Speaker one: I watch series with subtitles and repeat the sentences. It feels like playing, not studying. Speaker two: I have a weekly video call with a language partner. We correct each other, which helps a lot. Speaker three: I write a short diary entry every evening and check the grammar online. Speaker four: I use an app for ten minutes every day. It\'s not much, but the routine matters. Speaker five: I read the news in the language and note down new words in a notebook.',
            audioUrl: '/audio/tts/b2-final-l-p4.mp3',
            questions: [
              {
                id: 'b2-final-l-p4-q1',
                type: 'multiple_choice',
                concept: 'listening multiple matching',
                difficulty: 5,
                prompt: 'Speaker one learns by:',
                correctAnswer: 'Watching series and repeating sentences',
                options: [
                  'Watching series and repeating sentences',
                  'Writing a daily diary',
                  'Talking to a language partner',
                  'Using a daily app',
                  'Reading the news',
                ],
                explanation: '"I watch series with subtitles and repeat the sentences."',
              },
              {
                id: 'b2-final-l-p4-q2',
                type: 'multiple_choice',
                concept: 'listening multiple matching',
                difficulty: 5,
                prompt: 'Speaker two learns by:',
                correctAnswer: 'Weekly video calls with a partner',
                options: [
                  'Weekly video calls with a partner',
                  'Reading the news',
                  'Using a daily app',
                  'Writing a daily diary',
                  'Watching series',
                ],
                explanation: '"I have a weekly video call with a language partner."',
              },
              {
                id: 'b2-final-l-p4-q3',
                type: 'multiple_choice',
                concept: 'listening multiple matching',
                difficulty: 5,
                prompt: 'Speaker three learns by:',
                correctAnswer: 'Writing a diary entry and checking grammar',
                options: [
                  'Writing a diary entry and checking grammar',
                  'Watching series',
                  'Using a daily app',
                  'Talking to a partner',
                  'Reading the news',
                ],
                explanation: '"I write a short diary entry every evening and check the grammar online."',
              },
              {
                id: 'b2-final-l-p4-q4',
                type: 'multiple_choice',
                concept: 'listening multiple matching',
                difficulty: 5,
                prompt: 'Speaker four learns by:',
                correctAnswer: 'Using an app for ten minutes every day',
                options: [
                  'Using an app for ten minutes every day',
                  'Writing a diary',
                  'Reading the news',
                  'Watching series',
                  'Talking to a partner',
                ],
                explanation: '"I use an app for ten minutes every day."',
              },
              {
                id: 'b2-final-l-p4-q5',
                type: 'multiple_choice',
                concept: 'listening multiple matching',
                difficulty: 5,
                prompt: 'Speaker five learns by:',
                correctAnswer: 'Reading the news and noting down words',
                options: [
                  'Reading the news and noting down words',
                  'Using a daily app',
                  'Writing a diary',
                  'Talking to a partner',
                  'Watching series',
                ],
                explanation: '"I read the news in the language and note down new words in a notebook."',
              },
            ],
          },
        },
      ],
    },
  ],
}